### ISSUE TITLE
Any tls+tcp transport example ?

### ISSUE THREAD

**Issue by tisyang** [nanomsg/nng#1000]
I need a secure connection between clients and server, and tls would be the best choice.
But I don't know how to do it step by step, so if any example about tls+tcp transport usage ?

**Comment by fhajji** [comment]
Did you have a look at the [TLS test case](https://github.com/nanomsg/nng/blob/master/tests/tls.c)?

Or, if you prefer the [C++ equivalent](https://github.com/cwzx/nngpp/blob/master/test/tls.cpp).

**Comment by tisyang** [comment]
@fhajji Thanks for the links.
