### ISSUE TITLE
nngcat should accept --data or --file over stdin

### ISSUE THREAD

**Issue by dch** [nanomsg/nng#1007]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

nng 1.1.1 (via FreeBSD ports)

## Expected Behavior

```
ping localhost | nngcat --pub --listen=tcp://127.0.0.1:4567 -i 1 -v --file -
```

## Actual Behavior

```
Protocol requires either --file or --data.
```

it seems nngcat doesn't accept piped stdin, nor via `--file -` or `--data -` or the same without `-`.

## Steps to Reproduce

See above, run `nngcat --sub --dial=tcp://127.0.0.1:4567 --raw` in another term.

**Comment by dch** [comment]
same restriction observed on git master, 32d17517b87713e4

**Comment by gdamore** [comment]
Actually this might be a bug/limitations.  I was thinking we want a new feature, but arguably "-" should work.
