### ISSUE TITLE
httpclient test should not rely on SHA1 hash of www.example.com response body

### ISSUE THREAD

**Issue by mzipay** [nanomsg/nng#1008]
## NNG & Platform details.

NNG 1.1.1 running in a Debian Buster (stable) container hosted on Fedora Core 30.

## Expected Behavior

`tests/httpclient` completes successfully.

## Actual Behavior

`tests/httpclient` fails three tests:

```shell
# ./tests/httpclient -v
=== RUN: HTTP Client

  Given a TCP connection to example.com ....
    We can initiate a message ......
      The message contents are correct ......X..............
  Given a client ...
    One off exchange works ....X...
    Timeout works ......
    Connection reuse works ......X...
  Given a client (chunked) ...
    One off exchange works ........


Failures:

  * Assertion Failed (The message contents are correct)
  File: /usr/local/src/nng-1.1.1/tests/httpclient.c
  Line: 33
  Test: memcmp(digest, example_sum, 20) == 0
  
  * Assertion Failed (One off exchange works)
  File: /usr/local/src/nng-1.1.1/tests/httpclient.c
  Line: 33
  Test: memcmp(digest, example_sum, 20) == 0
  
  * Assertion Failed (Connection reuse works)
  File: /usr/local/src/nng-1.1.1/tests/httpclient.c
  Line: 33
  Test: memcmp(digest, example_sum, 20) == 0
  


69 assertions thus far

--- FAIL: HTTP Client (6.76s)
FAIL
FAIL    ./tests/httpclient                                     6.766s
```

## Steps to Reproduce

Run the `tests/httpclient` test case.

**Comment by mzipay** [comment]
The reason the three tests are failing is because `tests/httpclient` relies on a pre-defined (hardcoded) SHA1 hash of the http://www.example.com/ response body (`example_sum` in _tests/httpclient.c_).  However, that response body changed on 2019-10-17 (about three weeks ago).

I have an immediate need to have this working, so I will be submitting a patch in a moment here to update the hardcoded SHA1 so that the tests pass.

Longer term, this is just not a reliable testing approach (i.e. relying a pre-computed hash of an HTTP response from a domain outside of the project's control).  If I have the time, I'll try to submit something better, but I can't commit to that.

(I think in this scenario it would be perfectly reasonable to just assert against a  non-4xx/5xx HTTP response code and a response Content-Length > 0.  There isn't much beyond that you could guarantee for purposes of unit testing.)

**Comment by mzipay** [comment]
Further context:

```python
>>> import hashlib
>>> from urllib.request import urlopen
>>> ", ".join([hex(b) for b in hashlib.sha1(urlopen("https://web.archive.org/web/20191017000103id_/http://www.example.com/").read()).digest()])
'0xe, 0x97, 0x3b, 0x59, 0xf4, 0x76, 0x0, 0x7f, 0xd1, 0xf, 0x87, 0xf3, 0x47, 0xc3, 0x95, 0x60, 0x65, 0x51, 0x6f, 0xc0'
>>> ", ".join([hex(b) for b in hashlib.sha1(urlopen("https://web.archive.org/web/20191017233701id_/http://www.example.com/").read()).digest()])
'0x4a, 0x3c, 0xe8, 0xee, 0x11, 0xe0, 0x91, 0xdd, 0x79, 0x23, 0xf4, 0xd8, 0xc6, 0xe5, 0xb5, 0xe4, 0x1e, 0xc7, 0xc0, 0x47'
>>> ", ".join([hex(b) for b in hashlib.sha1(urlopen("http://www.example.com/").read()).digest()])
'0x4a, 0x3c, 0xe8, 0xee, 0x11, 0xe0, 0x91, 0xdd, 0x79, 0x23, 0xf4, 0xd8, 0xc6, 0xe5, 0xb5, 0xe4, 0x1e, 0xc7, 0xc0, 0x47'
```

First output line is from the view of http://www.example.com/ at 20191017000103 (you'll notice this corresponds to the current hardcoded SHA1 in *tests/httpclient.c*.

Second output line is from the same view at a later time that day (20191017233701), identifying 2019-10-17 as the day on which the document changed.

Third output line (identical to second) is from a current request of http://www.example.com/ and corresponds to the change made in the PR.

**Comment by jtavares** [comment]
May I suggest https://httpbin.org/.

Gives you control of the response. Can run an instance locally during unit testing, if you prefer.

**Comment by mzipay** [comment]
The fundamental issue is that www.example.com is not a domain under NNG's control; therefore, NNG unit tests cannot (safely) assume that response bodies from that domain will always have the same SHA1 hash.

Unless I miss something obvious in httpbin's interface, I don't see how httpbin addresses or solves that problem.
