### ISSUE TITLE
Question regarding thread count

### ISSUE THREAD

**Issue by maingig** [nanomsg/nng#1016]
NNG uses 16 threads (have limited the NNG_NUM_TASKQ_THREADS count to 8 and will reduce further) on QNX and Linux.  Eight of the threads are outside a users control.  If I have 50 services (embedded) using NNG, the count becomes pretty large.  Are there any plans to reduce the thread count?

**Comment by gdamore** [comment]
This is a reasonable question.  We should probably offer some kind of tunable to reduce the number of workers.  The limit was set on the assumption that you want to engage all the CPUs, and we set it to 2x the CPU count by default to ensure that we minimize context switch based latency.   I would be open to an environment variable that reduced this count (probably also NNG_NUM_TASKQ_THREADS).  One thing is that you always to have at least 2 workers to avoid potential deadlocks.  You *can* reduce it down to 2 without ill effects.

(We assume, perhaps poorly, that threads are not very expensive entities.  If you're going to run a lot of these services then you probably don't want them all vying for 100% of the available CPU.)

**Comment by maingig** [comment]
Another option would be for dynamic thread creation based on need, rather than having a number of idle threads.  In the short term I would be happy with a tunable.  If I wanted to make a change in the meantime, Can you point me the code which manages the current non-tunable threads?

**Comment by gdamore** [comment]
Making thread creation dynamically tunable is a little harder than it sounds (at least to do safely), and I'm kind of trying to manage the complexity.  On most systems, within a given process, a few extra idle threads should not be a big deal.  We allocate about 2x the core count (plus a small number of additional fixed threads), on the assumption that this should not be onerous, and yet still sufficient to permit good scaling.

Having said that, I recognize that it some circumstances even this is too many.

**Comment by maingig** [comment]
Okay but can you answer my last question?
Can you point me the code which manages the current non-tunable threads?

**Comment by gdamore** [comment]
It’s scattered around. For example the resolver creates two I think.

Garrett D’Amore

________________________________

**Comment by gdamore** [comment]
I don't think there is anything else actionable here.  I'm closing it.
