### ISSUE TITLE
nng library panic

### ISSUE THREAD

**Issue by cr-galrosen** [nanomsg/nng#1018]
NNG version 1.1.1
Platform windows 10

I have created a demo of client/server using pair sockets.
While killing the client the server crash.

It happened one time. I have no idea how to reproduce it.

The demo is written in c++ and compile and link statically with the NNG library.

The message that I got on the terminal was:
panic: inserting node already on a list or not inited
This message is indicative of a BUG.
Report this at https://github.com/nanomsg/nng/issues

C:\Users\gal.rosen\nng_demo\build\server\Debug\server.exe (process 19300) exited with code -2147483645.

Hope this information can help.

**Comment by gdamore** [comment]
Ok thanks.  Can you tell me what transport you were using?  Were you using pair v1, and if so were you using polyamorous mode?

**Comment by cr-galrosen** [comment]
The transport is ipc.
Yes, I used pairv1 with polyamorous mode.

בתאריך יום ד׳, 27 בנוב׳ 2019, 19:25, מאת gdamore ‏<notifications@github.com

**Comment by gdamore** [comment]
So it would be useful if I had a reproduction test case for this (sample code).  Unfortunately this particular crash can arise if you try to improperly reuse an aio, and I want to make sure that you aren't doing that -- plus having a repro case will help me track down whatever error exists in the library.

**Comment by cr-galrosen** [comment]
I will send it on Sunday.

בתאריך יום ה׳, 12 בדצמ׳ 2019, 04:02, מאת gdamore ‏<notifications@github.com

**Comment by cr-galrosen** [comment]
Hi Garrett,

Attached are the demo source code, however, I am almost sure that the code
change a bit since the crash, so I am not sure it would help.

Gal.

**Comment by gdamore** [comment]
It looks like the attachment didn't make it through?

**Comment by cr-galrosen** [comment]
Hi Garrett,

What do you mean ? I see the attachment files, do you want me to send it to
other mail ?

Gal.

**Comment by gdamore** [comment]
You're dropping your updates via email instead of using the web app -- whatever attachments you are sending via email isn't making it here.  Maybe try posting it on github or in a gist somewhere?

**Comment by cr-galrosen** [comment]
Hi Garrett,
Hope that now files would be uploaded.
Gal.
[
[nng_demo.zip](https://github.com/nanomsg/nng/files/3999676/nng_demo.zip)
](url)

**Comment by gdamore** [comment]
Yeah, that worked.  I'll look soon.

**Comment by gdamore** [comment]
I see one potential obvious red flag to me.

You're doing sleeping and AIO operations from within  the pipe event hooks.  This is almost certainly a no-no.  I never intended this API for that kind of usage.  Probably I should make this documentation more clear.

**Comment by gdamore** [comment]
Also, it's almost certain you wind up trying to call nng_sleep_aio() more than once on the same AIO, which is also absolutely verboten.  You can only have *one* operation outstanding on an AIO at a time.  That's by design.

I'm now thinking that this defect is in your code.

**Comment by gdamore** [comment]
So yes, its certain.  Your callbacks are incorrectly using nng_sleep_aio() on the same AIO object.  This is most definitely *not* safe, and leads to this failure.

Probably we should give better errors in the error message.  I'll look into that.
