### ISSUE TITLE
Can u give us a async client for IPC req/rep mode

### ISSUE THREAD

**Issue by wildwild** [nanomsg/nng#1019]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

<include NNG version, and platform/operating system, and if you are using
another programming language what language> 
c++
1.0.0

## Expected Behavior
use async aio client ,sometimes it works ,but most time it did not work

## Steps to Reproduce

I use async recv server demo as my server , use private msg  for my own use,
I use the work struct as w_global , and I use "ipc:///somepipe" req/rep mode 

and the code below I want to use ctx to connect the server ,and hope the server  to response only to this client ,when multi clients connect the server ,they can do their own thing!!, if I use the "nng_send" and "nng_recv" it will get the msg from other client ,I read the doc online , find ctx_send can help ,so I want to use aio and ctx to solve the problem !
`
nng_msg_alloc(&w_global->msg,0);

	nng_msg_append(w_global->msg, req.data(), req.size());

	nng_aio_set_msg(w_global->aio, w_global->msg);
	nng_ctx_send(w_global->ctx, w_global->aio);
	rv = nng_aio_result(w_global->aio);
	if (0!=rv)
	{
	cerr << "[node] << send request failed, errno=" << nng_strerror(rv) << endl;
	}
 nng_aio_wait(w_global->aio);

	nng_ctx_recv(w_global->ctx, w_global->aio);

	rv = nng_aio_result(w_global->aio);
	if (0 != rv)
	{
		cerr << "[node] << send request failed, errno=" << nng_strerror(rv) << endl;
	}
	nng_sleep_aio(123, w_global->aio);  

	nng_msg * pmsg = nng_aio_get_msg(w_global->aio);  
//error null msg here ,once it woked ,but later it never work again 

	char* pData = (char*)nng_msg_body(pmsg);

	size_t iLen = nng_msg_len(pmsg);
	if (iLen <= 0 || pData == NULL)
	{
		cerr << "[node] << recv response empty, errno=" << nng_strerror(rv) << endl;
		return;
	}
	rsp.append(pData, iLen);
	string sMsg;
	sMsg.append((char*)nng_msg_body(pmsg), nng_msg_len(pmsg));
`
and i init the sock like this 
`

	if ((pWorker = (work*)nng_alloc(sizeof(*pWorker))) == NULL)
	{
		cerr << "[master] nng_alloc failed" << endl;
		exit(-1);
	}
	pWorker->id = id;
	if ((rv = nng_aio_alloc(&pWorker->aio, processing, pWorker)) != 0)
	{
		cerr << "[master] worker_" << id << " nng_aio_alloc failed" << endl;
		exit(-1);
	}
	if ((rv = nng_ctx_open(&pWorker->ctx, sock)) != 0)
	{
		cerr << "[master] worker_" << id << " nng_ctx_open failed" << endl;
		exit(-1);
	}
	pWorker->state = work::INIT;
`

<If possible, if include a copy of, or link to, a minimal test program
to demonstrate the behavior.  We prefer test cases written in C when
possible.>

**Comment by wildwild** [comment]
I  find  it use serve work numbers to control multi clients , maybe I misunderstood it ……

**Comment by wildwild** [comment]
if use IPC req/rep mode , I start multi clients  ,the message order has some problem

**Comment by gdamore** [comment]
I think you're missing the point of contexts.  Using a global context makes no sense.  Instead, you should use a single context per thread.  On a given context, you need to follow the send request/receive reply (for REQ sockets) or receive request, send reply (for REP sockets) model, without any intervening activity. 

In other words, each context is a separate instance of the request/reply state machine, and you need to treat them as not thread safe (though you can have many threads using a single socket, each thread should have it's own context to do its work.)

**Comment by wildwild** [comment]
> I think you're missing the point of contexts. Using a global context makes no sense. Instead, you should use a single context per thread. On a given context, you need to follow the send request/receive reply (for REQ sockets) or receive request, send reply (for REP sockets) model, without any intervening activity.
> 
> In other words, each context is a separate instance of the request/reply state machine, and you need to treat them as not thread safe (though you can have many threads using a single socket, each thread should have it's own context to do its work.)

thx for help
