### ISSUE TITLE
Support tcp6 link local addresses

### ISSUE THREAD

**Issue by athei** [nanomsg/nng#1022]
In order to properly use link local adresses the device needs to be specified. I propose the syntax detailed in this example:
`tcp6://[fe80::2%lan]:80 `

For example Linux ping supports this syntax:
`ping fe80::2%lan`

I did not find any issue discussing this or any way to use link local addresses with nng. If there are please tell me how to do it.

**Comment by gdamore** [comment]
I don't have support for that in the parser today.  I'm not entirely sure how this is supposed to work in various operating systems -- I know that on the systems I've used you can use link local addresses without a scoped interface, but it means that the address refers to *any* of the scopes.

**Comment by athei** [comment]
The scope id for link local address is specified as the second 16-bit word of the address:
`fe80::1%lan -> fe80:6::1%lan`
This assumes that the netdev lan has the index 6. This should be portable because it's just IPv6.

Not specifying the scope id leads to a failure (at least on my linux machine). I tried with nng master to bind on` tcp://[fe80::bfe8:7f1a:a55c:54c0]:1234` which is a ip on my ethernet device.

strace:
`bind(5, {sa_family=AF_INET6, sin6_port=htons(1234), inet_pton(AF_INET6, "fe80::bfe8:7f1a:a55c:54c0", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EINVAL (Invalid argument)`

As you can see the strace parsed the scope id from the address: `sin6_scope_id=0`. This fails because my net device indices start with one rather than zero. I guess that is a safety measure to  not bind a random device by accident. Not specifying a scope id is almost never what you want because at best it fails. In the worst case you bind the wrong interface.

However, determining the scope id from an interface name seems to be non portable. `inet_pton()` seems to support the `ip%dev_name` syntax but it depends on the c std lib you are using. At least uclibc did not support it the last time I tested. Given the fragmented clib space on Linux I would recommend using the kernel interface directly there:
http://man7.org/linux/man-pages/man7/netdevice.7.html
You can just do the ioctl on a socket to get the scope id from a name. That works on any Linux.
For other operating systems it has to be implemented separately I guess.

**Comment by gdamore** [comment]
This all seems quite reasonable -- it will take some time for me to get through the particulars on this -- especially with the portability considerations that you mentioned.

**Comment by gdamore** [comment]
I'm moving this 1.4, only because I want to press out 1.3 asap.

**Comment by gdamore** [comment]
I've posted a draft PR that I think resolves this.  If folks can test it out and let me know, I'd be grateful.
