### ISSUE TITLE
Need NN_IPV4ONLY option (NNG_OPT_IPV4ONLY)

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#103]
For compatibility, we should support the IPv4 only option.

**Comment by gdamore** [comment]
I'm pretty sure that I don't want to do this.  The problem with this option is that it affects DNS resolution which occurs frankly too soon.  And it is specific to IPv4.

I think what I want to do is add URL formats of tcp4:// and tcp6:// that resolve specifically to IPv4 or IPv6.

**Comment by jaybny** [comment]
fyi - nng_pipe_getopt_sockaddr() is giving me NNG_AF_INET6 - but the ip address inside nng_sockaddr_in6 is an ipv4 address....

**Comment by gdamore** [comment]
@jaybny I need more information about the above.

Also, I've added tcp4:// and tcp6:// now.

Btw, with a wild card bind by default, we bind to IPv6 if the host has IPv6 configured. Then you will see IPv4 addresses come in via NNG_AF_INET6, but the address will decode as an IPv4-in-IPv6 address.  Something like ::FFFF:192.0.0.1  -- the presence of this is highly subject to the underlying operating system.  For example, I'm pretty sure Windows does not do this, and neither does OpenBSD.

**Comment by gdamore** [comment]
Compat issue here only.

**Comment by gdamore** [comment]
I'm closing this ... tcp4, tcp6 are better.
