### ISSUE TITLE
Consider using libdispatch on macOS

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#1033]
The pthreads experience on macOS is absolutely terrible.  Really really awful, due to design decisions made by the macOS team.  (If you have *anything* else wanting to run, you need to be careful never to yield a lock, because you will be punished *hard*, even when dropping and reacquiring an otherwise uncontended lock.)

It's likely that libdispatch may be better, and it offers a different kind of waiting paradigm (dispatch semaphores).

Converting NNG to libdispatch should be possible, but it's probably going to be a very big effort.

**Comment by gdamore** [comment]
If we ever had a GSoC sponsorship, this would be a great GSoC project for a talented student.

**Comment by mattwidmann** [comment]
Semaphores have no ownership concept (a signal can come from any thread), so they cannot avoid priority inversions by boosting the priority of an owner when higher-priority waiters are present. The exclusion system offered by GCD is the serial dispatch_queue.

What version of macOS did you see the fair-share behavior of pthread mutexes (going to the back of the line to allow waiters to take the lock, to avoid starvation)? The default policy changed in a macOS Mojave SU to be unfair.

**Comment by gdamore** [comment]
I didn't know that the policy changed.  It was probably a while back.   I'm aware of the issue with semaphores, and you'll find that I pretty much never use them -- they have numerous problems, and priority inversion is just one of them.  One of the others is that as they don't have an "owner", they are almost impossible debug when you have a bug.

**Comment by gdamore** [comment]
Reader/writer locks have some similar problems as well, and are often abused/used incorrectly, which is another reason I tend to avoid them unless I have a demonstrated case where I have a lot of pressure from readers, and exceedingly rare writer use.

**Comment by gdamore** [comment]
At this point, macOS is kind of a niche platform for NNG.  Almost everyone using NNG at any kind of scale is doing so using Linux, or in some cases one of the BSDs or illumos.   It may be easiest to just accept the performance limitations of macOS, and move on.

**Comment by gdamore** [comment]
FYI; at this point I consider this issue back-burnered into oblivion.  This and numerous other decisions made by Apple over the past several years make supporting macOS a less and less interesting project.  (Note that I'm no longer running macOS myself -- the decision by the most recent to remove shared libraries from the file system is just another world-breaking change by Apple that demonstrates that they don't really care about their desktop ecosystem or who they break.)

**Comment by gdamore** [comment]
I'm closing this for now.  (Btw, I am back to running on mac hardware, and macOS, but I don't want to go through unnatural acts for this platform -- I don't recommend macOS for folks looking for the highest performing solutions, although it is more than sufficient for typical use cases.)
