### ISSUE TITLE
Need RCVPRIO and SNDPRIO options

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#104]
For legacy compatibility, and perhaps for other use case, it would be nice to support tuning the
send and receive priorities.  The send priority especially would be useful for REQ/REP when
dealing with "less optimal" peers (e.g. over a wider area network).

**Comment by hoytluo** [comment]
Since it has reached to v1.6, what about this feature?

**Comment by gdamore** [comment]
Duplicate of #11
