### ISSUE TITLE
testutil.h could offer better test failure diagnosis

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#1042]
We could improve the test failure diagnosis by providing a TEST_RESULT or TEST_NNG_RESULT or something that looked at the return value, and included a message with the expected result and the actual one (including nng_strerror() of it) if the result does not match.

**Comment by mity** [comment]
Please note I've commented on https://github.com/nanomsg/nng/commit/7c6ce24b028a8c201ac8eb1513a6424205c4d8d8#comments

(Not sure if github notifies you automatically in the case of a comment made on a commit outside any pull request.)
