### ISSUE TITLE
spin locks can help

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#1086]
There are a few places in NNG where we have locks that should be uncontended and are leaf locks guarding accesses.  It would be good to use cheap spin locks for those locations, hopefully reducing the context switching and maybe making macOS in particular perform better.

Having said that, macOS doesn't actually have a great story for spin locks either.

**Comment by gdamore** [comment]
Note that #1108 introduced a lock free algorithm around the nni_pollable, and also inlined (reducing some extra dereferencing), giving between 5% (on macOS) and 28% (ubuntu on WSL) improvement in the inproc_lat latency numbers  (Stock Windows saw 25%.)

This is a large (percentage wise) boost.

**Comment by mattwidmann** [comment]
Check out `os_unfair_lock` on macOS -- it acts like a spinlock in user space when uncontended.

**Comment by gdamore** [comment]
I believe we could consider os_unfair_lock on macOS for sure.  I think however recent macOS has switched the default behavior to unfair (which is a good thing).

Spin locks in general seem like maybe a poor choice.  The issue here is that some ugly things can happen with priority inversion if they *only* spin and don't prevent the thread from preempting the holder.

My feeling is that ultimately, spinlocks will lead to more harm than good -- we might get a tiny amount of performance on some paths, but will probably wind up doing so with significantly increased risk on platforms that can pre-empt a spinlock holder, or that have a crummy spinlock implementation.

Mostly, we need, I think, to assume that the platform has done a reasonable job with regular locks.  So far that has been true everywhere except (historically) macOS -- the other mainstream platforms don't drop in the kernel unless there is contention on the lock.  I *think* macOS pthread behavior now does the same.  If so, I'll probably just close this, and users of older macOS releases will just have to put up with correct, but slow, behavior.

**Comment by gdamore** [comment]
Hmm... it seems even pretty far back there is an API on macOS:

__API_AVAILABLE(macos(10.7), ios(5.0))
int pthread_mutexattr_setpolicy_np(pthread_mutexattr_t *, int);

The default policy is fair.  But we can ask for unfair with:

#define PTHREAD_MUTEX_POLICY_FIRSTFIT_NP    3

Unfortunately none of this is well documented anywhere.

**Comment by gdamore** [comment]
Well, the api available is a lie -- it's really only defined on macOS 10.14 apparently, and it's the default there.  I'm going to close this -- 354 remains open for the macOS case until I can prove I see a benefit on macOS 10.14 or newer.
