### ISSUE TITLE
nng_ctx_send() does not handle data set via nng_aio_set_iov()

### ISSUE THREAD

**Issue by dziegel** [nanomsg/nng#1127]
## NNG & Platform details.
NNG tag 1.2.3 on Linux x64

## Expected Behavior
nng_ctx_send() should not crash when TX data is set via nng_aio_set_iov()

## Actual Behavior
I modified the nng/demo/async/server.c code to set TX data via nng_aio_set_iov() instead of 
nng_set_msg(). The subsequent call to nng_ctx_send() crashes in nni_msg_header_append() because the message inside struct aio is already freed.
It seems nng_ctx_send() can only handle messages, not iovs.

## Steps to Reproduce
Modify example from nng/demo/async/server.c:
```
    case work::RECV:
    {
        auto rv = nng_aio_result(work->aio);
        // error handling omitted for brevity

        auto msg = nng_aio_get_msg(work->aio);
        // RX msg handling omitted for brevity
        nng_msg_free(msg); // ------ MSG in struct AIO is freed here

        // modification: directly send response (state WAIT does not exist in my code)

        // generation of TX data omitted for brevity
        struct nng_iov iov;
        iov.iov_buf = tx_data;
        iov.iov_len = tx_data_len;
        rv = nng_aio_set_iov(work->aio, 1, &iov);
        // error handling omitted for brevity

        work->state = work::SEND;
        nng_ctx_send(work->ctx, work->aio);  // --------------- BOOM here!
        break;
    } 
```

**Comment by gdamore** [comment]
nng_ctx_send can only send messages, and nng_ctx_recv can only receive messages.  Attempting to misuse the API is a programming error in the consuming application.

The IOV members of struct aio are used principally for the lower level transports, or when using the raw byte streams.

I could make some extra checks to harden nng_ctx if you do this, but it would only return an error.   I have no plans of making nng_ctx_send() support iovs.

**Comment by gdamore** [comment]
I'm going to close this for now.
