### ISSUE TITLE
(openindiana) compile error

### ISSUE THREAD

**Issue by flexoron** [nanomsg/nng#1131]
Hello,
compiling on SunOS openindiana 5.11 illumos,
gcc --version (OpenIndiana 9.2.0-oi-0) 9.2.0,
breaks with an error:

../src/platform/posix/posix_ipclisten.c
../src/platform/posix/posix_ipclisten.c: In function 'ipc_remove_stale':
../src/platform/posix/posix_ipclisten.c:188:21: error: expected identifier or '(' before numeric constant
  188 |  struct sockaddr_un sun;
../src/platform/posix/posix_ipclisten.c:191:5: error: request for member 'sun_family' in something not a structure or union
  191 |  sun.sun_family = AF_UNIX;

It turns out that the variable name 'sun' caused the error.
Changing it to sul :) in function ipc_remove_stale and everything is just fine:

file: src/platform/posix/posix_ipclisten.c
line 188: struct sockaddr_un sul;
line 191: sul.sun_family = AF_UNIX;
line 192: sz = sizeof(sul.sun_path);
line 194: ... sul.sun_path ...
line 208: ... (void *) &sul, sizeof(sul),  ... 

btw
Thank you for such a clean codebase, no compiler warnings,
excellent:
100% tests passed, 0 tests failed out of 83

nng
git status
On branch master
Your branch is up to date with 'origin/master'.
Date: January 13, 2020

**Comment by gdamore** [comment]
I'll fix this momentarily -- thanks for reporting it.
