### ISSUE TITLE
docs: Major differences and motivation vs. nanomsg

### ISSUE THREAD

**Issue by ERnsTL** [nanomsg/nng#114]
Greetings, In the nng repository, I could not find information regarding:

* What was the motivation to start a separate library, nng - vs. a refactoring of nanomsg in a separate git branch? Will libnng stay a separate library or will it be libnanomsg version 2?
* Are there any limitations in nanomsg, which nng seeks to overcome?
* What are the major differences between nng and nanomsg?
* Is a new wire protocol used? Is / will integration on the wire be possible with deployed applications using nanomsg?

Most things seem to be still in flux, but these informations would be useful to present in the README file as a general, broad-strokes bullet list or a few short paragraphs for orientation.

**Comment by gdamore** [comment]
Good request.  I'll definitely add this.
