### ISSUE TITLE
How to build Docker image?

### ISSUE THREAD

**Issue by chainhead** [nanomsg/nng#1148]
The `Dockerfile` in either the [clang](https://github.com/nanomsg/nng/tree/master/.circleci/images/clang) or the [gcc](https://github.com/nanomsg/nng/tree/master/.circleci/images/gcc) folders, ends with a `apt-get update`. How does `nng` get built?

**Comment by gdamore** [comment]
Those Dockerfiles are for the Circle-CI environment we use to build and test NNG.  It does not including building NNG itself -- that's specified in the .circleci/config.yml file. 

This isn't really a Dockerfile for deploying NNG, which is perhaps what you were looking for.

I'm probably going to delete the entire .circleci directory at some point in the future, as I'm not really using it any more (I'm using GitHub actions for most of my CI now.)

**Comment by gdamore** [comment]
Sorry I don't really have a better answer for what you're probably looking for.

**Comment by chainhead** [comment]
I am working on building the `Dockerfile` for `nng`. Would you be willing to accept PR?

**Comment by gdamore** [comment]
Possibly -- I'll need to do some research as I've no experience with Dockerfiles for what are strictly libraries.
