### ISSUE TITLE
Following the BDD-style reconnect tests, nng_sendmsg fails to receive the message

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#115]
Literally the result is empty, nothing is received. As we've discussed, I do not know that this is Catch related, per se, but I can't rule it out, either. From my experience with Catch thus far, I can't say that this is an issue there, but I could be wrong.

I'm going to use this pause in momentum to pull my local repo into Github for your consideration, as well as the Catch folks, and see if we can't get to the bottom of it.

Definitely the "same" thing "works" under Convey. Which leaves me scratching my head as to just what is being expanded into the Catch macros. It's sounding more Catch related than NNG related to me.

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reconnect.exe is a Catch v1.10.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
C style NNG reconnect works
  We can create a pipeline
  Dialing before listening works
  We can send a frame
-------------------------------------------------------------------------------
G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\reconnect.cpp(12
8)
...............................................................................

G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\reconnect.cpp(15
3): FAILED:
  REQUIRE( ::nng_msg_len(msgp) == std::strlen(hello.c_str()) )
with expansion:
  0 == 5
with messages:
  Dialing push on address: 'inproc://nng'
  Pull listening on address: 'inproc://nng'

===============================================================================
test cases:  1 |  0 passed | 1 failed
assertions: 23 | 22 passed | 1 failed
```

**Comment by mwpowellhtx** [comment]
I've stripped it back to about as bare close to the metal as I can without dropping Catch altogether. At this point I am convinced this is not a problem with Catch at all, but with internal bookkeeping of the message structure.

I'm entirely open to learning more about *nng* at the same time. Perhaps this is me grokking what messaging is about. Of course, the pattern going on here is repeated at least one other time in the reconnect test alone.

There is one section of code in particular that is problematic at best. In the wild, not in a controlled setting, it is unlikely that the push socket will know anything about the pull socket, will likely be in entirely different parts of the code, per se.

```C++
Convey("We can send a frame", {
    nng_msg *msg;
    nng_usleep(100000);
    So(nng_msg_alloc(&msg, 0) == 0);
    APPENDSTR(msg, "hello");
    So(nng_sendmsg(push, msg, 0) == 0);
    msg = NULL; // <== methinks this is potentially problematic leading to memory leaks, but I could be wrong about that
    So(nng_recvmsg(pull, &msg, 0) == 0);
    So(msg != NULL);
    CHECKSTR(msg, "hello");
    nng_msg_free(msg);
});
```

On the surface, does this mean that "sending" simply leaves a message "in an inbox" of sorts for the receive to "pick up"?

After stripping back the test case to about as bare close to the metal as possible, no sections involved, etc, I can "reproduce" successfully when I too nullify the message. However, permutations separating the send from the receive are problematic at best.

Which, in my opinion, perhaps it is my nng naivity, the receive should support the receiver potentially presenting a message of his/her own to receive the message. In other words, not always leave it up to the framework to pull the message.

So, this, in a couple different permutations, freeing, or not freeing, or asking for an allocation, etc, is problematic and causes a crash.

```C++
INFO("We can send a frame");

::nng_msg* sendmsgp = nullptr;
this_thread::sleep_for(100ms);
NNG_TESTS_REQUIRE_ERR_EQ(::nng_msg_alloc(&sendmsgp, 0), 0);
REQUIRE(sendmsgp != nullptr);
NNG_TESTS_APPEND_STR(sendmsgp, hello.c_str());
NNG_TESTS_REQUIRE_ERR_EQ(::nng_sendmsg(push, sendmsgp, 0), 0);

::nng_msg* recvmsgp = nullptr;
NNG_TESTS_REQUIRE_ERR_EQ(::nng_recvmsg(pull, &recvmsgp, NNG_FLAG_ALLOC), 0);
REQUIRE(recvmsgp != nullptr);
NNG_TESTS_CHECK_STR(recvmsgp, hello.c_str());

::nng_msg_free(sendmsgp);
::nng_msg_free(recvmsgp);
```

Not surprisingly when I nullify my message pointer in the same way, it "works". And, perhaps as unsurprisingly, when I free the then-sent message, the receive receives "nothing".

Which leaves me wondering whether the message is the same message sent as was allocated. Is that really what you want to do there?

**Comment by gdamore** [comment]
You can't free a message that you sent.  That's a critical bug.  We've talked about this stuff offline -- let's keep discussion about potential issues you find in your library out of this git issues and in email.

If you find a real bug in nng however, then please *do* file it here.

**Comment by mwpowellhtx** [comment]
My mistunderstanding. I understand it now, thanks.
