### ISSUE TITLE
nni_aio_lk is white hot

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#1172]
Probably the single biggest performance problem in the system right now is the nni_aio_lk which is central to all aio callbacks, and used to manage scheduling, timeouts, etc.

I've done some initial experimentation with lock-free algorithm changes to reduce the contention on this lock -- a central lock is still needed to manage the expiration queue for now, but I believe we'll see more significant gains on this front in the future.

**Comment by gdamore** [comment]
One simple idea here might be to use an array of locks.  It would make expiration more complex, but would permit the aios themselves to be somewhat less likely to trip over each other.

**Comment by or17191** [comment]
Hi, I might be able (if my schedule allows it) to try to work on improving the lock usage. Can you go into the benchmarks you are working on?

Thanks!

**Comment by gdamore** [comment]
I'm working on a PR that creates multiple expire queues, which should substantially reduce the heat on this lock.  This change will actually impact this in two ways -- first by having fewer threads hitting the same lock, and second by reducing the length of the expire list, which should result in faster iteration when inserting record into the expire list.

The expire list could be a heap, but my instinct is that these lists should not be so long as to be worth this.
