### ISSUE TITLE
Issues building for QNX

### ISSUE THREAD

**Issue by mrtnggnn** [nanomsg/nng#1177]
I'm having issues building nng 1.2.4 for the QNX Neutrino 6.6.0 platform.
My main dev platform is QNX 6.5.0 SP1 but seems to come with GCC 4.4.2 while 6.6.0 uses 4.7.2.

I couldn't find CMake 3.1+ for QNX so I went for cross-compiling from Win10.
Please note that I've never used cmake before.

I created a toolchain file [qnx-toolchain.cmake.txt](https://github.com/nanomsg/nng/files/4118034/qnx-toolchain.cmake.txt) and asked CMake to generate a Unix Makefile project.

The Configuration step goes through but it looks like quite a bit of stuff is missing. Should this be addressed first? See [configure-output.txt](https://github.com/nanomsg/nng/files/4118017/configure-output.txt)

The Generate step does not complain.

The build process goes a long way but stops at 67% with errors building posix_atomic.c.o, see 
[build-output.txt](https://github.com/nanomsg/nng/files/4118028/build-output.txt) for details.

Should I try to get CMake 3.1+ for the QNX platform and try to build natively?
Has anyone successfully built nng for QNX 650SP1? 
What should my next step be?

Any help is welcome.
Thank you

**Comment by gdamore** [comment]
This looks like another case of #1176 -- I will address soon.

If you have the ability to upgrade your toolchain to a more recent compiler, I strongly recommend doing so.  Modern clang and gcc should not see this, and you'll gain some nice performance wins too.

**Comment by mrtnggnn** [comment]
Thanks Garrett.
I don't think I can upgrade the toolchain, will have a closer look at this for sure.
Will stay tuned in the meantime.

**Comment by gdamore** [comment]
I just pushed v1.2.5 that should fix this.  Please let me know if you find otherwise.

**Comment by gdamore** [comment]
I'm closing this now.

**Comment by mrtnggnn** [comment]
Thanks Garrett for the quick release!
Just tried it and the build fails on the same spot: [nng-1.2.5.build-output.txt](https://github.com/nanomsg/nng/files/4131989/nng-1.2.5.build-output.txt)

The build halts at posix-atomic.c:137, nni_atomic_set_bool(). 
Since it's conflicting, I went ahead and remmed it out, along with nni_atomic_get_bool() and nni_atomic_swap_bool() that were both reported as conflicting as well. That's a comment block from line 136 to 163. I'm not suggesting this as a fix, just want to see what pops up next...
```
[  1%] Building C object src/CMakeFiles/nng.dir/platform/posix/posix_atomic.c.o
N:/Embedded/Projets/contrib/nng/nng-1.2.5/src/platform/posix/posix_atomic.c: In function 'nni_atomic_init_bool':
N:/Embedded/Projets/contrib/nng/nng-1.2.5/src/platform/posix/posix_atomic.c:168:3: error: dereferencing pointer to incomplete type
```
I'm stuck.
If you do put some time on this again, I can test builds locally off a branch instead of pushing a release.
Thank you
