### ISSUE TITLE
TCP6 transport testing utilizes nni_* internals

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#118]
Please expose these via first class *nng_** API if you would please. It's a block, however small of one; and I'm not sure it isn't causing infinite wait issues during similar transport testing, i.e. IPC.

Thank you!

**Comment by mwpowellhtx** [comment]
I'm going to make an effort to connect with the */path/to/nng/src*, as contrasted with the */path/to/nng/install/prefix/include*, in order to wire in the necessary includes for my transport unit test conversion efforts. Early indications are encouraging, but we'll see. For "ordinary" use during the library build itself, the include would be to the install prefix.

Will keep you posted.

**Comment by gdamore** [comment]
Can you detail *which* nni_ internals you think should be made part of the public API?

**Comment by mwpowellhtx** [comment]
I am translating the protocol tests. So, pretty much working through those. Unless there is a decent alternative we could do otherwise.

**Comment by gdamore** [comment]
So nni_random() is just a nicer way for me to call rand()... you don't need that.  (nni_random() actually gives better quality randomness, but I could easily have called rand() for the test case.)

nni_tran_find() is something you should not be doing in your code -- this is me validating the internals of the API and transports, and it is not appropriate for you to be testing that at all.
That's also true of the trantest_scheme() stuff -- that's an internal test that is inappropriate for you to duplicate.

Remember I built my test suite to validate my implementation -- it wasn't intended to act as a model for folks consuming the "public" APIs... which is you.

You are struggling in part because I have yet to produce documentation for this stuff.

**Comment by mwpowellhtx** [comment]
@gdamore Yes, I get the random stuff. That's no big deal using the std API.

Well, I could be struggling, but unless there are some flags or something hidden at compile time, the surface level nng_* API calls yield things like blocking behavior.

As for scheme testing, yes, I reviewed that as well and dismissed it as "under the hood" diagnostics. Not necessary for consumer vetting during wrapper integration.

I'll try with the non block flags and see if that makes a difference, though.

**Comment by mwpowellhtx** [comment]
@gdamore So at the moment I can get a clean compile out of my TCP6 adaptation, but for unresolved externals in ``::nni_plat_udp_open`` and ``::nni_plat_udp_close``. The functions are there in the include headers, and is there in the source code.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	2 unresolved externals	tcp6	G:\Source\Spikes\nanomsg\cppnngswig-working\build\swig\cpp\tests\Debug\tcp6.exe	1	
Error	LNK2019	unresolved external symbol "int __cdecl nni_plat_udp_open(struct nni_plat_udp * *,struct nng_sockaddr *)" (?nni_plat_udp_open@@YAHPEAPEAUnni_plat_udp@@PEAUnng_sockaddr@@@Z) referenced in function "bool __cdecl nng::transport::has_v6(void)" (?has_v6@transport@nng@@YA_NXZ)	tcp6	G:\Source\Spikes\nanomsg\cppnngswig-working\build\swig\cpp\tests\tcp6.obj	1	
Error	LNK2019	unresolved external symbol "void __cdecl nni_plat_udp_close(struct nni_plat_udp *)" (?nni_plat_udp_close@@YAXPEAUnni_plat_udp@@@Z) referenced in function "bool __cdecl nng::transport::has_v6(void)" (?has_v6@transport@nng@@YA_NXZ)	tcp6	G:\Source\Spikes\nanomsg\cppnngswig-working\build\swig\cpp\tests\tcp6.obj	1	
```

And the problem is that your headers do not have ``extern "C" {}``.

So with this, the build fails:

```C
#include <core/nng_impl.h>
```

Whereas, when I do this, the build works:

```C++
#ifdef __cplusplus
extern "C" {
#   include <core/nng_impl.h>
}
#endif // __cplusplus
```

**Comment by mwpowellhtx** [comment]
@gdamore Well, the tests run and pass when I include the ``::nni_init`` call before asking ``has_v6()``.

```C++
REQUIRE(::nni_init() == 0);
```

So, I take it this initializes NNG under the hood that the ``nni_*`` calls depend upon?

Is this something that always happens under the hood of the ``nng_*`` calls? Does it hurt anything for unit tests, for example, to just always call ``::nni_init`` coupled with the ``::nng_fini`` boundary?

Just besides that, built the TCP6 unit tests and they run to successful completion.
