### ISSUE TITLE
Problems building for QNX

### ISSUE THREAD

**Issue by mrtnggnn** [nanomsg/nng#1191]
This is *very closely* related to issue #1177 
Just realized that posting to a closed issue doesn't reopen it... Here's a follow up on this issue after the proposed fix.

> Thanks Garrett for the quick release!
> Just tried it and the build fails on the same spot: [nng-1.2.5.build-output.txt](https://github.com/nanomsg/nng/files/4131989/nng-1.2.5.build-output.txt)
> 
> The build halts at posix-atomic.c:137, nni_atomic_set_bool(). 
> Since it's conflicting, I went ahead and remmed it out, along with nni_atomic_get_bool() and nni_atomic_swap_bool() that were both reported as conflicting as well. That's a comment block from line 136 to 163. I'm not suggesting this as a fix, just want to see what pops up next...
> ```
> [  1%] Building C object src/CMakeFiles/nng.dir/platform/posix/posix_atomic.c.o
> N:/Embedded/Projets/contrib/nng/nng-1.2.5/src/platform/posix/posix_atomic.c: In function 'nni_atomic_init_bool':
> N:/Embedded/Projets/contrib/nng/nng-1.2.5/src/platform/posix/posix_atomic.c:168:3: error: dereferencing pointer to incomplete type
> ```
> I'm stuck.
> If you do put some time on this again, I can test builds locally off a branch instead of pushing a release.
> Thank you

**Comment by gdamore** [comment]
Pull down 1.2.6.  It should work.  If it doesn't let me know.

**Comment by gdamore** [comment]
I'm closing this for now... we can reopen if we need to.  But v1.2.6  should solve your problems.
