### ISSUE TITLE
Unexpected error return code: NNG_ENOMEM

### ISSUE THREAD

**Issue by codypiersall** [nanomsg/nng#1201]
A zero-length message can be sent without error, but on receive nng returns `NNG_ENOMEM`.  I'm not sure that sending a zero-length message actually makes any sense to try to send, but the return code from recv is surprising.  This was reported in pynng (my Python bindings to nng): https://github.com/codypiersall/pynng/issues/57

Here's a simple C reproducer:

```c
#include <assert.h>
#include <stdio.h>
#include <nng/nng.h>
#include <nng/protocol/pair0/pair.h>

#define CHECK(x) (assert((x) == 0))
#define ADDR "tcp://127.0.0.1:14224"

int main() {
    nng_socket s0, s1;
    char *data = NULL;
    size_t *recv_size = NULL;

    CHECK(nng_pair0_open(&s0));
    CHECK(nng_listen(s0, ADDR, NULL, 0));

    CHECK(nng_pair_open(&s1));
    CHECK(nng_dial(s1, ADDR, NULL, 0));

    CHECK(nng_send(s0, "", 0, 0));
    int ret = nng_recv(s1, &data, recv_size, NNG_FLAG_ALLOC);
    assert(ret == NNG_ENOMEM);
    fprintf(stdout, "ret %d\n", ret);

    CHECK(nng_close(s1));
    CHECK(nng_close(s0));
}
```

I'm not sure exactly what behavior I expected.  I guess ideally receiving a zero-length message would be supported?  I've never had need of it but I'm trying to bring closure to my issue in pynng.

**Comment by gdamore** [comment]
This certainly does sound like a bug.  I have some ideas and I will add a test for it. Zero length messages are definitely supposed to be supported.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gdamore** [comment]
This certainly does sound like a bug.  I have some ideas and I will add a test for it. Zero length messages are definitely supposed to be supported.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gdamore** [comment]
Btw, what platform was this encountered on?  I am wondering if the libc malloc implementation might play a role here (in particular, what does malloc(0) do....)

**Comment by codypiersall** [comment]
Good question!

```bash
  % uname -a      
Linux compster 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

  % lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 18 Sarah
Release:        18
Codename:       sarah
```

From man 3 malloc:

> If size is 0, then malloc() returns either NULL, or a unique pointer value that can be successfully passed to free()

And a test C program:

```c
#include <stdio.h>
#include <stdlib.h>

int main() {

    printf("pointer to %p\n", malloc(0));
    return 0;
}
```

Compiling and running yields a non-NULL pointer on my computer.
```

**Comment by gdamore** [comment]
So the issue is quite clear to me.  We try to allocate using nni_alloc.  That can give back a NULL if size is zero. 

The fix is simple, but we have to agree on semantics.

Two options:

1. The function returns NULL, with size 0, but passes success.  These values can be passed to nng_free(), so that should still be fine.

2. Create a magical non-NULL pointer and imbue it with special exceptional powers so that nng_free does not return it, but understands to simply ignore it.

I like option 1 the best.  Its the simplest and clearest in the implementation,  But it may cause problems for code that treats NULL specially.

Option 2 is far less elegant, and still suffers where callers might be comparing message pointers and will be surprised to find the same two values are present.

Opinions?

**Comment by gdamore** [comment]
So I'm going to take option 1 for lack of feedback.  I know, less than 24 hours, but I'm impatient.

**Comment by gdamore** [comment]
This is a potential backport candidate.  However, it only applies for folks sending zero length messages, which is probably an edge case.  If folks want a backport to the 1.2.x branch, please let me know by commenting here.

**Comment by codypiersall** [comment]
Thanks for fixing this!  Sorry for the lack of response earlier.
