### ISSUE TITLE
More than 120 threads was started by NNG

### ISSUE THREAD

**Issue by 19317362** [nanomsg/nng#1202]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.
1. OS: Ubuntu 18.04 LTS (x86-64)
2. IDE: CLion
3. NNG: 1.1.1
4. Compiler: GCC-5

When I break the app, I found more than 120 threads was started by NNG.

## Expected Behavior
Not so many threads.

## Actual Behavior
More than 120 threads was started by NNG.

## Steps to Reproduce
Just a simple NNG app.

**Comment by gdamore** [comment]
I'm curious about the system you ran into this on.  We create threads based on core count.  I'd expect if you're seeing this you're running on a system with many many cores.

Probably we should consider some default upper limit on this -- the code is designed to scale well across multiple cores, but engaging that many threads at once is likely to compound contention.

**Comment by 19317362** [comment]
> I'm curious about the system you ran into this on. We create threads based on core count. I'd expect if you're seeing this you're running on a system with many many cores.
> 
> Probably we should consider some default upper limit on this -- the code is designed to scale well across multiple cores, but engaging that many threads at once is likely to compound contention.

Yes.  I found this when I was debugging my APP on a server with 28 core 56 threads. The APP will finally run on ARM-embeded-linux system.  Because it's hard to debug on board, so mostly I debug it in Linux simulated.

I thinks threads is the less the better. :)

**Comment by gdamore** [comment]
So in the PR, I've created a new CMake option, with a default limit of 16, which specifies the maximum number of taskq workers.  This was responsible for the explosion.  There are a few other threads that we create (some for DNS resolving, and some for running the pollers), but those are not at present scaled to the core count.

**Comment by 19317362** [comment]
> So in the PR, I've created a new CMake option, with a default limit of 16, which specifies the maximum number of taskq workers. This was responsible for the explosion. There are a few other threads that we create (some for DNS resolving, and some for running the pollers), but those are not at present scaled to the core count.

Sorrry for my poor English to describe the issue.  
Thanks for your quickly help.

I'll upgrade my NNG to v1.3 and try the same debugging on the same server today or the next day when I have time.
