### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [nanomsg/nng#1205]
I find that an include guard like “[`NNG_H`](https://github.com/nanomsg/nng/blob/0a315e4e5f7d90789babba312079462953114e0d/include/nng/nng.h#L11 "Update candidate")” is too short for the safe reuse of your header file (when it belongs to an application programming interface).

**Comment by gdamore** [comment]
We would expect all symbols NNG* or nng* to be "safe" for our own use.  Did you run into specific problems with this?

**Comment by elfring** [comment]
I suggest to reduce the probability for name clashes a bit more also for [short include guards](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Coherent naming scheme for include guards").

**Comment by gdamore** [comment]
So, all of the headers, except nng.h, use filepath based header guards.

I'll change nng.h to do the same for consistency, which will then be NNG_NNG_H.  (Originally nng.h was delivered into /usr/include/ as nng.h, but that was during very early development.)

I believe your concerns around this issue are overstated.

**Comment by elfring** [comment]
Thanks for [your adjustment of an include guard](https://github.com/nanomsg/nng/commit/4f7cf93dd0d9c37c7e5c6ec31d057f7cb3714a9c "Renaming of an include guard").
