### ISSUE TITLE
panic: chunk_append failed This message is indicative of a BUG. Report this at https://github.com/nanomsg/nng/issues

### ISSUE THREAD

**Issue by Jackozoo** [nanomsg/nng#1208]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.
nng 1.2.6
win server 2016

Pair V1

panic: chunk_append failed
This message is indicative of a BUG.
Report this at https://github.com/nanomsg/nng/issues

**Comment by gdamore** [comment]
Thanks for reporting this.  Can you describe this in more detail.  Were you using polyamorous mode, or just regular (monogamous) mode?  Was there any particular actions you took to lead to this?  What transport (e.g. tcp, inproc, etc?)  Was there a stack backtrace you can share?

**Comment by gdamore** [comment]
Actually, I am thinking maybe you were out of memory, and I made a false assumption in code -- it looks like this might actually be uncovering a double allocation, the fixing of which should help boost performance a bit!

**Comment by gdamore** [comment]
Actually, looking at this, I think I may have been mistaken.  It looks like this is during message allocation, which means (barring heap corruption, which might be a risk) that access to the message is exclusive.

One thing that might cause bizarre behavior is attempting to pass a value to nng_msg_alloc() that is unreasonably large, or is negative.  We probably should put some guards in place for that.

**Comment by gdamore** [comment]
Would like to know how big a message you were trying to allocate -- or did this occur while trying to *receive* a message?

**Comment by Jackozoo** [comment]
1. I used polyamorous mode.
2. it's TCP
3. I always pass 0 to nng_msg_alloc.
```
    	nng_msg *repost_msg;
	int rv = nng_msg_alloc(&repost_msg, 0);
```
4. I forgot to notice the available memory size that moment, may be it's out of memory , however, if that, then nng leaks memory, and I think nng leaks memory too,
`0:035> !heap -stat -h 011f0000 
 heap @ 011f0000
group-by: TOTSIZE max-display: 20
    size     #blocks     total     ( %) (percent of total busy bytes)
    138 17802d - 1ca436d8  (40.38)
    3d8 35b77 - ce79168  (18.19)
    2e0 35b71 - 9a6e4e0  (13.61)
    34 17801e - 4c60618  (6.73)
    f0 35b75 - 325bdb0  (4.44)
    ed4100 3 - 2c7c300  (3.92)
    219dbe3 1 - 219dbe3  (2.96)
    8c 35b72 - 1d60258  (2.59)
    800000 2 - 1000000  (1.41)
    4c 35b75 - ff26bc  (1.41)
    40 271a3 - 9c68c0  (0.86)
    46 1f1b1 - 881666  (0.75)
    1ffb8 40 - 7fee00  (0.70)
    24 35b6e - 78db78  (0.67)
    38 1f1b2 - 6cdef0  (0.60)
    18 35b78 - 509340  (0.44)
    10 35afc - 35afc0  (0.30)
    4059f 1 - 4059f  (0.02)
    20000 1 - 20000  (0.01)
    3bc 22 - 7ef8  (0.00)`
I use nng for pair_v1 of poly mode, there are more than 10 thousands clients connected to my server and the memory keeps being eatten. from 200M to 1G, 2G,3G...
the above stats is what I copied from windbg. all these sizes of block increaes...

Besides, more details in my application:
1. VS2013
2. Pair V1 Poly (listen) * 2 ( one for server of more than 10K clients, one for 0~20 special use(net SDK))
3. Pull (listen) pattern * 1 (which for 3 pushers)
4. Push(listen) * 1 (for 3 pullers)
5. Survey(listen) * 1 for broadcast command to 3clients (pubsub drop message, I gave up it)
It's rather complicated.... I am lazy,so I don't want give nng up.
But, now , my sencond PairV1_poly socket seems to can't recv msg affer some packets...my SDK hung when call nng_send.

6. except the 2 pair-poly sockets uses nng_recvmsg, all other just use nng_send & nng_recv.


I hope you can recommand one stable version for me . thanks.

**Comment by gdamore** [comment]
Lot of things here.

Unfortunately it's hard to fully grok the heap output.  It seems like you might be leaking 40.38% somewhere... but I can't tell from this output what the size of the allocations are.

Having said that, please test master if you can.  Lots of changes there, and fewer allocations and copies too.  I'm not sure that this will address the problem identified here (I doubt it), but I'm hopeful it might help with the memory pressure.

If you have a simple reproducer written in C, I'd love to take a deeper look at it.

**Comment by gdamore** [comment]
Btw, for anyone who watches here, we do run with sanitizers to attempt to find and squash leaks.  I'm not aware of any known leaks in NNG at present.  However the sanitizers don't run on Windows, and there is different code for Windows, so it's possible that's wrong.  (The reason we don't run the sanitizers on Windows is because I've not yet figured out how to make them work on that platform.  If folks have clear advice here, I'd love to benefit from it.)

**Comment by gdamore** [comment]
I'm going to remove this from the milestone, because at present I can't reproduce, and I don't know enough about what is happening to affirmatively say this is a bug in NNG.

**Comment by Jackozoo** [comment]
Thank you for your reply. I will use master instead of 1.2.6.
Yes, I agree that maybe it's not NNG'bug, because my codes is a little terrible, I am not fimilar with net/socket programming. I wish I can paste some code snipper, but they are so massive and broken now.   I plan to use master intead of 1.2.6, and if any exception occurs again, I will write and post my simple reproducer (of C language) to here.
Sincerely thanks. Sorry for my poor english.
