### ISSUE TITLE
TCPv6 port number fails to parse

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#121]
During the TCP IPv6 tests, I have the following issue going on.

According to the TCPv6 specification, port number should be specified along these lines. Such as for loop back address, *"tcp://[::1]:<port>"*.

The address I provided was this: *"tcp://[::1]:12501"*. After getting the option back from the pipe, the address itself looks fine. However the port number I got back was ***54567 != 12501***.

**Comment by mwpowellhtx** [comment]
@gdamore This appears to be a case of 16-bit network versus host order. Can you confirm this?

**Comment by codypiersall** [comment]
It's definitely an endianness issue.  Is the wrong port actually getting bound to or is it just getting displayed incorrectly?  Is this a bug in nng or in the code that displays the bytes to you?  What code did you actually run to reproduce this?

**Comment by codypiersall** [comment]
To demonstrate it's an endianness issue, here is some quick Python:

```
import struct
print(struct.unpack('>H', struct.pack('<H', 12501)))
# prints (54576,)
```

**Comment by mwpowellhtx** [comment]
From a consumer POV, we would expect to see *12501*. But from the *sockaddr** struct POV, I gather that is in network order, as is par for the course it would seem. That's all I'm after, whether that's the case.

**Comment by gdamore** [comment]
Sockaddr structures represent port numbers in network byte order.

(Weird exception for ZeroTier... and I've not decided what to do about that.)

**Comment by mwpowellhtx** [comment]
That's good to know. Just FYI, and why I'm looking at this so intently, not that it should concern NNG, per se, however, I am representing "views" to the unionized data in a C++ way, so it should be easy to isolate port endianness depending on the view.
