### ISSUE TITLE
Link Errors for nng in vs2019

### ISSUE THREAD

**Issue by foroughmajidi** [nanomsg/nng#1212]
I am trying to build a nanomsg next gen (https://github.com/nanomsg/nng) on a windows box. I am using VS2019.
I am getting link errors.
the Linker/General/Additional Library Directories is:F:\nng-1.2.5\build
The .h files are read fine. But I am getting the following link errors:
![Capture](https://user-images.githubusercontent.com/51900859/75445689-c6f22080-591a-11ea-84dd-5b1f007d47d0.PNG)
These are my VS2019 settings (x64 .lib and x64 project).

![Capture2](https://user-images.githubusercontent.com/51900859/75445929-3ff17800-591b-11ea-96aa-f1f198166fb0.PNG)

![Capture3](https://user-images.githubusercontent.com/51900859/75446047-80e98c80-591b-11ea-9f79-e229e09449b1.PNG)
at the end I should say that I built nng-1.2.5 as the following:

1-Download/clone NNG source
2-create Command Prompt suitable for Visual Studio:
Run x64 Visual Studio Developer Command Prompt to create a 64-bit library 
3-  then put cmake and Ninja  in PATH environment variable
Run:
4-mkdir build && cd build
5-cmake -G Ninja -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
6-ninja
please help me how to solve this problem;
thanks

**Comment by gdamore** [comment]
Is the error in building NNG itself, or in trying to build your program(s) that use it?

**Comment by gdamore** [comment]
(For the record, I build NNG on Windows all the time with the VS compilers.  I do it from the command line though, and not in the VS GUI.  I have roughly zero experience with the VS GUI.)

**Comment by jimmybutler1201** [comment]
_imp_xx means dynamic link, however your nng is build by static.

How to resolve:
right-click your vs project, properties-->C++-->Preprocessor--> Add NNG_STATIC_LIB

**Comment by jimmybutler1201** [comment]
it's not nng's problem, it's your project config

**Comment by foroughmajidi** [comment]
> _imp_xx means dynamic link, however your nng is build by static.
> 
> How to resolve:
> right-click your vs project, properties-->C++-->Preprocessor--> Add NNG_STATIC_LIB

I had done it in the way you said but it didn't work

**Comment by foroughmajidi** [comment]
> Is the error in building NNG itself, or in trying to build your program(s) that use it?

I built nng and got nng.lib and nng.dll but when adding them in my project ,I got those errors that attached in first message

**Comment by foroughmajidi** [comment]
> (For the record, I build NNG on Windows all the time with the VS compilers. I do it from the command line though, and not in the VS GUI. I have roughly zero experience with the VS GUI.)

I built nng similar to your way in command line but my project was built in VS GUI

**Comment by foroughmajidi** [comment]
> it's not nng's problem, it's your project config

I had done all setting and errors are related to nng

**Comment by jimmybutler1201** [comment]
if nng MT, then your project MT
if MTd ... MTd
...
it must be the same.

**Comment by gdamore** [comment]
Yes.  I really need to have these flags inherited in the cmake parlance.  The current way NNG does this is a bit hackish, and as noted here, error prone.  (There's already a ticket filed for this.  I probably won't fix for 1.3, but probably in 1.4.)

**Comment by gdamore** [comment]
I'm going to close this particular ticket, since it's clear that the problem doesn't represent a bug in NNG.  (Modulo that other ticket I just referenced.)
