### ISSUE TITLE
pub/sub : nothing received with nng_sub0_open()

### ISSUE THREAD

**Issue by nmset** [nanomsg/nng#1220]
A sub socket would receive a published message if it is opened with nng_sub0_open_raw() only. It fails to receive anything with nng_sub0_open(). The pub socket may send with nng_pub0_open_raw() or nng_pub0_open() regardless.

The documentation does not state it as a feature. It's more likely I'm missing something.

The attached file may demonstrate it. I'm using latest git sources on Linux.

Please advise, namely if nng_sub0_open_raw() is mandatory.

Regards.

[nng_pub_sub.cpp.txt](https://github.com/nanomsg/nng/files/4306200/nng_pub_sub.cpp.txt)

**Comment by gdamore** [comment]
You need to subscribe to something.  Otherwise the messages get filtered.  See NNG_OPT_SUBSCRIBE.

**Comment by nmset** [comment]
It works with : 

`nng_socket_set(sub_sock_c, NNG_OPT_SUB_SUBSCRIBE, (void*) "", 0);`

Thank you.
