### ISSUE TITLE
CMake support is inconsistent and causes build failure

### ISSUE THREAD

**Issue by petr-nechaev** [nanomsg/nng#1221]
NNG version 1.13 and also master require CMake 3.13.  It makes nng hard to build on 'production' LTS platforms which typically lag 1-2 years behind.  Our system has just painfully migrated to CMake 3.8 for example.

See https://github.com/nanomsg/nng/blob/f09864b1343e4ce4b8fd7d7df0ed63061a39ef6c/CMakeLists.txt#L28
https://github.com/nanomsg/nng/commit/ee0b44406d2b658886760ea08c0af12781ab7e3a

README claims "To build this project, you will need a C99 compatible compiler and CMake version **3.1 or newer**." which is reasonable.

I believe that for such a basic middleware like NNG, every effort should be made to reduce requirements for the compiler and the platform.

As a separate note, switch to CMP0079 seems like a temporary workaround.

If we all agree, I could propose a patch.

**Comment by gdamore** [comment]
I forgot to update the the readme.  Sorry about that.

There are reasons that CMake 3.13 was chosen - -there are specific features which are required to support the external TLS libraries, and those require 3.13.

I'm not especially interested in going backwards.  CMake is trivial to update, and if you've updated to 3.8 then your 90% of the way there.   (Note that CMake has a PPA available for Ubuntu 16.04 and 18.04 if you're using Ubuntu releases.  I think they also have snaps available for RedHat releases.)

The alternative for you would be to run NNG1.2.x which does not require 3.13.  You'll lose some features, most notably the ability to use modern TLS 1.3 and the wolfSSL library.  (TLS 1.2 will still be an option with the mbed TLS library though.)

**Comment by petr-nechaev** [comment]
We use Yocto Linux builds for embedded hardware. Integration of such a system takes 2-3 years depending on complexity. CMake 3.13 is jut 

Do you want me to try to create and submit a workaround that allows to reduce CMake version requirement?  Or do you prefer me to keep it private?
I think C99 was chosen (vs C++14)  for nng for the same reason I am trying to reduce CMake version required.

**Comment by gdamore** [comment]
I thought with Yocto you were typically cross-compiling, meaning the tool chain requirements were on the build system, not the target.

You're welcome to submit a "fix", but unless you can cleanly make this work in a way that doesn't compromise the external module support for wolfSSL and mbedTLS (and future work I'm doing), I'm probably going to reject it.

**Comment by gdamore** [comment]
poky builds were updated to CMake 3.13 about a little over a year ago.  They're at 3.16 now.

https://git.yoctoproject.org/cgit/cgit.cgi/poky/log/meta/recipes-devtools/cmake

I'm not a Yocto person, but maybe that can help you?

**Comment by gdamore** [comment]
I've fixed the docs to indicate 3,13 is needed now.

**Comment by gdamore** [comment]
I'm closing this now.

**Comment by petr-nechaev** [comment]
Thank you for the documentation update
