### ISSUE TITLE
platforms support nng

### ISSUE THREAD

**Issue by foroughmajidi** [nanomsg/nng#1222]
Does nng library support Windows ARM (visual studio)platform?
If it is possible, please tell me the steps of building and running it .
Working X-64 platform,I built it as the following:
1-Download/clone NNG source
2-On Windows, create Command Prompt suitable for Visual Studio:
Run x64 Visual Studio Developer Command Prompt to create a 64-bit library (or x86 for 32-bit)
OR, run vcvars64.bat in cmd.exe (or vcvars32.bat)
3-Make sure cmake and Ninja are in PATH environment variable
4-Run:
mkdir build && cd build
cmake -G Ninja -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
ninja
 I got libnng.dll.a and it work.
But I don't know how to build it in ARM platform (visual studio).
thanks

**Comment by gdamore** [comment]
Yes. Sent from Mail for Windows 10 From: foroughmajidiSent: Monday, March 16, 2020 6:02 AMTo: nanomsg/nngCc: SubscribedSubject: [nanomsg/nng] platforms support nng (#1222) Does nng library support Windows ARM platform?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by foroughmajidi** [comment]
Does nng library support Windows ARM (visual studio)platform?
If it is possible, please tell me the steps of building and running it .
Working X-64 platform,I built it as the following:
1-Download/clone NNG source
2-On Windows, create Command Prompt suitable for Visual Studio:
Run x64 Visual Studio Developer Command Prompt to create a 64-bit library (or x86 for 32-bit)
OR, run vcvars64.bat in cmd.exe (or vcvars32.bat)
3-Make sure cmake and Ninja are in PATH environment variable
4-Run:
mkdir build && cd build
cmake -G Ninja -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
ninja
I got libnng.dll.a and it work.
But I don't know how to build it in ARM platform (visual studio).
thanks
    On Monday, March 16, 2020, 07:20:36 AM PDT, gdamore <notifications@github.com> wrote:  
 
 

Yes. Sent from Mail for Windows 10 From: foroughmajidiSent: Monday, March 16, 2020 6:02 AMTo: nanomsg/nngCc: SubscribedSubject: [nanomsg/nng] platforms support nng (#1222) Does nng library support Windows ARM platform?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by foroughmajidi** [comment]
I don't understand?!!!!!

**Comment by gdamore** [comment]
My email package apparently spewed HTML CSS at github when I tried to reply by email.

Yes, NNG should work fine with Windows on ARM.  (Having said that, I haven't actually *tested* it, as I don't have such a configuration to test with.)

**Comment by gdamore** [comment]
I believe the same instructions for building for ARM will work, but you may need to set some environment variable to do that so that CMake knows to use the ARM based tool chain.

**Comment by gdamore** [comment]
Google around, for example: https://gitlab.kitware.com/cmake/cmake/issues/18880

I imagine you're cross building, so the tool chain support for cross compiling is probably what you need.

**Comment by foroughmajidi** [comment]
I run vcvarsamd64_arm.bat in cmd.exe and 
mkdir build && cd build
cmake -G Ninja -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
ninja
but when I use libnng.dll.a in my project I get this error 
Error LNK1112	module machine type 'x64' conflicts with target machine type 'ARM'	libnng.dll.a(d000045.o)

**Comment by gdamore** [comment]
Did you have any luck?

**Comment by gdamore** [comment]
See: https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019

You need to use vcvarsx86_arm.bat or vcvarsamd64_arm.bat to set up a cross compilation tool chain.

I'm not sure this is actually sufficient -- I believe CMake needs to see that you're cross compiling as well, in order to skip certain tests that it otherwise normally performs.

I think vcvars.bat is just not sufficient to the task.

**Comment by gdamore** [comment]
(I just cleaned up the HTML nonsense.)  Unfortunately, I'm not really super equipped to help with cross compilation -- I can try to make it work, but I can't promise it will, as I don't have any ARM targets to test with.

**Comment by gdamore** [comment]
More detail: https://cmake.org/pipermail/cmake/2015-November/061927.html

**Comment by gdamore** [comment]
Also, lots more here: https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html

This is really just CMake standard stuff... cross compilation is hard. :/

There are also docs in the docs/ directory that talk about cross compilation.  See for example:

https://github.com/nanomsg/nng/blob/master/docs/BUILD_CROSSCOMPILE.adoc

https://github.com/nanomsg/nng/blob/master/docs/BUILD_ANDROID.adoc

and

https://github.com/nanomsg/nng/blob/master/docs/BUILD_IOS.adoc

I'm going to close this issue, as I believe I've done everything reasonably possible to make sure you have the information necessary to be successful.

If you run into specific bugs in NNG or our CMakeLists files (like the one you filed for #1225 ) then please let me know and I'll try to address.

**Comment by foroughmajidi** [comment]
I downloaded new version of nng library after you closed the bug and built it with android NDK ,It worked correctly.
You did me a great favor.
Thanks a lot.
    On Sunday, March 29, 2020, 11:02:09 AM PDT, gdamore <notifications@github.com> wrote:  
 
 


Also, lots more here: https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html

This is really just CMake standard stuff... cross compilation is hard. :/

There are also docs in the docs/ directory that talk about cross compilation. See for example:

https://github.com/nanomsg/nng/blob/master/docs/BUILD_CROSSCOMPILE.adoc

https://github.com/nanomsg/nng/blob/master/docs/BUILD_ANDROID.adoc

and

https://github.com/nanomsg/nng/blob/master/docs/BUILD_IOS.adoc

I'm going to close this issue, as I believe I've done everything reasonably possible to make sure you have the information necessary to be successful.

If you run into specific bugs in NNG or our CMakeLists files (like the one you filed for #1225 ) then please let me know and I'll try to address.
