### ISSUE TITLE
atomic check operation fails with android cross toolchain

### ISSUE THREAD

**Issue by foroughmajidi** [nanomsg/nng#1225]
Hello
I have problem in nng building:
 I want to build it for android platform with MinGW  as  following :
cmake -G "MinGW Makefiles" -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK=C:/Microsoft/AndroidNDK64/android-ndk-r16b -DCMAKE_ANDROID_STL_TYPE=gnustl_shared -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_MAKE_PROGRAM=C:/mingw/mingw64/bin/mingw32-make 

but  I got this error:

![Capture4](https://user-images.githubusercontent.com/51900859/77537527-7dceb700-6e5b-11ea-82f6-6100bf0a7327.PNG)

**Comment by gdamore** [comment]
Note t hat 1.2.6 and 1.3.0 are both  newer than what you have.

Having said that, there should be a CheckSanitizer.cmake file located in the cmake directory.  I'm not sure how you're building completely, but I believe that our CMake files direct cmake to search that directory.  Are you calling this within the context of a larger cmake?  If so you might need to arrange to add that file to your cmake search directory.

**Comment by gdamore** [comment]
Actually, looking more closely, it seems that you're missing the ".." at the end of that cmake line, so cmake doesn't know what your source directory is.  In fact they are explicitly warning about it.

**Comment by foroughmajidi** [comment]
Thanks for your answer,
I got a new version of nng and  added this folder ,mkdir externals
git submodule add git://github.com/arsenm/sanitizers-cmake.git externals/sanitizers-cmake , in nng ,and changed the line 42 into cmakelists to this:
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/externals/sanitizers-cmake/cmake" ${CMAKE_MODULE_PATH})
, but I got these errors!
![Capture6](https://user-images.githubusercontent.com/51900859/77815655-e6937a80-7079-11ea-8abe-ddc7854611d4.PNG)
 If it's possible tell me how to do it.

**Comment by foroughmajidi** [comment]
> Note t hat 1.2.6 and 1.3.0 are both newer than what you have.
> 
> Having said that, there should be a CheckSanitizer.cmake file located in the cmake directory. I'm not sure how you're building completely, but I believe that our CMake files direct cmake to search that directory. Are you calling this within the context of a larger cmake? If so you might need to arrange to add that file to your cmake search directory.

how can I do this?

**Comment by foroughmajidi** [comment]
> Actually, looking more closely, it seems that you're missing the ".." at the end of that cmake line, so cmake doesn't know what your source directory is. In fact they are explicitly warning about it.

If I add the".." I got these errors:
![Capture7](https://user-images.githubusercontent.com/51900859/77816884-cff22100-7083-11ea-82dc-9634c276851e.PNG)

**Comment by gdamore** [comment]
Hmm, that's not great.  We can operate without the atomics, but apparently this check is failing "hard", and it should not.  Having said that, its awfully strange that you would have a system without working atomic operations.

**Comment by gdamore** [comment]
Perhaps the check for atomic operations doesn't work with the cross toolchain.

**Comment by gdamore** [comment]
I'm going to change the title of this bug to reflect the problem with atomic detection, and leave it open.

**Comment by gdamore** [comment]
I'm also looking at your output.  It looks like the problem may also be related to your use of gcc 4.9.  I think gcc 4.9 may require explicitly passing -std=c11  -- it might not even support that at all.  Stay tuned.

**Comment by gdamore** [comment]
No, gcc added stdatomic.h and the underlying atomic stuff in 4.9.  I'm assuming your cross toolchain is a full gcc 4.9....

**Comment by foroughmajidi** [comment]
thanks for your response
I checked the gcc version on my system,it's gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
![Capture10](https://user-images.githubusercontent.com/51900859/77887402-5d1dad00-721f-11ea-97ad-39324047efd8.PNG)
