### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by foroughmajidi** [nanomsg/nng#1231]
I used nng for server code on my pc and client code on mobile (android),  I wrote the following codes 
1- nng_dial (sock, "tcp:// * :4444", NULL, 0) for server code and 
2- nng_dial (sock, "tcp://IPv4 Address:4444", NULL, 0) for client code 
IPv4 Address is IP of my system ,both server and client connect to my WiFi.

Are they correct?

**Comment by gdamore** [comment]
You can't use "*" in a dial operation.  Dial always needs an explicit address. 

The wildcard "*" corresponds to INADDR_ANY, and is meant for servers (where you want to listen to all IP interfaces, not just a specific named one.)

As this a question, not a defect report, I'm closing it.
