### ISSUE TITLE
AIO with message replaced.

### ISSUE THREAD

**Issue by iyer-arvind** [nanomsg/nng#1249]
I am facing an issue with a small change made on the example `raw.c` example, I am sure I am missing something fundamental here.

Adding these two lines after line 91:

``` patch
92,93d91
<     nng_msg_clear(work->msg);
<     nng_msg_append(work->msg, "test", strlen("test"));
``` 

... and the client hangs. If however, I do not clear, but append an extra message, as the example suspiciously comments on line 91:
``` c
91     // We could add more data to the message here.
```
all goes well, and the client receives the right data.

What would be the correct way to  to replace the message completely while replying?

**Comment by gdamore** [comment]
If you're using raw mode, then you're also deleting the very important SP protocol headers that are part of the original message.

Normally I discourage folks from using raw mode.  Its far better to use separate contexts for most of the use cases that raw mode was previously used.  (Basically raw mode lets you construct a wire-protocol level message - which must have the appropriate things in it like the pipe ID or backtrace, and request ID.  The details of the header vary from protocol to protocol.)

If you're wanting raw mode just to get to concurrency (multiple request outstanding for example), then you should just use the contexts -- see nng_ctx(5) or nng_ctx_open().

**Comment by iyer-arvind** [comment]
Thanks, for the very prompt answer!
