### ISSUE TITLE
Pair unit testing now blocks after duration changes

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#125]
What the subject says. I am analyzing the source changes for possible differences.

**Comment by mwpowellhtx** [comment]
@gdamore I do not see any differences apart from how time is treated.

*Chrono* prefers ``uint64_t`` by default. That was not a problem with the previous implementation. But now you've suddenly ripped the rug out from under that, but for the units of measure, milliseconds from microseconds.

Please put the base type back. The typical use case is something close to this:

```C++
#include <chrono>
// ...
#define CAST_DURATION_TO_MS std::chrono::duration_cast<std::chrono::milliseconds>
// ...
auto timeout = 1s;
objp->set_option_ms(O::receive_timeout_duration, CAST_DURATION_TO_MS(timeout).count());
```

There are a few more steps involved with the option getter, but this is just to illustrate.

**Comment by gdamore** [comment]
What I would do is define a new duration time:

using nng_duration = std::chrono::duration<int, std::milli>;

Probably then you can convert back and forth in C++ 11 idiomatic ways.

**Comment by gdamore** [comment]
To be clear, I'm not *dead* set against changing back to 64-bit signed integers; I just am not yet convinced that doing so wouldn't just be hiding incorrect assumptions in your code.  I thought pretty hard about this type change before I made it.

**Comment by gdamore** [comment]
One reason to go back to 64-bit values would be if we ever want to support durations of usec resolution -- 32-bits only covers a little over a half our in usec (if signed).

**Comment by mwpowellhtx** [comment]
You're correct, I believe Chrono supports ``duration<uint64_t, std::milli>`` by default. Sure it's possible to define my own representation, whether that's 64-bit unsigned integer or 32-bit signed integer, but I do not want to constrain that.

So when I say,

```C++
const auto timeout = 100ms;
```

I know what that means, i.e. ``duration<uint64_t, milli>(100)``.

I'm not saying 32-bit signed integers might not work. But what I am saying is that I don't want the library making that a constraint for me or for my consumers.

Indeed, corollary to your scaling observation, ever want to prove that to yourself, run conversions between time units, you quickly discover just how wide 32-bit signed integers really are (**NOT!**). Just as a side experiment. It's quite enlightening.

**Comment by gdamore** [comment]
So I'm not sure where we are then?  The original synopsis here had nothing to do with bit width, but a complaint that pair was hanging.  Is that still an issue?

**Comment by mwpowellhtx** [comment]
I'm okay with the approach for now. I doubt there will be scaling issues, but time will tell.
