### ISSUE TITLE
TLS auth fails with certificate signed by unknown authority

### ISSUE THREAD

**Issue by rolandjitsu** [nanomsg/nng#1250]
## NNG & Platform details.

NNG: `v1.1.1`
Platform: `Linux mypie 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux`
OS:
```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
mbedtls: `libmbedtls-dev/oldstable,oldstable,now 2.4.2-1+deb9u3 armhf`
mangos: `v3.0.0`

## Expected Behavior
I'm trying to setup an nng server and mangos client with TLS client auth enabled and I would expect it to work.

## Actual Behavior
First dial from the mangos client fails with:
```
x509: certificate signed by unknown authority
```
Subsequent requests hang forever.

## Steps to Reproduce
I'm using the following to setup the a req/rep loop on the nng side (more or less):
```cpp
int SetupReqRepTLS(nng_socket *sock, char *addr, const char *ca, const char *cert, const char *key)
{
    int rv;
    nng_listener l;

    if ((rv = nng_rep0_open(sock)) != 0)
        return rv;

    if ((rv = nng_listener_create(&l, *sock, addr)) != 0)
        return rv;

    if ((rv = SetupTLS(l, ca, cert, key)) != 0)
        return rv;

    if ((rv = nng_listener_start(l, 0)) != 0)
        return rv;

    return 0;
}

int SetupTLS(nng_listener l, const char *ca, const char *cert, const char *key)
{
    int rv;
    nng_tls_config *cfg;

    // Create TLS config
    if ((rv = nng_tls_config_alloc(&cfg, NNG_TLS_MODE_SERVER)) != 0)
        return rv;

    // Set server cert and key
    // https://nng.nanomsg.org/man/v1.3.0/nng_tls_config_own_cert.3tls.html
    if ((rv = nng_tls_config_own_cert(cfg, cert, key, NULL)) != 0)
        goto out;

    // Set TLS config
    // https://nng.nanomsg.org/man/v1.3.0/nng_listener_setopt.3.html
    if ((rv = nng_listener_setopt_ptr(l, NNG_OPT_TLS_CONFIG, cfg)) != 0)
        goto out;

    // Set the CA
    // https://nng.nanomsg.org/man/v1.3.0/nng_tls_config_ca_chain.3tls.html
    if ((rv = nng_tls_config_ca_chain(cfg, ca, NULL)) != 0)
        goto out;

    // Set auth mode to client auth
    // https://nng.nanomsg.org/man/v1.3.0/nng_tls_config_auth_mode.3tls.html
    if ((rv = nng_tls_config_auth_mode(cfg, NNG_TLS_AUTH_MODE_REQUIRED)) != 0)
        goto out;

out:
    nng_tls_config_free(cfg);
    return rv;
}

void StartRepLoop(nng_socket &sock)
{
    int rv;
    while (true)
    {
        char *buf = NULL;
        size_t sz;
        if ((rv = nng_recv(sock, &buf, &sz, NNG_FLAG_ALLOC)) != 0)
        {
            nng_free(buf, sz);
            continue;
        }

        if (buf == NULL || buf[0] == '\0')
        {
            nng_free(buf, sz);
            continue;
        }

        json res;
        res["data"] = 1234;
        SendRep(sock, res);

        nng_free(buf, sz);
    }
}

void SendRep(nng_socket &sock, json &res)
{
    std::string resStr = res.dump();
    nng_send(sock, &resStr[0], resStr.size(), 0);
}


int main()
{
    // nng req/rep socket
    nng_socket reqRepSock;
    char *reqRepURL = std::getenv("REQ_REP_URL");

    std::ifstream ca_f(std::getenv("CA_CERT"));
    std::string ca((std::istreambuf_iterator<char>(ca_f)),
                   std::istreambuf_iterator<char>());

    std::ifstream cert_f(std::getenv("SRV_CERT"));
    std::string cert((std::istreambuf_iterator<char>(cert_f)),
                     std::istreambuf_iterator<char>());

    std::ifstream key_f(std::getenv("SRV_KEY"));
    std::string key((std::istreambuf_iterator<char>(key_f)),
                    std::istreambuf_iterator<char>());

    int rv;
    if ((rv = SetupReqRepTLS(&reqRepSock, reqRepURL, ca.c_str(), cert.c_str(), key.c_str())) != 0)
        return -1;
   
    std::thread repLoopT(StartRepLoop,
                         std::ref(reqRepSock));
    repLoopT.detach();    

    return 0;
}
```

And on the mangos side I just do a one time request (for now, but I want to reuse the connection for multiple requests as the TLS encryption and handshakes takes quite some time):
```go
var crt tls.Certificate
var sock mangos.Socket
var err error

crt, err = tls.X509KeyPair([]byte("client cert"), []byte("client private key"))
if err != nil {
	return
}

cas := x509.NewCertPool()
cas.AppendCertsFromPEM([]byte("CA cert"))

cfg = &tls.Config{
	ServerName:   "my-service.local",
	Certificates: []tls.Certificate{crt},
	RootCAs:      cas,
	ClientAuth:   tls.RequireAndVerifyClientCert,
	// TODO: Same issue?
	// https://github.com/nanomsg/mangos/issues/94
	// InsecureSkipVerify: true,
}


sock, err = req.NewSocket()
if err != nil {
	return
}

opts := map[string]interface{}{}
opts[mangos.OptionTLSConfig] = cfg

d, err := sock.NewDialer("tls+tcp://127.0.0.1:1234", opts)
if err != nil {
	return
}

err = d.Dial()
if err != nil {
	return
}

defer sock.Close()

err = sock.Send([]byte("some data"))
if err != nil {
	return
}

data, err = sock.Recv()
if err != nil {
	return
}

...
```

I've used this [tutorial](https://jamielinux.com/docs/openssl-certificate-authority/sign-server-and-client-certificates.html) to generate the CA, server and client certs/keys.

If I set `InsecureSkipVerify` to true, I get back `EOF`.

I hope the above is enough to illustrate what I'm doing.

**Comment by gdamore** [comment]
So that message indicates that the mangos side does not recognize the authority (your CA) that you presumably used to sign the server's certificate.

This code is probably suspect:

cas.AppendCertsFromPEM([]byte("CA cert"))

Your "CA cert" needs to contain the bytes of the PEM file associated with your CA's public certificate.  Without that, mangos has no idea who your CA is, and that's why it's getting rejected.

**Comment by gdamore** [comment]
Also, if the mangos client is not doing client authentication, you can probably skip the process of loading or explicitly creating a server key -- the server key actually used will be supplied by the server.

**Comment by rolandjitsu** [comment]
> So that message indicates that the mangos side does not recognize the authority (your CA) that you presumably used to sign the server's certificate.

I see. So is the error msg coming from mangos or the `"crypto/x509"` lib?

> This code is probably suspect:
> 
> cas.AppendCertsFromPEM([]byte("CA cert"))
> 
> Your "CA cert" needs to contain the bytes of the PEM file associated with your CA's public certificate. Without that, mangos has no idea who your CA is, and that's why it's getting rejected.

Hmm, ok. The `CA cert` is the root (intermediate) certificate authority, no other certificate embedded with it. And with `crt, err = tls.X509KeyPair([]byte("server cert"), []byte("server private key"))` I actually meant `crt, err = tls.X509KeyPair([]byte("client cert"), []byte("client private key"))`.

So I have:
- 1 root CA cert
- 1 pair of server key/cert
- 1 pair of client key/cert

Both the server and client keys were signed by the CA. I've followed [these](https://jamielinux.com/docs/openssl-certificate-authority/sign-server-and-client-certificates.html) steps to issue the certs/keys.

My goal is to authenticate clients trying to connect to a server, so if the client doesn't have the right cert, it wouldn't be allowed to connect to the server. Could it be that I'm not generating the certs properly?

**Comment by rolandjitsu** [comment]
> Also, if the mangos client is not doing client authentication, you can probably skip the process of loading or explicitly creating a server key -- the server key actually used will be supplied by the server.

I made a typo in the description code example. Mangos is indeed the client and the server (nng c lib) is supposed to check the client's cert. So the mangos client is loading it's own client key/cert pair, is this unnecessary? Is it enough for the client to provide just the root CA cert?

Also, on the server side:
```cpp
// Set server cert and key
    // https://nng.nanomsg.org/man/v1.3.0/nng_tls_config_own_cert.3tls.html
    if ((rv = nng_tls_config_own_cert(cfg, cert, key, NULL)) != 0)
        goto out;

// Set the CA
    // https://nng.nanomsg.org/man/v1.3.0/nng_tls_config_ca_chain.3tls.html
    if ((rv = nng_tls_config_ca_chain(cfg, ca, NULL)) != 0)
        goto out;
```
Is the `cert` and `key` just the server key/cert pairs? And the `ca` is just the root CA's cert? Or am I supposed to concat these and pass it all as the `cert`?

**Comment by rolandjitsu** [comment]
I figured out the issue(s). Though, I still don't understand why it doesn't timeout when it dials with bad certificate configs.
