### ISSUE TITLE
build nng for android 

### ISSUE THREAD

**Issue by foroughmajidi** [nanomsg/nng#1251]
I built nng for android on my system 3 month ago on my system and got the libnng.so but now I want to build it on another system and I get this error.

![Capture2](https://user-images.githubusercontent.com/51900859/83966330-d9dba000-a8ce-11ea-8405-ea710d88ebb2.PNG)

 Would you please help me about this error?

**Comment by gdamore** [comment]
If you read the error message, it seems pretty clear that your tool chain is somehow broken.  The compiler selected cannot generate a functional binary.

This is not an NNG specific problem -- its a problem with your environment.
