### ISSUE TITLE
(android, termux, unix) nng_stream_get_addr anomaly

### ISSUE THREAD

**Issue by flexoron** [nanomsg/nng#1253]
Hello,
## NNG & Platform details
Android_10, Environment(App): Termux(94)
nng: master branch (6/8/2020)
clang version 9.0.1
$ termux-chroot
$ git clone https://github.com/nanomsg/nng.git
$ mkdir nng/build; cd nng/build; cmake -G Ninja ..; ninja; ninja test

## 
nng runs on Android under Termux and just one test fails:
tests/ipcsupp.c
Problem: Line 126, Convey("Socket name matches" ...

Termux: /tmp and /usr/tmp are hard links(same i-node)
and nng_stream_get_addr(c2, NNG_OPT_LOCADDR, &sa2)
picks /usr/tmp ???
sa2.s_ipc.sa_path = "/usr/tmp/ipcsupp_test0"
so
strcmp(sa2.s_ipc.sa_path, url + strlen("ipc://")
fails.
url+strlen(...) = "/tmp/ipcsupp_test0"

I guess this test fails under Unix as well when /tmp and /usr/tmp are hard
linked.

**Comment by gdamore** [comment]
This is actually going to return whatever the underlying operating systems getsockaddr() returns.  That's not anything we have control over.

Hard links have a bunch of extra complexities associated with them, and I'd generally discourage their use unless you have a very specific need for them.  (Typically the use case for them is in virtualization environments where you need to present the same node in different chroot jails, zones, or namespaces depending on the underlying system.)

**Comment by gdamore** [comment]
I think I'm probably going to close this.  The test case could be more resilient, but really the tests cannot accommodate every strange system configuration under the sun.  There's very little value to be had in trying to do so.

That said, if you are bothered enough by this to submit a PR to either skip that particular check on android or provide a better fix for Android, I'd be happy to review and merge as appropriate.  (I don't have an Android environment myself, so it's not easy for me to do that myself.)

**Comment by flexoron** [comment]
I agree. It is an OS issue.
btw under Linux here(gentoo) /usr/tmp is a soft link to /var/tmp.
So it is in no way a nng bug. (the main part of the test is successful)
100% tests passed, 0 tests failed out of 88
