### ISSUE TITLE
Socket closed unexpectedly

### ISSUE THREAD

**Issue by amunhoz** [nanomsg/nng#1258]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.
1.3.0
node-addon-api 3.0.0
Ubuntu 18.04
Using it from a binding to nodejs
Using nngcpp too.

## Expected Behavior
- I'm doing a stress test on a binding to nodejs, using IPC and it supose to keep sending/receiving messages until i stop it.  Using pair v1 protocol.
## Actual Behavior
- The dialer closes the socket at 61000 (around) messages received, tried many times and it happens at this point always
## Steps to Reproduce
- Hard to reproduce exactly, but the listener send the messages (around 50bytes each) and the dialer receive it and count. It does not look like a behaviour from nngcpp or node-addon-api. Only happens with dialer. Sender and receiver run in different processes.
If possible, just help-me find what could be.

**Comment by amunhoz** [comment]
yep.. it's really happening.

**Comment by codypiersall** [comment]
If you could show the code that's doing it that would be ideal.  C would be the best, but even the nodejs code would be helpful.

**Comment by amunhoz** [comment]
I've created a git repository with most part of the code here:
https://github.com/amunhoz/nng_application

ps. the nodejs application is functional

**Comment by codypiersall** [comment]
That sure is a lot of code :sweat_smile: I was hoping for something a  little more minimal.  So from the code in that repository, how can the issue be reproduced?  What commands need to be run?  I've never done any nodejs dev before, so it may be obvious to some people but it's not to me... and I suspect Garrett doesn't do nodejs either.  (Sorry if that's not true and I'm misrepresenting you Garrett!)

**Comment by amunhoz** [comment]
From nodejs, you can run:
$ node ./test/snd.js
and at the same time
$ node ./test/recv.js

Here the socket closes after 61000 messages

However, to run the c++ code could be more complex.

**Comment by amunhoz** [comment]
I'm closing it because i need to collect more info... it looks like the addon architecture is influencing the situation
