### ISSUE TITLE
nng_msg_alloc and size parameter

### ISSUE THREAD

**Issue by PunishedSnakePr** [nanomsg/nng#1260]
Is it really intended that the size parameter of nng_msg_alloc finally determines message's current body chunk length though nothing has been appended so far? I just appended some bytes to the message after calling nng_msg_alloc with a size of 1 MB and I ran into heavy performance issues when using req-rep sockets with TLS as the whole 1 MB got encrypted / decrypted and not only my few bytes. My workaround (and the way I felt like it should work in general) was to call nng_msg_clear right after nng_msg_alloc which encrypted/decrypted only the few bytes I really appended and not the whole memory I reserved.

Any thoughts or clarifications on this are welcome!

**Comment by gdamore** [comment]
That is the intention.  Mostly we expect folks to either:

Use nng_msg_alloc with a size and then use nng_msg_body() pointer and write stuff directly (perhaps via memcpy).

Or, use nng_msg_append() family of functions to append to the body.

If you want to preallocate the message, but not fill it, as an optimization, then nng_msg_alloc followed by nng_msg_clear is indeed the correct approach, and it was how I intended this to be used.

If you're only sending a few bytes in your messages, I'd recommend allocating a message size of 0, and then just appending the bytes.  The allocation logic attempts to ensure that there is some space so you can append up to about 64 bytes without having to reallocate.

**Comment by PunishedSnakePr** [comment]
Got it! Thank u very much!
