### ISSUE TITLE
Bad format TCP address causes null pointer exception

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#127]
That's a pretty hard break for what could be an consumer's innocent mistake. In the function:

```C
static int nni_tcp_parse_pair(char *pair, char **hostp, char **servp);
```

I know your API is geared for C, but have you considered something like an internal usage of ``std::regex`` for purposes of quickly and efficiently matching up patterns such as this and not leaving it up to something like a *"missing pair"*?

Case in point:

```
http://123.456.789.12312332
```

Where *12332* was supposed to be the port number, but for the missing colon. The parser wouldn't know what's a port or not, and rightly so, but a null pointer exception is a case that should be trapped.

Regex could do that for you pretty easily.

**Comment by gdamore** [comment]
Ok, so NULL pointer exception is *clearly* a nasty bug.  To be clear, do you have a TCP address string that causes this problem? I need a specific example so I can see the bug and fix it.  (Probably, I will go ahead and review the code anyway.)

Using a regex library is a non-starter.  It shouldn't be hard to get this right anyway -- and I am unwilling to create additional external dependencies.  (Yeah, C++ has a bunch of things available in std:: but standard C lacks most of that.)

**Comment by gdamore** [comment]
I'm pretty sure I see the problem now... 

It looks like I failed to consider the case where a service (":") delimited is absent.

**Comment by gdamore** [comment]
Actually i think just initializing serv to NULL and checking for it being non-NULL will solve the problem.

**Comment by gdamore** [comment]
Need to make sure I add test coverage for this to the test suite, too.

**Comment by gdamore** [comment]
(And yes, the library should *never* crash on inputs that could come from an end-user like this.  There are circumstances where we insist that the API be passed valid data -- so passing a bad pointer to a getopt function could cause a crash -- but that's not something we can guard against.  But for things like this, that would be outside the obvious control of application or layered library code, and triggered by perhaps bogus user input or other environmental conditions, we need to be rock solid.  Crashing on a bad URL is unacceptable.)

**Comment by mwpowellhtx** [comment]
I provided the case I had in this instance.

**Comment by mwpowellhtx** [comment]
@gdamore Thanks for looking into this. Please take to mean helpful friendly suggestions. I appreciate the dependencies concern, however. Cheers. :+1:
