### ISSUE TITLE
win_io.c  line 64l nni_win_io_init  71 line

### ISSUE THREAD

**Issue by Lyuxi8006** [nanomsg/nng#1273]
win_io.c  line 64l nni_win_io_init  71 line  

Do you really need to create an event for each connection? Event is a kernel object, will it affect efficiency?

**Comment by gdamore** [comment]
I think so, but I could be mistaken.  I'm by no means a Win32 expert.  I think this events lets us easily discriminate between I/O events on specific files.  Do you have a specific reason for concern?  Have you got test results that indicate a problem?

**Comment by gdamore** [comment]
So let me clarify.  I think we do need an event for each connection, and I do not think it will affect efficiency in the least.  Just being a kernel object is not necessarily a problem -- indeed the connection itself has kernel state associated with it.  We assume that the Windows kernel handles multiple event objects efficiently, such that there is no O(n) algorithms involved.  Experimentally that seems to be the case.
