### ISSUE TITLE
Test timeouts on FreeBSD

### ISSUE THREAD

**Issue by swills** [nanomsg/nng#1275]
## NNG & Platform details.

nng 1.3.2 on FreeBSD

## Expected Behavior
Test succeed
## Actual Behavior

The following tests FAILED:
          1 - compat_tcp_test (Timeout)
         20 - bug1247 (Timeout)
         24 - device (Timeout)
         27 - httpclient (Timeout)
         28 - httpserver (Timeout)
         29 - idhash (Timeout)
         30 - inproc (Timeout)
         31 - ipc (Timeout)
         32 - ipcperms (Timeout)
         33 - ipcsupp (Timeout)
         34 - ipcwinsec (Timeout)
         37 - multistress (Timeout)
         38 - nonblock (Timeout)
         40 - pipe (Timeout)
         42 - resolv (Timeout)
         43 - scalability (Timeout)
         44 - set_recvmaxsize (Timeout)
         45 - stats (Timeout)
         48 - tcpsupp (Timeout)
         49 - tcp (Timeout)
         50 - tcp6 (Timeout)
         51 - transport (Timeout)
         52 - udp (Timeout)
         54 - ws (Timeout)
         56 - bus (Timeout)
         57 - pipeline (Timeout)
         58 - reqctx (Timeout)
         59 - reqstress (Timeout)
         64 - compat_msg (Timeout)
         72 - compat_reqttl (Timeout)
         74 - compat_surveyttl (Timeout)
         75 - compat_ws (Timeout)

## Steps to Reproduce

Run tests. I can dig more into this, but I looked at the first timeout (compat_tcp_test) and the last thing I see is:

...nng/src/compat/nanomsg/compat_tcp_test.c:76: Check nn_close(sb) == 0... ok

Then it hangs. What is the right approach to investigating these?

**Comment by gdamore** [comment]
This looks like something badly wrong in the FreeBSD port - maybe in the kqueue code.  I would need to investigate - I don't have an image handy at present but I will try to look sometime this week.

**Comment by gdamore** [comment]
I've installed FreeBSD in a HyperV VM (color me impressed btw, speedy as heck!) and have reproduced.  Hopefully I'll sort this out this weekend.
