### ISSUE TITLE
UDP: nng_aio_result failed

### ISSUE THREAD

**Issue by foroughmajidi** [nanomsg/nng#1282]
In my code I used nng but when I opened udp socket and then I wanted to send message got error 
:

const char* _trace_info = "_io_udp_socket";

    if (!pSocket || !pMessage || !pMessageLength)
    {
        W_ASSERT(false, "parameters are NULL. trace info: _io_udp_socket");
        return NNG_ENOARG;
    }
    if (pSocketMode != two_way_dialer && pSocketMode != two_way_listener)
    {
        W_ASSERT(false, "pSocketMode must be one of the following enums: two_way_dialer or two_way_dialer. trace info: _io_udp_socket");
        return NNG_ENOARG;
    }

    W_RESULT _rt = W_SUCCESS;
    size_t _sent_len = 0;
    const size_t _buf_len = (pSocketMode == two_way_dialer ? (*pMessageLength + 1) : *pMessageLength);

    nng_sockaddr* _sa = (nng_sockaddr*)pSocket->sa;
    nni_plat_udp* _udp = (nni_plat_udp*)pSocket->u;
    nng_aio* _aio= (nng_aio*)pSocket->a;
    

    nng_iov _iov;//(nng_iov*)pSocket->i;
    _iov.iov_buf = pMessage;
    _iov.iov_len = _buf_len;

    _rt = nng_aio_set_iov(_aio, 1,&_iov);
    if (_rt)
    {
        _net_error(_rt, "nng_aio_set_iov failed", _trace_info);
        goto out;
    }
    _rt = nng_aio_set_input(_aio, 0, _sa);
    if (_rt)
    {
        _net_error(_rt, "nng_aio_set_input failed", _trace_info);
        goto out;
    }

    //send buffer over udp
    if (pSocketMode == two_way_dialer)
    {
        nni_plat_udp_send(_udp, _aio);
    }
    else
    {
        nni_plat_udp_recv(_udp, _aio);
    }

    //wait
    nng_aio_wait(_aio);

    _rt = nng_aio_result(_aio);
   if (_rt )
    {
        _net_error(_rt, "nng_aio_result failed", _trace_info);
        goto out;
    }

    _sent_len = nng_aio_count(_aio);
    if (_sent_len != _buf_len)
    {
        _net_error(_rt, "length of the sent buffer is not equal to inputted buffer", _trace_info);
        goto out;
    }

out:
    return _rt;
}

in my programm First I opened udp socket and then sent message but in nng_aio_result I got error

**Comment by gdamore** [comment]
The UDP APIs are not public.  You'll note that by the nni_ prefix, which means that they won't be exported symbols in a DLL for example.

Probably the aio length field is not getting set by the platform code; that's not entirely unreasonable as with sending UDP, you either send the whole thing, or nothing.  (The IP stack may fragment, but that's beneath our ability to detect.)

Either way, you're using an API that is not yet meant for general application use.  (The only internal consumer for this API is the ZeroTier code.)

**Comment by foroughmajidi** [comment]
I meant which factors caues this(nng_aio_result failed) .my code is work but in nng_aio_result return 7 and this means that object closed how can I solve it?I opened one socket and sent message .Is there any other work that should be doe?

**Comment by gdamore** [comment]
I don't see the whole of your code (particularly where you open the socket.).  That error usually means that the socket isn't open (nni_plat_udp_open()) or has been closed (nni_plat_udp_close()).

As I've indicated, you're using undocumented internal functions, so YMMV.  Officially NNG has no documented support for UDP at this time.

**Comment by foroughmajidi** [comment]
Thanks for your help.
