### ISSUE TITLE
nng get error when building for android with tls

### ISSUE THREAD

**Issue by foroughmajidi** [nanomsg/nng#1294]
I built tls as following:
cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL=21 -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_STATIC_LIB="On" -DBUILD_SHARED_LIBS="Off" ..
make 
it was ok but when build nng as following I got these warning:
  cmake -G "Unix Makefiles"  -DCMAKE_SYSTEM_NAME=Android -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_ANDROID_NDK=/home/forogh/Downloads/android-ndk-r21d-linux-x86_64/android-ndk-r21d  -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DNNG_ENABLE_TLS=ON -DMBEDTLS_TLS_LIBRARY=/home/forogh/Pictures/mbedtls-2.7.17/build/library -DMBEDTLS_CRYPTO_LIBRARY=/home/forogh/Pictures/mbedtls-2.7.17/build/library -DMBEDTLS_X509_LIBRARY=/home/forogh/Pictures/mbedtls-2.7.17/build/library -DMBEDTLS_INCLUDE_DIR=/home/forogh/Pictures/mbedtls-2.7.17/build/include

![nng](https://user-images.githubusercontent.com/51900859/91975296-6d890500-ed34-11ea-8d4a-d11e04a44daa.png)

after running make command ,it  fails several times and finally it runs ok for just one time, why does this happen?

**Comment by gdamore** [comment]
It looks to me like you failed to pass the *full* library names in -DMBEDTLS_TLS_LIBRARY (and your MBEDTLS options.)

The tooling I wrote depends on getting the full path to those libraries.

**Comment by gdamore** [comment]
I'm going to close this -- I think I answered the question.
