### ISSUE TITLE
build nng with tls for android: question 

### ISSUE THREAD

**Issue by foroughmajidi** [nanomsg/nng#1295]
https://github.com/nanomsg/nng/issues/1294#issue 
If you pay attention , I set the path of include library for mbedtls and it is the full name of path .

as a result , do you think the static library I got, is built by tls?

**Comment by gdamore** [comment]
The static library will include references to symbols from the mbedTLS libraries, but you will need to link against all of them when building applications.  Typically you would list nng first, and the other libraries in order afterwards.  This is typical for how static libraries are used.

**Comment by FabianKnapp** [comment]
Try the following (understand it and modify for your needs!):

```
git clone -b mbedtls-2.24.0 git@github.com:ARMmbed/mbedtls.git
git clone -b v1.3.2 git@github.com:nanomsg/nng.git
cd mbedtls
mkdir installed
mkdir build
cd build
cmake -DENABLE_TESTING=Off -DUSE_SHARED_MBEDTLS_LIBRARY=On -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../installed/ <YOUR_CUSTOM_CROSS_COMPILE_SETTINGS> ..
make install
cd ../../nng
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DNNG_ENABLE_TLS=ON -DMBEDTLS_ROOT_DIR=../../mbedtls/installed -DMBEDTLS_TLS_LIBRARY=../../mbedtls/installed/lib/libmbedtls.so -DMBEDTLS_CRYPTO_LIBRARY=../../mbedtls/installed/lib/libmbedcrypto.so -DMBEDTLS_X509_LIBRARY=../../mbedtls/installed/lib/libmbedx509.so -DMBEDTLS_INCLUDE_DIR=../../mbedtls/installed/include -DBUILD_SHARED_LIBS=ON <YOUR_CUSTOM_CROSS_COMPILE_SETTINGS> ..
make
```

**Comment by gdamore** [comment]
Unfortunately, I can't really answer questions for how to build stuff on Android, as I don't develop for that platform.  NNG works like any other library consumer of mbedTLS, and itself exports stuff.  All this should Just Work with CMake, but this does assume some basic familiarity with CMake and -- if you are cross compiling -- with using the cross compilation tool chain.
