### ISSUE TITLE
Documentation for the API

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#13]
Formal API documentation is desired.

We should provide this in asciidoc form, just like nanomsg, and structure as man pages.

**Comment by gdamore** [comment]
I'm also investigating the use of cldoc to extract documentation from the code directly.  That might actually be better.

**Comment by skyformat99** [comment]
It's going really fast. :+1: 
If possible, Can you describe the design idea of the code.

**Comment by gdamore** [comment]
This is planned.

**Comment by gdamore** [comment]
Someone who is a good technical author could contribute here!  That said the API is still not final yet, so docs *might* be premature.  The past 2 weeks there has been a lot of API churn.

**Comment by gdamore** [comment]
Huge huge progress is made here.  There are a few pages still missing, but I'm close to being able to close this issue.

**Comment by gdamore** [comment]
Documentation is now largely complete.  There might be some missing things, but at the moment I can't think of any.  I'm closing this.  If any things are not documented that should be, file specific issues for them.
