### ISSUE TITLE
Cannot read from socket (client app).

### ISSUE THREAD

**Issue by mikehouse** [nanomsg/nng#1303]
Hello. I cannot figure out what I do wrong. Could someone help me where to look for the issue. Thanks in advance.

## NNG & Platform details.

- nng v1.3.2
- iOS 14+
- pure c language

## Expected Behavior

Able to receive messages from socket.

## Actual Behavior

Cannot receive messages from socket and seems a stream gets closed.

## Steps to Reproduce

```c
int fatal(int rv)
{
	fprintf(stderr, "%s\n", nng_strerror(rv));
        return 1;
}

int make_stream_wss() {
	nng_stream_dialer *dialer;
	nng_aio *aio;
	nng_stream *stream;
	int rv;
	nng_tls_config *cfg;
	nng_url *url;

        // Also I cannot create stream with url if it doesn't have `/` at the end.
	if ((rv = nng_url_parse(&url, "wss://x.x.x.x:5000/")) != 0) {
		return fatal(rv);
	}
	if ((rv = nng_stream_dialer_alloc_url(&dialer, url)) != 0) {
		return fatal(rv);
	}
	if ((rv = nng_aio_alloc(&aio, NULL, NULL)) != 0) {
		return fatal(rv);
	}
	if ((rv = nng_tls_config_alloc(&cfg, NNG_TLS_MODE_CLIENT)) != 0) {
		return fatal(rv);
	}
	if ((rv = nng_tls_config_ca_chain(cfg, ca, NULL)) != 0) {
		return fatal(rv);
	}
        // skip validation for convenience.
	if ((rv = nng_tls_config_auth_mode(cfg, NNG_TLS_AUTH_MODE_NONE)) != 0) {
		return fatal(rv);
	}
	if ((rv = nng_stream_dialer_set_ptr(dialer, NNG_OPT_TLS_CONFIG, cfg)) != 0) {
		return fatal(rv);
	}

        // A server sees our attempt to connect and sends to us a success message.
	nng_stream_dialer_dial(dialer, aio);
	nng_aio_wait(aio);

	if ((rv = nng_aio_result(aio)) != 0) {
		return fatal(rv);
	}

	if ((stream = nng_aio_get_output(aio, 0)) == NULL) {
		return fatal(3);
	}

	printf("did open stream\n");

	const size_t buf_len = 1024;
	nng_aio *aio_req;
	nng_iov iov;
	static char read_buf[buf_len];

	if ((rv = nng_aio_alloc(&aio_req, NULL, NULL)) != 0) {
		return fatal(rv);
	}

	nng_aio_set_timeout(aio_req, NNG_DURATION_INFINITE);

	iov.iov_buf = read_buf;
	iov.iov_len = buf_len;

	if ((rv = nng_aio_set_iov(aio_req, 1, &iov)) != 0) {
		return fatal(rv);
	}

	while (true) {
		memset(read_buf, 0, buf_len);

		nng_stream_recv(stream, aio_req);
		nng_aio_wait(aio_req);

		if ((rv = nng_aio_result(aio_req)) != 0) {
                        // All the time I'm getting 'Object closed' error.
			return fatal(rv);
		}

		printf("received %zu bytes\n", nng_aio_count(aio_req));
		printf("data: %s\n", read_buf);
	}
}
```

There is a js backend with code something like this:

```javascript
// "wss://x.x.x.x:5000"
this.websocketServer.on('connection', (ws, req) => {
    ws.send('{"status": "ok"}')
}
```

I make a client app for iOS. When I use native socket API from iOS SDK I able to get the messages from the backed, iOS SDK socket API:

```swift
let task = URLSession.shared.webSocketTask(with: URL(string: "wss://x.x.x.x:5000"))
// set callback for incoming messages.
```

Just for testing also made a ruby script to test the socket connection and it also works:

```ruby
require 'faye/websocket'
require 'eventmachine'

EM.run {
  ws = Faye::WebSocket::Client.new('wss://x.x.x.x:5000', [], :tls => {
    :verify_peer => false
  })

  ws.on :message do |event|
    p [:message, event.data]
  end
}
```

Using socket API from `nng` library I cannot make it working. I see at the backend logs that `connection` function called on `nng_stream_dialer_dial(dialer, aio)`. But then in `while` block when calling `nng_aio_result()` I'm getting `Object closed` error. The interesting part is that this code works for local iOS device stream listener.

**Comment by gdamore** [comment]
Check to make sure you're using binary format.  I think text mode isn't support (though I'm not 100% certain -- there was an issue for this but I don't remember offhand if I fixed it or not).

**Comment by gdamore** [comment]
You might also see if you can obtain the entire set of headers in the negotiation from the server -- I think there's a way to collect them from NNG as well.

**Comment by gdamore** [comment]
The issue of needing a trailing "/" is a known bug -- I believe there is a ticket filed for it already.

**Comment by mikehouse** [comment]
Found https://github.com/nanomsg/nng/issues/914, https://github.com/nanomsg/nng/issues/955, seems only binary format supported for now as you've said. I asked the backend devs to use binary data format for my ip and after this it started working.

```javascript
if (ip === 'x.x.x.x') {
    const array = new Float32Array();
    // ... filling the array.
    ws.send(array);
}
```

But there are tons of code written to work with json like message format on my project 😢
Thank you. Awesome project! Will look for other solutions though!

**Comment by gdamore** [comment]
The issue is not JSON, the issue is that properly supporting UTF-8 requires some extra work to validate messages.  Originally NNG was designed for binary message formats (not for a general purpose stream transport), so we didn't have support for this because we *required* a binary format (in order to send very specific binary encoding details). 

As NNG has been extended into working in different areas, some of these shortcomings have become evident. 

However, every modern browser supports binary format.  So, really there is no reason to restrict oneself to the text format. You can still deliver JSON over binary format, that's not a problem.  The problem is that when you require the UTF-8 to be validated by the transport layer, which comes at a cost.

I will probably address this properly at some point.
