### ISSUE TITLE
Non-blocking send on rep sockets always fails

### ISSUE THREAD

**Issue by BohemianXen** [nanomsg/nng#1304]
We have been working on a Qt project that utilises a host of req/rep sockets. Up until now we had been using nng v1.2.6 with no issues but upon updating to the latest release, v1.3.2, our pre-existing unit tests have shown a reproducible error; non-blocking calls to `nng_sendmsg` _always_ fail  (code `NNG_EAGAIN`) when using rep sockets that have received a message.  This occurs even in isolation, with no other ipc traffic, and while also allowing for multiple send attempts. Blocking calls still work as usual so this has been our workaround for the time being.

## NNG & Platform details.

- nng v1.3.2
- Ubuntu 18.04.5 LTS
- C/C++

## Expected Behaviour

0 return value indicating successful send of a received message when using a non-blocking call to `nng_sendmsg` on a rep socket.

## Actual Behaviour

Return value of 8 (`NNG_EAGAIN`) every time.

## Steps to Reproduce

1. Open req0 and rep0 sockets
2. Start listening on the rep socket
3. Dial using the req socket
4. Send an `nng_msg` from the req socket (blocking or non-blocking, matters not)
5. Receive the message using the rep socket (blocking or non-blocking, matters not)
6. Attempt to send a reply message using a non-blocking call to `nng_sendmsg`

Typically, under normal use, you can repeat step 6 if the message is not accepted at first (possibly due to backpressure). However, this is not the case here. Replacing step 6 with a blocking send or reverting back to nng v1.2.6 allows the test to pass again.

A verbose demonstration can be observed below.

 ```
int32_t testRepNonBlockSend(void)
{
    const char * const testUrl   = "ipc:///tmp/ut_nng_rep0.ipc";
    const int32_t      testValue = 265338;
    nng_socket         reqSock   = NNG_SOCKET_INITIALIZER;
    nng_socket         repSock   = NNG_SOCKET_INITIALIZER;
    nng_msg *          pTxMsg    = NULL;
    nng_msg *          pRxMsg    = NULL;

    // Start listening on the rep socket and dial
    int32_t rv = nng_rep0_open(&repSock);
    if (0 == rv)
    {
        rv = nng_listen(repSock, testUrl, NULL, 0);
    }
    if (0 == rv)
    {
        rv = nng_req0_open(&reqSock);
    }
    if (0 == rv)
    {
        rv = nng_dial(reqSock, testUrl, NULL, 0);
    }

    // Prepare the tx and rx messages
    if (0 == rv)
    {
        rv = nng_msg_alloc(&pTxMsg, sizeof(testValue));
    }
    if (0 == rv)
    {
        rv = nng_msg_alloc(&pRxMsg, sizeof(testValue));
        if (0 != rv)
        {
            nng_msg_free(pTxMsg);
        }
    }

    // Append an arbitrary value to the request message then send it
    if (0 == rv)
    {
        rv = nng_msg_append(pTxMsg, &testValue, sizeof(testValue));
    }
    if (0 == rv)
    {
        rv = nng_sendmsg(reqSock, pTxMsg, 0);
        if (0 != rv)
        {
            nng_msg_free(pTxMsg);
        }
    }

    // Receive the message
    if (0 == rv)
    {
        rv = nng_recvmsg(repSock, &pRxMsg, 0);
    }

    // Attempt to send the reply using a non-blocking call. This will always fail (even with
    // multiple attempts) when using nng v1.3.2. When using nng v1.2.6, the send works.
    if (0 == rv)
    {
        rv = nng_sendmsg(repSock, pRxMsg, NNG_FLAG_NONBLOCK);
        if (0 != rv)
        {
            nng_msg_free(pRxMsg);
        }
    }

    nng_close(repSock);
    nng_close(reqSock);

    return rv;
}
```

This was tested from C++ when wrapped using the gtest framework:

```
TEST(TestFixture, testRepNonBlockSend)
{
    EXPECT_EQ(0, testRepNonBlockSend());
}
```

Console Output:
```
Expected equality of these values:
  0
  testRepNonBlockSend()
    Which is: 8
```

**Comment by gdamore** [comment]
Looking at this now.  I *think* the problem may be the rearchitecture of REP which avoids some extra queueing layers.  Stay tuned.

**Comment by gdamore** [comment]
8 is NNG_EAGAIN btw.

**Comment by gdamore** [comment]
I see the code where this is happening.  The refactor use nng_aio_schedule() results in always returning NNG_EAGAIN.  We need to check to see if we can complete the request immediately before calling that.

**Comment by gdamore** [comment]
So we shouldn't call nni_aio_schedule() until we know we are going to sleep.

Fixing this breaks a test case case, that incorrectly tested for a zero timeout.
