### ISSUE TITLE
Sub contexts/AIOs can share a single nng_msg

### ISSUE THREAD

**Issue by 0xERIC** [nanomsg/nng#1308]
The sub half of pub/sub can use contexts/AIOs such that multiple subscribers can share a single socket. Each AIO should completely own a version of the received `nng_msg`; mutating the message contained by one AIO should not affect another AIO. However, if multiple subscribers call `nng_ctx_recv` before a message is published, those subscribers will all share a single version of the received `nng_msg`. If one mutates it, the others will see that mutation.

## NNG & Platform details.

C++, NNG 1.3.0, Ubuntu 16.04

## Expected Behavior

If multiple subscribers are using contexts to share a socket, they should each get a separate copy of any message that matches their topic.

## Actual Behavior

Subscribers all appear to share a single copy of messages that they receive.

## Steps to Reproduce

1. Open a pub socket
2. Open a sub socket
3. Create multiple contexts/AIOs attached to the sub socket, each with an empty topic
4. Call `nng_ctx_recv` for each subscriber
5. Publish a message
6. Mutate the message in the first subscriber that receives it
7. Verify the contents of the message in the other subscribers; it will have changed
8. (Optionally) check the ref count of the message taken from the AIO; it will be higher than 1

After looking at the source, I think this is only an issue if `nng_ctx_recv` is called while no messages are queued. If there is a message when `nng_ctx_recv` is called I believe the message will be duplicated as it should be. I haven't tested that though.

```
// clang++-10 repro.cc -lnng -lpthread
#include <string.h>

#include <cassert>
#include <chrono>
#include <functional>
#include <string>
#include <thread>

#include <nng/nng.h>
#include <nng/protocol/pubsub0/pub.h>
#include <nng/protocol/pubsub0/sub.h>

#define URL "ipc:///tmp/pubsub.ipc"

void
server()
{
    // Set up socket
    nng_socket sock;
    assert(nng_pub0_open(&sock) == 0);
    assert(nng_listen(sock, URL, NULL, 0) == 0);

    // Wait for clients to connect
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));

    // Broadcast 0-9
    for (int i = 0; i < 10; i++) {
        char data[1024] = {};
        strcpy(data, std::to_string(i).c_str());
        assert(nng_send(sock, data, strlen(data) + 1, 0) == 0);

        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }

    // Wait for clients to shutdown
    std::this_thread::sleep_for(std::chrono::milliseconds(50));
}

void client_cb(void *arg);

struct Client {
    int i;
    nng_aio *aio;
    nng_ctx ctx;

    void run(nng_socket *sock) {
        // Set up AIO/context
        assert(nng_aio_alloc(&aio, client_cb, this) == 0);
        assert(nng_ctx_open(&ctx, *sock) == 0);
        assert(nng_ctx_setopt(ctx, NNG_OPT_SUB_SUBSCRIBE, "", 0) == 0);

        // Start receiving from 0
        i = 0;
        nng_ctx_recv(ctx, aio);
    }
};

void
client_cb(void *arg)
{
    auto client = static_cast<Client *>(arg);

    // Receive and make sure the count is right
    assert(nng_aio_result(client->aio) == 0);
    nng_msg *msg = nng_aio_get_msg(client->aio);
    auto msg_str = std::string(static_cast<char *>(nng_msg_body(msg)));
    if (msg_str != std::to_string(client->i)) {
        printf("Expected message (%p) with value %d but got \"%s\"!\n",
               msg,
               client->i,
               msg_str.c_str());
    }

    // Mess with the message by doubling the value; this shouldn't cause
    // problems for other clients :o
    nng_msg_clear(msg);
    char data[1024] = {};
    strcpy(data, std::to_string(client->i * 2).c_str());
    assert(nng_msg_append(msg, data, strlen(data) + 1) == 0);

    // Get ready to receive again
    nng_msg_free(msg);
    client->i++;
    nng_ctx_recv(client->ctx, client->aio);
}

int
main()
{
    // Wait for server to startup
    std::thread server_thread{server};
    std::this_thread::sleep_for(std::chrono::milliseconds(10));

    // Create shared client socket
    nng_socket sock;
    assert(nng_sub0_open(&sock) == 0);
    assert(nng_setopt(sock, NNG_OPT_SUB_SUBSCRIBE, "", 0) == 0);
    assert(nng_dial(sock, URL, NULL, 0) == 0);

    // Create clients
    Client a, b, c;
    std::thread client_thread_a{std::bind(&Client::run, &a, &sock)};
    std::thread client_thread_b{std::bind(&Client::run, &b, &sock)};
    std::thread client_thread_c{std::bind(&Client::run, &c, &sock)};

    // Wait for everything to finish
    client_thread_a.join();
    client_thread_b.join();
    client_thread_c.join();
    server_thread.join();

    assert(a.i == 10 && b.i == 10 && c.i == 10);
    return 0;
}
```

**Comment by 0xERIC** [comment]
Noting that I'm filing this based on Discord discussion beginning [here](https://discord.com/channels/639573728212156478/639574541743423491/770692002709897287).

**Comment by gdamore** [comment]
So this is definitely a bug... the nni_msg_unique() is called only when the thread calls recv *after* the message is queued.

We need to make the message unique before putting it on the per context "lmq".
