### ISSUE TITLE
Message pipe (in-)subordination

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#131]
Hello,

So my question is re: the nature of message pipe in relation to its parent entity, i.e. the message itself, etc.

When the message goes out of scope and its resources are cleaned up, I gather this also cleans up whatever resources were associated with the pipe, but I just wanted to get a better understanding of that.

In other words, it is entirely plausible for closing the pipe to return 0 (OK), or ENOENT, when its parent entry has been dealt with.

Thanks!

**Comment by gdamore** [comment]
The message carries a pipe ID, and the pipe ID is not guaranteed to still exist at the time the message is passed to the application.  I've been thinking about fixing this to ensure that the message carries a "reference count" on the pipe to ensure that the pipe "exists" (but may not be open) at that time too, but that is not currently the case.

Generally, I expect *very* few applications to ever explicitly close pipes.  This mostly exists for apps that want to reject a misbehaving peer, or a peer that fails some kind of security check.

But yes, returning NNG_ENOENT in response to pipe related operations is perfectly possible.

**Comment by mwpowellhtx** [comment]
Great, I just wanted to clarify. I think that's been the only case of entity close ENOENT behavior I've encountered thus far.

**Comment by mwpowellhtx** [comment]
Follow on question re: pipe (channel) versus message semantics. If I understand it correctly, when I request to ``::nng_msg_get_pipe``, I am effectively transferring ownership of the channel away from the message itself? Conversely, ``::nng_msg_set_pipe`` transfers ownership of the pipe channel back into the message? I just want to be sure I have that more or less correct.

Once that is accomplished, then what? So my pipe abstraction has ownership. Great, so what? I can get options, but that's about it. Is the intent to eventually support things like getters/setters of data and so forth on the message via the pipe?

Thanks!
