### ISSUE TITLE
test regression #49 nng.tcp

### ISSUE THREAD

**Issue by joel-sampson** [nanomsg/nng#1339]
## NNG & Platform details.
Fedora 33 cinnamon
intel i7-1065G7

## Expected Behavior
Test harness is successful
## Actual Behavior
TCP test fails:
Assertion Failed (Botched local interfaces fail resonably) [tcp test out.txt](https://github.com/nanomsg/nng/files/5521785/tcp.test.out.txt). According to git bisect this was introduced in commit: 452ecf5ae83adc9ae77518746f4f81171c42248c

I've rerun the test several time and gotten the same result. However I double checked on kubuntu and debian stable 32bit and the tests always pass.

**Comment by gdamore** [comment]
I have a sneaking suspicion that there is something environmental at play.

Are you using v6 interfaces anywhere?

I might need to send you code for a modified version that dumps the actual error that we are receiving.  Something is fishy.

(It might actually be the resolver being different in Fedora.  I know that there have been issues in the past with changes in Linux to use a systemd specific resolver that different things than other resolvers....)

**Comment by joel-sampson** [comment]
I forgot about some of the resolved drama but, I've installed fedora on two other machines and everything works fine. So this isn't a problem with nng. It's a newer laptop so it might be drivers... If it's a weird edge case, i'll keep you informed, otherwise thanks for the help.
