### ISSUE TITLE
consider eliminating nng_shutdown

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#136]
I think nng_shutdown() is a vestige of when we had pointers instead of numeric socket indexes, and is therefore likely not needed.

Note that internally, nni_shutdown() *is* still needed; I'm only talking about removing the external facing API.

**Comment by mwpowellhtx** [comment]
@gdamore I see in places where consumers should just close instead of shutdown. That makes sense.

However, there is an entire section of unit test that was removed? Is that really the case? Or should we just test close and the same behavior can be expected?

```C
Convey("And we can shut it down", {
  // ...
});
```
