### ISSUE TITLE
[Question] How to make nng_recv() timeout in req protocol?

### ISSUE THREAD

**Issue by db4** [nanomsg/nng#1360]
I'm using req/rep protocol in a client/server application. Once the server becomes unavailable (e.g. network connection is permanently down etc.) the client goes stuck in `nng_recv()` (while req/rep protocols retries the failing request). The question is: can I stop this process after some timeout making `nng_recv()` just return an error? Or `nng_recv_aio()` is the only way to do it? If the latter is true, do you have an example of using `nng_recv_aio()` on req side?

**Comment by gdamore** [comment]
You should look at NNG_OPT_RECVTIME -- this is an option that can be set on the socket.

**Comment by db4** [comment]
> You should look at NNG_OPT_RECVTIME -- this is an option that can be set on the socket.

Thanks, but does nng_recv() return an error after NNG_OPT_RECVTIMEO for req/rep protocol? My impression is that it will keep trying to resend a request until a reply is received.
