### ISSUE TITLE
nng_recvmsg returns NNG_ETIMEDOUT rather than NNG_EAGAIN

### ISSUE THREAD

**Issue by bsirang** [nanomsg/nng#1365]
**Describe the bug**
Using a `nng_sub0_open` socket, calls to `nng_recvmsg` with `NNG_FLAG_NONBLOCK` return `NNG_ETIMEDOUT`.

When the socket has data ready to receive, I call `nng_recvmsg` in a loop until first non-zero response. In these cases, I would expect the first non-zero response to be `NNG_EAGAIN`, which would be analogous to POSIX APIs. However, instead I get `NNG_ETIMEDOUT`.

**Expected behavior**
I expected the first non-zero return code from `nng_recvmsg` to be `NNG_EAGAIN` in the scenario described above.

**Actual Behavior**
The first non-zero return code from `nng_recvmsg` after the socket has data ready to receive is `NNG_ETIMEDOUT`.

**To Reproduce**
See pseudo code below outlining the relevant NNG calls.

```c
nng_socket sock_;
nng_dialer dial_;

// assume no error for the sake of this pseudo code
nng_sub0_open(&sock_);
nng_dial(sock_, "connection_string", &dial_, 0));

int recvfd = -1;
nng_getopt_int(sock_, NNG_OPT_RECVFD, &recvfd);

// use recvfd to block until data is ready to receive (using external library in my case)

int rv;
do {
  rv = nng_recvmsg(sock_, &msg, NNG_FLAG_ALLOC | NNG_FLAG_NONBLOCK));
} while(rv == 0);

// expect rv == NNG_EAGAIN however rv == NNG_ETIMEDOUT
```

** Environment Details **
 - NNG v1.3.2
 - Ubuntu 18.04
 - GNU Toolchain / C++
 - Shared library

**Comment by gdamore** [comment]
Ok, so the issue is that the code currently checks == NNG_FLAG_NONBLOCK instead of doing a bit test.
