### ISSUE TITLE
Underlying recvfd not showing ready for read despite nng_recvmsg returning messages

### ISSUE THREAD

**Issue by bsirang** [nanomsg/nng#1368]
**Describe the bug**
I'm running into an intermittent issue where the recvfd descriptor representing the socket that is underlying NNG's sub0 protocol socket is not showing ready for read despite there actually being messages returned via `nng_recvmsg` calls.

I am using another 3rd party library (non-boost version of ASIO) for asynchronous, event-driven I/O. I use `nng_getopt_int(sock_, NNG_OPT_RECVFD, &recvfd))` to retrieve the underlying file descriptor that I pass to the library. I then use the library to call back when there is data ready to be read or errors on the socket.

In some hard to reproduce cases, I encounter the receive callback stops firing altogether. I instrumented a watchdog of sorts to trigger under this condition, and for testing purposes I issued a `select()` call on the file descriptor and observed that the read/write/error flags were all unset. I then called `nng_recvmsg()` with `NONBLOCK` in a loop immediately after the `select()` call and observed 5 successful reads. The number 5 is significant because that matches the receive FIFO size configured with nng.

It may take hundreds of thousands of messages to be sent across the socket before this condition occurs. In these scenarios, after the successful reads triggered by the watchdog timeout, the socket "recovers" and then again starts reporting data ready to receive again.

**Expected behavior**
I expect the socket receive file descriptor "read ready" state as indicated by system calls such as `select()` to be coupled with whether or not `nng_recvmsg()` will have a message ready to receive

**Actual Behavior**
A call to `select()` showed that the receive file descriptor was not in the "read ready" state, however NONBLOCK calls to `nng_recvmsg()` did return successfully.

**To Reproduce**
Here's some pseudo C code that describes the problem.
```c
void initialize() {
  nng_sub0_open(&sock_);
  nng_setopt(sock_, NNG_OPT_SUB_SUBSCRIBE, "", 0);
  nng_setopt_ms(sock_, NNG_OPT_RECVTIMEO, NNG_DURATION_INFINITE));
  nng_setopt_int(sock_, NNG_OPT_RECVBUF, 5));
  nng_setopt_size(sock_, NNG_OPT_RECVMAXSZ,(100 * 1024 * 1024)));
  int recvfd;
  nng_getopt_int(sock_, NNG_OPT_RECVFD, &recvfd));
}

void checkDescriptorIOFlags(int recvfd_) {
  fd_set read_fds;
  fd_set write_fds;
  fd_set err_fds;
  FD_ZERO(&read_fds);
  FD_SET(recvfd_, &read_fds);
  FD_ZERO(&write_fds);
  FD_SET(recvfd_, &write_fds);
  FD_ZERO(&err_fds);
  FD_SET(recvfd_, &err_fds);
  struct timeval to {
    0
  };
  int rv = select(recvfd_ + 1, &read_fds, &write_fds, &err_fds, &to);
  if (rv == 0) {
    bool read_flag = FD_ISSET(recvfd_, &read_fds);
    bool write_flag = FD_ISSET(recvfd_, &write_fds);
    bool err_flag = FD_ISSET(recvfd_, &err_fds);
    log::info << "Receive socket state: read = " << read_flag << " write = " << write_flag
              << " error = " << err_flag << log::end;
  } else {
    log::error << "select() failed " << strerror(errno) << log::end;
  }
}

// this fires when async library times out waiting for read event in recvfd
void watchdog() {
  checkDescriptorIOFlags(recvfd_);
  int rv;
  int read_count = 0;
  do {
    rv = nng_recvmsg(sock_, &msg, NNG_FLAG_ALLOC | NNG_FLAG_NONBLOCK);
    if (rv == 0) {
      ++read_count;
    }
  } while(rv == 0);

  // at this point read_count == 5 && checkDescriptorIOFlags() showed all 3 flags were false
}
```

** Environment Details **
NNG v1.3.2
Ubuntu 18.04
GNU Toolchain / C++
Shared library

**Comment by gdamore** [comment]
Its possible I botched this in 1.3.x.  Can you possibly test a v1.2.x version instead?  I just want to know if this is a regression.  Thanks!

**Comment by bsirang** [comment]
I actually discovered this issue on v1.1.1 initially. I then upgraded to v1.3.2 in hopes of resolving it but observed the issue still.

**Comment by gdamore** [comment]
Btw, using select() is not very efficient.  You should consider using poll() for this case.  Or possibly epoll() or kqueue() if you are on a system that can support those.  (poll() is everywhere though.)

**Comment by gdamore** [comment]
I'm wondering if there is a race condition in here.  How long does it take to encounter this condition?  How many messages per second are you doing?  Basically we have to set the pollable flag by by writing a value, and then we clear it by reading that value.  (I really dislike this architecture, but it's what you have to do if you need to interact with poll/select loops.)

If we wind up clearing doing the raise out of order, we could conceivably miss it.

I do see that we raise this flag while not holding the lock, but we clear it under that condition.  I'm having a hard time groking why that particular order could cause a loss of event (although I could see it leading to spurious conditions), but maybe I'm missing something.

I'll put together a branch for you try.

**Comment by bsirang** [comment]
It takes between roughly 30-90 minutes to occur. In my testing I'm running extra fast at a few hundred messages per second on a system that's fairly loaded CPU and I/O wise.

I originally started observing this issue with a 50Hz message rate and could not reproduce it when dropping the message rate to 25Hz, so a race condition sounds reasonable.

I'd be happy to test out a branch. Thank you.

**Comment by gdamore** [comment]
(That commit isn't right yet.)

**Comment by gdamore** [comment]
Ok, you can now try that PR... it *should* work; I'd like to know either way.  I probably won't merge it unless I get confirmation from you.

**Comment by bsirang** [comment]
I left a test running overnight and no occurrences of the issue! Your PR seems to be working.

**Comment by bsirang** [comment]
When do you anticipate a release that rolls in this fix?

**Comment by bsirang** [comment]
@gdamore I ended up taking your fix and cherry picking it on top of my v1.3.2 fork.

I really really appreciate the very quick turn around on this issue!

**Comment by gdamore** [comment]
Glad it worked.  I'll merge this onto master.  I might be willing to do a special 1.3.3 release with this cherry picked, if need be.  Version 1.4 is probably still at least a week away.

**Comment by bsirang** [comment]
At this point I can just run with my cherry-picked version, and when v1.4.x is released, I can point my code towards it instead.
