### ISSUE TITLE
Add nni_protocol and nni_peer

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#139]
Kindly,

```C
uint16_t
nni_protocol(nng_socket sid)
{
  int rv;
  uint16_t pnum;
  nni_sock *sock;

  if ((rv = nni_sock_find(&sock, sid)) != 0) {
    return (rv);
  }
  pnum = nni_sock_proto(sock);
  nni_sock_rele(sock);
  return (pnum);
}
```

```C
uint16_t
nni_peer(nng_socket sid)
{
  int rv;
  uint16_t pnum;
  nni_sock *sock;

  if ((rv = nni_sock_find(&sock, sid)) != 0) {
    return (rv);
  }
  pnum = nni_sock_peer(sock);
  nni_sock_rele(sock);
  return (pnum);
}
```

Thank you.

**Comment by mwpowellhtx** [comment]
Also, while you're there, include ``msgqueue.h`` in ``socket.h``. That one is missing.

**Comment by gdamore** [comment]
msgqueue.h comes in via nng_impl.h.  That header does the work of ensuring everything is included in the right order.

I'm unconvinced that there is any useful value in these beyond possibly my own self tests.  (And frankly, I've already convinced myself that even in the self tests there extremely little value -- getting the protocol numbers wrong would pretty much cause the entire *rest* of the test suite to fall down, and with the "new" protocol specific constructors there is almost no chance I can actually screw this up.)

**Comment by gdamore** [comment]
There are collision checks in the protocol registration code.  Even someone else would really have to work hard to screw this up in a way that doesn't fail in a pretty obvious matter.
