### ISSUE TITLE
nng 1.3.2 with mbedtls-2.25.0 can not establish TLS connection with a browser

### ISSUE THREAD

**Issue by zakharov** [nanomsg/nng#1391]
I have noticed that nng with the latest mbedtls-2.25.0 does not connect to a
browser over https and wss. The error in the browser console says: 
**failed: Error in connection establishment: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH**
When I replace mbedtls-2.25.0 with the older version 2.16.6 everything works as expected.
I wonder if anyone has observed this behavior and where the problem is.   

**Environment Details**
 - NNG version 1.3.2, mbedtls-2.25.0
 - Ubuntu 20.04
 - gcc 9.3.0
 - both nng and mbedtls are shared
 - browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit), Firefox 84.0 (64-bit)
 - self-signed certificate

**Comment by gdamore** [comment]
I haven't reviewed mbedTLS lately, but it would not surprise me if there are some options required to enable more or different cipher suites.  NNG by default just exposes the cipher suites provided by the underlying mbedTLS library.  Note also that it may depend on what your *certificate* is configured with.  For example, if you have old EXPORT class ciphers, then that probably won't work.

It might be good to look at the ChangeLogs for mbedTLS itself.  Also look closely at the cert you are providing -- if you can share some details on the public certificate I might be able to help debug.

**Comment by gdamore** [comment]
Looking at the change log, 2.20 has this note:

   * Deprecate MBEDTLS_SSL_SRV_SUPPORT_SSLV2_CLIENT_HELLO that enables parsing
     SSLv2 ClientHello messages.
   * Deprecate MBEDTLS_SSL_PROTO_SSL3 that enables support for SSLv3.

I wonder if you are using SSLv3 certificate?   Make sure you're using TLS v1.2 if possible.  I don't think mbedTLS supports TLS v1.3 yet.

**Comment by zakharov** [comment]
We are using TLS v1.2 and self signed certificates with X.509 extensions. I am going to check after which version of mbedtls this error has occurred.

**Comment by gdamore** [comment]
Any news on this?

**Comment by zakharov** [comment]
I checked a few versions. Last one which works has the tag v2.16.9. Next one v2.23.0 gives net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH. I am not sure how to compile versions 
with the tags mbedtls-2.19 and mbedtls-2.20.

**Comment by zakharov** [comment]
I did more testing. I discovered that the problem is in our library. nng 1.3.2 and mbedtls-2.25.0 are fine.
