### ISSUE TITLE
Please sort out your includes

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#140]
Well, not sure your includes need work. I'm getting this error now:

```
12>G:\Source\Spikes\nanomsg\nngcpp\working\repos\nng\src\core/options.h(19): error C2065: 'nni_msgq': undeclared identifier
12>G:\Source\Spikes\nanomsg\nngcpp\working\repos\nng\src\core/options.h(19): error C2059: syntax error: ','
```

```C
// nni_setopt_buf sets the queue size for the message queue.
extern int nni_setopt_buf(nni_msgq *, const void *, size_t);

// nni_getopt_buf gets the queue size for the message queue.
extern int nni_getopt_buf(nni_msgq *, void *, size_t *);
```

**Comment by mwpowellhtx** [comment]
This is a sub-optimal workaround at best. When I dive into your includes to get at the function declarations themselves, all hell breaks loose, headers that should be included when they are necessary, are not, structures are defined in source files, and on and on.

```C++
#include "../../../../repos/nng/src/core/defs.h"

#   ifdef __cplusplus
extern "C" {
#   endif // __cplusplus

extern int nni_sock_find(nni_sock**, nng::uint32_t);
extern nng::uint16_t nni_sock_proto(nni_sock*);
extern nng::uint16_t nni_sock_peer(nni_sock*);
extern void nni_sock_rele(nni_sock*);

#   ifdef __cplusplus
}
#   endif // __cplusplus
```

**Comment by gdamore** [comment]
You're accessing headers that are not intended to be used outside of nng itself.

There are a bunch of hidden implementation details, and the logic behind what is exposed and what is not is very well thought out.

Better is to address what the core need you have is.

**Comment by mwpowellhtx** [comment]
@gdamore Not my my analysis, nor by the errors I received including from the source. I started *"from the top"*, so to speak, including NNG ``socket.h``, and things slid downhill quickly from there, with missing includes, structs in source files instead of headers, and so on.

Anyway, as stated, I've worked around it, sub-optimally, but worked around nevertheless.

**Comment by gdamore** [comment]
That's because you don't understand that you shouldn't include socket.h without first including nng_impl.h.  There is a method to my madness believe it or not.

**Comment by mwpowellhtx** [comment]
If that's the case, then even conventional wisdom suggests that you should include ``nng_impl.h`` from ``socket.h``. And if that's inappropriate, then that suggests to me there is a deeper factoring issue going on.

But I digress. I'm really not here to peel back the layers of the onion. Just to verify the protocol/peer handshake, which I've already done.

Moving on.

**Comment by gdamore** [comment]
There's more here than you realize.  Nothing #include's socket.h directly.  Instead the "core" does a #include of nng_impl.h, which has the "ordering" issues resolved, and brings in all the needed things in the right order.  There are gnarly dependencies in which headers need which others...

Yeah, this is  bit of "undocumented" knowledge, and probably I should comment it somewhere.  You're only running into this because you continue to insist on probing at nng's guts.

Eventually I'm going to subset things a bit more, so that external transports and protocols can be built without depending on the details of the core.  That's not the case today.  The design for this is clear, I just haven't got that far yet.

**Comment by mwpowellhtx** [comment]
Sute, I realize it's a side long view of the NNG landscape. I simply searched the code base for appearances of *nni**, and that's what popped out.

**Comment by gdamore** [comment]
Yeah... the issue is that all the nni_* symbols are "private".  ("i" means "internal").

**Comment by mwpowellhtx** [comment]
I understand that. None of the internal symbols are being exposed via my public facing C++ API, either. My internal unit testing, however, is a different story altogether, as we've discussed ad nauseam, ad infinitum.

**Comment by gdamore** [comment]
So this is where we disagree… You’re unit testing is not covering the edges
of your library layer, but is also validating the internals of nng itself.
I think you should “rely” on nng’s test suite to provide the guarantees
that nng is behaving correctly, and then any of your testing would only be
covering that portion of the code for which you are actually responsible.
 (I.e. the code you wrote, not the code I wrote.)

**Comment by mwpowellhtx** [comment]
Only insofar as is necessary to verify whether I integrated correctly. I am not doing white box testing on NNG itself, But I am testing the edges, top, bottom (including NNG integration), left, and right, as much as possible.
