### ISSUE TITLE
Multi-client pair server

### ISSUE THREAD

**Issue by denis-troller** [nanomsg/nng#1405]
I'm having a hard time understanding how to transcribe what I used to do with standard sockets. I hope someone can shed some light on this.
I want to use a Pair socket with multiple clients, to achieve full-duplex communication with each client.
Basically, I would like to replicate what we used to do with Accept().

This is to support an RPC + notification system, which means REQ-REP does not work since I can have messages sent from the server to the client, hence my choice of Pair.
Once dialed, I should be able to address each client specifically (either responding to requests or sending a notification).

Can this be achieved ? If so, how ?

**Comment by gdamore** [comment]
There are a few options:

1. Polyamorous pair v1.  However, this requires the server to know the pipe ID of clients that it wants to send to, it doesn't work with nng_device, and is deprecated.  It also only works with nng (no libnanomsg or mangos support).
2. Separate sockets. This will require some extra effort to synchronize between them.
3. If your traffic is relatively light, and you don't care about duplications, BUS sends to *everyone*.

**Comment by gdamore** [comment]
There are plans for a richer, more complete, mesh protocol.  Identifying peers on the network will still be needed.  It's not been built yet though.

**Comment by denis-troller** [comment]
So basically what you mean is that, whatever protocol I am using, a context serves one request (which can be a req/rep cycle for Reqrep context) and then becomes available for another request from whichever client.
Basically, there is no connection-oriented context ?
So I would have to have a "master" req-rep endpoint that will spin up a pair to allow one-to-one dialog (thus mimicking the Accept() "server" architecture).

Thanks for clarifying this, I was beginning to think there was something I did not get !

One more question: is concurrent Send and Receive operation possible on a single context on a pair socket ? (alllowing to both process incoming messages and send messages at the same time) or do we have to take care not to do both at the same time ?
I am using a .Net wrapper and it seems it imposes either calling send or receive but not both concurrently and I was wnodering if that was a requirement of nng or of the wrapper.

**Comment by gdamore** [comment]
Yes, it is possible to have concurrent send and receive.
