### ISSUE TITLE
[Question]How to get address of req client in a nng_msg?

### ISSUE THREAD

**Issue by Yifangxx** [nanomsg/nng#1411]
**Describe the bug**
In a req-rep protocol,I get a msg by nng_aio_get_msg func.
then， Can I get rep address through this msg?

**Expected behavior**

**Actual Behavior**
Describe what occurred.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NNG version
 - Operating system and version
 - Compiler and language used
 - Shared or static library

**Additional context**

**Comment by gdamore** [comment]
You can get the pipe, via nng_msg_get_pipe().  From that you can get numerous details about the peer or the local end point using nng_pipe_get() and similar APIs.  (For example, see, NNG_OPT_REMADDR and NNG_OPT_URL).
