### ISSUE TITLE
Protocols and transports should be "configurable"

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#143]
We should be able to configure which protocols and transports are included in the build. We already do this for ZeroTier (although poorly); we can do it for all of them.

This can also lead to the ability to make user-defined protocols and transports (in the future), or to library minimization.

When doing this, we should have logic in the test suites to skip over things that can't be tested due to missing configuration.

**Comment by 363568233** [comment]
Can the TCP protocol of nng be replaced with TCP protocol based on DPDK implementation？
