### ISSUE TITLE
nng_sockaddr larger than nng_sockaddr_storage

### ISSUE THREAD

**Issue by Ankkatalo** [nanomsg/nng#1430]
nng_sockaddr is larger than nng_sockaddr_storage. 

I tried 
		nng_sockaddr_storage a;
		nng_pipe_get_addr(pipe, NNG_OPT_REMADDR, (nng_sockaddr*)&a);
which corrupts the stack.
The actual stack corruption occurs in the function nni_copyout_sockaddr(), which
copies a nng_sockaddr into the variable a.

Compiler is Visual Studio Version 16.8.5, x64.
nanomsg is 1.4.0, dll.
nng_sockaddr is 136 bytes
nng_sockaddr_storage is 130 bytes

As far as I can tell this is caused be the aligment requirement of nng_sockaddr_zt, which is 8 bytes.

Greetings,
Jörn Sierwald

**Comment by gdamore** [comment]
yeah, padding alignment problems... urk.

You can avoid this by using nng_sockaddr instead of nng_sockaddr_storage. I'm fixing anyway.
