### ISSUE TITLE
nng_sleep_aio doesn't check the status of aio before dispatching new task.

### ISSUE THREAD

**Issue by JaylinYu** [nanomsg/nng#1431]
**Describe the bug**
Since the manual says nothing about forbidden calling nng_sleep_aio in its own callback. Hence I wanna implement a timer that can reschedule itself depends on nng_sleep_aio. However, it ends up in an infinity loop when the pipe disconnects after calling nng_sleep_aio in the callback.

**Expected behavior**
the callback should not be triggered when AIO has been stopped

**Actual Behavior**
Infinity loop of callback.

**To Reproduce**
Allocating an AIO with a callback function.
Using nng_sleep_aio to trigger this cb, and calling nng_sleep_aio in its own callback.
Disconnecting the pipe/ calling nng_aio_stop

**Comment by gdamore** [comment]
I confirm that there is indeed a bug here -- nng_sleep_aio is returning immediately after the first call.  Stay tuned.

**Comment by gdamore** [comment]
Actually, I was wrong.   My test case I was using to cover this had bugs.

I'll push up a new test case that demonstrates both rescheduling sleeps, and cancellation with nng_aio_cancel().

**Comment by gdamore** [comment]
Test cases for this are in commit 7a0de1b25287f08b73c04d4f9c2834ae265cc382

**Comment by gdamore** [comment]
I'm closing this one.
