### ISSUE TITLE
Guard against possible undefined behaviour when subscribing to all topics

### ISSUE THREAD

**Issue by lnksz** [nanomsg/nng#1436]
**Describe the bug**
If `sub0_ctx_subscribe` is reached with `buf=NULL; sz=0`. (Subscribing to _all_ topics.)
Which seems to be an intended feature: see  https://nng.nanomsg.org/man/v1.3.2/nng_sub.7.html:
> To receive all messages, an empty topic (zero length) can be used.
UBSAN complains:
> runtime error: null pointer passed as argument 2, which is declared to never be null

We call `nn_setsockopt(sock.id, NN_SUB, NN_SUB_SUBSCRIBE, "", 0)`

nng version: 1.3.0
Platform: Linux

**Expected behavior**
No UBSAN runtime error

**Actual Behavior**
UBSAN runtime error

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NNG version: 1.3.0
 - Operating system and version: Debian GNU/Linux 10 (buster)
 - Compiler and language used: C, GCC-8.3.0
 - Shared or static library: shared

**Additional context**

**Comment by gdamore** [comment]
So technically, the declared never to be null attribute of memcpy is wrong.  Its perfectly fine to call it with a length of zero and either argument NULL.  

But I'll merge this anyway.
