### ISSUE TITLE
What is nng_aio exactly?

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#144]
``::nng_aio``? What is it? An empty struct? i.e. same as saying:

```C
struct nng_aio {
};
```

**Comment by gdamore** [comment]
It's *opaque*, and for good reason.

**Comment by gdamore** [comment]
The details of it are in either aio.c or aio.h.

**Comment by gdamore** [comment]
Instead of filing "issues", maybe questions like this can come to email first?

**Comment by mwpowellhtx** [comment]
I may be able to run with ``System.IntPtr`` without needing to know what's behind it for purposes of adapting into C#/.NET. I'll keep you posted.
