### ISSUE TITLE
Weired problem in async req-rep mode

### ISSUE THREAD

**Issue by Yifangxx** [nanomsg/nng#1440]
**Describe the bug**
Hi, man.I got the problem when I use async req-rep mode just like the demo:
Server:  
    listen connection.
    recv  msg - process - send reply
Client:
    connect server - send msg - recv reply

    The whole wrokfow is normal in the begining. But the callback associated with the aio would not execute after server called 'nng_ctx_send'. Then server could not recieve any message but connection could recieve(I register the event).
    So, is there any reason to cause this situation?

**There is code**
`bool ReplyServer::Open(const char* listen_str)
{
    bool ret{false};

    int rv;
    rv = nng_rep0_open(&socket_);
    if (rv != 0)
    {
        SPDLOG_WARN("ReplyServer open error.nng_rep0_open[{}].", rv);
    }
    else
    {
        DoPipeOpRegister();

        if (InitWorks())
        {
            if ((rv = nng_listen(socket_, listen_str, NULL, 0)) != 0)
            {
                SPDLOG_ERROR("nng_listen error[{}].", rv);
            }
            else
            {
                for (auto& work : works_)
                {
                    ServerCb(work);  // this starts them going (INIT state)
                }
                ret = true;
            }
        }
        else
        {
            SPDLOG_ERROR("Init works error.");
        }
    }

    return ret;
}

bool ReplyServer::Close()
{
    int rv;
    if ((rv = nng_close(socket_)) != 0)
    {
        SPDLOG_ERROR("nng_close error[{}]", rv);
        return false;
    }

    CloseWorks();

    return true;
}

bool ReplyServer::InitWorks()
{
    bool ret{true};
    for (auto& work : works_)
    {
        nng_work* w;
        int rv;
        if ((w = reinterpret_cast<nng_work*>(nng_alloc(sizeof(*w)))) == NULL)
        {
            SPDLOG_WARN("nng_alloc error[{}].", NNG_ENOMEM);
            ret = false;
            break;
        }
        if ((rv = nng_aio_alloc(&w->aio, ReplyServer::ServerCb, w)) != 0)
        {
            SPDLOG_WARN("nng_aio_alloc error[{}].", rv);
            ret = false;
            break;
        }
        if ((rv = nng_ctx_open(&w->ctx, socket_)) != 0)
        {
            SPDLOG_WARN("nng_ctx_open error[{}].", rv);
            ret = false;
            break;
        }

        w->reply_server = this;
        w->state = nng_work::INIT;

        work = w;
    }

    return ret;
}

void ReplyServer::CloseWorks()
{
    for (auto& work : works_)
    {
        nng_ctx_close(work->ctx);
        nng_aio_free(work->aio);
        nng_free(work, sizeof(*work));
    }
}

void ReplyServer::ServerCb(void* args)
{
    nng_work* work = reinterpret_cast<nng_work*>(args);

    int rv;
    switch (work->state)
    {
        case nng_work::INIT:
            work->state = nng_work::RECV;
            nng_ctx_recv(work->ctx, work->aio);
            break;
        case nng_work::RECV:
            if ((rv = nng_aio_result(work->aio)) != 0)
            {
                SPDLOG_ERROR("nng_ctx_recv error[{}].", rv);
                work->state = nng_work::INIT;
            }
            else
            {
                auto msg = nng_aio_get_msg(work->aio);
                if (msg != nullptr)
                {
                    auto remote_addr = get_remote_addr(msg);
                    strncpy(work->remote_addr, remote_addr.c_str(), remote_addr.size() + 1);
                    SPDLOG_TRACE("[{}]nng_ctx_recv msg[len:{}] from {}.", get_thread_str(),
                                 nng_msg_len(msg), work->remote_addr);

                    // process request msg
                    work->reply_server->on_msg_update()(
                        nng_msg_body(msg), nng_msg_len(msg), [&msg](void* data, size_t len) {
                            if (nng_msg_len(msg) >= len)
                            {
                                nng_msg_clear(msg);
                                nng_msg_append(msg, data, len);
                            }
                            else
                            {
                                SPDLOG_WARN("realloc response msg data[len:{}/{}]", nng_msg_len(msg), len);
                                auto rrv = nng_msg_realloc(msg, len);
                                if (rrv != 0)
                                {
                                    SPDLOG_ERROR("nng_msg_realloc error[{}].", rrv);
                                }
                                else
                                {
                                    nng_msg_clear(msg);
                                    nng_msg_append(msg, data, len);
                                }
                            }
                        });

                    SPDLOG_TRACE("[{}]nng_ctx_send to call[peer:{}, len:{}].", get_thread_str(),
                                 work->remote_addr, nng_msg_len(msg));

                    // send reply info
                    work->msg = msg;
                    nng_aio_set_msg(work->aio, work->msg);
                    nng_ctx_send(work->ctx, work->aio);
                    work->state = nng_work::SEND;
                }
            }
            break;
        case nng_work::SEND:
            if ((rv = nng_aio_result(work->aio)) != 0)
            {
                nng_msg_free(work->msg);
                SPDLOG_ERROR("[{}]nng_ctx_send to {} error[{}].", get_thread_str(), work->remote_addr, rv);
            }
            else
            {
                SPDLOG_TRACE("[{}]nng_ctx_send to {} successed.", get_thread_str(), work->remote_addr);
            }

            work->state = nng_work::RECV;
            nng_ctx_recv(work->ctx, work->aio);
            break;
        default:
            SPDLOG_ERROR("bad state[{}]!", work->state);
            break;
    }
}

void ReplyServer::DoPipeOpRegister()
{
    auto conn_cb = [](nng_pipe pipe, nng_pipe_ev ev, void*) {
        nng_sockaddr sock_addr;
        nng_pipe_getopt_sockaddr(pipe, NNG_OPT_REMADDR, &sock_addr);
        auto remote_addr = get_addr_str(sock_addr.s_in);

        std::string status_str;
        switch (ev)
        {
            case NNG_PIPE_EV_ADD_POST:
                status_str = "connected";
                break;
            case NNG_PIPE_EV_REM_POST:
                status_str = "disconnected";
                break;
            default:
                break;
        }
        SPDLOG_INFO("[{}]{} {}.", get_thread_str(), remote_addr, status_str);
    };

    // set pipe callback
    nng_pipe_notify(socket_, NNG_PIPE_EV_ADD_POST, conn_cb, nullptr);
    nng_pipe_notify(socket_, NNG_PIPE_EV_REM_POST, conn_cb, nullptr);
}`

**There is log**
[20210408 18:32:45.475] [ trace  ] [zerg::zms::ReplyServer::ServerCb] [15824]nng_ctx_send to call[peer:127.0.0.1:59615, len:142].
[20210408 18:32:45.476] [ trace  ] [zerg::zms::ReplyServer::ServerCb] [25468]nng_ctx_send to 127.0.0.1:59615 successed.
[20210408 18:32:45.490] [ trace  ] [zerg::zms::ReplyServer::ServerCb] [42860]nng_ctx_recv msg[len:76] from 127.0.0.1:59615.
[20210408 18:32:45.490] [ trace  ] [zerg::zms::ZmsCore::ParseDepthRequest] [42860]read depth of Series:au in session[9491001]
[20210408 18:32:45.490] [warning ] [zerg::zms::ReplyServer::ServerCb::<lambda_72614d273f8c9794215609e80b0b03ab>::operator ()] realloc response msg data[len:76/142]
[20210408 18:32:45.490] [ trace  ] [zerg::zms::ZmsCore::ParseDepthRequest] [42860]read depth over in session[9491001]
_[20210408 18:32:45.490] [ trace  ] [zerg::zms::ReplyServer::ServerCb] [42860]nng_ctx_send to call[peer:127.0.0.1:59615, len:142].
[20210408 18:32:45.491] [ trace  ] [zerg::zms::ReplyServer::ServerCb] [24852]nng_ctx_send to 127.0.0.1:59615 successed._
[20210408 18:32:45.505] [ trace  ] [zerg::zms::ReplyServer::ServerCb] [15824]nng_ctx_recv msg[len:76] from 127.0.0.1:59615.
[20210408 18:32:45.506] [ trace  ] [zerg::zms::ZmsCore::ParseDepthRequest] [15824]read depth of Series:au in session[9491001]
[20210408 18:32:45.506] [warning ] [zerg::zms::ReplyServer::ServerCb::<lambda_72614d273f8c9794215609e80b0b03ab>::operator ()] realloc response msg data[len:76/142]
[20210408 18:32:45.506] [ trace  ] [zerg::zms::ZmsCore::ParseDepthRequest] [15824]read depth over in session[9491001]
_[20210408 18:32:45.506] [ trace  ] [zerg::zms::ReplyServer::ServerCb] [15824]nng_ctx_send to call[peer:127.0.0.1:59615, len:142].
[20210408 18:32:45.506] [ trace  ] [zerg::zms::ReplyServer::ServerCb] [49876]nng_ctx_send to 127.0.0.1:59615 successed._
[20210408 18:32:45.520] [ trace  ] [zerg::zms::ReplyServer::ServerCb] [42860]nng_ctx_recv msg[len:76] from 127.0.0.1:59615.
[20210408 18:32:45.520] [ trace  ] [zerg::zms::ZmsCore::ParseDepthRequest] [42860]read depth of Series:au in session[9491001]
[20210408 18:32:45.520] [warning ] [zerg::zms::ReplyServer::ServerCb::<lambda_72614d273f8c9794215609e80b0b03ab>::operator ()] realloc response msg data[len:76/142]
[20210408 18:32:45.520] [ trace  ] [zerg::zms::ZmsCore::ParseDepthRequest] [42860]read depth over in session[9491001]
_[20210408 18:32:45.520] [ trace  ] [zerg::zms::ReplyServer::ServerCb] [42860]nng_ctx_send to call[peer:127.0.0.1:59615, len:142]._
[20210408 19:02:32.524] [warning ] [zerg::zms::ZmsCore::DoCheckHeartbeat] session[9491001] timout[1800].
[20210408 19:02:32.525] [  info  ] [zerg::zms::ZmsCore::DoStreamOperation] Set expire time[1800] of key[session_stream_9491001].

As we see, "nng_ctx_send  ... successed."  should be logged after "nng_ctx_send to call" logged.However, there is no "successed" 
after the last "nng_ctx_send" until the session time out.

** Environment Details **
 - NNG version: v1.3.2
 - win10
 - vs2019 and  c++17
 - use nng with static library

**Additional context**

**Comment by gdamore** [comment]
I don't see anything intrinsically wrong here.  The code looks basically reasonable, but I don't have the rest of your app.  The things I'd look for -- is your peer receiving the message?  If the peer pipe doesn't actually consume messages on it's end, that pipe will fill up, and the send will block waiting for there to be room to post it.

**Comment by Yifangxx** [comment]
Oh, I found the source.
I set the state of work to 'SEND' after nng_ctx_send called. 
It is a stupid mistake, sorry.
