### ISSUE TITLE
does nng_stream can make sure the order when use multi nng_aio?

### ISSUE THREAD

**Issue by shishaotang** [nanomsg/nng#1442]
hello, I want to make sure a question, thank you.
when I use nng_stream, I get a nng_stream* by nng_aio_get_output;
and I make two or more nng_aio task, by use nng_sleep_aio, and in the asio task, I send msg by using nng_stream_send, and these aio task use the same nng_stream* object.
I want to know the msg will ordered or the msg will disordered?
just like task1 send msg A, 16 bytes, task2 send msg B, 20 bytes,  and in the receive side, will receive msg A 8 bytes, msg B 20 bytes, msg A 8 bytes, will this happen？

**Comment by gdamore** [comment]
No.  If you use two aio's on the same stream, you'll probably get scrambled data.  This is basically just like doing write or read from parallel threads -- you can't claim anything about ordering.

Needless to day, you don't want to do this.  One aio per stream per direction (although it is possible to use the same aio for read & write, provided you never do both at the same time.)
