### ISSUE TITLE
expire queue is really hot

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#1443]
The expire queue for aios is kept in order.  This causes some performance concerns, if you have (as one user does) 80,000 entries in the queue and they aren't all strictly with the same general lengths.

This makes adding (scheduling) an O(n) operation, and if you have n of those, we are now O(n^2).  This is seen as excessively long times trying to schedule.

The design intent was to make the aio expire thread not have to scan the entire list.  But the process of doing this has led to moving that work to every scheduler, which turns out to make the problem far worse.  We can easily amortize this in the scheduler by having it scan when it wakes up, and on super busy systems it will probably be able to run multiple expirations.

An alternative structure involving a heap could be done, but that makes it an O(n*logn) problem all the time, which is undesirable as well.

**Comment by JaylinYu** [comment]
looking forward to the solution of it

**Comment by gdamore** [comment]
This was fixed with #1449
