### ISSUE TITLE
pub-sub

### ISSUE THREAD

**Issue by jinyuttt** [nanomsg/nng#1444]
1. Is socket a long connection?

2. Is sub receiving all messages and filtering them?

3. is there a c# binding library?

**Comment by gdamore** [comment]
1. nng will generally keep connections alive.
2. sub is indeed receiver side filtered.
3. i believe there is such a library - https://github.com/jeikabu/nng.NETCore

**Comment by gdamore** [comment]
btw, i make no claims about the .net binding for NNG.
