### ISSUE TITLE
c#

### ISSUE THREAD

**Issue by jinyuttt** [nanomsg/nng#1451]
Is there a C# Binding library

**Comment by codypiersall** [comment]
All the bindings I know about are here: https://nanomsg.org/documentation.html#_language_bindings

I don't see C# on that list, but I did find this: https://github.com/jeikabu/nng.NETCore which has packages [available through NuGet](https://www.nuget.org/packages/nng.NET/) and looks like it's maintained.

**Comment by jinyuttt** [comment]
ok
