### ISSUE TITLE
Any idea when the websocket api will be "available"?

### ISSUE THREAD

**Issue by schmidtw** [nanomsg/nng#1466]
I was reading through the websocket code and saw [this](https://github.com/nanomsg/nng/blob/58337cfc78c86fe36a7f6f17c29ad9d24504a52a/src/supplemental/websocket/websocket.h#L32) saying it's not really ready for use.  I also saw the last activity around the websockets was in ~Jan 2021.  Do you have any timeline for when you'll be happy with this code enough to bless some of the API?

**Comment by gdamore** [comment]
That "api" is indeed private.

But you can use websockets now using the nng_stream_xxx API.  You just use a ws:// API.  That API is blessed and stable.

**Comment by gdamore** [comment]
ws://  URL I mean (or wss://)

**Comment by schmidtw** [comment]
oh, cool - thanks for the update & suggestion.
