### ISSUE TITLE
[Feature] add `-fPIC` compiler flag

### ISSUE THREAD

**Issue by sdrgeek** [nanomsg/nng#1484]
**Is your feature request related to a problem? Please describe.**
More or less. `nng` is a dependency of [SatDump](https://github.com/altillimity/SatDump). Compiling this library without a specific flag for the C-compiler results in a linkage error. Please see [this](https://github.com/altillimity/SatDump/issues/25#issuecomment-893516581) comment for further information.

**Describe the solution you'd like**
Currently I have to build the library with this lengthy command:
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} ${NNG_WARN_FLAGS} ${NNG_COVERAGE_C_FLAGS} ${NNG_SANITIZER_FLAGS} -fPIC" -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} ${NNG_WARN_FLAGS} ${NNG_COVERAGE_C_FLAGS} ${NNG_SANITIZER_FLAGS} -fPIC" ..`
I'd love to see your library to compile without potentially breaking something.

**Describe alternatives you've considered**
A valid alternative is ofc using this lengthy command. I think it can be shorter than that (ie. only add `-fPIC` to the chain of flags) but I'm not sure how to accomplish this at this point.

**Additional context**
For additional information see https://github.com/altillimity/SatDump/issues/25

**Comment by gdamore** [comment]
Please have look at this page on CMake which describes the correct way to achieve what you want: 

https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html

So really all you should need to do is supply -DPOSITION_INDEPENDENT_CODE=on

But if you're building shared libraries then it should not be needed.  If you're not building shared libraries, why do you need PIC?

**Comment by Aang23** [comment]
> Please have look at this page on CMake which describes the correct way to achieve what you want:
> 
> https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html
> 
> So really all you should need to do is supply -DPOSITION_INDEPENDENT_CODE=on
> 
> But if you're building shared libraries then it should not be needed. If you're not building shared libraries, why do you need PIC?

That is actually the issue. In all cases shared libraries are being built and installed, but cannot be linked against due to the aforementioned PIC-related issue. (Unless such CMake flags are passed to nng).

**Comment by gdamore** [comment]
The link command seems to indicate that it is trying to link against a static build of NNG however.

**Comment by gdamore** [comment]
Closing this as it was resolved in other discussion.
