### ISSUE TITLE
libnng在arm-linux-gcc编译问题

### ISSUE THREAD

**Issue by jinfazhou** [nanomsg/nng#1493]
配置好了cmakelists.txt生成arm-linux-gcc的文件.为什么编译出来的linux下的libnng.a不是arm下的libnng.a?

**Comment by ruantu** [comment]
Please check the README

**Comment by gdamore** [comment]
Unfortunately I don't understand Chinese/Mandarin.  Google translate sort of helped, but the question still doesn't make perfect sense to me.

Fortunately the good folks at EMQX have put together a support forum for Chinese users of NNG:

https://askemq.com/c/nanomsg-nng/15

I'd direct your question there, and I'm sure someone there will be better able to help you than I am.
