### ISSUE TITLE
Cannot pass test_numeric_v6 in not support ipv6 kernels

### ISSUE THREAD

**Issue by ruantu** [nanomsg/nng#1496]
**Describe the bug**
Cannot pass test_numeric_v6 in not support ipv6 kernels

**Expected behavior**
All tests passed in not support ipv6 kernels.

**Actual Behavior**
Message: 
resolver_test.c:63: Check nng_aio_alloc(&aio, NULL, NULL) succeeds... ok
resolver_test.c:66: Check nng_aio_result(aio) succeeds... failed
nng_aio_result(aio): expected success, got Address invalid (15)
resolver_test.c:67: Check sa.s_in6.sa_family == NNG_AF_INET6... failed
resolver_test.c:68: Check sa.s_in6.sa_port == nuts_be16(80)... failed
resolver_test.c:69: Check memcmp(sa.s_in6.sa_addr, v6loop, 16) == 0... failed
FAILED: 4 conditions have failed.

Whether to conduct test_numeric_v6 condition should be changed to whether the kernel supports ipv6:
[ -f /proc/net/if_inet6 ] && echo 'IPv6 ready system!' || echo 'No IPv6 support found! Compile the kernel!!'

** Environment Details **
 - v1.3.9
 - not support ipv6 kernels.

**Comment by gdamore** [comment]
It seems like it may depend on the specific host you get deployed to, as I've run IPv6 tests on GitHub Actions numerous times in the past.

**Comment by gdamore** [comment]
Oh wait  this isn't GitHub perhaps.

I think this is a problem with your environment -- if you don't have IPv6 support then these tests are going to fail.  I don't really want to compile tests for every operating system to detect whether that OS or build of the OS or even specific environment supports IPv6. 

I might be amenable to disabling the test via an environment variable NNG_NO_IPV6 or something like that.

**Comment by drws** [comment]
I've just encountered the same issue, came here to report and found this. Please implement the `NNG_NO_IPV6` or possibly an automatic test for IPv6 support before building. Another possibility would be to make the v6 test failures only output warnings and not fail building if these don't pass.
