### ISSUE TITLE
Memory occupation of arm platform

### ISSUE THREAD

**Issue by ziyuyouxia** [nanomsg/nng#1497]
**Describe the bug**
Using NNG on ARM platform takes up 160m of memory, while using the same program on Windows platform takes up only about 2m

**Expected behavior**

**Actual Behavior**
Describe what occurred.

**To Reproduce**
int main ()
{
    int rc;
    int bus1;
    int bus2;
    int bus3;
    char buf [3];

    /*  Create a simple bus topology consisting of 3 nodes. */
    bus1 = test_socket (AF_SP, NN_BUS);
    test_bind (bus1, SOCKET_ADDRESS_A);
    bus2 = test_socket (AF_SP, NN_BUS);
    test_bind (bus2, SOCKET_ADDRESS_B);

    nn_sleep(100);

    test_connect (bus2, SOCKET_ADDRESS_A);
    bus3 = test_socket (AF_SP, NN_BUS);
    test_connect (bus3, SOCKET_ADDRESS_A);
    test_connect (bus3, SOCKET_ADDRESS_B);

    /* Wait for connections to establish asynchronously. */
    nn_sleep(100);

    /*  Send a message from each node. */
    test_send (bus1, "A");
    test_send (bus2, "AB");
    test_send (bus3, "ABC");

    /*  Check that two messages arrived at each node. */
    rc = nn_recv (bus1, buf, 3, 0);
    errno_assert (rc >= 0);
    nn_assert (rc == 2 || rc == 3);
    rc = nn_recv (bus1, buf, 3, 0);
    errno_assert (rc >= 0);
    nn_assert (rc == 2 || rc == 3);
    rc = nn_recv (bus2, buf, 3, 0);
    errno_assert (rc >= 0);
    nn_assert (rc == 1 || rc == 3);
    rc = nn_recv (bus2, buf, 3, 0);
    errno_assert (rc >= 0);
    nn_assert (rc == 1 || rc == 3);
    rc = nn_recv (bus3, buf, 3, 0);
    errno_assert (rc >= 0);
    nn_assert (rc == 1 || rc == 2);
    rc = nn_recv (bus3, buf, 3, 0);
    errno_assert (rc >= 0);
    nn_assert (rc == 1 || rc == 2);

    /*  Wait till both connections are established. */
    nn_sleep (10);

    while(1){
        nn_sleep (100);
    }
    test_close (bus3);
    test_close (bus2);
    test_close (bus1);

    return 0;
}

** Environment Details **
 - NNG version 1.5.2
 - arm 
 - arm-linux-gnueabihf 
 - Shared and static library

**Comment by gdamore** [comment]
160 MB does seem like a lot.  There should not be anything specific to ARM in this regard.

What transport were you using (what URL)?  What compile options did you use?  What tool did you use to measure the memory footprint?

Also, be careful not to confuse RSS and SIZE.  RSS is the *resident* memory, and is the "real" value, where as SIZE represents mapped pages can reflect larger shared libraries, as well as pages mapped for use by the operating system for various purposes including zero copy I/O.

Note that there are good and easy ways to minimize the footprint of the system as well.  For example, disabling statistics support, and disabling transports and protocols you are not going to use.  However, even if you build with all the options, it seems hard to believe you'd have 160M.

I have no idea how memory usage is measured on Windows, so I can't offer a good comparison.

**Comment by gdamore** [comment]
Closing due to lack of sufficient information to debug this.
