### ISSUE TITLE
nng_device causes nng_close to blocking

### ISSUE THREAD

**Issue by ruantu** [nanomsg/nng#1503]
**Describe the bug**
nng_device causes nng_close to block.

**Expected behavior**
nng_device exits after called nng_close.

**Actual Behavior**
the return condition of nng_device is that one of the sockets is closed, but nng_close is now blocked.

** Environment Details **
 - v1.5.2
 - linux 5.13.12
 - gcc 11

**Comment by gdamore** [comment]
The issue is caused by the reference count on the socket not being dropped before entering into nni_device.
