### ISSUE TITLE
coredump on nng_stream mode

### ISSUE THREAD

**Issue by shishaotang** [nanomsg/nng#1506]
when I use nng_stream mode, and send data very fast from the client,(about 10000 package per second, 128bytes per package, three clients together), and when I kill the clients, the server will get a core dump, just like this:
![image](https://user-images.githubusercontent.com/17543013/132467421-efab389c-78e0-432f-bbcf-cf204dc25c70.png)
another core dump backtrace like this:
![image](https://user-images.githubusercontent.com/17543013/132470700-507b9a63-5a59-4157-919c-207f8abffec7.png)

I use nng_stream_close, and then nng_stream_free to free the stream resource when the server got recv error or send error,
I want to know whether I have some mistake or it's really a bug in nng? thank you!
the system is 
![image](https://user-images.githubusercontent.com/17543013/132469312-27e34a6a-bbe9-411c-b3cd-e17890f4133e.png)

**Comment by shishaotang** [comment]
I make some test, and find that if I use nng_stream_close and nng_stream_free in aio_sent fuction, and kill all the clients, the server will core.

**Comment by gdamore** [comment]
Looks like a bug.  Any chance you can provide a simple reproducer?

**Comment by shishaotang** [comment]
I just resolved this problem by free them(use nng_stream_close and nng_stream_free) in aio_recv function, that will not core dump...
