### ISSUE TITLE
How to connect to a websocket port using nng_dial?

### ISSUE THREAD

**Issue by sleichu2** [nanomsg/nng#1508]
I know very little about the relevant knowledge.
When I dial a ws port, I get a ret "9", which means "Invalid argument". 
How to configure correctly, or if additional configuration is needed

my code as following
`ret = nng_push0_open(&mSocket)`
`if (ret != 0)`
`{`
  `setError("Creating push socket", ret);`
  `return false;`
`}`
`ret = nng_dial(mSocket, url, nullptr, 0);`
`if (ret != 0)`
`{`
  `setError("Could not dial", ret);`
  `return false;`
`}`
the ws url is "ws://127.0.0.1:50051", This is a random url and I wanna how to get a legal ws url.

Thanks.

**Comment by gdamore** [comment]
You need to append a path to the URL, probably.

**Comment by sleichu2** [comment]
It seems that I can dial the number, but still cannot successfully communicate. I used aio to implement a async communication, does this influential?

**Comment by gdamore** [comment]
do you have a server listening at the corresponding the url

**Comment by gdamore** [comment]
I need to see the corresponding server side before I can really be of much assistance.

**Comment by gdamore** [comment]
Absent more information, I can't help.  I'm going to close this -- feel free to reopen with a sample of your server code that demonstrates the problem -- I will help if I'm able.
