### ISSUE TITLE
Http server stops working after 16 input stream connection!

### ISSUE THREAD

**Issue by afshin2003** [nanomsg/nng#1510]
Hi Guys,

After 16 incoming stream connection (each on different listener i.e.  ws://*/rtm/Gtjk6FLZkdV), server stops to calling back handlers. I have a few http handlers too. My scenario is to accept each new incoming stream in a dedicated web socket address. So I allocate a new listener for it. After the stream is created I close and free it properly. For the 16th connection my callback function is called but no further event at all even on my http handlers!

I expect the http server continue working!

**Actual Behavior**
Describe what occurred.

**To Reproduce**
I do :

nng_stream_listener_alloc
nng_stream_listener_listen
nng_aio_alloc
nng_aio_set_timeout
nng_stream_listener_accept

in the callback:

nng_aio_result
nng_aio_get_output

getting stream and ...

nng_stream_listener_close
nng_stream_listener_free
nng_aio_free

** Environment Details **
 - NNG version 1.5.2
 - Operating system Debian Buster 10.10
 - gcc (Debian 8.3.0-6) 8.3.0 / C language
 - libjwt, libhredis, libae

**Additional context**

**Comment by gdamore** [comment]
Based on the symptoms, my guess is that you're doing things you shouldn't inside the callback, and that the callback threads are all blocked.  When that happens, nothing else can run.

I'm not 100% certain it is safe to free streams or listeners in aio callbacks.  It used to be that nng_aio_free was *not* safe, but I believe it should be in recent versions as I've specifically done work to make that function.

If you're doing anything else in your callback which blocks, or has a dependency on something else running, that could easily be the source of your grief.

Note that various other users of NNG have created projects with *thousands* of concurrent stream objects.  (Tens of thousands in some cases!)  But care is needed to make sure your callbacks are "safe".

**Comment by afshin2003** [comment]
Really appreciated for your comment. It seems that caused by nng_aio_free in the call back function. I will provide more data soon.

Best

**Comment by gdamore** [comment]
I just refreshed my memory.  Change your call from nng_aio_free() to nng_aio_reap().  They both free the object, but nng_aio_reap() does it asynchronously and is safe to call from the callback.  (It was created especially for this purpose.)

**Comment by afshin2003** [comment]
Great job! It works.
