### ISSUE TITLE
 can nng socket do async  recv in client side ?

### ISSUE THREAD

**Issue by bigo2050** [nanomsg/nng#1513]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bigo2050** [comment]
struct nn_polld pfd [2];
pfd [0].fd = s1;
pfd [0].events = NN_POLLIN | NN_POLLOUT;
pfd [1].fd = s2;
pfd [1].events = NN_POLLIN;
rc = nn_poll (pfd, 2, 2000);
if (rc == 0) {
    printf ("Timeout!");
    exit (1);
}
if (rc == -1) {
    printf ("Error!");
    exit (1);
}
if (pfd [0].revents & NN_POLLIN) {
    printf ("Message can be received from s1!");
    exit (1);
}

is there an call back function notify me  recv are ready?

**Comment by gdamore** [comment]
I think look for nng_poll.  But you can also use regular poll or select with the fd from NNG_OPT_RECVFD.

**Comment by bigo2050** [comment]
I appreciate your message.  and you work
