### ISSUE TITLE
assert in aio.c

### ISSUE THREAD

**Issue by apsgc** [nanomsg/nng#1514]
**Describe the bug**
core/aio.c: 331: assert err: aio->a_cancel_fn == NULL

**To Reproduce**
Minimal test case based on the [pair example](https://nanomsg.org/gettingstarted/nng/pair.html);
[pair.c](https://github.com/nanomsg/nng/files/7284134/pair.txt)

1. Start on two computers
    - first:         `.\NNG-Test.exe node0 sync tcp://:3400`
    - second:    `.\NNG-Test.exe node1 sync tcp://ip_of_first:3400`
2. Disconnect one computer from the network
3. Assert happens on reconnection

**Environment Details**
 - 8fffbb7
 - Windows 10, 21H1
 - mingw 8.1.0, x86_64
 - static

**Comment by gdamore** [comment]
You're calling an operation on the aio from the pipe event callback.  And I don't think you're properly confirming that the aio is not already in progress, or using separate aio objects for each of this.

Unfortunately, the pipe event callbacks were never intended for this kind of usage, and the use of aio operations inside them is doomed to failure.  You *can* call nng_pipe_close() but really from that context that's about all you can do.

I've not tested your program yet, but I'm reasonably certain from just a casual reading of it that it cannot possibly work.

It looks like you're trying to do this to provide some sort of application layer keep alive, but unfortunately you'd need to rethink this somewhat.  My guess is that you should just use an unconditional keep alive on the socket, and not try to tie this to application connection events.
