### ISSUE TITLE
Disconnect during negotiation breaks listener

### ISSUE THREAD

**Issue by jfink2** [nanomsg/nng#1518]
**Describe the bug**
Window 1 
$  ./nngcat --sub0 --listen ipc:///tmp/gw --ascii

Window 2
$  ./nngcat --sub0 --listen ipc:///tmp/gw --ascii
Unable to listen on ipc:///tmp/gw: Address in use

Window 3
$ ./nngcat --count=200 -i 1 --pub0 --dial ipc:///tmp/gw --verbose --data "Window 3"

**Expected behavior**
Window 1 nngcat should print "Window 3"

**Actual Behavior**
Nothing, Window 1 did not print anything.  IF you skip the nngcat in Window 2, Window 1 will print as expected.

**To Reproduce**
I do have C code that does the same - that's how I discovered, but thought nngcat would be better.

** Environment Details **
nng 1.5.2 running on Centos 7.x, gcc 4.8.5 libnng.a (compiled from source)
nng 1.5.2 running on Xubuntu 20.04, gcc 9.3, libnng.a (compiled from source)

**Additional context**
N/A

**Comment by gdamore** [comment]
I confirm this behavior.  I'm having a difficult time explaining it since the system calls seem to indicate that I'm doing the right thing (analysis via strace).  I will test on other operating systems, perhaps this is a Linux bug.

**Comment by gdamore** [comment]
Well it happens on macOS as well.  So I guess it's something I've botched.
