### ISSUE TITLE
tests/httpserver static handler response body format not correct

### ISSUE THREAD

**Issue by ZRiemann** [nanomsg/nng#1522]
**Describe the bug**
1. add test code nng_msleep(3600000) at line 284 tests/httpserver, then build and run httpserver
2. postman send GET http://127.0.0.1:5547/home.html
3. response ERROR body: \<html\>\<body\>Someone \<b\>is\</b\> home!\</body\</html\>
4. expected correct body: \<html\>\<body\>Someone \<b\>is\</b\> home!\</body\>\</html\>

**Expected behavior**
Except body:
\<html\>\<body\>Someone \<b\>is\</b\> home!\</body\>\</html\>

**Actual Behavior**
Actual body:
\<html\>\<body\>Someone \<b\>is\</b\> home!\</body\</html\>
lost '>' behind "\</body"

**To Reproduce**
Non

** Environment Details **
 - NNG version:                               v1.5.1
 - Operating system and version:   Ubuntu 20.04
 - Compiler and language used:     gcc9.0
 - Shared or static library:                static library

**Additional context**
Non

**Comment by gdamore** [comment]
This is an error in the actual inline HTML.  Oops.
