### ISSUE TITLE
relocation against

### ISSUE THREAD

**Issue by alvin1221** [nanomsg/nng#1524]
**Describe the bug**
The issue happened while building third-party **dynamic** library with nng **static** library :

/usr/bin/ld: /usr/local/lib/libnng.a(inproc.c.o): warning: relocation against `nni_inproc_tran' in read-only section `.text'
/usr/bin/ld: /usr/local/lib/libnng.a(posix_debug.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC

**Expected behavior**
Add compile option "-fPIC"

**Actual Behavior**
Describe what occurred.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NNG version: 1.5.2 
 - Operating system and version: Ubuntu 20.04
 - Compiler and language used: C
 - Shared or static library: static 

**Additional context**

**Comment by gdamore** [comment]
-fPIC is usually *not* what you want for static compilation.  The fact that you're creating a static library, but then trying to use it in a dynamically linked project, is to blame.  This requires a little more savvy on the part of the app developer.

Probably you should just link dynamically.

**Comment by gdamore** [comment]
Please either ensure the entire project uses static libraries, or none of them do.  Alternatively, you can set the compile flags in your top-level (or the consuming project if that is better) to specify -fPIC or whatever. 

This particular problem isn't a bug with NNG itself, and it is quite normal (preferable) that static libraries are not position independent.
