### ISSUE TITLE
two nodes dial one node when using pair protocol doesn't return error

### ISSUE THREAD

**Issue by wutianze** [nanomsg/nng#1527]
**Describe the bug**
When using pair protocol(version 0 or version 1), I try to use more than one node to dial one node. Let's say node1 and node2 try to talk with node0 at the same time. The result is node0 and node1 can talk freely, but node2 can still run nng_dial or nng_send without returning error, although node0 seems to ignore the msg from node0.

**Expected behavior**
When node0 and node1 make a pair, node2 should fail to build another one-to-one relationship with node0 which means nng_dial or nng_send by node2 shouldn't return 0.

**Actual Behavior**
nng_send and nng_dial by node2 still return 0.

**To Reproduce**
Use the pair demo in the getstarted doc: https://nanomsg.org/gettingstarted/nng/pair.html. Just add one node.

** Environment Details **
 - NNG version: latest
 - Operating system and version: ubuntu 20.04
 - Compiler and language used: c
 - Shared or static library

**Comment by gdamore** [comment]
The demo did not specify a send timeout.  This means that you won't see an error, because it will keep trying to send the message *indefinitely*.   This was a basic demo, admittedly, and does not cover all error cases.

The dial will likewise keep retrying in the background in case the first relationship is broken and the second partnership might later become functional.

I don't think, therefore, that this is necessarily a bug.

If you want observability into this, you can configure a pipe event handler which will tell you when the other side disconnects (which it will when it already has a relationship established.)

But really the best for you is probably to configure a send timeout.

**Comment by wutianze** [comment]
> The demo did not specify a send timeout. This means that you won't see an error, because it will keep trying to send the message _indefinitely_. This was a basic demo, admittedly, and does not cover all error cases.
> 
> The dial will likewise keep retrying in the background in case the first relationship is broken and the second partnership might later become functional.
> 
> I don't think, therefore, that this is necessarily a bug.
> 
> If you want observability into this, you can configure a pipe event handler which will tell you when the other side disconnects (which it will when it already has a relationship established.)
> 
> But really the best for you is probably to configure a send timeout.

Thank you for your time and reply. Could you please tell me how to configure a send timeout? In my understanding, to configure a send timeout, I should use nng_aio_scheduler to configure an aio with a specified cancel function, in that function, I should check the a_result to see whether the msg is sent successfully. However, I found that the a_result is always 0(like in doc, nng_send only provides the best-effort option). Then it seems that only configuring a send timeout is no use? The only method to know whether the message is sent successfully is to both configure a pipe event and a send timeout in aio (despite the pattern of reqrep which ensures reliability by receiving a reply)?

**Comment by janjaapbos** [comment]
To catch the pipe removal event, the demo can be extended as follows:

```
void pipe_cb(nng_pipe p, nng_pipe_ev ev, void *arg) {
        switch (ev) {
                case NNG_PIPE_EV_ADD_PRE: printf("NNG_PIPE_EV_ADD_PRE\n");
                case NNG_PIPE_EV_ADD_POST: printf("NNG_PIPE_EV_ADD_PRE\n");
                case NNG_PIPE_EV_REM_POST: printf("NNG_PIPE_EV_REM_PRE\n");
        }
}

int
node1(const char *url)
{
        nng_socket sock;
        int rv;
        sleep(1);
        if ((rv = nng_pair0_open(&sock)) != 0) {
                fatal("nng_pair0_open", rv);
        }

        if ((rv = nng_pipe_notify(sock, NNG_PIPE_EV_REM_POST, pipe_cb, NULL)) != 0) {
                fatal("nng_pipe_notify", rv);
        };

        if ((rv = nng_dial(sock, url, NULL, 0)) != 0) {
                fatal("nng_dial", rv);
        }
        return (send_recv(sock, NODE1));
}
```

**Comment by wutianze** [comment]
> To catch the pipe removal event, the demo can be extended as follows:
> 
> ```
> void pipe_cb(nng_pipe p, nng_pipe_ev ev, void *arg) {
>         switch (ev) {
>                 case NNG_PIPE_EV_ADD_PRE: printf("NNG_PIPE_EV_ADD_PRE\n");
>                 case NNG_PIPE_EV_ADD_POST: printf("NNG_PIPE_EV_ADD_PRE\n");
>                 case NNG_PIPE_EV_REM_POST: printf("NNG_PIPE_EV_REM_PRE\n");
>         }
> }
> 
> int
> node1(const char *url)
> {
>         nng_socket sock;
>         int rv;
>         sleep(1);
>         if ((rv = nng_pair0_open(&sock)) != 0) {
>                 fatal("nng_pair0_open", rv);
>         }
> 
>         if ((rv = nng_pipe_notify(sock, NNG_PIPE_EV_REM_POST, pipe_cb, NULL)) != 0) {
>                 fatal("nng_pipe_notify", rv);
>         };
> 
>         if ((rv = nng_dial(sock, url, NULL, 0)) != 0) {
>                 fatal("nng_dial", rv);
>         }
>         return (send_recv(sock, NODE1));
> }
> ```

Thanks, I will try this in my use case.

**Comment by gdamore** [comment]
Btw, SEND timeouts can be configured with nng_socket_set_ms(socket, NNG_OPT_SENDTIMEO, <some time in msec>)

Have a look at nng_options(5) for more details.
