### ISSUE TITLE
bug in nni_chunk_insert

### ISSUE THREAD

**Issue by wutianze** [nanomsg/nng#1541]
**Describe the bug**
![image](https://user-images.githubusercontent.com/13427786/144172236-b18782b4-5360-40b8-bab1-63f76cdb9069.png)
![image](https://user-images.githubusercontent.com/13427786/144172598-ea7a39a8-a227-4f04-8d3f-5d40acf4c089.png)
Like I paint in the second pic. If the ch_ptr = 2, ch_buf=0, ch_len=3, ch_cap=7, data len=4, the insert func will move ch_ptr to place 6 which is an error.

Should correct memmove(ch->ch_ptr + len, ch->ch_ptr, ch->ch_len); to memmove(ch->ch_buf + len, ch->ch_ptr, ch->ch_len);

**Comment by gdamore** [comment]
Good catch. Thanks.
