### ISSUE TITLE
GCC diagnostic inside functions not supported in older compilers

### ISSUE THREAD

**Issue by npoppleton** [nanomsg/nng#1550]
Simple fix for posix_pipe.c:
Moving these pragmas outside the function body allows it to compile on older compilers that would otherwise fail.

void
nni_plat_pipe_raise(int wfd)
{
	char c = 1;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-result"
	(void) write(wfd, &c, 1);
#pragma GCC diagnostic pop
}

**Comment by gdamore** [comment]
I quite honestly *hate* this.  The entire pragma thing is complete bullshit -- by using (void) I've explicitly said that I know that the return value is unused, and it's ok.  This is an instance of compiler people trying to be smarter, but actually being dumber.

I'm inclined to just remove the diagnostic overrides (pragmas) altogether.

**Comment by gdamore** [comment]
Actually, the need for this pragma is caused by an idiot operating system that says that all calls to write() should be error checked.  While that might often be the case, it isn't the case here -- we're completely fine if this fails.

**Comment by gdamore** [comment]
It looks like *I* made the change to add those pragmas, probably in response some boneheaded Linux header.  I'm going to just remove them altogether.
