### ISSUE TITLE
Several warnings compiling in Windows with Visual Studio 2019

### ISSUE THREAD

**Issue by wan1271** [nanomsg/nng#1552]
**Describe the bug**
Warning to compile in 64bits:

Implementation of function nni_atomic_set_ptr diferent to declaration in platform.h

src/platform/windows/win_thread.c line 231
void nni_atomic_set_ptr(nni_atomic_ptr *v)
but 
src/core/platform.h
extern void nni_atomic_set_ptr(nni_atomic_ptr *, void *);
-----------
src/core/reap.c lines 23 and 24
src/platform/windows/win_resolv.c line 30
Initializing warning incompatible type. from nni_mtx * to PSRWLOCK
-----------
src/core/idhash.c lines 195, 195 and 199
Conversion from size_t to uint32_t
-----------
src/core/idhash.c line 180
Posible arithmetic overflow 
id_count is uint32_t and new_cap is size_t 

** Environment Details **
 - NNG version: 1.6.0
 - Operating system and version: Windows 10
 - Compiler and language used: Visual Studio 2019  - 16.11.8
 - Shared or static library

**Comment by JaylinYu** [comment]
I am curious about where to find NNG ver 1.6...

**Comment by wan1271** [comment]
See commit
https://github.com/nanomsg/nng/commit/efa702387fcfa80ddd02e1a85f73c5b6f6ba1955

include/nng.h

**Comment by gdamore** [comment]
It's not tagged. So not really 1.6. 😄

**Comment by gdamore** [comment]
So one of these "warnings" is actually a rather serious crasher bug if you try to use TLS on Windows.
