### ISSUE TITLE
High CPU usage and memory leak

### ISSUE THREAD

**Issue by rty813** [nanomsg/nng#1570]
**Describe the bug**
When I use the pynng module, there will be occasional memory leaks, the available memory will gradually decrease, and the CPU usage will reach more than 120%. Since my program is more complicated, I'm not sure if it's a problem with the pynng module, or something else. So I want to ask, is there any way to troubleshoot?

**Expected behavior**
run normally

**Actual Behavior**
CPU usage high and free memory decrease

**To Reproduce**
I cannot find a way to reproduce.

** Environment Details **
 - NNG version
 pynng==0.7.1
 - Operating system and version
 ubuntu18.04
 - Compiler and language used
 python
 - Shared or static library

**Additional context**
There are some logcat screenshot.

1. lsof
![e06d2d7f99a1fd4d06642fa48749213](https://user-images.githubusercontent.com/22488813/151483299-b8ce6316-22cf-49a6-a1ef-c9bc91a23b24.png)

2. strace (9742 is the problematic process)
![4ab9b2a9d415eacb7833808b076755b](https://user-images.githubusercontent.com/22488813/151483308-703a2cb7-f201-45a9-b531-d81619b9855b.png)

3. top -c
![image](https://user-images.githubusercontent.com/22488813/151484163-391ba202-e541-449b-b619-eed59e3c593e.png)

4. mem_avail
![1643342449(1)](https://user-images.githubusercontent.com/22488813/151485157-1d3d4284-18c8-42ff-8a2d-267ef7065357.jpg)

**Comment by gdamore** [comment]
Can you confirm, are you running a recent build of NNG?  I can't speak to pynng itself, as that's a third party product.

**Comment by rty813** [comment]
The nng commitID used by pynng is `4f5e11c391c4a8f1b2731aee5ad47bc0c925042a`. Is there anything wrong with this version?

**Comment by gdamore** [comment]
That is a quite old version.  I've made a *lot* of improvements since thing, especially for performance and scalability.  I think you should try the new version if you can.

**Comment by gdamore** [comment]
Also, which pattern (req/rep, pub/sub, etc.) are you using?

**Comment by rty813** [comment]
> 

req/rep and bus

**Comment by rty813** [comment]
> That is a quite old version. I've made a _lot_ of improvements since thing, especially for performance and scalability. I think you should try the new version if you can.

OK, I'll have try,  thank you

**Comment by rty813** [comment]
![Snipaste_2022-08-12_09-53-55](https://user-images.githubusercontent.com/22488813/184270703-a72b5e56-cd83-4d02-b75b-1dc04bc184c3.jpg)
This time, I installed nng's master branch, but `rcu_preempt` still happend. 
There are my code:
```python
import pynng
import time
while True:
  req = pynng.Req0()
  req.dial(f'tcp://127.0.0.1:12345')
  req.send(b'asdvasdvasdv')
  data = req.recv()
  req.close()
```

```python
import pynng
node = pynng.Rep0(send_timeout=1000)
node.listen(f'tcp://0.0.0.0:12345')
while True:
  data = node.recv()
  node.send(b'asdfasdfasdf1')
```

**Comment by rty813** [comment]
`rcu_preempt` problems will occur after the program runs for several hours.

**Comment by gdamore** [comment]
Are you trying to run NNG as a realtime priority process?  It isn't qualified or suitable really for that because of interactions between different threads.  Fixed priority scheduling won't work well, I think.

**Comment by gdamore** [comment]
So I think RCU preempt is happening not because of NNG, but because of something in your tuning, hardware, or workload.  See:

https://www.kernel.org/doc/Documentation/RCU/stallwarn.txt

rcu_preempt is a detector for kernel threads.  A user space application should not be able to trigger this unless you're making a mistake of running it at real-time priority.  Running NNG at real-time priority (or higher priority than kernel threads) is definitely *not* supported.
