### ISSUE TITLE
httpclient test failed

### ISSUE THREAD

**Issue by leaveye** [nanomsg/nng#1573]
**Describe the bug**
maybe reproduced #787 

**Expected behavior**
test should pass, maybe other does.

**Actual Behavior and Reproduce**
`ninja test` failed, and follow the script, i get this:

```shell
levi@Levi-15pIMH /home/levi/.cache/paru/clone/nng/src/build/tests
⚡ ./httpclient -v -p TEST_PORT=13040
=== RUN: HTTP Client

  Given a TCP connection to example.com ✔✔✔✔
    We can initiate a message ✔✔✔✔✔✔
      The message contents are correct ✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔
  Given a client ✔✔✔
    One off exchange works ✔✔✔✔✔✔✔✔
    Connection reuse works ✔✔✔✔✔✔✔✔✔✔✔✔✔
  Client times out ⚠
  Given a client (chunked) ✔✔✔
    One off exchange works ✔✔✘✔✔✔


Failures:

  * Assertion Failed (One off exchange works)
  File: /home/levi/.cache/paru/clone/nng/src/nng-1.5.2/tests/httpclient.c
  Line: 37
  Test: nng_aio_result(aio) == 0
```

**Environment Details**
 - Archlinux
 - [nng 1.5.2](https://aur.archlinux.org/packages/nng) and the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nng)

**Comment by gdamore** [comment]
This is so old, and has not been seen anywhere else,  I'm just closing it as not reproducible.
