### ISSUE TITLE
demo projects don't build

### ISSUE THREAD

**Issue by pptz** [nanomsg/nng#1582]
Ubuntu 16. The problem during `cmake` stage is:

CMake Warning (dev) at CMakeLists.txt:18 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "raw" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

And building will fail.

The solution is to add to CMakeLists.txt:

`set(THREADS_PREFER_PTHREAD_FLAG ON)`
`find_package(Threads REQUIRED)`

For more: https://stackoverflow.com/questions/1620918/cmake-and-libpthread

**Comment by gdamore** [comment]
This is now fixed in 60ff324b1e6e5124dbbfefec732940512ed40f87
