### ISSUE TITLE
TLS should log errors

### ISSUE THREAD

**Issue by Sec42** [nanomsg/nng#1588]
**Is your feature request related to a problem? Please describe.**
When using the `tls+tcp://` protocol I can not tell whether the connection does not work because the other side is not listening, or if the tls handshake is not working.

`nng_pipe_notify()` does not seem to have triggers for this case.

**Describe the solution you'd like**
Some way to get notified of the failed connection attempts. Preferably including a reason why the connection failed

**Describe alternatives you've considered**
It would probably be possible to do a connection attempt outside of nng to test for this case, but that seems convoluted.

**Additional context**
It would help me make my program more user-friendly to notify the end user of such a problem instead of waiting indefinitely for a connection.

**Comment by gdamore** [comment]
the problem is that nni_pipe_notify() is only able to pick up post-negotiation.  I need to think about adding either logging hooks or some kind of other callback mechanism for TLS.

**Comment by gdamore** [comment]
If you're client side, nng_dial() should return an error, and the error code should discriminate between TLS and non-TLS errors (e.g. ECONNREFUSED).   Getting more detail about the TLS error is harder.  I'll think on this.
