### ISSUE TITLE
question about the order of pub server and sub client

### ISSUE THREAD

**Issue by kwangxn** [nanomsg/nng#1592]
**Describe the bug**
I found that data can be received normally when the server is started first. However, when the client is started first,, the data cannot be received. Is this a question please？

**Comment by gdamore** [comment]
What version are you running?  This sounds like a bug that I think I already fixed.

**Comment by kwangxn** [comment]
thank you for your reply
The software version number I use is 1.5.2
My test code is as follows
MacOs 12.3.1 
<img width="596" alt="image" src="https://user-images.githubusercontent.com/55137299/171198076-7f9f2578-48c3-4cfd-8a14-3c3a3a738815.png">


```
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include <nng/nng.h>
#include <nng/protocol/pubsub0/pub.h>
#include <nng/protocol/pubsub0/sub.h>

#define SERVER "server"
#define CLIENT "client"

void fatal(const char *func, int rv)
{
    fprintf(stderr, "%s: %s\n", func, nng_strerror(rv));
}

char *
date(void)
{
    time_t now = time(&now);
    struct tm *info = localtime(&now);
    char *text = asctime(info);
    text[strlen(text) - 1] = '\0'; // remove '\n'
    return (text);
}

int server(const char *url)
{
    nng_socket sock;
    int rv;

    if ((rv = nng_pub0_open(&sock)) != 0)
    {
        fatal("nng_pub0_open", rv);
    }
    if ((rv = nng_listen(sock, url, NULL, 0)) < 0)
    {
        fatal("nng_listen", rv);
    }
    for (;;)
    {
        char *d = date();
        printf("SERVER: PUBLISHING DATE %s\n", d);
        if ((rv = nng_send(sock, d, strlen(d) + 1, 0)) != 0)
        {
            fatal("nng_send", rv);
        }
        sleep(1);
    }
}

int client(const char *url, const char *name)
{
    nng_socket sock;
    int rv;

    if ((rv = nng_sub0_open(&sock)) != 0)
    {
        fatal("nng_sub0_open", rv);
    }

    // subscribe to everything (empty means all topics)
    if ((rv = nng_setopt(sock, NNG_OPT_SUB_SUBSCRIBE, "", 0)) != 0)
    {
        fatal("nng_setopt", rv);
    }
    if ((rv = nng_dial(sock, url, NULL, 0)) != 0)
    {
        fatal("nng_dial", rv);
    }
    for (;;)
    {
        char *buf = NULL;
        size_t sz;
        if ((rv = nng_recv(sock, &buf, &sz, NNG_FLAG_ALLOC)) != 0)
        {
            fatal("nng_recv", rv);
        }
        printf("CLIENT (%s): RECEIVED %s\n", name, buf);
        nng_free(buf, sz);
    }
}

int main(const int argc, const char **argv)
{
    if ((argc >= 2) && (strcmp(SERVER, argv[1]) == 0))
        return (server(argv[2]));

    if ((argc >= 3) && (strcmp(CLIENT, argv[1]) == 0))
        return (client(argv[2], argv[3]));

    fprintf(stderr, "Usage: pubsub %s|%s <URL> <ARG> ...\n",
            SERVER, CLIENT);
    return 1;
}
```

when I run client first, the results are as follows
<img width="575" alt="image" src="https://user-images.githubusercontent.com/55137299/171198707-cf2a7a91-3ba7-4824-b0eb-c95486ce4707.png">

When I run the server first, and then run the client, the results are as follows
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/55137299/171199168-f7226991-271b-48d8-8d5c-6ebe9823a427.png">

**Comment by gdamore** [comment]
Ah yeah, the "fatal" should have included an exit().

This is because the dialer has failed, and it does this if you use the default settings for dialing (this is to make diagnosing failures like this easier -- it more closely matches the people working with TCP expect.)

If you want it to "self-heal" in this case, you need to use asynchronous dialing.

Instead of passing 0 as the last argument to nng_dial(), pass NNG_FLAG_NONBLOCK

It should start working then.

**Comment by kwangxn** [comment]
Thanks a lot, nng is a great project
