### ISSUE TITLE
How can I determine whether a certain socket is open or not?

### ISSUE THREAD

**Issue by SpaceView** [nanomsg/nng#1593]
In order to prevent reopening an open socket, is there any way to retrieve the socket status of a specific socket?
e.g.  I cannot retrieve anything with the following code, the program crashes
```
        nng_socket sock = {1};
	int        rv;		

	if ((rv = nng_req0_open(&sock)) != 0) {
		fatal("nng_pair0_open", rv);
	}
	nng_stat* stats = NULL;
	nng_stats_get(stats);     // <--------------- program crash
	nng_stat* st = nng_stat_find_socket(stats, sock);
```

**Comment by gdamore** [comment]
You use of the stats API is wrong.  You have to pass a pointer to stats, like this:

nng_stats_get(&stats);

If you had sufficient compiler flags enabled, it should have warned about incorrect pointer usage.
