### ISSUE TITLE
http_uri_canonify() out-of-bounds

### ISSUE THREAD

**Issue by manuelgustavo** [nanomsg/nng#1594]
http_uri_canofify() fails for URIs terminating with e.g. %AF.
It goes out of bounds.

** Environment Details **
 - NNG version 1.5.2 (and previous version)
 - Operating system and version Windows / Linux
 - Compiler and language used. clang / msvc 
 - Both shared and static libraries

**Comment by gdamore** [comment]
Lol.  that's an invalid URL, but yeah, the code that deals with it is busted, I see your PR.
