### ISSUE TITLE
NNG large virtual memory allocation

### ISSUE THREAD

**Issue by hpk-roquette** [nanomsg/nng#1596]
Hi,

Playing around with NNG, we notice the virtual memory allocation seems very large. Is this normal?

For example, with the simple example pubsub.c (https://nanomsg.org/gettingstarted/nng/pubsub.html):
```
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 2174  2069 root     S     101m  41%   0% ./pubsub server ipc:///tmp/pubsub.ipc
```

This seems very large, any explanation for this?

Thank you!

**Comment by gdamore** [comment]
Virtual memory means very little in the real world -- I would not stress about it.

The issue of growth of virtual memory can be based on many things, such as mappings made to C libraries, devices (via mmap for example) and so forth.

Look at *real* (resident) memory instead.  On Solaris systems this is identified as SZ, but I'm not sure if it's the same on Linux or whatever OS you're running.

There may be other tools that let you see where the pages are used.  Again, I am not familiar with the tools for this on Linux, but on Solaris you'd use (for example) the "pmap" utility, which would show the various mappings are used.

**Comment by gdamore** [comment]
One thing it might be (probably is), is allocation of room (virtual address space) for stacks.  We create a number of threads, mostly which run idle, but if you have a large number of cores present, and your default stack size is 8M or something like that, we could wind up allocating page space for those stacks.

Note that NNG itself does not normally use very much stack space, and most system that do this kind of allocation won't actually allocate real memory unless the the stack grows beyond the initial allocation which is typically a page (say 4K).  Often they grow a page at a time.

The virtual allocation is to allow for the *possibility* that a thread could e.g. put a 1M object on its stack.

Assuming that's what this is, I would not worry about it -- its probably perfectly normal for your platform.
