### ISSUE TITLE
Questions about sendmsg and recemsg

### ISSUE THREAD

**Issue by kwangxn** [nanomsg/nng#1597]
version : nag-1.5.2

Hello, I have two questions about nng_sendmsg and nng_recemsg in pub/sub mode:
1. When I use nng_sendmsg to send a string, but the size of the received message is inconsistent with the sent size, is there something wrong with my usage?

```
std::string data("hello");
nng_msg* msg;
nng_msg_alloc(&msg,data.length());
nng_msg_append(msg,&data[0],data.length());
nng_sendmsg(sock,msg,0)
```
data.length()==5

```
nng_msg* msg;
nng_recvmsg(sock,&msg,0);
int len=nng_msg_len(msg);
```
len=10;

2. When using nng_sendmsg and nng_recemsg, how to set nng_setopt(sock,NNG_OPT_SUB_SUBSCRIBE,xxx,xxx) on the subscriber side, if I want to filter the message

Looking forward to your reply.

**Comment by gdamore** [comment]
You have allocated a message of five bytes and then appended to it 5 more bytes. 

Instead nng_msg_append you could just write those 5 bytes to the body using nng_msg_body.

**Comment by gdamore** [comment]
Subscriptions filter on the first bytes of your message.  Maybe that wasnt working for you because the first bytes for you were zero due to the above bug?

**Comment by kwangxn** [comment]
oh. I see, extremely grateful

**Comment by kwangxn** [comment]
I have another question, there was an option of sendmore when using zmq to send messages before, is there a way to achieve a similar function in nng?

**Comment by gdamore** [comment]
No.  Because NNG doesn't really support multipart messages like that.
