### ISSUE TITLE
Consultation on compatibility issues

### ISSUE THREAD

**Issue by wsxjbupt** [nanomsg/nng#1609]
In the past, we used nanomsg as a tool for interprocess communication.
Run the following command to check whether the nanomsg channel of the peer process is initialized:
---------------------------------------------------------------------------------------------------------------
int isInitOk(int fd)
{
    uint32_t invlid_num = (uint64_t)(-1);
    while (1) {
        uint32_t subs = (uint32_t) nn_get_statistic (fd, NN_STAT_CURRENT_CONNECTIONS);
        if (subs != invlid_num && subs > 0) {
            return 0;
        }
    }
}
---------------------------------------------------------------------------------------------------------------
In nng1.5.2, the nn_get_statistic interface no longer takes effect. Is there any replacement method?

--------------------------------------------------------------------------------------------------------------
== DESCRIPTION

The `nn_get_statistic()` function exists only as a stub, and always returns
zero.
---------------------------------------------------------------------------------------------------------------

**Comment by gdamore** [comment]
NNG has a statistics API, but it is not directly compatible with legacy nanomsg.

See nng_stats_get() for more information.
