### ISSUE TITLE
TLS test failures

### ISSUE THREAD

**Issue by kiufta** [nanomsg/nng#1618]
Compiled git master with GCC 12.2 under Linux:

```
The following tests FAILED:
	 33 - nng.sp.transport.tcp.tcp_test (Failed)
	 66 - nng.tls (Failed)
```

**Comment by gdamore** [comment]
I probably need a little more information about this.

**Comment by gdamore** [comment]
I'm going to close this because I don't have enough information here to debug those tests.  It might have been environmental who knows.
