### ISSUE TITLE
Warning when building with NDEBUG

### ISSUE THREAD

**Issue by L0PiTaL** [nanomsg/nng#1621]
**Describe the bug**
The compiler emits a warning when building with NDEBUG, due to expanding `NNI_ASSERT` to `(0)`

**Expected behavior**
No warnings

**Actual Behavior**
Warnings emited

**To Reproduce**
Just build the lib in release mode (or with NDEBUG set)

**Comment by ori-d** [comment]
I think this can be replaced with just emty define like
`#define NNI_ASSERT(x) `
That's all.

**Comment by L0PiTaL** [comment]
@ori-d 
yes, there are a lot of ways to fix this. The PR is just one of them, which doesn't alter the current behavior, which is just to introduce a `(0)` instruction (which leads to a no-op). It just silences the diagnostic caused by this instruction.

By the way, with your fix, I _think_ that it silences the diagnostic "empty instruction", but it would emit another diagnostic, "empty statement":
`NNI_ASSERT(whatever);` //Note the last semicolon, so NNI_ASSERT() can be treated as a "normal" function

would be expanded to:
`;` //nothing, but the semicolon remains

which now emits the "empty statement" diagnostic.
While with the solution in the PR, it expands to:
`((void)(0));`

which is a silenced empty instruction (so no diagnostic for this one, as it is silenced), and also not an empty statement (so it neither emits the other diagnostic).

**Comment by gdamore** [comment]
#1622 fixes this.

You can't elide away the (0) ... because it may be used in a context where we have to have a valid statement.
