### ISSUE TITLE
Throw NNG_EADDRINUSE but cannot find which process

### ISSUE THREAD

**Issue by rty813** [nanomsg/nng#1625]
**Describe the bug**
I used "reqrep", tcp socket. When I call "nng_listen" method, it thow NNG_EADDRINUSE exception.

Then, I use "lsof -i:5000" and "ss -tunlp |grep 5000", nothing in the output.

After retry several times, it succeed.

So, how to find which process use the port? and how can I avoid this exception?

**Environment Details**
 - NNG version: 1.3.2
 - Operating system and version: ubuntu 16.04
 - Compiler and language used
 - Shared or static library

**Comment by gdamore** [comment]
I would use netstat -a -f inet | grep LISTEN ... but ports above some port number might actually be in use other than for listening, depending on your operating system configuration.

This is pretty much a standard systems administration problem.  I believe port 5000 is actually widely used for UPnP.  You probably should choose a different port number.  There are other unofficial uses of that port as well: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

I recommend choosing a different port number.  You can use that URL as an initial source of data that you can use to try to avoid common conflicts.  Technically, once a port number is wired into your product, you're supposed to register your use with IANA, but almost nobody does.

**Comment by gdamore** [comment]
This isn't an NNG specific question, so I'm closing this issue.
