### ISSUE TITLE
NNG Socket Concept and Endpoints

### ISSUE THREAD

**Issue by chip5441** [nanomsg/nng#1631]
After going through "NNG Manual" and a quick look at source code, I think there are few shortcomings which should be taken into consideration for better understanding, for people using this lovely library to develop efficient and elegant products on top of it.

In "NNG Manual / Conceptual Overview" mentioned that, "Each socket can have zero, one or many endpoints, which are either listeners or dialers. (A given socket may freely choose whether it uses listeners, dialers or both.)"

Correspondingly, we could have a socket with different endpoints, listeners and dialers, bound to it on different addresses. Right? If correct, what if it is required to send different messages from that single socket with different dialers to different peers, selectively? Or how to filter incoming messages from different peers received through listeners, selectively?

According to interface, a dialer could be queried by its "id" and then associated socket could be retrieved through another function call. Is this socket different from the original socket by which dialer has been created? And same for listeners. This whole story is not about pipes but using the interface, its design and the perception.

Another thing I would like to discuss at this moment is about "NNG" aio. "NNG" is getting its way and many developers are using it in variety of projects. One thing which is very common among them, I think, is using only scaling protocols without using "aio" for asynchronous operations. I think one of the major reasons for such decision making is about execution mechanism. I think it would be a game changer if execution mechanism of "NNG" could be configurable and make it possible to integrate an execution mechanism of choice.

I know "NNG" is a journey and still in progress. But key decision makings and priorities could put it in front of queue as users have a basket with limited resources and different utility functions.

Thank you for all your efforts and contribution.
Omid

**Comment by gdamore** [comment]
Most of the questions about mapping peers to each other is a protocol-specific detail handled by the upper layer Scalability Protocols.  Each protocol has it's own way of doing this, but underpinning them all is the notion of "pipe IDs".

As far as aio, it is indeed quite general purpose now, and it is used for implementing the web server and client, TLS, SP protocols, and even (in another project) MQTT.

I'm not sure what kinds of additional extensibility you're asking for.  It would be good to have something more concrete in terms of a feature request.
