### ISSUE TITLE
NNG Port to Other Languages

### ISSUE THREAD

**Issue by chip5441** [nanomsg/nng#1633]
Hello there:

I do not want to criticize other people efforts and contributions to community but just asking to be responsible for what they are doing or willing to do.

Porting a piece of art, i.e. NNG, to another language is not just about wrapping all the code in target language such as C++. But, it is about efficiency, ellegancy, techniques and based on standard.

We are living in a world full of products which are the outcome of repackaging. A marketing beast which is wasting resources for nothing.

I think, originators should pay more attention to porters and the quality of such ports. As it has a direct impact on originator.

Thank you for all efforts and contribution.
Omid

**Comment by gdamore** [comment]
I am not sure what this ticket is about - it doesn't seem to be asking for anything nor identifying any specific problem in the code or the repo.

**Comment by gdamore** [comment]
Closing this, since it there is nothing actionable here.

**Comment by JaylinYu** [comment]
LOL someone is complaining about other language bindings of NNG.
