### ISSUE TITLE
Can NNG be used for LAN service discovery?

### ISSUE THREAD

**Issue by gatopeich** [nanomsg/nng#1645]
I am trying to connect Surveyor and Respondent via UDP multicast without success.

Is there a way to do it, or another way to implement discovery with NNG?

**Comment by gdamore** [comment]
NNG doesn't have SP protocol support for UDP.  Hence no multicast. You can use mDNS or something like that with NNG for your discovery needs.

**Comment by gdamore** [comment]
The recommended way to do service discovery is to use DNS (or mDNS) and use a single proxy server (running NNG using an nng_device() instance) that both clients and servers can connect to.  This becomes a kind of rendezvous server.

It's not precisely what you're asking for, but it's what we recommend.

**Comment by gatopeich** [comment]
Thanks. Typical mDNS/zeroconf install on Ubuntu brings a relatively complex set of services which are overkill for my use case.
I am sticking to plain simple multicast announcements every few seconds
