### ISSUE TITLE
Still cannot subscribe to topic. Continued from #706  (which is CLOSED)

### ISSUE THREAD

**Issue by nicwainwright** [nanomsg/nng#1656]
Why a new issue?
I tried commenting on a closed issue [#706] a few weeks back, but wasn't sure if updates on a CLOSED issue were getting sent... Lemme know if I should revert back to there

EDITTED: FURTHER TEXT DELETED AS RESOLVED in [#706] follow-up

**Comment by gdamore** [comment]
I am closing this as I think this is resolved.  If not, let me know and I'll be happy to try to help.
