### ISSUE TITLE
Unable to connect to a pair0 wss:// listener: fatal alert message (msg 46)

### ISSUE THREAD

**Issue by jritts** [nanomsg/nng#1660]
I'm trying to implement a simple test of a browser tab connecting to a NNG listener over websockets with TLS enabled.  
The server accepts the connection, but then NNG's call to mbedtls_ssl_handshake fails with -0x7780.

I've attached the server code (nngserver.cpp), along with the verbose log from NNG and mbedtls.

The same client succeeds when connecting to a nodejs websocket server configured to use the same certificate/key pair files.  I've attached that test code too.

If I instead bind the NNG listener to the same URL but with "ws://", disabling TLS, then the connection succeeds and I can send messages from browser to server.

Environment:
- I'm on tip NNG repo: SHA c5e9d8acfc226418dedcf2e34a617bffae043ff6.
- I built and installed mbedtls tag v3.4.0.
- Both were built as shared libraries.
- Windows 10 Pro

I'd be very grateful for any suggestions!  Thanks in advance for your time.

[log.txt](https://github.com/nanomsg/nng/files/11429215/log.txt)
[nngserver.cpp.txt](https://github.com/nanomsg/nng/files/11429218/nngserver.cpp.txt)
[ssl.js.txt](https://github.com/nanomsg/nng/files/11429249/ssl.js.txt)

**Comment by jritts** [comment]
I'm using Chrome: Version 113.0.5672.93 (Official Build) (64-bit)

In chrome://flags/, I enabled the setting "Allow invalid certificates for resources loaded from localhost."

**Comment by shikokuchuo** [comment]
When you built `mbedtls`, were the following lines in the source file ‘include/mbedtls/mbedtls_config.h’ commented out?

1. #define MBEDTLS_SSL_DTLS_CONNECTION_ID
2. #define MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT 0.

If not, you may want to try that to see if it solves your problem. `libmbedtls` >=3.3.0 defines a new default that I have found problematic, and is an issue that @gdamore is aware of.
