### ISSUE TITLE
Bug introduced since build 8e1836f

### ISSUE THREAD

**Issue by shikokuchuo** [nanomsg/nng#1662]
**Describe the bug**

I have a user program using NNG SP req/rep. Consists of a long running req node which constantly ingests data, and sends it periodically to a short-lived single-purpose rep node that writes this data to disk and sends back a completion message - it is a new process that does this each time. Before the data is sent each time, the main node checks for completion of the previous write.

However I find after a couple of days one of these short-lived processes remains running even though the main process carries on.

I have tested using the same user program and verified that builds 539e559 (31 Dec) and 8e1836f (8 Feb) produce good behaviour.

That means a bug was possibly introduced as one of the latest set of commits since then. 

** Environment Details **
 - NNG 1.6.0 [c5e9d8a](https://github.com/nanomsg/nng/commit/c5e9d8acfc226418dedcf2e34a617bffae043ff6)
 - Ubuntu 22.04.02
 - GCC 11.3.0
 - Static lib

**Comment by shikokuchuo** [comment]
I am re-resting this with the latest NNG build and an updated version of my code. The characterisation above was unfortunately incorrect - it was the long-running task that sometimes did not exit (this is also re-spawned periodically).

If I had to guess, it would be a deadlock upon closing a websocket stream. But this is possibly my error and not the library. Hope to report back shortly.

**Comment by shikokuchuo** [comment]
It seems to be resolved. FYI I think the issue was a deadlock on stream dialer close on a 'wss' stream, as I was not building libmbedtls with pthread support (needs to be enabled in 'mbedtls_config.h').

There is nothing gating from my side now for an NNG 1.6.0 release. Thanks, and apologies for raising a false concern!

**Comment by alawn-wang** [comment]
> It seems to be resolved. FYI I think the issue was a deadlock on stream dialer close on a 'wss' stream, as I was not building libmbedtls with pthread support (needs to be enabled in 'mbedtls_config.h').
> 
> There is nothing gating from my side now for an NNG 1.6.0 release. Thanks, and apologies for raising a false concern!

Hi, i want to build a websocket server use NNG, but there seems just a little information about this, no matter in docs or codes.
The problem which most confused me is that if just use simple rep/req mode how can i create a new websocket server? If i use http api, this seems will totally become a http server, just like nng/demo/rest?
Could you please tell me how you solved this problem?

**Comment by shikokuchuo** [comment]
In that particular case, I was in fact using SP over WebSocket i.e. req/rep. If that's all you mean, then just specify a URL with the scheme 'ws://' instread of 'tcp://' in your listen / dial.

If you want to create an actual WebSocket server (speaking to a non-NNG client), then you need the low-level stream interface, and look into setting options for 'ws:recv-text' and 'ws:send-text' if you need to deal with text rather than binary frames.

I maintain the R language binding and there is quite extensive documentation there (https://shikokuchuo.net/nanonext/), which may help provide some intuitive grounding.

**Comment by alawn-wang** [comment]
> In that particular case, I was in fact using SP over WebSocket i.e. req/rep. If that's all you mean, then just specify a URL with the scheme 'ws://' instread of 'tcp://' in your listen / dial.
> 
> If you want to create an actual WebSocket server (speaking to a non-NNG client), then you need the low-level stream interface, and look into setting options for 'ws:recv-text' and 'ws:send-text' if you need to deal with text rather than binary frames.
> 
> I maintain the R language binding and there is quite extensive documentation there (https://shikokuchuo.net/nanonext/), which may help provide some intuitive grounding.

Thanks for your reply. 
It's unforunately that may be i need create a real WebSocket Server. Because it should need received multi-clients connections and transport information with them, although client&server communication by NNG.
