### ISSUE TITLE
TLS cannot establish more than one connection at the same time

### ISSUE THREAD

**Issue by AnasASK** [nanomsg/nng#1666]
**Describe the bug**
Launching multiple clients (pair1 dialer) at the same time to connect to a server (pair1_open_poly listener) with tls+tcp doesnt work. Using tcp alone works.

note that the issue is not specific to the pair protocol, all protocols have the same issue.
note that this issue has been reported in a reply to #1661  . I think it deserves its own issue report.

**Expected behavior**
All dialers should be able to start.

**Actual Behavior**
only one dialer starts, the rest get a connection shutdown error

**To Reproduce**
Quoting from a reply on issue #1661 :
> Here's a self-contained test for vs2022, with the output of one run on my machine. I highlighted the case where dialing a tls+tcp listener from multiple REQ sockets on different threads failed. Most of the time, all 4 dials fail, but sometimes one works.
> 
> The prebuilt libs are the version you mentioned - NNG [8e1836f](https://github.com/nanomsg/nng/commit/8e1836f57e8bcdb228dd5baadc71dfbf30b544e0), mbed 981743d.
> 
> While running this test repeatedly, I also saw a crash in an NNG thread, but it's difficult to reproduce. Will try a bit more.
> 
> ![multiple_tls_dialer_fail](https://user-images.githubusercontent.com/3199673/240078641-2693266d-5b51-455f-af89-443f1957c7a4.png) [NNGReqRepTest.zip](https://github.com/nanomsg/nng/files/11537905/NNGReqRepTest.zip)

** Environment Details **
 - NNG version: I have tested with 1.5.2 and master branch
 - mbedtls version: I have tested with 3.0, 3.1, and 3.3
 - Operating system and version: Ubuntu:22.04
 - Compiler and language used: gcc, tested with c and c++
 - Shared or static library: static

**Additional context**
Compiling with address sanitizer doesn't show any issues.

**Comment by gdamore** [comment]
I just tested your code on Ubuntu 20 on ARM (that's all I have handy at the moment) with mbed 2.6, and it works.  I did have to change your test code to eliminate Windows-isms.

```
parallels@ubuntu-linux-20-04-desktop:/tmp$ ./test
NNG version: 1.6.0pre
mbedTLS version: 2.16.3

- Testing tcp://127.0.0.1:4000 with 1 dialer socket(s)
-- Spawning listener thread
-- Spawning 1 dialer thread(s)
-- Dialing...
-- Dialing SUCCEEDED
-- Joining
- Done

- Testing tcp://127.0.0.1:4000 with 4 dialer socket(s)
-- Spawning listener thread
-- Spawning 4 dialer thread(s)
-- Dialing...
-- Dialing...
-- Dialing...
-- Dialing...
-- Dialing SUCCEEDED
-- Dialing SUCCEEDED
-- Dialing SUCCEEDED
-- Dialing SUCCEEDED
-- Joining
- Done

- Testing tls+tcp://127.0.0.1:4000 with 1 dialer socket(s)
-- Spawning listener thread
-- Spawning 1 dialer thread(s)
-- Dialing...
-- Dialing SUCCEEDED
-- Joining
- Done

- Testing tls+tcp://127.0.0.1:4000 with 4 dialer socket(s)
-- Spawning listener thread
-- Spawning 4 dialer thread(s)
-- Dialing...
-- Dialing...
-- Dialing...
-- Dialing...
-- Dialing SUCCEEDED
-- Dialing SUCCEEDED
-- Dialing SUCCEEDED
-- Dialing SUCCEEDED
-- Joining
- Done
```

**Comment by gdamore** [comment]
I'm going to try upgrading.

**Comment by gdamore** [comment]
The mbed TLS I have is version 2.16 because that's what APT install installed.

**Comment by gdamore** [comment]
I will have to look at this post 1.6.0 -- I'm not going to hold the release for this.

**Comment by gdamore** [comment]
I'm continuing to hear reports of problems with TLS on windows using mbedTLS 3.x.  Please try mbedTLS 2.28.

See also #1668

**Comment by gdamore** [comment]
I'd like folks to try again with 1.7.0.  There were some fixes in 1.6.0 that I think *may* have helped here.  In particular I think we were spinning on accept, which may have caused some starvation in mbedTLS.

**Comment by AnasASK** [comment]
I will give it a test during the weekend

**Comment by gdamore** [comment]
Any update?

**Comment by AnasASK** [comment]
Sorry for the (very) late reply, I had tested nng v1.7.1 with mbedtls v3.5.1 but I encountered the same issue. I had planned to try older mbedtls versions and give more debugging information but still didn't get around doing it yet.

**Comment by gdamore** [comment]
I'm closing this as "stale".  If folks find otherwise, please reopen with details.
