### ISSUE TITLE
errno EAGAIN when use nng_send

### ISSUE THREAD

**Issue by wsxjbupt** [nanomsg/nng#1667]
1. NNG & Platform details.
nng-1.5.2, Ubuntu x86_64

2.Expected Behavior
I expect to send and receive messages normally.

3.Actual Behavior
After running for a period of time, the sending thread fails to invoke nng_send. The value of errno is EAGAIN.

4.Other Details
- nng_send flag with NNG_FLAG_NONBLOCK | NNG_FLAG_ALLOC.
- Use nng_socket_set to set the recv buffer size of sockets on both the server and client, set value is 0.

Can you give some effective advice?

**Comment by gdamore** [comment]
If you're using NNG_FLAG_NONBLOCK, then when you send more data than the receiver can receive, it will fail with exactly this EAGAIN -- that's your signal to reduce your send rate or increase the receive rate on the receiver.

If you're not equipped for EAGAIN handling, I don't recommend using NNG_FLAG_NONBLOCK.  Either use blocking I/O (which won't actually block unless it has to), or better use the asynchronous I/O operations, which will actually be faster and more scalable to boot.

**Comment by gdamore** [comment]
This is behaving as expected, so I'm closing it.
