### ISSUE TITLE
Issue with POST Request Header and Payload Being Segmented into Two Frames

### ISSUE THREAD

**Issue by linaki-o** [nanomsg/nng#1670]
Problem Description:
When using the nanomsg library to send a POST request, the header and payload of the request are segmented into two frames instead of being sent as a single packet. According to the HTTP/1.1 protocol specification, a POST request should be sent as a complete entity, without being split into multiple frames.
Is this a feature of nanomsg?
I appreciate your assistance in resolving this issue. Thank you!
![image](https://github.com/nanomsg/nng/assets/78514733/6ec43dd4-ba3b-48ab-a786-c07e23df4532)

**Comment by JaylinYu** [comment]
This is how TCP works bro....

**Comment by linaki-o** [comment]
no. it divide into 2 frame before it meet the MSS.
but that doesn't matter i already solve my problem. not nng's failure.
