### ISSUE TITLE
undefined behavior in posix ipc_dialer_dial

### ISSUE THREAD

**Issue by JoshSalitSonos** [nanomsg/nng#1675]
**Describe the bug**
In the `ipc_dialer_dial` implementation in `src/platform/posix/posix_ipcdial.c`, if `nni_posix_pfd_init` fails then `goto error` is executed, and `nni_mtx_unlock(&d->mtx)` is called without the mutex having been locked. this passes through to a `pthread_mutex_unlock` call, which is documented as having undefined behavior if the mutex is not locked.

https://github.com/nanomsg/nng/blob/c5e9d8acfc226418dedcf2e34a617bffae043ff6/src/platform/posix/posix_ipcdial.c#L190-L191

It looks like this was introduced by PR #1111.

**To Reproduce**
This was found via code inspection.

** Environment Details **
 - NNG version - commit c5e9d8acfc226418dedcf2e34a617bffae043ff6
 - linux (various kernels)

**Comment by gdamore** [comment]
The TCP code path suffers the same flaw.

**Comment by gdamore** [comment]
One note for anyone looking at this -- short of running of out RAM, it's exceedingly unlikely that you've observed this particular bug.  The failure path here should really not be one we expect to see executed.
