### ISSUE TITLE
How to obseve nng threads on windows

### ISSUE THREAD

**Issue by xinxinxiangying258** [nanomsg/nng#1680]
While using nng inside a project, I am confusing about how to obseve nng threads on windows.
Like the issue #1572 said, nng threads have different types.
But I cannot find any thread named like the elements of #1572 table no matter using Process Explorer or Powershell.

Is there any body could tell me how to obseve nng threads on windows? thx.❤

**Comment by gedalia** [comment]
A profiling tool like Tracy https://github.com/wolfpld/tracy can help visualize the thread usage (which is pretty bad and actually can break Tracy on a high core machine) there are others like superluminal https://superluminal.eu/ and optick https://github.com/bombomby/optick
I'm really hoping that there is a release with this fix soon, it makes nng really problematic to use in a whole class of applications.

**Comment by phsilva** [comment]
I can't confirm, but apparently, Windows only shows thread names in certain places, like debuggers.

From[1], it says that you can inspect thread names in WinDbg or Windows Performance Analyzer [2], for instance.

A recent open question in some MS forums [3] indicates that this is really not present in Process Explorer, as I would expect.

[1] https://learn.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2022
[2] https://learn.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer
[3] https://learn.microsoft.com/en-us/answers/questions/1341178/feature-request-show-thread-name-in-process-explor

This also answers your question in #1572 I think.

**Comment by gdamore** [comment]
This is a question, and I'm not sure what the best answer is, as I'm not really a Windows guy.  But as it's not related specifically to the code of NNG, I'm closing it.  I hope the answers @phsilva provided were useful.
