### ISSUE TITLE
setting the sub receive socket with nng_socket_set_ms will generates a segment fault

### ISSUE THREAD

**Issue by halikuosang** [nanomsg/nng#1682]
**Describe the bug**
Open a process to send data using “pub”, and two processes to receive data using “sub”. Use “nng_socket_set_ms” to set the timeout for the receiving socket of the “sub” process. After running for a period of time (a few hours), the “sub” process will generate a segmentation fault, while it will not generate a segmentation fault if the timeout is not set.

**Expected behavior**
Both “sub” processes can continuously receive data without generating a segmentation fault.

**Actual Behavior**
Both “sub” processes will generate a segmentation fault.

**To Reproduce**
See this modified demo:
[pubsub.zip](https://github.com/nanomsg/nng/files/12416752/pubsub.zip)
 - ./pilot_pub
 - ./pilot_sub
 - ./pilot_sub

** Environment Details **
 - NNG version 1.5.2 
 - Allwinner T507(Quad A53)
 - aarch64-linux-gnu-gcc(gcc version 7.4.1 20181213)  and C
 - Shared library(libnng.so.1.5.2)

**Additional context**
Open “ulimit -c unlimited” and modify “/proc/sys/kernel/core_pattern” (“/root/nng/core-%e-%p”) to generate core dump files. Use “aarch64-linux-gnu-gdb” for debugging and see that there is an issue with the “nng:task/nng:aio:expire” function calling “nni_list_remove”. “nng:task/nng:aio:expire” is the problem encountered by the two “sub” processes respectively.

**Comment by gdamore** [comment]
Can you try this on the latest main?  There are changes that have been made there that might make a difference.

**Comment by halikuosang** [comment]
Yes, I have tested using the code from the master branch and recompiled the dynamic library. However, when using the same test code, I am still Yes, I have tested using the code from the master branch and recompiled the dynamic library. However, when using the same test code, I am still experiencing intermittent segmentation faults. segmentation faults.

**Comment by halikuosang** [comment]
Yes, I have tested using the code from the master branch and recompiled the dynamic library(libnng.so.1.6.0-pre). However, when using the same test code, I am still Yes, I have tested using the code from the master branch and recompiled the dynamic library. However, when using the same test code, I am still experiencing intermittent segmentation faults. segmentation faults.

I have conducted another test by running the same program on a PC with an x86-64 architecture, and I also encountered a segmentation fault with the x86-64 dynamic library(libnng.so.1.6.0-pre)

**Comment by halikuosang** [comment]
Yes, I have tested using the code from the master branch and recompiled the dynamic library(libnng.so.1.6.0-pre). However, when using the same test code, I am still experiencing intermittent segmentation faults.
I have conducted another test by running the same  test code on a PC with an x86-64 architecture, and I also encountered a segmentation fault with the x86-64 dynamic library(libnng.so.1.6.0-pre)

**Comment by halikuosang** [comment]
> I have reproduced this issue，and I think #1695 will fix it.

Yes, I have added the modifications from #1695 in the latest version, and it is working now without any segmentation faults. Thank you。
