### ISSUE TITLE
Generated HTML documentation title tags are empty

### ISSUE THREAD

**Issue by zegelin** [nanomsg/nng#1687]
**Describe the bug**
The `<title>` tags are empty in the generated HTML documentation/man pages.

For example: https://nng.nanomsg.org/man/v1.3.2/nng_aio_set_output.3.html

The result is that the window/tab title in most browsers reverts to the full (or partial) URL of the page, which makes it very difficult browse the docs and to locate specific man pages if multiple of them are open at once.

Here are some screen shots of Chrome, Firefox, and Firefox with the Sidebery extension:

![Chrome](https://github.com/nanomsg/nng/assets/19296634/da1cc9e0-e8a1-4cdd-8b5c-54e935911f6a)

![Firefox](https://github.com/nanomsg/nng/assets/19296634/6ea17d73-a19e-48d4-8b2e-f143c018dae5)

![Firefox + Sidebery](https://github.com/nanomsg/nng/assets/19296634/7f796fb0-c90c-4f49-9594-99f7caf6702b)

**Expected behavior**
Please include the man page title, such as `nng_aio_abort(3)`, in the `<title>` tag of the generated documentation.

This will correctly set the window/tab title in the browser and make it much easier to browse the docs.

**Actual Behavior**
No title is included. On all pages the title tag is empty: `<title></title>`. The browser defaults to displaying the URL of the page.

**Comment by gdamore** [comment]
This should be fixed now. Thanks for reporting it.
