### ISSUE TITLE
Test cases don't work with TCP endpoints with localhost host name

### ISSUE THREAD

**Issue by zboszor** [nanomsg/nng#1688]
**Describe the bug**

The documentation uses `ipc://` URL as examples but the URL is accepted from the command line.

When changing the execution to use `tcp://` endpoints, the examples don't work:
```
./reqrep node0 tcp://*:6799 & node0=$! && sleep 1
./reqrep node1 tcp://localhost:6799
kill $node0
```

**Expected behavior**

The  tcp:// endpoint should work with the native and compat APIs.

**Actual Behavior**
The result is:
- node0 listens on port 6799
- node1 exits with `nng_dial: Connection refused`

When changing the `nng_dial()` line to use NNG_FLAG_NONBLOCK, the `./reqrep node1 ...` command is stuck in `nng_send()`.

Same effect with the nanomsg reqrep.c example if linked with `-lnng`, i.e. using the nanomsg compat API, the client side is stuck in `nn_send()`.

The nanomsg example linked with `-lnanomsg` works properly with the tcp:// endpoint.

**To Reproduce**
The test case is the stock reqrep examples from https://nanomsg.org/gettingstarted/nng/reqrep.html and https://nanomsg.org/gettingstarted/reqrep.html

** Environment Details **
 - NNG version: nng-1.4.0-5.fc38.x86_64
 - OS: Fedora 38
 - Compiler: gcc version 13.2.1 20230728 (Red Hat 13.2.1-1) (GCC)
 - Shared library of nng

**Additional context**

**Comment by zboszor** [comment]
Same thing happens with rebuilding [1.5.2-2.fc39](https://koji.fedoraproject.org/koji/buildinfo?buildID=2245135) on Fedora 38 using the previously indicated GCC version.

**Comment by zboszor** [comment]
The test case is successful when directly connecting to 127.0.0.1:port instead of localhost:port.

**Comment by gdamore** [comment]
It doesn't explicitly prefer I think. But it should depend on your resolver. 

There is a way to force ipv4 if we need to using tcp4://

**Comment by gdamore** [comment]
The actual documented examples (using ipc) are fine, so there's really no further action required here.
