### ISSUE TITLE
Is there a release plan for the new version?

### ISSUE THREAD

**Issue by liutttttttt** [nanomsg/nng#1691]
Version 1.5.2 has been released for more than two years. Is there any plan to release a new version of Nng?

**Comment by gdamore** [comment]
The issue is that I need to find time to resolve the outstanding bugs.  Unfortunately I have been really busy. But hopefully soon.

**Comment by gdamore** [comment]
Specifically we need to fix this bug https://github.com/nanomsg/nng/issues/1523

**Comment by gdamore** [comment]
Today #1523 got fixed, so I'll probably cut a release in the next day or so.  I think there are some other cases that are identical to that bug so I'd like to fix them too, first.
