### ISSUE TITLE
Request for HTTP Client and Server Demo

### ISSUE THREAD

**Issue by MuNianCi** [nanomsg/nng#1696]
Hello everyone,

I'm currently working on a project involving NNG-HTTP communication. I'm trying to understand how to create an HTTP client that sends a GET request, and an HTTP server that responds with a string.

I was wondering if anyone could provide a simple demo of an NNG-HTTP client and server that fits this description. This would be really helpful for my project.

Any help would be greatly appreciated. Thank you in advance!

Best regards,

**Comment by alawn-wang** [comment]
In  demo/rest directory at 'root' dir supply a http-server which receive 'POST' request.  And demo/http-client may be useful to create a http client.
