### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by Bajix** [nanomsg/nng#1697]
It's been an extended duration since the last release. I think it would be good to cut a release soon because then that would encourage [nng-sys](https://crates.io/crates/nng-sys) to integrate and release as well.

**Comment by gdamore** [comment]
I'm close to a release.  Finally got some time to spend on this today and have squashed a few bugs. :-)

**Comment by Bajix** [comment]
Awesome! This is a really fantastic project you've done great work

**Comment by gdamore** [comment]
1.6.0 is now released.

**Comment by Bajix** [comment]
Amazing! Appreciate your efforts
