### ISSUE TITLE
Demand for dynamic size event queue

### ISSUE THREAD

**Issue by AdamNusser** [nanomsg/nng#1699]
**Is your feature request related to a problem? Please describe.**
When the event queue receives a large amount of events, a lot of those events are lost.

**Describe the solution you'd like**
We would like a configurable queue size, instead of the 16 built in size. If 0 is given as size it's size should be dynamic.

**Describe alternatives you've considered**
lmq has a resize function that can be used to implement the dynamic functionality. Size can be set from cmake.

**Comment by gdamore** [comment]
There is a runtime configuration that can be set for this, `NNG_OPT_SENDBUF` 

That should be used instead.

I've rejected the PR that made this automatically growing, and I'm not going to do that.  Please just use the runtime configuration and size the queue large enough to accommodate your largest expected burst.
