### ISSUE TITLE
compat: nn_reallocmsg is incorrect

### ISSUE THREAD

**Issue by Snarpix** [nanomsg/nng#1701]
https://github.com/nanomsg/nng/blob/a54820ff0e1b74554c7f649e8386ee8c4ecd98f5/src/compat/nanomsg/nn.c#L366-L379

In this code nng_msg_realloc copies message without trimmed nng_msg* in the beginning.
Then we overwrite first 8 message bytes with nng_msg*, and trim them, so on realloc we are actually removing first 8 bytes of message.

**Comment by gdamore** [comment]
Upon reading, I agree.  There is no test for this code, and I don't use it.  I should fix this, and a test case for it.
