### ISSUE TITLE
Crashed by SIGABRT

### ISSUE THREAD

**Issue by oronge** [nanomsg/nng#1707]
the process crashed by signal SIGABRT when receive data use nn_recv, the flags param is 0

the socket is created by nn_socket(AF_SP, NN_REP)
NN_RCVTIMEO is set to -1 by nn_setsockopt
the size of data should receive is about 34KB

if the data should receive is small, the process will not crash

Version : nanomsg-1.1.5
OS : CentOS Linux release 7.9.2009 (Core)
Language  C++   g++
shared library

what's the reason of the problem,  thank you very much!

**Comment by gdamore** [comment]
This is against the wrong project -- you're using legacy nanomsg so please use that project -- github.com/nanomsg/nanomsg - for reporting bugs.

Having said that, more information is required to understand the SIGABRT -- there should have been a message emitted on stderr or something like that -- and ideally I'd like a stack backtrace.

**Comment by gdamore** [comment]
I'm closing this for now .. there isn't enough data to debug this, and it's filed against the wrong repo.  Please supply more information (see above), and file against the nanomsg repository.
