### ISSUE TITLE
websocket transport use nng_stream will cause crashed

### ISSUE THREAD

**Issue by alawn-wang** [nanomsg/nng#1708]
**Describe the bug**
when use 'nng_stream_send' send data when do pressure test(send data frequently), it will crashed.
I use another repo('https://github.com/robiwano/siesta') to create a websocket server and communicate with client.  In 'siesta' examples/web_socket_client.cpp and web_socket_server.cpp. 

**Expected behavior**
It will continious receive and send data.

**Actual Behavior**
There is a nni_panic 'panic: appending node already on a list or not inited'

**To Reproduce**
https://github.com/robiwano/siesta/blob/master/examples/web_socket_client.cpp
https://github.com/robiwano/siesta/blob/master/examples/web_socket_server.cpp

** Environment Details **
 - nng: 1.5.2, the latest master branch.
 - OS: windows 11
 - vs 2022
 - static lib

**Comment by gdamore** [comment]
Well, I am not sure about the siesta code.. it appears to use NNG, but I really would not like to debug that project. 

When that panic comes about, it usually means someone is trying to submit a second operation on an AIO.

Otherwise I'd need more detail (in the form a stack backtrace perhaps) to say more.

**Comment by gdamore** [comment]
What I would suggest is file the bug against siesta, and then if the author there has evidence that there is an NNG bug here, they can contact me with specifics (including why they believe that and a bit more detail).

**Comment by alawn-wang** [comment]
> Well, I am not sure about the siesta code.. it appears to use NNG, but I really would not like to debug that project.
> 
> When that panic comes about, it usually means someone is trying to submit a second operation on an AIO.
> 
> Otherwise I'd need more detail (in the form a stack backtrace perhaps) to say more.

THX for your reply and suggustion of bugging. I'am try to do it. I will close this issue before I  find more details

**Comment by alawn-wang** [comment]
> What I would suggest is file the bug against siesta, and then if the author there has evidence that there is an NNG bug here, they can contact me with specifics (including why they believe that and a bit more detail).

BTW， I want to know if there is anyway to solve this problem?
