### ISSUE TITLE
nng_aio_stop.3 refers to `nng_aio_schedule()` instead of `nng_aio_begin()`

### ISSUE THREAD

**Issue by paddor** [nanomsg/nng#1754]
The two links to `nng_aio_schedule()` on [1] are broken. Maybe it should instead refer to `nng_aio_begin()`?

[1] https://nng.nanomsg.org/man/tip/nng_aio_stop.3.html

**Comment by gdamore** [comment]
Yes, this is wrong.  I've got a fix on the way -- the language also needs minor tweaks.
