### ISSUE TITLE
Reduce number of FDs

### ISSUE THREAD

**Issue by paddor** [nanomsg/nng#1758]
I've managed to integrate NNG into Ruby's new Fiber Scheduler (transparent Async programming on top of Fibers [1]) by using the FDs to wait for readability/writability before each recv/send. When I tried to test scalability, I could barely reach 250 sockets with a `ulimit -n` = 1024. I'm assuming NNG creates 4 FDs per socket (read pipe, write pipe, `OPT_RECV_FD`, and `OPT_SEND_FD`).

Would it reduce the number of FDs created if I used nng_aio instead? If not, is there a way this feature could be controlled for apps that definitely don't need the additional `OPT_RECV_FD` and `OPT_SEND_FD` FDs? I'm assuming they're not used internally.

Since the Ruby Fiber Scheduler also supports blocking/unblocking Fibers manually [2], I think this would play well with nng_aio. That way I wouldn't need the `OPT_RECV_FD`, and `OPT_SEND_FD` FDs.

[1] https://brunosutic.com/blog/ruby-fiber-scheduler
[2] https://github.com/ruby/ruby/blob/master/include/ruby/fiber/scheduler.h#L187-L207

**Comment by gdamore** [comment]
Yes. If you can you aio you will eliminate the extra FDs.  You will also see a performance benefit by having fewer system calls.

**Comment by paddor** [comment]
Thanks. I'll try that.
