### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by advatar** [nanomsg/nng#1769]
**Describe the bug**
Receive this message:

panic: ../externals/nng/src/core/aio.c: 330: assert err: !nni_aio_list_active(aio)
This message is indicative of a BUG.
Report this at https://github.com/nanomsg/nng/issues

**Expected behavior**
no bug

**Actual Behavior**
as above

**To Reproduce**
Hard to arrange

** Environment Details **
 - NNG version
 https://github.com/nanomsg/nng/tree/169221da8d53b2ca4fda76f894bee8505887a7c6
 - Operating system and version
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
 - Compiler and language used
 gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) 
 - Shared or static library
 Static?

**Additional context**

**Comment by rednaxela5950** [comment]
It seems like I am to blame?

```
// If any of these triggers then the caller has a defect because
	// it means that the aio is already in use.  This is always
	// a bug in the caller.  These checks are not technically thread
	// safe in the event that they are false.  Users of race detectors
	// checks may wish ignore or suppress these checks.
	nni_aio_expire_q *eq = aio->a_expire_q;

	aio_safe_lock(&eq->eq_mtx);

	NNI_ASSERT(!nni_aio_list_active(aio));
```

**Comment by rednaxela5950** [comment]
Also this

`panic: ../externals/nng/src/core/aio.c: 670: assert err: aio->a_nio != 0`

**Comment by gdamore** [comment]
This is almost certainly a bug in the application code as you infer.  You must not have more than a single operation in flight on an aio at any given time.

**Comment by gdamore** [comment]
Yes.

**Comment by gdamore** [comment]
I'm going to close this.  If you feel that the bug is *not* in your application, you may reopen this, but please provide an explanation for why that is so, and ideally also some code reproducing the problem.
