### ISSUE TITLE
If I understand correctly, NNG's REP is analog to ROUTER when in raw mode or using a context object for asynchronous operations.  REQ is similarly analog to DEALER when in raw mode or using a context object.  So these socket types are unnecessary...  I presume that the same reasoning applies to the lack of XPUB/XSUB in NNG.

### ISSUE THREAD

**Issue by mohit-kumawatt** [nanomsg/nng#1789]
i want to replace zmq by nng  in my project and in which there are more than one number of dealers where i want to send the message. Can it be possible to replace zmq. and if it is possible then please provide the document of nng raw mode.

**Comment by gdamore** [comment]
I've moved the answer to this to the Q&A discussion group.   And your understanding about XPUB/XSUB is correct.  IN the case of PUB/SUB there really is no difference between raw and cooked mode, except that raw mode does not filter messages at all.  For REQ/REP and SURVEYOR/RESPONDENT the details are documented in the manuals.
