### ISSUE TITLE
DNS resolution should be done at connect time

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#179]
Right now names are resolved synchronously during endpoint initialization.  We move this to an asynchronous step performed during connect.  This will allow for better DNS-based recovery, and better DNS based load balancing.

**Comment by Ek0n** [comment]
Hi, I was going through the open issues and this seems like a good one to start getting to the code base, what do you think?
Does the `help_wanted` tag apply to this issue?

**Comment by gdamore** [comment]
You’re welcome to try, but I think this is kind of “tricky”, since it means
you need to add some additional asynchronous behaviors.  Having said that,
if you’re feeling confident, go for it!

**Comment by Ek0n** [comment]
You're the main author, you know the project through and through, so I believe you. I'll go through the `help_wanted` and see which makes more sense to me.

Thank you for your (very) honest reply.

**Comment by gdamore** [comment]
Fixed in b44e20c80c936a29bfeaf964ec94bc62ac0386f5
