### ISSUE TITLE
Your text about Russia/Ukraine (typo)

### ISSUE THREAD

**Issue by lopippo** [nanomsg/nng#1795]
Greetings, Garrett,

I read your text about the war by Russians in Ukraine. I liked its tone and its contents. My grandfather was Ukrainian from Kharkhov, and while he used to speak Russian---he used to pronounce Kharkhov and not Kharkhiv---, he certainly would not have been pro-Putin!

Bug report :-)

 In the meantime, the worst prices will be paid for by innocents in Ukraine, and by young Russian mean forced to carry out the orders of Putin’s corrupt regime.

s/mean/men/

Sincerely,
Filippo

**Comment by gdamore** [comment]
I've fixed this, and added some additional text.  Thanks for pointing it out.
