### ISSUE TITLE
Tools or API could obtain all communication endpoint information for establishing communication with this machine

### ISSUE THREAD

**Issue by louislau86** [nanomsg/nng#1840]
As a center node for communication with NNG，we need to monitor the connection status of these connections and show the information of these communication endpoints in a visual way, so, the feature in the title is important for me. The yarpmanager in YARP framework is a good example.

**Comment by gdamore** [comment]
This is something that someone could implement on top NNG.  I have long had plans to utilize NNG stats to build this and make it available as a commercial offering, I just haven't had enough time to do it.  It's not something I'm likely to do and give away for free, unless someone pays me to do so.

**Comment by louislau86** [comment]
OK，I got it.  Thanks for your honest response.
