### ISSUE TITLE
How to build nng_testing as a dynamic library?

### ISSUE THREAD

**Issue by MuNianCi** [nanomsg/nng#1843]
When I was building the dynamic library for the protocol, I encountered some errors. I modified line 90 of the CMakeLists.txt file. The modified content snippet is as follows, but I got errors during the compilation. The error message is as follows. Please advise on how to compile and generate the dynamic library.
By defining set(BUILD_SHARED_LIBS ON), nng has been compiled and built as a dynamic library.
My Modification(line 76 to line92):
 76 set(BUILD_SHARED_LIBS ON)
 77 if (NOT (BUILD_SHARED_LIBS))
 78     set(NNG_STATIC_LIB ON)
 79     message(STATUS "Building static libs.")
 80 endif ()
...
 89 add_library(nng)
 90 
 91 add_library(nng_testing SHARED EXCLUDE_FROM_ALL)
 92 target_compile_definitions(nng_testing PUBLIC NNG_SHARED_LIB NNG_TEST_LIB NNG_PRIVATE)

ERROR INFO：
`Scanning dependencies of target options
[ 76%] Building C object tests/CMakeFiles/compat_reqrep.dir/compat_testutil.c.o
[ 76%] Building C object tests/CMakeFiles/compat_pair.dir/compat_testutil.c.o
/usr/bin/ld: ../libnng_testing.so: undefined reference to `test_message_color_'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/cplusplus_pair.dir/build.make:85: tests/cplusplus_pair] Error 1
make[1]: *** [CMakeFiles/Makefile2:2523: tests/CMakeFiles/cplusplus_pair.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 76%] Building C object tests/CMakeFiles/options.dir/options.c.o
[ 76%] Linking C executable compat_survey
/usr/bin/ld: ../libnng_testing.so: undefined reference to `test_message_color_'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/compat_reqttl.dir/build.make:100: tests/compat_reqttl] Error 1
make[1]: *** [CMakeFiles/Makefile2:2550: tests/CMakeFiles/compat_reqttl.dir/all] Error 2
[ 77%] Building C object tests/CMakeFiles/options.dir/convey.c.o
[ 77%] Linking C executable compat_pipeline
[ 77%] Linking C executable compat_reqrep
/usr/bin/ld: ../libnng_testing.so: undefined reference to `test_message_color_'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/compat_survey.dir/build.make:100: tests/compat_survey] Error 1
make[1]: *** [CMakeFiles/Makefile2:2577: tests/CMakeFiles/compat_survey.dir/all] Error 2
[ 78%] Linking C executable compat_pair
/usr/bin/ld: ../libnng_testing.so: undefined reference to `test_message_color_'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/compat_pipeline.dir/build.make:100: tests/compat_pipeline] Error 1
make[1]: *** [CMakeFiles/Makefile2:2631: tests/CMakeFiles/compat_pipeline.dir/all] Error 2
/usr/bin/ld: ../libnng_testing.so: undefined reference to `test_message_color_'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/compat_pair.dir/build.make:100: tests/compat_pair] Error 1
make[1]: *** [CMakeFiles/Makefile2:2658: tests/CMakeFiles/compat_pair.dir/all] Error 2
[ 78%] Linking C executable options
/usr/bin/ld: ../libnng_testing.so: undefined reference to `test_message_color_'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/compat_reqrep.dir/build.make:100: tests/compat_reqrep] Error 1
make[1]: *** [CMakeFiles/Makefile2:2604: tests/CMakeFiles/compat_reqrep.dir/all] Error 2
/usr/bin/ld: ../libnng_testing.so: undefined reference to `test_message_color_'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/options.dir/build.make:100: tests/options] Error 1
make[1]: *** [CMakeFiles/Makefile2:2685: tests/CMakeFiles/options.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
`

**Comment by gdamore** [comment]
This library was never meant to be dynamic.  Various things probably won't work if you try to do so -- because we rely on otherwise private symbols being exposed for linking (because we are testing the guts of NNG, not just black box testing.)

I don't understand why you want this to be dynamic.

**Comment by MuNianCi** [comment]
okay thanks ~
