### ISSUE TITLE
Document - Wrong description

### ISSUE THREAD

**Issue by ZoomingTeng** [nanomsg/nng#1851]
**Describe the bug**
In the doc `https://github.com/nanomsg/nng/blob/master/docs/man/nng_sub.7.adoc`, the description of option `NNG_OPT_SUB_UNSUBSCRIBE` is as follow:
> This option, also read-only, removes a topic from the subscription list. Note that if the topic was not previously subscribed to with NNG_OPT_SUB_SUBSCRIBE then an NNG_ENOENT error will result.

**Expected behavior**
I think there should be "write-only" rather than "read-only".
Because the test `const char *opt2 = NNG_OPT_SUB_UNSUBSCRIBE;
NUTS_PASS(nng_socket_set(sub, opt2, "abc", 3));`is passed.

**Comment by gdamore** [comment]
Yes, it should be write-only.  Thanks for reporting it.
