### ISSUE TITLE
Warning on calloc()

### ISSUE THREAD

**Issue by leaveye** [nanomsg/nng#1858]
Compiler warning on [line 278](https://github.com/nanomsg/nng/blob/6e5cf2967bc8717ab712a6cdda9d297d18bdeef0/src/tools/perf/pubdrop.c#L278)

I guess the call of calloc should be:
```c
calloc((size_t) pa.count + 1, sizeof(nng_thread *))
```

as a reference in [manpage of calloc](https://linux.die.net/man/3/calloc):

> The calloc() function allocates memory for an array of nmemb elements of size bytes each and returns a pointer to the allocated memory.

**Comment by gdamore** [comment]
Lol.  I always mix the order of those two things up.  It doesn't really matter since the compiler just does a multiplication. :-)

**Comment by leaveye** [comment]
true, except there is a warning with `-Wall`. lol
