### ISSUE TITLE
I feel that nng has experienced a serious memory leak. Can someone tell me what happened?

### ISSUE THREAD

**Issue by dianjixz** [nanomsg/nng#1865]
==1812896== 
==1812896== HEAP SUMMARY:
==1812896==     in use at exit: 20,507 bytes in 65 blocks
==1812896==   total heap usage: 24,683 allocs, 24,618 frees, 2,586,074 bytes allocated
==1812896== 
==1812896== 1 bytes in 1 blocks are still reachable in loss record 1 of 33
==1812896==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x116009: nni_alloc (posix_alloc.c:20)
==1812896==    by 0x118A4E: nni_strdup (strs.c:34)
==1812896==    by 0x1212FA: url_canonify_uri (url.c:230)
==1812896==    by 0x121801: nni_url_parse (url.c:402)
==1812896==    by 0x12260E: nni_listener_create (listener.c:215)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 1 bytes in 1 blocks are still reachable in loss record 2 of 33
==1812896==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x116009: nni_alloc (posix_alloc.c:20)
==1812896==    by 0x12185C: nni_url_parse (url.c:413)
==1812896==    by 0x12260E: nni_listener_create (listener.c:215)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 4 bytes in 1 blocks are still reachable in loss record 3 of 33
==1812896==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x116009: nni_alloc (posix_alloc.c:20)
==1812896==    by 0x1214FC: nni_url_parse (url.c:324)
==1812896==    by 0x12260E: nni_listener_create (listener.c:215)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 5 bytes in 1 blocks are still reachable in loss record 4 of 33
==1812896==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x116009: nni_alloc (posix_alloc.c:20)
==1812896==    by 0x118A4E: nni_strdup (strs.c:34)
==1812896==    by 0x121B09: nni_url_parse (url.c:488)
==1812896==    by 0x12260E: nni_listener_create (listener.c:215)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 8 bytes in 1 blocks are still reachable in loss record 5 of 33
==1812896==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x116009: nni_alloc (posix_alloc.c:20)
==1812896==    by 0x121A70: nni_url_parse (url.c:470)
==1812896==    by 0x12260E: nni_listener_create (listener.c:215)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 13 bytes in 1 blocks are still reachable in loss record 6 of 33
==1812896==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x116009: nni_alloc (posix_alloc.c:20)
==1812896==    by 0x12176B: nni_url_parse (url.c:390)
==1812896==    by 0x12260E: nni_listener_create (listener.c:215)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 19 bytes in 1 blocks are still reachable in loss record 7 of 33
==1812896==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x116009: nni_alloc (posix_alloc.c:20)
==1812896==    by 0x118A4E: nni_strdup (strs.c:34)
==1812896==    by 0x121464: nni_url_parse (url.c:307)
==1812896==    by 0x12260E: nni_listener_create (listener.c:215)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 64 bytes in 1 blocks are still reachable in loss record 8 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x11E4D8: nni_aio_sys_init (aio.c:852)
==1812896==    by 0x1172B9: nni_init_helper (init.c:38)
==1812896==    by 0x14818B: nni_plat_init (posix_thread.c:422)
==1812896==    by 0x11732E: nni_init (init.c:58)
==1812896==    by 0x11A21E: nni_sock_open (socket.c:644)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896==    by 0x129B1F: nng_pair1_open (pair.c:822)
==1812896==    by 0x110034: main (product_test_server.cpp:101)
==1812896== 
==1812896== 80 bytes in 1 blocks are still reachable in loss record 9 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x1178D0: id_map_register (idhash.c:126)
==1812896==    by 0x117A91: id_resize (idhash.c:176)
==1812896==    by 0x117ECF: nni_id_set (idhash.c:283)
==1812896==    by 0x11814C: nni_id_alloc (idhash.c:353)
==1812896==    by 0x1181A3: nni_id_alloc32 (idhash.c:365)
==1812896==    by 0x11A27E: nni_sock_open (socket.c:650)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896==    by 0x129B1F: nng_pair1_open (pair.c:822)
==1812896==    by 0x110034: main (product_test_server.cpp:101)
==1812896== 
==1812896== 80 bytes in 1 blocks are still reachable in loss record 10 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x121443: nni_url_parse (url.c:303)
==1812896==    by 0x12260E: nni_listener_create (listener.c:215)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 80 bytes in 1 blocks are still reachable in loss record 11 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x151154: nni_tcp_listener_init (posix_tcplisten.c:50)
==1812896==    by 0x14C3E7: tcp_listener_alloc_addr (tcp.c:379)
==1812896==    by 0x14C6F6: nni_tcp_listener_alloc (tcp.c:435)
==1812896==    by 0x14A9C3: nng_stream_listener_alloc_url (stream.c:273)
==1812896==    by 0x12E09F: tcptran_listener_init (tcp.c:992)
==1812896==    by 0x12280A: nni_listener_create (listener.c:255)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 152 bytes in 1 blocks are still reachable in loss record 12 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x11653D: nni_posix_pfd_init (posix_pollq_poll.c:90)
==1812896==    by 0x15172B: nni_tcp_listener_listen (posix_tcplisten.c:237)
==1812896==    by 0x14C149: tcp_listener_listen (tcp.c:302)
==1812896==    by 0x14A86A: nng_stream_listener_listen (stream.c:239)
==1812896==    by 0x12E489: tcptran_ep_bind (tcp.c:1103)
==1812896==    by 0x122D5A: nni_listener_start (listener.c:410)
==1812896==    by 0x111833: nng_listen (nng.c:590)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 152 bytes in 1 blocks are still reachable in loss record 13 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x11653D: nni_posix_pfd_init (posix_pollq_poll.c:90)
==1812896==    by 0x1513DA: tcp_listener_doaccept (posix_tcplisten.c:150)
==1812896==    by 0x15152D: tcp_listener_cb (posix_tcplisten.c:183)
==1812896==    by 0x116CCF: nni_posix_poll_thr (posix_pollq_poll.c:291)
==1812896==    by 0x1262FB: nni_thr_wrap (thread.c:94)
==1812896==    by 0x147DE0: nni_plat_thr_main (posix_thread.c:266)
==1812896==    by 0x4918AC2: start_thread (pthread_create.c:442)
==1812896==    by 0x49A9A03: clone (clone.S:100)
==1812896== 
==1812896== 176 bytes in 1 blocks are still reachable in loss record 14 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x152F1F: nni_posix_tcp_alloc (posix_tcpconn.c:487)
==1812896==    by 0x151394: tcp_listener_doaccept (posix_tcplisten.c:143)
==1812896==    by 0x15152D: tcp_listener_cb (posix_tcplisten.c:183)
==1812896==    by 0x116CCF: nni_posix_poll_thr (posix_pollq_poll.c:291)
==1812896==    by 0x1262FB: nni_thr_wrap (thread.c:94)
==1812896==    by 0x147DE0: nni_plat_thr_main (posix_thread.c:266)
==1812896==    by 0x4918AC2: start_thread (pthread_create.c:442)
==1812896==    by 0x49A9A03: clone (clone.S:100)
==1812896== 
==1812896== 192 bytes in 1 blocks are still reachable in loss record 15 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x124C1D: nni_taskq_init (taskq.c:74)
==1812896==    by 0x1253AE: nni_taskq_sys_init (taskq.c:273)
==1812896==    by 0x11729D: nni_init_helper (init.c:36)
==1812896==    by 0x14818B: nni_plat_init (posix_thread.c:422)
==1812896==    by 0x11732E: nni_init (init.c:58)
==1812896==    by 0x11A21E: nni_sock_open (socket.c:644)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896==    by 0x129B1F: nng_pair1_open (pair.c:822)
==1812896==    by 0x110034: main (product_test_server.cpp:101)
==1812896== 
==1812896== 192 bytes in 1 blocks are still reachable in loss record 16 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x117AFC: id_resize (idhash.c:191)
==1812896==    by 0x117ECF: nni_id_set (idhash.c:283)
==1812896==    by 0x11814C: nni_id_alloc (idhash.c:353)
==1812896==    by 0x1181A3: nni_id_alloc32 (idhash.c:365)
==1812896==    by 0x11A27E: nni_sock_open (socket.c:650)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896==    by 0x129B1F: nng_pair1_open (pair.c:822)
==1812896==    by 0x110034: main (product_test_server.cpp:101)
==1812896== 
==1812896== 192 bytes in 1 blocks are still reachable in loss record 17 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x117AFC: id_resize (idhash.c:191)
==1812896==    by 0x117ECF: nni_id_set (idhash.c:283)
==1812896==    by 0x11814C: nni_id_alloc (idhash.c:353)
==1812896==    by 0x1181A3: nni_id_alloc32 (idhash.c:365)
==1812896==    by 0x1227CA: nni_listener_create (listener.c:248)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 192 bytes in 1 blocks are still reachable in loss record 18 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x14C3C2: tcp_listener_alloc_addr (tcp.c:376)
==1812896==    by 0x14C6F6: nni_tcp_listener_alloc (tcp.c:435)
==1812896==    by 0x14A9C3: nng_stream_listener_alloc_url (stream.c:273)
==1812896==    by 0x12E09F: tcptran_listener_init (tcp.c:992)
==1812896==    by 0x12280A: nni_listener_create (listener.c:255)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 192 bytes in 1 blocks are still reachable in loss record 19 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x117AFC: id_resize (idhash.c:191)
==1812896==    by 0x117ECF: nni_id_set (idhash.c:283)
==1812896==    by 0x11814C: nni_id_alloc (idhash.c:353)
==1812896==    by 0x1181A3: nni_id_alloc32 (idhash.c:365)
==1812896==    by 0x125B6A: pipe_create (pipe.c:263)
==1812896==    by 0x125D33: nni_pipe_create_listener (pipe.c:312)
==1812896==    by 0x11C577: nni_listener_add_pipe (socket.c:1634)
==1812896==    by 0x122C08: listener_accept_cb (listener.c:361)
==1812896==    by 0x124B67: nni_taskq_thread (taskq.c:47)
==1812896==    by 0x1262FB: nni_thr_wrap (thread.c:94)
==1812896== 
==1812896== 264 bytes in 1 blocks are still reachable in loss record 20 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x12DC2B: tcptran_ep_init (tcp.c:897)
==1812896==    by 0x12E020: tcptran_listener_init (tcp.c:986)
==1812896==    by 0x12280A: nni_listener_create (listener.c:255)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 272 bytes in 1 blocks are possibly lost in loss record 21 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x40147D9: calloc (rtld-malloc.h:44)
==1812896==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==1812896==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==1812896==    by 0x49197B4: allocate_stack (allocatestack.c:430)
==1812896==    by 0x49197B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==1812896==    by 0x147E4C: nni_plat_thr_init (posix_thread.c:279)
==1812896==    by 0x126408: nni_thr_init (thread.c:121)
==1812896==    by 0x116E2E: nni_posix_pollq_create (posix_pollq_poll.c:328)
==1812896==    by 0x116EA7: nni_posix_pollq_sysinit (posix_pollq_poll.c:341)
==1812896==    by 0x148077: nni_plat_init (posix_thread.c:396)
==1812896==    by 0x11732E: nni_init (init.c:58)
==1812896==    by 0x11A21E: nni_sock_open (socket.c:644)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896==    by 0x129B1F: nng_pair1_open (pair.c:822)
==1812896== 
==1812896== 272 bytes in 1 blocks are possibly lost in loss record 22 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x40147D9: calloc (rtld-malloc.h:44)
==1812896==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==1812896==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==1812896==    by 0x49197B4: allocate_stack (allocatestack.c:430)
==1812896==    by 0x49197B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==1812896==    by 0x147E4C: nni_plat_thr_init (posix_thread.c:279)
==1812896==    by 0x126408: nni_thr_init (thread.c:121)
==1812896==    by 0x11901C: nni_reap_sys_init (reap.c:110)
==1812896==    by 0x1172AB: nni_init_helper (init.c:37)
==1812896==    by 0x14818B: nni_plat_init (posix_thread.c:422)
==1812896==    by 0x11732E: nni_init (init.c:58)
==1812896==    by 0x11A21E: nni_sock_open (socket.c:644)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896==    by 0x129B1F: nng_pair1_open (pair.c:822)
==1812896== 
==1812896== 456 bytes in 1 blocks are still reachable in loss record 23 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x11CE82: nni_aio_alloc (aio.c:129)
==1812896==    by 0x12E052: tcptran_listener_init (tcp.c:990)
==1812896==    by 0x12280A: nni_listener_create (listener.c:255)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 456 bytes in 1 blocks are still reachable in loss record 24 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x11CE82: nni_aio_alloc (aio.c:129)
==1812896==    by 0x12E07C: tcptran_listener_init (tcp.c:991)
==1812896==    by 0x12280A: nni_listener_create (listener.c:255)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 608 bytes in 1 blocks are still reachable in loss record 25 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x148F03: nni_posix_resolv_sysinit (posix_resolv_gai.c:496)
==1812896==    by 0x1480C9: nni_plat_init (posix_thread.c:404)
==1812896==    by 0x11732E: nni_init (init.c:58)
==1812896==    by 0x11A21E: nni_sock_open (socket.c:644)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896==    by 0x129B1F: nng_pair1_open (pair.c:822)
==1812896==    by 0x110034: main (product_test_server.cpp:101)
==1812896== 
==1812896== 1,024 bytes in 1 blocks are still reachable in loss record 26 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x116983: nni_posix_poll_thr (posix_pollq_poll.c:212)
==1812896==    by 0x1262FB: nni_thr_wrap (thread.c:94)
==1812896==    by 0x147DE0: nni_plat_thr_main (posix_thread.c:266)
==1812896==    by 0x4918AC2: start_thread (pthread_create.c:442)
==1812896==    by 0x49A9A03: clone (clone.S:100)
==1812896== 
==1812896== 1,024 bytes in 1 blocks are still reachable in loss record 27 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x1169AB: nni_posix_poll_thr (posix_pollq_poll.c:214)
==1812896==    by 0x1262FB: nni_thr_wrap (thread.c:94)
==1812896==    by 0x147DE0: nni_plat_thr_main (posix_thread.c:266)
==1812896==    by 0x4918AC2: start_thread (pthread_create.c:442)
==1812896==    by 0x49A9A03: clone (clone.S:100)
==1812896== 
==1812896== 1,088 bytes in 4 blocks are possibly lost in loss record 28 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x40147D9: calloc (rtld-malloc.h:44)
==1812896==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==1812896==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==1812896==    by 0x49197B4: allocate_stack (allocatestack.c:430)
==1812896==    by 0x49197B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==1812896==    by 0x147E4C: nni_plat_thr_init (posix_thread.c:279)
==1812896==    by 0x126408: nni_thr_init (thread.c:121)
==1812896==    by 0x148F64: nni_posix_resolv_sysinit (posix_resolv_gai.c:502)
==1812896==    by 0x1480C9: nni_plat_init (posix_thread.c:404)
==1812896==    by 0x11732E: nni_init (init.c:58)
==1812896==    by 0x11A21E: nni_sock_open (socket.c:644)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896==    by 0x129B1F: nng_pair1_open (pair.c:822)
==1812896==    by 0x110034: main (product_test_server.cpp:101)
==1812896== 
==1812896== 1,856 bytes in 1 blocks are still reachable in loss record 29 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x122663: nni_listener_create (listener.c:224)
==1812896==    by 0x111808: nng_listen (nng.c:586)
==1812896==    by 0x11007D: main (product_test_server.cpp:105)
==1812896== 
==1812896== 2,176 bytes in 8 blocks are possibly lost in loss record 30 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x40147D9: calloc (rtld-malloc.h:44)
==1812896==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==1812896==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==1812896==    by 0x49197B4: allocate_stack (allocatestack.c:430)
==1812896==    by 0x49197B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==1812896==    by 0x147E4C: nni_plat_thr_init (posix_thread.c:279)
==1812896==    by 0x126408: nni_thr_init (thread.c:121)
==1812896==    by 0x11E3B6: nni_aio_expire_q_alloc (aio.c:803)
==1812896==    by 0x11E4F6: nni_aio_sys_init (aio.c:856)
==1812896==    by 0x1172B9: nni_init_helper (init.c:38)
==1812896==    by 0x14818B: nni_plat_init (posix_thread.c:422)
==1812896==    by 0x11732E: nni_init (init.c:58)
==1812896==    by 0x11A21E: nni_sock_open (socket.c:644)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896== 
==1812896== 2,304 bytes in 8 blocks are still reachable in loss record 31 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x11E32E: nni_aio_expire_q_alloc (aio.c:794)
==1812896==    by 0x11E4F6: nni_aio_sys_init (aio.c:856)
==1812896==    by 0x1172B9: nni_init_helper (init.c:38)
==1812896==    by 0x14818B: nni_plat_init (posix_thread.c:422)
==1812896==    by 0x11732E: nni_init (init.c:58)
==1812896==    by 0x11A21E: nni_sock_open (socket.c:644)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896==    by 0x129B1F: nng_pair1_open (pair.c:822)
==1812896==    by 0x110034: main (product_test_server.cpp:101)
==1812896== 
==1812896== 2,560 bytes in 1 blocks are still reachable in loss record 32 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x11603A: nni_zalloc (posix_alloc.c:26)
==1812896==    by 0x124C4E: nni_taskq_init (taskq.c:77)
==1812896==    by 0x1253AE: nni_taskq_sys_init (taskq.c:273)
==1812896==    by 0x11729D: nni_init_helper (init.c:36)
==1812896==    by 0x14818B: nni_plat_init (posix_thread.c:422)
==1812896==    by 0x11732E: nni_init (init.c:58)
==1812896==    by 0x11A21E: nni_sock_open (socket.c:644)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896==    by 0x129B1F: nng_pair1_open (pair.c:822)
==1812896==    by 0x110034: main (product_test_server.cpp:101)
==1812896== 
==1812896== 4,352 bytes in 16 blocks are possibly lost in loss record 33 of 33
==1812896==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1812896==    by 0x40147D9: calloc (rtld-malloc.h:44)
==1812896==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==1812896==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==1812896==    by 0x49197B4: allocate_stack (allocatestack.c:430)
==1812896==    by 0x49197B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==1812896==    by 0x147E4C: nni_plat_thr_init (posix_thread.c:279)
==1812896==    by 0x126408: nni_thr_init (thread.c:121)
==1812896==    by 0x124D79: nni_taskq_init (taskq.c:92)
==1812896==    by 0x1253AE: nni_taskq_sys_init (taskq.c:273)
==1812896==    by 0x11729D: nni_init_helper (init.c:36)
==1812896==    by 0x14818B: nni_plat_init (posix_thread.c:422)
==1812896==    by 0x11732E: nni_init (init.c:58)
==1812896==    by 0x11A21E: nni_sock_open (socket.c:644)
==1812896==    by 0x14CC1B: nni_proto_open (protocol.c:21)
==1812896== 
==1812896== LEAK SUMMARY:
==1812896==    definitely lost: 0 bytes in 0 blocks
==1812896==    indirectly lost: 0 bytes in 0 blocks
==1812896==      possibly lost: 8,160 bytes in 30 blocks
==1812896==    still reachable: 12,347 bytes in 35 blocks
==1812896==         suppressed: 0 bytes in 0 blocks
==1812896== 
==1812896== For lists of detected and suppressed errors, rerun with: -s
==1812896== ERROR SUMMARY: 36877 errors from 8 contexts (suppressed: 0 from 0)

https://github.com/nanomsg/nng.git           a8a8bd435690e24e55dcdad485e97225902cb0c8
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by alawn-wang** [comment]
You just give a report of Valgrind, maybe you give an test-case or example can help analyse the reason of memory leap
