### ISSUE TITLE
`clock_gettime` is not used on Android, even though available (1.6.0+)

### ISSUE THREAD

**Issue by hungrycat** [nanomsg/nng#1866]
**Describe the bug**
Android has its own implementation of the system libraries: https://android.googlesource.com/platform/bionic.
`clock_gettime` is made available in `libc`, not in `librt` like on some other POSIX platforms. Yet, the check in the build system assumes `clock_gettime` is in `librt`:

From `src/platform/posix/CMakeLists.txt`:
```
nng_check_lib(rt clock_gettime NNG_HAVE_CLOCK_GETTIME)
```

As a consequence, on Android `NNG_HAVE_CLOCK_GETTIME` is never set, and fallback to `nni_clock` is used instead of `clock_gettime`. As documented in the file, this severely hinders stability of nng on that platform

**To Reproduce**
Build for Android, assert in `posix_clock.c` on which implementation is used. Expectation: `clock_gettime`.

**Environment Details**
 - NNG version: started in 1.6.0, with this change: https://github.com/nanomsg/nng/issues/1576
 - Operating system and version: Android
 - Compiler and language used: NDK 26.1.10909125
 - Shared or static library: should not matter

**Comment by hungrycat** [comment]
Possible solution:
[clock_gettime.patch](https://github.com/user-attachments/files/16873348/clock_gettime.patch)

**Comment by gdamore** [comment]
A better solution IMO is to look *first* in libc, and only look in librt if we didn't find it in libc.
