### ISSUE TITLE
Why no default for BUILD_SHARED_LIBS?

### ISSUE THREAD

**Issue by blozano-tt** [nanomsg/nng#1954]
https://github.com/nanomsg/nng/blob/ec714f06594269b671a6f484106259854b6a99b6/cmake/NNGOptions.cmake#L21

According to this, CMake does not define a default.

It seems like this project should be setting this to FALSE or OFF.

https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

**Comment by gdamore** [comment]
I believe if BUILD_SHARED_LIBS is unset at this point, it will become OFF.  So this isn't necessarily a problem.

I'm not sure what the best practice here is -- because in theory someone might have already set that variable if we are included as a sub project.

**Comment by blozano-tt** [comment]
> I believe if BUILD_SHARED_LIBS is unset at this point, it will become OFF. So this isn't necessarily a problem.
> 
> I'm not sure what the best practice here is -- because in theory someone might have already set that variable if we are included as a sub project.

I think you should default it to off for clarity.

Since it’s a cache variable… it’s designed to be overridden by command line, or option passing (fetch content)… and cache variables are shadowed by normal variables if there is some add_subdirectory inclusion.

Maybe ask ChatGPT to confirm :-).

**Comment by blozano-tt** [comment]
The reason I filed the issue, is I came here to check what the expectation is for this library…

and I see what looks like circular default…

set X = X;

**Comment by gdamore** [comment]
I see.  I don't actually have a strong opinion about the "default".
