### ISSUE TITLE
Complete transition to Circle CI

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#202]
Travis remains unreliable.  Lets finish the conversion -- mostly we need to update to generate code coverage from Circle CI (it would be nice to start running the mac tests there too, but lower priority.)

**Comment by eberkund** [comment]
It looks like Circle CI suggests using [gcov](http://gcc.gnu.org/onlinedocs/gcc/Gcov.html) for this

https://circleci.com/docs/1.0/code-coverage/

**Comment by gdamore** [comment]
That's correct.  Unfortunately, setting this up on circle is a bit more complex than with travis, owing to their new workflows system.

**Comment by eberkund** [comment]
Did you try using [codecov](https://codecov.io/)? It is mentioned as well, it's free for open source and it looks like it can be setup with just one line.

https://circleci.com/docs/1.0/code-coverage/#codecov

`test:
  post:
    - bash <(curl -s https://codecov.io/bash)
`

**Comment by eberkund** [comment]
I see you also tried codecov: https://github.com/nanomsg/nng/blob/master/etc/codecov.sh

Did you encounter some issues with that? Is it possible to get that working rather that switching to gcov?

**Comment by gdamore** [comment]
codecov just consumes the output from gcov and integrates into the CI.  (It can also use other coverage systems for other languages).

The issue I have right now is figuring out how to get a gcov/codecov (and I also have looked at coverage capabilities in coveralls and codacy) workflow integrated into circleci.  This is really just adding new steps to circleci.

**Comment by gdamore** [comment]
CircleCI is insisting that everyone switch to their 2.0 platform (which really is better) -- we are already using that.

It would be great if we could add workflows support, and use them to test different compiler suites and get code coverage as well. 

If there are any Circle CI experts in the audience, I invite them to step forward now.
