### ISSUE TITLE
Double definition of -DNNG_PLATFORM_POSIX for Darwin platform

### ISSUE THREAD

**Issue by snikulov** [nanomsg/nng#223]
https://github.com/nanomsg/nng/blob/b2800c58d63dc1b53557ea9294b323c3b1f90dab/CMakeLists.txt#L265

Perhaps should be something related to Darwin.

**Comment by gdamore** [comment]
Nice catch.  Will fix.  (Thanks.)

**Comment by liamstask** [comment]
this is included in #204 (also fine to address separately)

**Comment by gdamore** [comment]
I fixed it separately.  I have not forgotten about #204  will try to get to it in the next week.  I've been working on a bunch of other API stuff that I want to sort out before cutting another release first though.
