### ISSUE TITLE
Windows pipe name restrictions, unicode

### ISSUE THREAD

**Issue by JoernHbg** [nanomsg/nng#224]
In the file src/platform/windows/win_ipc.c, please consider converting the paths from utf-8 to ucs-2, probably using MultiByteToWideChar(CP_UTF8, ...), and calling the Unicode versions of the windows API.

Windows will accept all Unicode characters except the backslash in pipe names.

**Comment by gdamore** [comment]
So what is the point of this?  nng doesn't let users create named pipe with *any* name, but since only nng/nanomsg/mangos clients can use such named pipes, does it really matter?

**Comment by JoernHbg** [comment]
I was under the impression that other transports support full utf8 encoding, such as inproc or http, so why restrict the charset on one transport when the operation system supports it.
It’s not my choice how a customer names his objects, and if he wants Danish town names, let him have them. As a kind of inspiration I’d like to remind the readers that this compiles fine:

float foo(void)
{
       float β = 0.0f;
       return β;
}

Best regards,
Jörn Sierwald


Von: gdamore [mailto:notifications@github.com]
Gesendet: Mittwoch, 24. Januar 2018 18:47
An: nanomsg/nng
Cc: Sierwald, Jörn; Author
Betreff: Re: [nanomsg/nng] Windows pipe name restrictions, unicode (#224)


So what is the point of this? nng doesn't let users create named pipe with any name, but since only nng/nanomsg/mangos clients can use such named pipes, does it really matter?

**Comment by gdamore** [comment]
So won't that work with UTF-8 names?  (Btw, the above code is *not* compliant with C99.)  Maybe I'm misunderstanding something here in the Windows APIs?  I thought I could get away with using the 8-bit versions and passing UTF-8?

**Comment by gdamore** [comment]
Ah, a little more research, you're right.  UTF-8 doesn't *just work* for filenames in Windows like it does in UNIX.  I'll have to change the win_ipc.c code as you suggested.  I might also change the file creation code in win_file.c -- there is no reason to prevent the use of Unicode names anywhere there.

**Comment by gdamore** [comment]
Hmm... it looks like Windows named pipes "broke" with those changes.  I'm suspicious that this may require either \\.\pipe\LOCAL\ names noted for Windows 10 version 1709, or that the CI has other restrictions.

Furthermore, it turns out that we probably want to restrict ourselves to the same names used for legacy nanomsg, otherwise we break compatibility there.

I think I'm probably going to revert these changes.

**Comment by gdamore** [comment]
So it really appears to be the conversion to UCS-2 (UTF16LE) that causes problems here.  Rolling back to use the "A" versions of the functions and everything Just Works.

I actually strongly advise to use only ASCII characters in pipe names.  I guess if you have an ANSI code page active you could probably use those western european characters no problem.  I have no idea how DBCS pages (like GBK) work with the ANSI APIs in Windows.

**Comment by JoernHbg** [comment]
I just tested it, your code works fine if you change the NT 4.0-aera MB_PRECOMPOSED to 0.

       rv = MultiByteToWideChar(CP_UTF8, 0, scratch, -1,
           ep->wpath, NNI_NUM_ELEMENTS(ep->wpath));

By the way, it translates "ipc:///myfirstpipe"
to \\.\pipe\/myfirstpipe<file:///\\.\pipe\myfirstpipe>, is that intentional? My impression was that "ipc:///myfirstpipe" is correct for a local pipe,
but then the forward slash in the translated name doesn’t need to be there.

Anyway, I just named a pipe after a Unicode Emoji and it worked fine with that fix.

Cheers, Jörn

Von: gdamore [mailto:notifications@github.com]
Gesendet: Freitag, 9. Februar 2018 02:36
An: nanomsg/nng
Cc: Sierwald, Jörn; Author
Betreff: Re: [nanomsg/nng] Windows pipe name restrictions, unicode (#224)


So it really appears to be the conversion to UCS-2 (UTF16LE) that causes problems here. Rolling back to use the "A" versions of the functions and everything Just Works.

I actually strongly advise to use only ASCII characters in pipe names. I guess if you have an ANSI code page active you could probably use those western european characters no problem. I have no idea how DBCS pages (like GBK) work with the ANSI APIs in Windows.
