### ISSUE TITLE
REP0 documention is unclear

### ISSUE THREAD

**Issue by JoernHbg** [nanomsg/nng#238]
Please rewrite the "protocol headers" section of nng_rep.adoc. I dare say that it cannot be understood by mortals. And details as "each element in a path adds routing information to the end when sending a request" are plain wrong I think, isn't routing information added at the front when receiving a request?

**Comment by gdamore** [comment]
Yep, the wording was "bad".  I hope that fixed it.

**Comment by JoernHbg** [comment]
Much better. Thank you. Though the Rep0 page says that the details are found on the Rep0 page and points to itself, surely that should point to Req0.

Jörn

Von: gdamore [mailto:notifications@github.com]
Gesendet: Montag, 19. Februar 2018 20:29
An: nanomsg/nng
Cc: Sierwald, Jörn; Author
Betreff: Re: [nanomsg/nng] REP0 documention is unclear (#238)


Yep, the wording was "bad". I hope that fixed it.
