### ISSUE TITLE
nngcat is MIA

### ISSUE THREAD

**Issue by codypiersall** [nanomsg/nng#240]
I love nanocat!  I've found a use for it in my daily workflow for quick checks to ensure services are running and things like that.  I was excited to see that this library has an nngcat, but when I went to build the project from master with the command `mkdir build && cd build && cmake -DNNG_ENABLE_NNGCAT=ON ..`, I get the following error:

```
CMake Warning at CMakeLists.txt:420 (message)
  Could not find asciidoctor: skipping docs 


CMake Error at CMakeLists.txt:516 (install):
  install TARGETS given target "nngcat" which does not exist in this                                                   
  directory.


-- Configuring incomplete, errors occurred!
See also "/home/cody/dev/nng/build/CMakeFiles/CMakeOutput.log".
See also "/home/cody/dev/nng/build/CMakeFiles/CMakeError.log".
```

It seems that there are a couple problems:

1. The CMakeLists.txt file cannot decide whether the executable should be named nanocat or nngcat, and
2. The CMakeLists.txt file refers to `tools/nngcat.c` and `tools/options.c` (line 413), and neither of those files exist.

Will nngcat exist in this repository, or is it not a goal of the project?

**Comment by gdamore** [comment]
I had planned to add nngcat for sure, I just hadn't gotten to it yet!

**Comment by gdamore** [comment]
There is an "nngcat" branch that has a utility that is 95% complete and compatible with nanocat.  I have a little more tweaking & testing to do, but expect it to merge to master before too long.

**Comment by codypiersall** [comment]
Excellent!
