### ISSUE TITLE
uint64_t -> int64_t  compile warnings ZeroTier transport

### ISSUE THREAD

**Issue by janjaapbos** [nanomsg/nng#256]
When compiling including the  ZeroTier transport on OSX, the following warnings are given. These are caused by uint64_t -> int64_t changes in ZeroTier code.

[74/311] Building C object src/CMakeFiles/nng.dir/transport/zerotier/zerotier.c.o
../src/transport/zerotier/zerotier.c:320:60: warning: passing 'uint64_t *' (aka 'unsigned long long *') to parameter of type 'volatile int64_t *' (aka 'volatile long long *') converts between pointers to integer types with different sign [-Wpointer-sign]
                ZT_Node_processBackgroundTasks(ztn->zn_znode, NULL, now, &now);
                                                                         ^~~~
/usr/local/include/ZeroTierOne.h:1657:117: note: passing argument to parameter 'nextBackgroundTaskDeadline' here
ZT_SDK_API enum ZT_ResultCode ZT_Node_processBackgroundTasks(ZT_Node *node,void *tptr,int64_t now,volatile int64_t *nextBackgroundTaskDeadline);
                                                                                                                    ^
../src/transport/zerotier/zerotier.c:370:44: warning: passing 'uint64_t *' (aka 'unsigned long long *') to parameter of type 'volatile int64_t *' (aka 'volatile long long *') converts between pointers to integer types with different sign [-Wpointer-sign]
            ztn->zn_rcv4_buf, nni_aio_count(aio), &now);
                                                  ^~~~
/usr/local/include/ZeroTierOne.h:1617:20: note: passing argument to parameter 'nextBackgroundTaskDeadline' here
        volatile int64_t *nextBackgroundTaskDeadline);
                          ^
../src/transport/zerotier/zerotier.c:420:44: warning: passing 'uint64_t *' (aka 'unsigned long long *') to parameter of type 'volatile int64_t *' (aka 'volatile long long *') converts between pointers to integer types with different sign [-Wpointer-sign]
            ztn->zn_rcv6_buf, nni_aio_count(aio), &now);
                                                  ^~~~
/usr/local/include/ZeroTierOne.h:1617:20: note: passing argument to parameter 'nextBackgroundTaskDeadline' here
        volatile int64_t *nextBackgroundTaskDeadline);
                          ^
../src/transport/zerotier/zerotier.c:575:56: warning: passing 'uint64_t *' (aka 'unsigned long long *') to parameter of type 'volatile int64_t *' (aka 'volatile long long *') converts between pointers to integer types with different sign [-Wpointer-sign]
            nwid, srcmac, dstmac, zt_ethertype, 0, data, len, &now);
                                                              ^~~~
/usr/local/include/ZeroTierOne.h:1646:20: note: passing argument to parameter 'nextBackgroundTaskDeadline' here
        volatile int64_t *nextBackgroundTaskDeadline);
                          ^
4 warnings generated.
[143/311] Building C object src/CMakeFiles...static.dir/transport/zerotier/zerotier.c.o
../src/transport/zerotier/zerotier.c:320:60: warning: passing 'uint64_t *' (aka 'unsigned long long *') to parameter of type 'volatile int64_t *' (aka 'volatile long long *') converts between pointers to integer types with different sign [-Wpointer-sign]
                ZT_Node_processBackgroundTasks(ztn->zn_znode, NULL, now, &now);
                                                                         ^~~~
/usr/local/include/ZeroTierOne.h:1657:117: note: passing argument to parameter 'nextBackgroundTaskDeadline' here
ZT_SDK_API enum ZT_ResultCode ZT_Node_processBackgroundTasks(ZT_Node *node,void *tptr,int64_t now,volatile int64_t *nextBackgroundTaskDeadline);
                                                                                                                    ^
../src/transport/zerotier/zerotier.c:370:44: warning: passing 'uint64_t *' (aka 'unsigned long long *') to parameter of type 'volatile int64_t *' (aka 'volatile long long *') converts between pointers to integer types with different sign [-Wpointer-sign]
            ztn->zn_rcv4_buf, nni_aio_count(aio), &now);
                                                  ^~~~
/usr/local/include/ZeroTierOne.h:1617:20: note: passing argument to parameter 'nextBackgroundTaskDeadline' here
        volatile int64_t *nextBackgroundTaskDeadline);
                          ^
../src/transport/zerotier/zerotier.c:420:44: warning: passing 'uint64_t *' (aka 'unsigned long long *') to parameter of type 'volatile int64_t *' (aka 'volatile long long *') converts between pointers to integer types with different sign [-Wpointer-sign]
            ztn->zn_rcv6_buf, nni_aio_count(aio), &now);
                                                  ^~~~
/usr/local/include/ZeroTierOne.h:1617:20: note: passing argument to parameter 'nextBackgroundTaskDeadline' here
        volatile int64_t *nextBackgroundTaskDeadline);
                          ^
../src/transport/zerotier/zerotier.c:575:56: warning: passing 'uint64_t *' (aka 'unsigned long long *') to parameter of type 'volatile int64_t *' (aka 'volatile long long *') converts between pointers to integer types with different sign [-Wpointer-sign]
            nwid, srcmac, dstmac, zt_ethertype, 0, data, len, &now);
                                                              ^~~~
/usr/local/include/ZeroTierOne.h:1646:20: note: passing argument to parameter 'nextBackgroundTaskDeadline' here
        volatile int64_t *nextBackgroundTaskDeadline);
                          ^
4 warnings generated.

**Comment by gdamore** [comment]
Didn't see this as a separate bug.  I fixed it in b6298c28473acbed2f1429176c7cae4fb514d98b
