### ISSUE TITLE
nngcat should support ZeroTier transport

### ISSUE THREAD

**Issue by janjaapbos** [nanomsg/nng#260]
Currently the ZeroTier URI  seems not te be supported. E.g. when trying to create a listener:

addr="zt://6ab123456a57ac43.*:123"
nngcat --rep --listen=${addr} --data="42" --quoted

The following error is returned:
Unable to create listener for zt://6ab123456a57ac43.*:123: Address invalid

Working with ephemeral ZeroTier nodes raises the issue that we do not yet know the node id when we want to provide the address.

It would be nice if nngcat would support persistent nodes, and support the initialisation of a node, using a provided home path. Subsequent invocation would reuse the same home path.

Perhaps using a switch such as: init_zt home_path which would return the generated zerotier node id.

**Comment by gdamore** [comment]
First off the node and network number backwards.  The url should be 'zt://*. 6ab123456a57ac43'.

I have considered the idea of a persistent node (via path).

I think some things with the zerotier home path should be handled via a separate utility than nngcat.  For example, creation of the entity, joining networks, and setting up orbits (moons) should all be done by this other utility.

I'm also thinking about some kind of "locking" scheme (using OS provided file locking if available) to prevent inadvertent simultaneous accesses to the backing store by different processes (which could be "bad".)

**Comment by gdamore** [comment]
So the address invalid error is indeed that you have the nodeid and network id backwards.  I've just confirmed that by switching them it works.  The problem where the node id is not reported is indeed a problem.   I'll probably also file another issue to reflect the desire for nngcat to support persistent nodes.

**Comment by gdamore** [comment]
please see #262 -- I'm working on this.

**Comment by gdamore** [comment]
Ok, now that #262 is done, we can use nngcat with ephemeral nodes.  (Use --verbose to get the listen address.) . I've filed #265 to cover the concerns about persistent nodes.  Closing this one.
