### ISSUE TITLE
nngcat should support persistent ZT nodes

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#265]
We could take an option "--zt-home" (or perhaps an environment variable?) to support the use of persistent ZeroTier nodes.

Some thought needs to be given to locking the zt homedirs.

**Comment by gdamore** [comment]
See also #260 which has some relevant discussion.

**Comment by gdamore** [comment]
CC @janjaapbos

**Comment by janjaapbos** [comment]
Yes, environment variable would also be nice. BTW, was able to run nngcat ok with ephemeral node and correct URI.

**Comment by gdamore** [comment]
I have done the --zt-home argument option..  waiting for CI to come back clean.  I didn't do environment variables.
