### ISSUE TITLE
Update Zerotier transport URI documentation

### ISSUE THREAD

**Issue by janjaapbos** [nanomsg/nng#266]
The man page is correct. 

Therefore the following must be updated:
src/transport/zerotier/zerotier.h (ZeroTier URL format)
src/transport/zerotier/zerotier.adoc (URI Format)

If I read it correctly ;-)

**Comment by gdamore** [comment]
I've nuked the RFC, because it was stale, and we have a newer one in a different repo (the nanomsg/rfcs repo), and that is used to publish them online.

The header file was corrected in 15c08f97f1772dfa43dbd8ee27ba487ca553da6a
