### ISSUE TITLE
autoscale based on CPUs available

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#32]
We need a platform-specific way to inquire as to how many CPUs are available.  This should be used to automatically tune the number of threads used for the system wide taskq; it may be used to drive other decisions later.

**Comment by gdamore** [comment]
We will specifically need:

nni_plat_cpu_count();
nni_plat_cpu_current();

Both of these should return integers.  The first is the count of CPUs on the system, and the second should return the current CPU ID.

In an ideal world, the current CPU ID would never exceed the CPU count, and a given CPU will always return the same ID.  This would allow us to make certain kinds of assumptions (perhaps eliding certain locking paths.)

**Comment by gdamore** [comment]
We might also want thread identifiers....

**Comment by Grabber** [comment]
@gdamore, a good reference is:

https://github.com/jesselegg/x264/blob/master/common/cpu.c
https://github.com/jesselegg/x264/blob/master/common/cpu.h

**Comment by ClosetMonkey** [comment]
I understand that this is an old issue, but what is the state of managing nng thread count? Is it only possible during build time with NNG_MAX_TASKQ_WORKERS or does  the api provide a way to tune this in userspace?
