### ISSUE TITLE
replace NNG_OPT_RAW option with constructor

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#331]
It turns out that switching between raw and cooked mode on descriptors is something of a pain.  For some new things (like the contexts coming), going back and forth requires very different logic, extra locks, and resetting state machines, etc.

There is no reason to support this.  The option can become read-only (it's useful for nng_device() for example), but we would replace the settable option with protocol specific constructors such as nng_pair1_open_raw(). 

This is an API change, and possibly disruptive for users, but not many folks are using raw mode.  The API would not need to change for legacy mode, as it already uses a constructor-time decision (in this case an option to the constructor.)

The readable option can then be relegated to the socket core, by using a flag in the proto ops vector to indicate whether the socket is "raw" mode or not.

**Comment by gdamore** [comment]
This also means we can shorten some code paths by not having explicit checks for socket mode.

**Comment by codypiersall** [comment]
Do you think it would be worth it to keep the option for a period of time and issue a loud error message?  That way when users encounter this they will know that they need to change this.  The error message could read something like:

    fprintf(stderr, "ERROR: It is no longer supported to set NNG_OPT_RAW via nng_setopt_int.  Use the constructor nng_<protocol>_open_raw instead.\n")

OTOH this is still in the pre-release stage, so a warning may not be necessary, and like you said it seems unlikely many people are using the sockets in raw mode.
