### ISSUE TITLE
nn_poll() legacy API missing

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#344]
Working on docs, and I found that nn_poll is absolutely missing!

We need to correct this.

Legacy nn_poll uses multiple file descriptors, and performs a legacy poll operation on them.  In modern nng, we don't need to do that.  We can instead use callbacks or somesuch.  It may be worth thinking about.  (Having said, that we don't think many apps ever used this function -- it was rather niche since it doesn't work with other kinds of event descriptors.)

**Comment by SG7** [comment]
It is true that 'nn_poll' has a few shortcoming. Nevertheless, I have found
it useful and I have used it in my apps.

The ideal replacement for 'nn_poll' would be a blocking function with a
timeout which can wait at the same time on

a) nano sockets
b) native sockets
c) timers

**Comment by gdamore** [comment]
nn_poll doesn't give you access to native sockets, so it doesn't fill that need.

You can use the NNG_OPT_SENDFD and NNG_OPT_RECVFD to get pollable file dsecriptors (or NN_SNDFD and NN_RCVFD in the legacy API) for use with native poll().  nn_poll() was a convenience wrapper for applications that *only* multiplex nanomsg sockets and never any others.

When I write the replacement for nn_poll(), it will work the same way, just as a convenience wrapper, and it won't be very efficient at all.

Using nng_aio(5) will be far better for applications, saving a lot of wasted effort.  Right now it doesn't support native sockets -- but I'm probably going to fix that soon (using a thin-wrapper for TCP and IPC sockets).  You get timeouts, and even arbitrary timers via nng_sleep_aio().  Not only that, but you get the specific data back in a callback, and can get high levels of parallelism (callbacks can run in parallel, we supply the underlying threads for you!)

Please have a good look at the nng_aio(5) man page.  If you can make that work, you'll be happier, and have a more scalable and more performant application. 

Of course, this is only available in the NNG new API.

**Comment by gdamore** [comment]
I hit close and comment by mistake... this isn't meant to be closed yet.
