### ISSUE TITLE
Unable to build in MSYS + Win-builds

### ISSUE THREAD

**Issue by airways** [nanomsg/nng#430]
## NNG & Platform details.

NNG: Latest NNG master as of writing (1d033484ee1a2ec26d3eead073e7bc0f889ffdf4)
Platform: Windows 10, fully patched. MSYS + Win-builds (x64) setup according to instructions at http://win-builds.org/1.5.0/msys-cygwin.html -- latest as of writing

## Expected Behavior
Should build as easily as Nanomsg does (the original library builds in this environment without issue, however we want to instead use NNG for TLS support).

## Actual Behavior
Unable to build, output from ninja is:

```
$ ninja
[59/340] Building C object src/CMakeFiles/nng.dir/platform/windows/win_resolv.c.obj
FAILED: src/CMakeFiles/nng.dir/platform/windows/win_resolv.c.obj
C:\Dev\win-builds-mingw\msys\1.0\opt\windows_64\bin\cc.exe -DNNG_HAVE_BUS0 -DNNG_HAVE_CONDVAR=1 -DNNG_HAVE_PAIR0 -DNNG_HAVE_PAIR1 -DNNG_HAVE_PUB0 -DNNG_HAVE_PULL0 -DNNG_HAVE_PUSH0 -DNNG_HAVE_REP0 -DNNG_HAVE_REQ0 -DNNG_HAVE_RESPONDENT0 -DNNG_HAVE_SNPRINTF=1 -DNNG_HAVE_STRCASECMP=1 -DNNG_HAVE_STRNCASECMP=1 -DNNG_HAVE_STRNLEN=1 -DNNG_HAVE_SUB0 -DNNG_HAVE_SURVEYOR0 -DNNG_LITTLE_ENDIAN -DNNG_PLATFORM_WINDOWS -DNNG_PRIVATE -DNNG_SHARED_LIB -DNNG_SUPP_HTTP -DNNG_TRANSPORT_INPROC -DNNG_TRANSPORT_IPC -DNNG_TRANSPORT_TCP -DNNG_TRANSPORT_WS -D_CRT_RAND_S -D_CRT_SECURE_NO_WARNINGS -D_WIN32_WINNT=0x0600 -Dnng_EXPORTS -isystem ../src -Wall -Wextra    -std=gnu99 -MD -MT src/CMakeFiles/nng.dir/platform/windows/win_resolv.c.obj -MF src\CMakeFiles\nng.dir\platform\windows\win_resolv.c.obj.d -o src/CMakeFiles/nng.dir/platform/windows/win_resolv.c.obj   -c ../src/platform/windows/win_resolv.c
../src/platform/windows/win_resolv.c: In function 'win_resolv_task':
../src/platform/windows/win_resolv.c:137:21: error: 'AI_V4MAPPED' undeclared (first use in this function)
   hints.ai_flags |= AI_V4MAPPED;
                     ^
../src/platform/windows/win_resolv.c:137:21: note: each undeclared identifier is reported only once for each function it appears in
[64/340] Building C object src/CMakeFiles/nng.dir/platform/windows/win_tcp.c.obj
../src/platform/windows/win_tcp.c: In function 'nni_plat_tcp_ntop':
../src/platform/windows/win_tcp.c:704:4: warning: passing argument 2 of 'inet_ntop' discards 'const' qualifier from pointer target type [enabled by default]
    InetNtopA(af, ap, ipstr + 1, INET6_ADDRSTRLEN);
    ^
In file included from ../src/platform/windows/win_impl.h:26:0,
                 from ../src/core/platform.h:548,
                 from ../src/core/nng_impl.h:27,
                 from ../src/platform/windows/win_tcp.c:11:
c:\dev\win-builds-mingw\msys\1.0\opt\windows_64\x86_64-w64-mingw32\include\ws2tcpip.h:424:35: note: expected 'PVOID' but argument is of type 'const void *'
 WINSOCK_API_LINKAGE LPCSTR WSAAPI InetNtopA(INT Family, PVOID pAddr, LPSTR pStringBuf, size_t StringBufSize);
                                   ^
../src/platform/windows/win_tcp.c:709:4: warning: passing argument 2 of 'inet_ntop' discards 'const' qualifier from pointer target type [enabled by default]
    InetNtopA(af, ap, ipstr, INET6_ADDRSTRLEN);
    ^
In file included from ../src/platform/windows/win_impl.h:26:0,
                 from ../src/core/platform.h:548,
                 from ../src/core/nng_impl.h:27,
                 from ../src/platform/windows/win_tcp.c:11:
c:\dev\win-builds-mingw\msys\1.0\opt\windows_64\x86_64-w64-mingw32\include\ws2tcpip.h:424:35: note: expected 'PVOID' but argument is of type 'const void *'
 WINSOCK_API_LINKAGE LPCSTR WSAAPI InetNtopA(INT Family, PVOID pAddr, LPSTR pStringBuf, size_t StringBufSize);
                                   ^
ninja: build stopped: subcommand failed.
```

## Steps to Reproduce

Install MSYS + Win-builds (x64) according to http://win-builds.org/1.5.0/msys-cygwin.html
Install CMake, add to $PATH
Install ninja, place in msys/1.0/bin or other location on PATH

```
  $ mkdir build
  $ cd build
  $ cmake -G Ninja ..
  $ ninja
```

**Comment by gdamore** [comment]
You probably have to use mingw-w64.  The old version of mingw lacks support for modern Windows APIs, and I'm really not interested in supporting it.  That said, if you *are* using mingw-w64 (I don't know what msys means in this context) then let me know and I'll dive into it.

**Comment by airways** [comment]
Win-builds is based on mingw-w64, they are currently packaging Mingw-w64 v3.3.0

**Comment by gdamore** [comment]
Ok, I think the warnings are benign (I'm passing around values that are not const pointers, but the code shouldn't be changing anything in a bad way), but the real issue is that the headers you have seem to lack AI_V4MAPPED.  Modern Windows systems do have this header, but it's possible that that this was added after Vista...

In the POSIX code, I conditionalize the statement that sets that flag by guarding it with an #ifdef AI_V4MAPPED.  The same approach will work with Windows, I think.  (This flag indicates that we would like to receive a V4 address mapped as a V6 address if no V6 address is present.  It is used primarily on dual stack systems where the V6 APIs can be used to communicate with V4 IP addresses via this special form of "mapped" address.)

Anyway, you can just comment out (or ifdef out) the offending line for now.  I'll see about fixing this properly in the code shortly, along with fixes for the warnings.
