### ISSUE TITLE
nng_aio_free blocks during callback

### ISSUE THREAD

**Issue by widdma** [nanomsg/nng#508]
## NNG & Platform details.

nng version 1.0.0 rc.1

OSs tested:
-   Linux (Ubuntu 16.04)
-   macOS High Sierra                

## Expected Behavior

`nng_aio_free` not to block inside a callback function since the aio has finished.

## Actual Behavior

`nng_aio_free` blocks when called in a callback function

## Steps to Reproduce

The current rest demo exhibits this behaviour and eventually deadlocks after about 15 requests. 

Alternatively, below is a minimal example which I would expect to exit but never does.

```c
#include <stdio.h>
#include <stdlib.h>
#include <nng/nng.h>
#include <nng/supplemental/util/platform.h>

struct job {
    nng_aio* aio;
    // usually other stuff here
};

void callb(void* arg)
{
    struct job* job = arg;
    nng_aio_free(job->aio);
    exit(0);
}

int main(void)
{
    struct job job = {NULL};

    int rv = nng_aio_alloc(&job.aio, callb, &job);
    if (rv != 0) {
        printf("error allocating aio: %s\n", nng_strerror(rv));
        exit(1);
    }

    nng_sleep_aio(500, job.aio);
    for (;;) {
        nng_msleep(3600000); 
    }
}
```

If this is an incorrect way of calling `nng_aio_free`, could you please update the rest demo with the correct usage. Thanks for all your work.

David

**Comment by gdamore** [comment]
Thanks I'll look at this.  It seems to me that your code should work above so I will do some investigation and get back to you.  Likewise for the demo.

**Comment by gdamore** [comment]
Yes, definite deadlock here.  You can't call free on the callback from the callback itself.  I missed that you had placed the exit after that call.  Think of this as being akin to call pthread_join() from the thread itself.  Can't be done.

**Comment by gdamore** [comment]
So there is supposed to be some code that was supposed to make this work though -- basically if you were calling this from the same thread, then we wouldn't wait.  That looks missing.  Stay tuned.

**Comment by gdamore** [comment]
So there's no "trivial" fix for the rest demo.  What I'm doing for now is adding a freelist, and converting the code to recycle them.  This avoids needing to call the nng_aio_free() function altogether.

In 1.1 I will have a "real" fix, backed by a fix for #511 -- I don't want to disrupt 1.0 at this late date though.

**Comment by gdamore** [comment]
The number 15 is not coincidental -- its probably 16.  That's the number of taskq threads we have.  Basically we've gummed up the master taskq.

**Comment by widdma** [comment]
Great, thanks for looking into it.  Yes it seems some kind of asynchronous/deferred free would be handy for this pattern.

I'll close this in favour of #511.
