### ISSUE TITLE
ep_stop is not actually used

### ISSUE THREAD

**Issue by JoernHbg** [nanomsg/nng#521]
https://github.com/nanomsg/nng/blob/69190eb962f6a74be3d693f584320e42a79462d1/src/core/transport.h#L110

Do you have plans for it or do you want to remove that?

**Comment by gdamore** [comment]
I think at one point I had code that used this.  It may be stale now; I will review.

**Comment by gdamore** [comment]
Yeah, I should just remove this.  Also, it appears, I should remove the nni_ep_stop() declaration in endpt.h.
