### ISSUE TITLE
Feature request: customizable http error page

### ISSUE THREAD

**Issue by questor** [nanomsg/nng#539]
it would be great to have a customizable error handler for http errors. the current error-page only shows the error code, but it would be great to get information from the request aswell (for example which url was tried to access).

**Comment by questor** [comment]
I'm currently experimenting with this one. I've changed all calls to the error handler to include the request generating the error, but I've found two things:
- websockets are also using the http error handler, but there the request is already released. I'm not deep enough into the structure of the library to fix this.
- when I have a custom error handler I'm not allowed to use the "nni_" functions, right? (am I right that nni functions are internal only?). so when I have the request-pointer I have no public way to get request informations because all query functions are inside the http-api-header (like get_uri, get_version and so on). here also a bigger refactoring is needed to make more information from the request available to the user of the library (this also affects the normal usage of the library, for example when I want to call different routines inside my (user) http handler based on the uri of the request which currently I can not query).

**Comment by gdamore** [comment]
nni functions are indeed internal use only.

Note that in most cases, only 4XX errors need handling, and I think the customization should be limited to providing a templated HTML body; full dynamic handling of these error pages is likely to be problematic and frankly somewhat less than useful. (If strictly required, javascript can be used in the error page to provide conditional feedback.)

I'm inclined to think that using html/template is probably the way to here.

**Comment by gdamore** [comment]
Lol.  I was looking at *golang* thinking of mangos. 

Still a basic templating language is probably preferable.  Will need to look around for one...

**Comment by gdamore** [comment]
In retrospect, I don't even think templating is needed.  What I think probably *is* desirable is a way to register either a fixed file, or static HTML, on a per-error code basis.  (We could do templating, but really, its too much baggage for too little benefit here.)
