### ISSUE TITLE
Compile error with gcc on cygwin : /usr/include/w32api/winsock2.h:995:34: error: conflicting types for ‘select’

### ISSUE THREAD

**Issue by pederseg** [nanomsg/nng#554]
I've downloaded latest nng (#522) to my win10 installation, using cygwin with cmake 3.62 and gcc7.3
The default cmake compiler and makefiles are cl and nmake, but I used the following commands to make it gcc:

   _mkdir build
   cd build/
...
   \rm -rf *
   export CC=gcc
   cmake -G "Unix Makefiles" -DCMAKE_SYSTEM_NAME=Windows ..
   make

$ cmake -G "Unix Makefiles" -DCMAKE_SYSTEM_NAME=Windows ..
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/gcc.exe
-- Check for working C compiler: /usr/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found UnixCommands: /usr/bin/bash.exe
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Looking for InitializeConditionVariable
-- Looking for InitializeConditionVariable - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for strlcat
-- Looking for strlcat - found
-- Looking for strlcpy
-- Looking for strlcpy - found
-- Looking for strnlen
-- Looking for strnlen - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Building static libs
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gunnar.pedersen/eclipse-workspace/nng/build

gunnar@OSL-36 ~/eclipse-workspace/nng/build
$ make
Scanning dependencies of target nng
[  1%] Building C object src/CMakeFiles/nng.dir/nng.c.obj
[  2%] Building C object src/CMakeFiles/nng.dir/core/aio.c.obj
[  4%] Building C object src/CMakeFiles/nng.dir/core/clock.c.obj
[  5%] Building C object src/CMakeFiles/nng.dir/core/device.c.obj
[  7%] Building C object src/CMakeFiles/nng.dir/core/dialer.c.obj
[  8%] Building C object src/CMakeFiles/nng.dir/core/file.c.obj
[ 10%] Building C object src/CMakeFiles/nng.dir/core/idhash.c.obj
[ 11%] Building C object src/CMakeFiles/nng.dir/core/init.c.obj
[ 12%] Building C object src/CMakeFiles/nng.dir/core/list.c.obj
[ 14%] Building C object src/CMakeFiles/nng.dir/core/listener.c.obj
[ 15%] Building C object src/CMakeFiles/nng.dir/core/message.c.obj
In file included from /usr/include/w32api/winsock2.h:56:0,
                 from /home/gunnar.pedersen/eclipse-workspace/nng/src/platform/windows/win_impl.h:22,
                 from /home/gunnar.pedersen/eclipse-workspace/nng/src/core/platform.h:546,
                 from /home/gunnar.pedersen/eclipse-workspace/nng/src/core/nng_impl.h:27,
                 from /home/gunnar.pedersen/eclipse-workspace/nng/src/core/message.c:14:
/usr/include/w32api/psdk_inc/_fd_types.h:100:2: warning: #warning "fd_set and associated macros have been defined in sys/types.      This can cause runtime problems with W32 sockets" [-Wcpp]
 #warning "fd_set and associated macros have been defined in sys/types.  \
  ^~~~~~~
In file included from /home/gunnar.pedersen/eclipse-workspace/nng/src/platform/windows/win_impl.h:22:0,
                 from /home/gunnar.pedersen/eclipse-workspace/nng/src/core/platform.h:546,
                 from /home/gunnar.pedersen/eclipse-workspace/nng/src/core/nng_impl.h:27,
                 from /home/gunnar.pedersen/eclipse-workspace/nng/src/core/message.c:14:
/usr/include/w32api/winsock2.h:995:34: error: conflicting types for ‘select’
   WINSOCK_API_LINKAGE int WSAAPI select(int nfds,fd_set *readfds,fd_set *writefds,fd_set *exceptfds,const PTIMEVAL timeout);
                                  ^~~~~~
In file included from /usr/include/sys/types.h:68:0,
                 from /usr/include/stdio.h:61,
                 from /home/gunnar.pedersen/eclipse-workspace/nng/src/core/message.c:11:
/usr/include/sys/select.h:62:5: note: previous declaration of ‘select’ was here
 int select __P ((int __n, fd_set *__readfds, fd_set *__writefds,
     ^~~~~~
make[2]: *** [src/CMakeFiles/nng.dir/build.make:314: src/CMakeFiles/nng.dir/core/message.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:177: src/CMakeFiles/nng.dir/all] Error 2
make: *** [Makefile:150: all] Error 2_

I see that others have seen similar problems in other projects, but I was not able to find a solution by searching closed issues or google in general..
Hopefully someone else's eyes see the easy fix here?

thanks in advance

**Comment by gdamore** [comment]
If you read the compiler errors, its clear that your build has conflicting definitions in your system headers.  Your stdio.h appears to be coming from a UNIX style system, as it includes sys/select.h.  That's not a normal Windows header file.  This is brokenness in Windows.

Having said that this reference offers some advice:

https://stackoverflow.com/questions/48031258/mingw64-and-conflicting-declaration-of-c-function-int-select

It would appear that including <stdio.h> before the windows header includes is problematic.  Therefore, what you can try is reordering the #includes in message.c so that nng_impl.h is listed *before* the stdio.h and string.h.

(I find the include of sys/select.h by stdio.h to be really bizarre, but Windows header files are amongst the most broken I've ever encountered, as they are incredibly sensitive to the order that they listed.)

If that works for you, please let me know, and I'll make a real fix for it.

**Comment by pederseg** [comment]
but not 100% there yet - I have some linking problems when trying to compile one of the "getting started" applications. I googled a little but not been able to track down what libraries I'm missing (or if the order of libraries for the linker is correct)

gunnar.pedersen@OSL-820G4-36 ~/eclipse-workspace/magbat/test
$ gcc reqrep.cpp -I../include -o reqrep  -L../3rdParty/lib/Windows_NT/ -lnng -pthread -lWs2_32  -lwsock32 -Wl,--image-base  -Wl,0x10000000
../3rdParty/lib/Windows_NT//libnng.a(win_rand.c.obj):win_rand.c:(.text+0x1a): undefined reference to `rand_s'
../3rdParty/lib/Windows_NT//libnng.a(win_thread.c.obj):win_thread.c:(.text+0x290): undefined reference to `_beginthreadex'
../3rdParty/lib/Windows_NT//libnng.a(win_udp.c.obj):win_udp.c:(.text+0x344): undefined reference to `_malloca'
../3rdParty/lib/Windows_NT//libnng.a(win_udp.c.obj):win_udp.c:(.text+0x427): undefined reference to `_freea'
../3rdParty/lib/Windows_NT//libnng.a(win_udp.c.obj):win_udp.c:(.text+0x543): undefined reference to `_malloca'
../3rdParty/lib/Windows_NT//libnng.a(win_udp.c.obj):win_udp.c:(.text+0x615): undefined reference to `_freea'
../3rdParty/lib/Windows_NT//libnng.a(win_tcp.c.obj):win_tcp.c:(.text+0xca): undefined reference to `_malloca'
../3rdParty/lib/Windows_NT//libnng.a(win_tcp.c.obj):win_tcp.c:(.text+0x170): undefined reference to `_freea'
../3rdParty/lib/Windows_NT//libnng.a(win_tcp.c.obj):win_tcp.c:(.text+0x239): undefined reference to `_freea'
../3rdParty/lib/Windows_NT//libnng.a(win_file.c.obj):win_file.c:(.text+0x4e3): undefined reference to `_snprintf'
../3rdParty/lib/Windows_NT//libnng.a(win_file.c.obj):win_file.c:(.text+0x5a7): undefined reference to `_snprintf'
collect2: error: ld returned 1 exit status

**Comment by gdamore** [comment]
Those look like missing libc stuff -- -lc usually.

You're definitely doing stuff that is outside of the "stock" configuration.  Personally I've found nothing but pain and suffering where cygwin is involved.  Trying to paste-over Windows and turn it into Unix turns into just a giant mess -- this is why we support Windows as a first class system, even though we don't particularly enjoy working on it.
