### ISSUE TITLE
Messages received via subscriber via tcp are comming in short with garbage after first bytes

### ISSUE THREAD

**Issue by DrYSG** [nanomsg/nng#557]
Platform: Windows10 . NNG: latest release.

I am sure you will be calling me an *idiot* for this one. (and I will write it on the blackboard for you). But maybe you can see something obvious. 

I have a simple pub/sub client server. This was working fine when then were on the same node using IPC. I am now using TCP and encoding part of the message with Google FlatBuffers. 

On the outgoing side, I see a properly formatted message (publish). But the subscriber is getting garbage after the first few bytes of the received packet. I suspect my knowledge of NNG_FLAG_ALLOC is faulty, or some other simple error.

Anyway, same code is called either as a server or as a client:

LMB.exe client tcp://10.4.30.239:2018 client1
or
LMB.exe server tcp://10.4.30.239:2018 server

The outgoing data looks like this:
![out](https://user-images.githubusercontent.com/2865368/42110398-f2d7c56a-7bae-11e8-90e8-44ae1bac299c.png)

And the received data looks like this:

![in](https://user-images.githubusercontent.com/2865368/42110404-f5ebdcf0-7bae-11e8-9163-3ca90af4fc2c.png)

The source is very short and simple, and derived from the NNG tutorials. This is the complete source:

```
// LinkWareMessageBus.cpp : Defines the entry point for the console application.
//

#define NNG_STATIC_LIB 

#include "stdafx.h"
#include <Windows.h>
#include <stdio.h>
#include <string.h>
#include <time.h>

#include <nng/nng.h>
#include <nng/protocol/pubsub0/pub.h>
#include <nng/protocol/pubsub0/sub.h>

#include "messages/pntValue_generated.h"

#define SERVER "server"
#define CLIENT "client"

#define channelString "VBS3.Actor1.Position"

struct packetStruct {
	char channel[48];
	char source[32];
	char dateTime[32];
	uint8_t buffer[128];
	int buffSize;
};

void fatal(const char *func, int rv) {
	fprintf(stderr, "%s,%s\n", func, nng_strerror(rv));
}

char* date(void)
{
	struct tm clock;
	__time32_t now;
	char *text = new char[32];
	_time32(&now);   // Get time in seconds.  
	_localtime32_s(&clock, &now);   // Convert time to struct tm form.  
	asctime_s(text, 30, &clock);
	text[strlen(text) - 1] = '\0'; // remove '\n'
	return text;
}

int server(const char *url, const char *name)
{
	nng_socket sock;
	int rv;
	char channelName[] = channelString;
	flatbuffers::FlatBufferBuilder builder(128);
	auto position = PNT::Vec3(4.0, 5.0, 6.0);
	auto description = builder.CreateString("Magnetic Position");
	auto msg = PNT::CreatePseudoGPS(builder, &position, PNT::DeviceType_MAGNAV, description);
	builder.Finish(msg);
	uint8_t *payload = builder.GetBufferPointer();
	int payloadSize = builder.GetSize();


	if ((rv = nng_pub0_open(&sock)) != 0) {
		fatal("nng_pub0_open", rv);
	}
	if ((rv = nng_listen(sock, url, NULL, 0)) < 0) {
		fatal("nng_listen", rv);
	}
	for (;;) {
		char *d = date();
		packetStruct *p = (struct packetStruct*)nng_alloc(sizeof(packetStruct));

		strcpy_s(p->channel, sizeof(p->channel) ,channelName);
		strcpy_s(p->source, sizeof(p->source), name);
		memcpy(p->dateTime, d, strlen(d));
		memcpy(p->buffer, payload, payloadSize);
		p->buffSize = payloadSize;

		printf("SERVER: %s -> PUBLISHING DATE %s Channel: %s\n", p->source, p->dateTime, p->channel);
		if ((rv = nng_send(sock, p, sizeof(p), 0)) != 0) {
			fatal("nng_send", rv);
		}
		Sleep(1000);
		nng_free(p, sizeof(packetStruct));
	}
}

int client(const char *url, const char *name)
{
	nng_socket sock;
	int rv;

	if ((rv = nng_sub0_open(&sock)) != 0) {
		fatal("nng_sub0_open", rv);
	}

	// subscribe to everything (empty means all topics)
	if ((rv = nng_setopt(sock, NNG_OPT_SUB_SUBSCRIBE, "", 0)) != 0) {
		fatal("nng_setopt", rv);
	}
	if ((rv = nng_dial(sock, url, NULL, 0)) != 0) {
		fatal("nng_dial", rv);
	}
	for (;;) {
		char *buf = NULL;
		size_t size;
		if ((rv = nng_recv(sock, &buf, &size , NNG_FLAG_ALLOC)) != 0) {
			fatal("nng_recv", rv);
		}
		packetStruct *packet = (packetStruct *)buf;
		auto channel = packet->channel;
		auto dateTime = packet->dateTime;
		auto source = packet->source;

		auto buffer = packet->buffer;
		auto pkt = PNT::GetPseudoGPS(buffer);
		auto pos = pkt->pos();
		auto x = pos->x();
		auto dType = pkt->deviceType();
		auto desc = pkt->description()->str();

		assert(x == 4);
		assert(dType == PNT::DeviceType_MAGNAV);
		assert(desc == "Magnetic Postion");

		printf("CLIENT (%s): RECEIVED at: %s\n", source, packet->dateTime);
		nng_free(packet, sizeof(packetStruct));
	}
}


int main(const int argc, const char **argv)
{
	if ((argc >= 3) && (strcmp(SERVER, argv[1]) == 0))
		return (server(argv[2], argv[3]));

	if ((argc >= 3) && (strcmp(CLIENT, argv[1]) == 0))
		return (client(argv[2], argv[3]));

	fprintf(stderr, "Usage: pubsub %s|%s <URL> <ARG> ...\n",
		SERVER, CLIENT);
	return 1;
}
```

**Comment by gdamore** [comment]
The answer is in your send logic:

		if ((rv = nng_send(sock, p, sizeof(p), 0)) != 0) {

That should be sizeof (*p), as p is just a pointer.

 - Garrett

**Comment by DrYSG** [comment]
perfect. 

I am writing this on my blackboard:
"I am an idiot, I will check 10x more times before bothering @gdamore "

BTW, I suspect I am also doing something stupid with how on the receive (subscribe) side I am doing the NNG_FLAG_ALLOC for the zero-copy receive, and then doing the nng_free() at the end.

I was doing an explicit nng_alloc()  and followed by the nng_free() at the end which felt more symmetric to me. How should one really do that?

**Comment by DrYSG** [comment]
Thank you. Have a wonderful weekend (and 4th of July).

**Comment by DrYSG** [comment]
Probably a bit of confusion on my part as to the **nng_msg referencing.

		nng_msg *p;
		nng_msg_alloc(&p, sizeof(packetStruct));
		if ((rv = nng_recvmsg(sock, &p, 0)) != 0) {
			fatal("nng_recv", rv);
		}
		packetStruct *packet = (packetStruct *)p;

**Comment by gdamore** [comment]
nng_msg_alloc doesn't give a byte array, but a structure.

You can get the message body with nng_msg_body(p)

Please consider either using our gitter chat, or the nanomsg mailing list, for these questions.  I prefer to use github issues for things that represent a need to make changes in the code (either bugs in nng, or requests for enhancement) (including issues in the docs).

**Comment by gdamore** [comment]
Closing this, there is no bug in our code here.
