### ISSUE TITLE
is there a "connected" event or callback or status?

### ISSUE THREAD

**Issue by xoyojank** [nanomsg/nng#559]
I want to send some requests and do initialization when pairs reconnected, and handle some events when connection lost

**Comment by gdamore** [comment]
Yes, please have a look at nng_pipe_notify().  This function sets a callback that is executed when connections are created or destroyed.

**Comment by gdamore** [comment]
This is just a question, with no actionable changes for nng so I'm closing it.  Please consider using the mailing list or the gitter chat for questions.
