### ISSUE TITLE
kqueue spins hard

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#575]
A user submitted via email a bug report indicating that kqueue was spinning millions of times per second on macOS.  Testing revealed this to be the case:

```
sudo dtrace -n 'syscall:::entry /pid == $target/ {
    @num[probefunc] = count(); 
}' -p 83139

  psynch_cvbroad                    11
  write_nocancel                    11
  psynch_cvsignal                   33
  readv                             34
  psynch_mutexdrop                  39
  psynch_mutexwait                  39
  psynch_cvwait                     44
  kevent                            5004735
```

The problem is that we were never clearing the event, believing EVFILT to be a one shot filter.  Well, this isn't the case.  The solution is to add EVFILT_CLEAR, which auto clears the event on retrieval.

Further analysis also showed we were spinning hard in close on EVFILT_USER, with the same root cause.

**Comment by widdma** [comment]
I was just working on a bug report for this too, glad you got to the bottom of it, Cheers!
