### ISSUE TITLE
IPC listen unlinks UNIX socket on failure

### ISSUE THREAD

**Issue by widdma** [nanomsg/nng#576]
## NNG & Platform details.

Ubuntu 16.04 (but appears to be general POSIX platform bug)
NNG v1.0.0 -- current HEAD (68d117e)

## Expected Behavior

When calling `nng_listen` with an ipc endpoint where another process already listening, I expect the call to fail with NNG_EADDRINUSE and, on POSIX systems, to keep the UNIX socket file intact. 

## Actual Behavior

`nng_listen` fails with NNG_EADDRINUSE and unlinks the UNIX socket.

The error seems to be here:
https://github.com/nanomsg/nng/blob/68d117eb856b42e57cc3e912496d84d7bd8002fd/src/platform/posix/posix_epdesc.c#L182

One solution would be to replace `unlink` with something like `nni_plat_ipc_remove_stale` used in `posix_ipc.c`, but some work is needed to ensure it is called after the endpoint releases the UNIX socket, if it was bound to it.

## Steps to Reproduce

```c
#include <stdlib.h>
#include <stdio.h>
#include <nng/nng.h>
#include <nng/protocol/reqrep0/rep.h>

void fatal(const char *func, int rv) {
	fprintf(stderr, "%s: %s\n", func, nng_strerror(rv));
	exit(1);
}

int main() {
	int rv;
	nng_socket sock;
	nng_msg* msg;

	rv = nng_rep0_open(&sock);
	if (rv != 0) {
		fatal("nng_req0_open", rv);
	}

	rv = nng_listen(sock, "ipc:///tmp/ipcbug.sock", NULL, 0);
	if (rv != 0) {
		fatal("nng_listen", rv);
	}

	for (;;) {
		if ((rv = nng_recvmsg(sock, &msg, 0)) != 0) {
			fatal("nng_recv", rv);
		}
		nng_sendmsg(sock, msg, 0);
	}
}
```

then

```
> ./ipcbug &
> ls /tmp/ipcbug.sock
/tmp/ipcbug.sock
> ./ipcbug
nng_listen: Address in use
> ls /tmp/ipcbug.sock
ls: cannot access '/tmp/ipcbug.sock': No such file or directory
```

**Comment by gdamore** [comment]
Nice catch.  Reading the code, it's clear to me that the cleanup is too aggressive here.  I will fix it.
