### ISSUE TITLE
nng_close stuck indefinitely

### ISSUE THREAD

**Issue by jimmy00784** [nanomsg/nng#590]
nng_close is stuck indefinitely causing the application to hang and not exit.
What do I need to verify to ensure this state can be avoided?

## NNG & Platform details.

nng 1.0.0
Linux karim-inspiron 4.17.5-1-ARCH #1 SMP PREEMPT Sun Jul 8 17:27:31 UTC 2018 x86_64 GNU/Linux 
gcc (GCC) 8.1.1 20180531
cmake version 3.11.4
CMAKE_CXX_FLAGS: -fPIC
CMAKE_C_FLAGS: -fPIC
BUILD_SHARED_LIBS: off

## Expected Behavior
nng_close closes socket and releases all resources

## Actual Behavior
nng_close stuck indefinitely

Here is from the debug trace:
nng-1.0.0/src/core/socket.c nni_sock_shutdown
```
	// Go through the endpoint list, attempting to close them.
	// We might already have a close in progress, in which case
	// we skip past it; it will be removed from another thread.
	nep = nni_list_first(&sock->s_eps);
	while ((ep = nep) != NULL) {
		nep = nni_list_next(&sock->s_eps, nep);

		if (nni_ep_hold(ep) == 0) {
			nni_mtx_unlock(&sock->s_mx);
			nni_ep_close(ep);   // <<<<<<------  here: line 753
			nni_mtx_lock(&sock->s_mx);
		}
	}
```
nng-1.0.0/src/core/endpt.c nni_ep_close
```
	while ((!nni_list_empty(&ep->ep_pipes)) || (ep->ep_refcnt != 1)) {
		nni_cv_wait(&ep->ep_cv);  // <<<<<<------  here: line 287
	}
```
## Steps to Reproduce
Server and client are both async.

Code from the finalizer
```
void SocketClient::disconnectServer()
{
  std::cout << "SocketClient::disconnectServer started" << std::endl;

  nng_ctx_close(m_ctx);
  nng_close(m_socket);
  nng_aio_free(m_aio);

  std::cout << "SocketClient::disconnectServer finished" << std::endl;
}
```

**Comment by gdamore** [comment]
Can you see if this reproduces in the current tree?  I've made some significant changes and in particular I think this change: 953ca274ae57f8edd12536a3dd15d134aa6e5576 should address the problem.  It's also possible that aaec633023a1b3f2c6d24fe697bda4737abe84ee will help.

**Comment by jimmy00784** [comment]
@gdamore 
Still similar behavior with latest from the repo.

src/core/socket.c nni_sock_shutdown
```
	// We have to wait for *both* endpoints and pipes to be
	// removed.
	while ((!nni_list_empty(&sock->s_pipes)) ||
	    (!nni_list_empty(&sock->s_listeners)) ||
	    (!nni_list_empty(&sock->s_dialers))) {
		nni_cv_wait(&sock->s_cv);   //<<<<---- here : line 682
	}
```
I inspected each of the conditions in the while statement. Here is what I found:
![image](https://user-images.githubusercontent.com/1296705/42704843-05f88d3a-8697-11e8-95a5-9a5b253f920d.png)

The s_pipes and s_dialers lists aren't empty.

**Comment by gdamore** [comment]
I would not expect those to be empty per se, but to transition to empty.  Do you have a test program that reproduces this behavior easily?  Also what transport(s) are you using?

**Comment by jimmy00784** [comment]
I don't have a test program at this time. I may be able to spin something over the next couple days.
We am using req-rep protocol over ipc transport.

**Comment by gdamore** [comment]
Both sides NNG?

**Comment by jimmy00784** [comment]
Yes. both sides NNG built against the same version of nng library as well.

**Comment by gdamore** [comment]
The other thing you could do is send me a backtrace of all your threads.   How many active connections do you have? I have a theory that it is possible for us to wind up with a weird dependency in the cleanup that winds up with threads hung waiting for other others to get scheduled, resulting in a livelock.

The other thing I've seen in the past is a case where so many connections are busy that the thread that needs to shut stuff down gets starved.  I thought the reaping work would have addressed that, but if you have a case that demonstrates it, maybe I can better understand the conditions so that we can get a fix.

**Comment by jimmy00784** [comment]
Here are some implementation details that might help provide context.

The server class is designed to handle multiple client connections however this specific implementation of server only accepts a single client connection.

The client class is designed to only make a single connection to the server class.

Both client and server applications are running in separate applications.

The server runs into no such issues and closes the listener and socket successfully.

At the time of client shutdown, client application has 20 active threads out of which  9 were spawned by NNG.

Is there a secure way to provide the backtrace without posting it on Github?

**Comment by gdamore** [comment]
You can send it to me directly.  garrett@damore.org

**Comment by jimmy00784** [comment]
The issue was happening probably due to an implementation issue. Our code implementation had blocking calls in the aio callback which is not allowed as per the NNG AIO documentation.
Closing the issue.
