### ISSUE TITLE
Memory Leaks under Windows

### ISSUE THREAD

**Issue by ziposoft** [nanomsg/nng#611]
Master Revision: ccc24a8e508131a2226474642a038baaa2cbcc8c

`\src\supplemental\websocket.c` line 222

windows will allocate a block with `malloc(0)`. So `wm->buf `needs to freed even if `wm->bufsz==0

So:
```
if (wm->bufsz != 0) 
{
		nni_free(wm->buf, wm->bufsz);
}
```

should be:

```
	if (wm->buf)
	{
		nni_free(wm->buf, wm->bufsz);
	}
```

in '\src\platform\windows\win_io.c' 

`static nni_thr *win_io_thrs;`

Is allocated but never freed. So free it in nni_win_io_sysfini(void)
```
void
nni_win_io_sysfini(void)
{
	int    i;
	HANDLE h;

	if ((h = win_io_h) != NULL) {
		CloseHandle(h);
		win_io_h = NULL;
	}
	for (i = 0; i < win_io_nthr; i++) {
		nni_thr_fini(&win_io_thrs[i]);
	}
	if (win_io_thrs)
		NNI_FREE_STRUCTS(win_io_thrs, win_io_nthr);
}

```

**Comment by gdamore** [comment]
Thanks.  The fact that malloc(0) returns a non-NULL pointer is surprising to me, to say the least.  I'll verify and fix.

**Comment by ziposoft** [comment]
Thank you!

I'll let you know if I run into any others. I am using windows memory leak debugging which spits out memory leaks with source file/line numbers on process termination. 

Enable this at start up:

```
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
	_CrtSetReportMode(_CRT_WARN, _CRTDBG_MODE_FILE | _CRTDBG_MODE_DEBUG);
	_CrtSetReportFile(_CRT_WARN, _CRTDBG_FILE_STDOUT);
```

And I had to do this as a hack to get the appropriate line #s.

```
#define nni_zalloc(_X_) calloc(1, _X_)
#define nni_alloc(_X_) malloc( _X_)
```

**Comment by gdamore** [comment]
So I've taken a different approach with this, to prevent future confusion.   As most platforms malloc(0) returns NULL, I've changed my platform specific allocation code to treat an empty allocation as returning NULL (and I've made free ignore if the size is zero).

**Comment by firthm01** [comment]
> in '\src\platform\windows\win_io.c'
> 
> `static nni_thr *win_io_thrs;`
> 
> Is allocated but never freed. So free it in nni_win_io_sysfini(void)
> 
> ```
> void
> nni_win_io_sysfini(void)
> {
> 	int    i;
> 	HANDLE h;
> 
> 	if ((h = win_io_h) != NULL) {
> 		CloseHandle(h);
> 		win_io_h = NULL;
> 	}
> 	for (i = 0; i < win_io_nthr; i++) {
> 		nni_thr_fini(&win_io_thrs[i]);
> 	}
> 	if (win_io_thrs)
> 		NNI_FREE_STRUCTS(win_io_thrs, win_io_nthr);
> }
> ```

I've been trying to trace a troublesome leak which seems to come down to this same issue. I'm on commit 7b6e73f23104a50b898da1065cf9d3bf8b6a3bca .
Surely this part of the bug still exists? `nni_thr_fini` frees allocations pointed to by `nni_thr` struct members, but the allocations for the structs themselves remain (unless I've missed something.) This change fixes that. Seems to clear up the memory leak I was having.

**Comment by gdamore** [comment]
Good catch.   Probably doesn't need the conditional though.
