### ISSUE TITLE
demo/raw needs updating to use raw socket constructor

### ISSUE THREAD

**Issue by cwzx** [nanomsg/nng#612]
The raw socket demo uses nng_rep0_open() followed by setopt to enable RAW.
This no longer works and should now be nng_rep0_open_raw().

https://github.com/nanomsg/nng/blob/ccc24a8e508131a2226474642a038baaa2cbcc8c/demo/raw/raw.c#L138-L145

**Comment by gdamore** [comment]
Ah, thanks!  I'll fix it shortly.
