### ISSUE TITLE
tests/tls and tests/wssfile fail the "Valid verify works" test in v1.0.0+

### ISSUE THREAD

**Issue by mzipay** [nanomsg/nng#634]
This is a failed attempt to build nng (tag v1.0.1) with TLS support against static mbedtls (tag mbedtls-2.12.0).

First, the relevant details:

Platform (Fedora 27):
```
$ uname -a
Linux ******** 4.17.11-100.fc27.x86_64 #1 SMP Mon Jul 30 15:22:33 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

NNG version (1.0.1):
```
$ cd $HOME/.local/src/nng
$ git status
HEAD detached at v1.0.1
```

mbedTLS version (2.12.0):
```
$ cd $HOME/.local/src/mbedtls
$ git status
HEAD detached at mbedtls-2.12.0
```

Both builds complete successfully (I used CMake).  The mbedTLS test suite completes successfully (100% pass).  The nng test suite fails the _tests/tls_ and _tests/wssfile_ tests.

I repeated the nng build using both the master branch and the v1.0.0 tag; same result (_tests/tls_ and _tests/wssfile_ fail).

I then assumed that this might be due to a change in mbedTLS, so I attempted to build and test nng v1.0.1 against mbedtls-2.11.0, mbedtls-2.7.4 and mbedtls-2.1.13 (the three mbedtls releases that most recently predate nng's 05-Jul-2018 1.0.1 release). Again, the same result (all mbedtls tests pass; nng's _tests/tls_ and _tests/wssfile_ fail).

Here are the specific failures:

```
$ ./tests/tls
Failures:

  * Assertion Failed (Valid verify works)
  File: $HOME/.local/src/nng/tests/tls.c
  Line: 267
  Test: nng_dialer_start(d, 0) == 0

FAIL    ./tests/tls                                            1.478s
```

```
$ ./tests/wssfile

Failures:

  * Assertion Failed (Valid verify works)
  File: $HOME/.local/src/nng/tests/wssfile.c
  Line: 269
  Test: nng_dialer_start(d, 0) == 0
 
FAIL    ./tests/wssfile                                        1.886s
```

**Comment by mzipay** [comment]
Now I see the comment at the top of _tests/tls.c_ and _tests/wssfile.c_ where the test cert is generated for CN=localhost.

The "Valid verify works" cases in both suites bind the listener to the wildcard domain:

From tests/tls.c:
```
451                 trantest_next_address(addr, "tls+tcp://*:%u");                 
452                 So(nng_listener_create(&l, s1, addr) == 0);
```

From tests/wssfile.c:
```
374                 trantest_next_address(addr, "wss://:%u/test");                 
375                 So(nng_listener_create(&l, s1, addr) == 0);
```

If I change these to bind specifically to "localhost", both tests pass.

I'm not sure whether this should be the "full" fix, though.  I would assume that the listener binding to wildcard would give the cert with CN=localhost as long as the client connects specifically **to** localhost (which is what the tests do). Maybe that's a bad assumption, though...

In any case, I think this should be enough to pinpoint the bug in either nng or mbedtls.  For now I'll open a PR with the above change made so that the current tests pass.

**Comment by gdamore** [comment]
As I indicated in the closed PR, the problem is that the URL needs to use an IPv4 specific scheme, because of the inconsistencies in the way some systems handle AF_UNSPEC sockets.

**Comment by mzipay** [comment]
The "tls+tcp4:" scheme approach does resolve the issue for the tests/tls.c "Valid verify works" test. I can open a new PR with only that change, or I can also add a change to fix the still-failing tests/wssfile.c "Valid verify works" test as well if there is a similar IPv4-explicit change that can be made.

**Comment by gdamore** [comment]
I don't think the wss scheme has the same feature.  Probably we should add
it.  But I would be fine with just disabling the wildcard test there for
now.

**Comment by mzipay** [comment]
I opened PR #677 with the tests/tls.c change only. I'll leave how to deal with tests/wssfile.c to your judgment (I will not be using WebSockets, and now that I understand the nature of the issue, I am fine just avoiding that test case).
