### ISSUE TITLE
Is it possible to add function to publish message to a specific topic?

### ISSUE THREAD

**Issue by bwlee** [nanomsg/nng#706]
## NNG & Platform details.
V1.0.1 the latest 
Linux Ubuntu with C programming language

## Expected Behavior
I want to public many messages with different topics from a publish server, which has some clients but one maybe only interested in one or more topics, actually all clients received messages on all topics.

## Actual Behavior
As in demo,  the empty string means all topics, so changed the code as below:
```
  // subscribe to `SomeTopic`
  // if ((rv = nng_setopt(receiver, NNG_OPT_SUB_SUBSCRIBE, "SomeTopic", 0)) != 0) {
  //   logger->error("nng_setopt: {}", nng_strerror(rv));
  // }
```
So changed this to some specified string, but there is no way to publish message and set its topic, so 
could you tell where to find such example code? 

Thanks !

**Comment by gdamore** [comment]
The topic is just the first bytes of the body of the message.  So if the
topic is ABC then this will match all messages where the first three bytes
are ABC.

**Comment by gdamore** [comment]
@bwlee  Did this answer your question?

**Comment by gdamore** [comment]
I'm going to go ahead and close this, since I answered it.

**Comment by nicwainwright** [comment]
Hey there, struggling to attempt this 'topic' implementation for pub/sub as well. Following your instructions to make the first n-bytes of the msg body to be the topic (similar to the instructions for plain nng i found [here](https://stackoverflow.com/questions/70578194/nanomsg-pub-sub-with-multiple-subscribers-using-binary-msg-and-topic-name)) I am unable to receive the messages.

My client/server setup DOES work when just subscribing to ALL messages using `{}` as the opt for SUB_SUBSCRIBE, so I know that this 'topic1' addition is breaking the receive

My server looks like this (note: i commented the relevant line where I attempt to add "topic1" as the publisher topic:
```
// include nngpp
#include <nngpp/nngpp.h>
#include <nngpp/platform/platform.h>

// includes for publish subscribe
#include <nngpp/protocol/pub0.h>
#include <nngpp/protocol/sub0.h>

// sys includes
#include <cstdio>
#include <iostream>
#include <memory>
#include <pthread.h>

int main() try {
    setbuf(stdout, NULL);
    printf("start\n");

    nng::socket pub_socket = nng::pub::open();
    pub_socket.listen("tcp://localhost:8001");

    while(1) {
        try {
            printf("pub data\n");

            // attempting to set publish topic "topic1" here
            pub_socket.send("topic1BATTERY");
        }
        catch(const nng::exception& e) {
            printf( "FAILED... %s: %s\n", e.who(), e.what() );
        }
        nng::msleep(1000);
    }

    printf("end");

} catch(const nng::exception& e) {
    printf( "FAILED... %s: %s\n", e.who(), e.what() );
    return 1;
}
```

And my client code looks like this (also commented where I attempt to subscribe to "topic1" :
```
// include nngpp
#include <nngpp/nngpp.h>
#include <nngpp/platform/platform.h>

// includes for publish subscribe
#include <nngpp/protocol/pub0.h>
#include <nngpp/protocol/sub0.h>

// sys includes
#include <cstdio>
#include <iostream>
#include <memory>
#include <pthread.h>

int main() try {
    setbuf(stdout, NULL);
    printf("start client\n");

    nng::socket sub_socket = nng::sub::open();

    // attempting to set subscribe topic to "topic1" instead of "{}" which would receive all msg
    sub_socket.set_opt(NNG_OPT_SUB_SUBSCRIBE, "topic1");

    sub_socket.dial("tcp://localhost:8001");
    while(1) {
        printf("recv message start... ");
        try {
            // sub_socket.dial("tcp://localhost:8001");
            nng::buffer msg = sub_socket.recv(NNG_FLAG_NONBLOCK | NNG_FLAG_ALLOC);
            printf("recv message: %s\n", (char*)msg.data());
        }
        catch(const nng::exception& e) {
            printf( "FAILED... %s: %s\n", e.who(), e.what() );
        }
        nng::msleep(1000);
    }

    printf("end\n");

} catch(const nng::exception& e) {
    printf( "FAILED... %s: %s\n", e.who(), e.what() );
    return 1;
}
```

**Comment by nicwainwright** [comment]
> Hey there, struggling to attempt this 'topic' implementation for pub/sub as well. Following your instructions to make the first n-bytes of the msg body to be the topic (similar to the instructions for plain nng i found [here](https://stackoverflow.com/questions/70578194/nanomsg-pub-sub-with-multiple-subscribers-using-binary-msg-and-topic-name)) I am unable to receive the messages.
> 
> My client/server setup DOES work when just subscribing to ALL messages using `{}` as the opt for SUB_SUBSCRIBE, so I know that this 'topic1' addition is breaking the receive
> 
> My server looks like this (note: i commented the relevant line where I attempt to add "topic1" as the publisher topic:
> 
> ```c++
> // include nngpp
> #include <nngpp/nngpp.h>
> #include <nngpp/platform/platform.h>
> 
> // includes for publish subscribe
> #include <nngpp/protocol/pub0.h>
> #include <nngpp/protocol/sub0.h>
> 
> // sys includes
> #include <cstdio>
> #include <iostream>
> #include <memory>
> #include <pthread.h>
> 
> int main() try {
>     setbuf(stdout, NULL);
>     printf("start\n");
> 
>     nng::socket pub_socket = nng::pub::open();
>     pub_socket.listen("tcp://localhost:8001");
> 
>     while(1) {
>         try {
>             printf("pub data\n");
> 
>             // attempting to set publish topic "topic1" here
>             pub_socket.send("topic1BATTERY");
>         }
>         catch(const nng::exception& e) {
>             printf( "FAILED... %s: %s\n", e.who(), e.what() );
>         }
>         nng::msleep(1000);
>     }
> 
>     printf("end");
> 
> } catch(const nng::exception& e) {
>     printf( "FAILED... %s: %s\n", e.who(), e.what() );
>     return 1;
> }
> ```
> 
> And my client code looks like this (also commented where I attempt to subscribe to "topic1" :
> 
> ```c++
> // include nngpp
> #include <nngpp/nngpp.h>
> #include <nngpp/platform/platform.h>
> 
> // includes for publish subscribe
> #include <nngpp/protocol/pub0.h>
> #include <nngpp/protocol/sub0.h>
> 
> // sys includes
> #include <cstdio>
> #include <iostream>
> #include <memory>
> #include <pthread.h>
> 
> int main() try {
>     setbuf(stdout, NULL);
>     printf("start client\n");
> 
>     nng::socket sub_socket = nng::sub::open();
> 
>     // attempting to set subscribe topic to "topic1" instead of "{}" which would receive all msg
>     sub_socket.set_opt(NNG_OPT_SUB_SUBSCRIBE, "topic1");
> 
>     sub_socket.dial("tcp://localhost:8001");
>     while(1) {
>         printf("recv message start... ");
>         try {
>             nng::buffer msg = sub_socket.recv(NNG_FLAG_NONBLOCK | NNG_FLAG_ALLOC);
>             printf("recv message: %s\n", (char*)msg.data());
>         }
>         catch(const nng::exception& e) {
>             printf( "FAILED... %s: %s\n", e.who(), e.what() );
>         }
>         nng::msleep(1000);
>     }
> 
>     printf("end\n");
> 
> } catch(const nng::exception& e) {
>     printf( "FAILED... %s: %s\n", e.who(), e.what() );
>     return 1;
> }
> ```
> 
> Lemme know if there's something obvious here I am missing. Thanks
> 
> Here's the comparison. In the first running of the subscriber, we are subscribed to all messages with `{}` and can see the message output. In the second run, we are attempting to subscribe to `topic1` and see no output since the rcv buffer grabs nothing. ![image](https://user-images.githubusercontent.com/40005273/229904335-be55a4b1-c24a-4cb7-a258-302b7f130e49.png)

opened issue [#1656] to create a new thread on this

**Comment by gdamore** [comment]
You need to inject a NUL byte (\0) after the "topic1".  Recall in C that strings have NUL terminating characters.
