### ISSUE TITLE
API to increase max receive size

### ISSUE THREAD

**Issue by lkesteloot** [nanomsg/nng#726]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

master (0863d12e2)

The `core/socket.c` file sets the max receive size to 1 MB:

    s->s_rcvmaxsz  = 1024 * 1024; // 1 MB by default

Messages longer than this silently fail. I was sending a 1.2 MB image and it took a long time to track down this problem! It would be great if (1) something failed somewhere, and (2) there were an API to change this limit, in case we want to send/receive larger messages. If (2) is not possible, then (3) make this limit available through the API so I can break larger messages into pieces myself.

I'm happy to make the change if you'll give me a few-sentence direction on how you'd do it.

**Comment by gdamore** [comment]
There is already an option for this.  See the nng_options manual page.  I
think it is called NNG_OPT_RECVMAXSZ or some such.

**Comment by lkesteloot** [comment]
You're right! Sorry, I didn't follow the code's logic carefully enough. To anyone who finds this bug later, this is how I set the value:

    if ((rv = nng_req0_open(&sock)) != 0) {
        fatal("nng_socket", rv);
    }
    if ((rv = nng_setopt_size(sock, NNG_OPT_RECVMAXSZ, 20*1024*1024)) != 0) {
        fatal("nng_setopt_size", rv);
    }
    if ((rv = nng_listen(sock, url, NULL, 0)) != 0) {
        fatal("nng_listen", rv);
    }
