### ISSUE TITLE
Invalid URL reports NNG_EINVAL instead of NNG_EADDRINVAL

### ISSUE THREAD

**Issue by neachdainn** [nanomsg/nng#731]
## NNG & Platform details.

Running nng v1.0.1 on an up-to-date Arch Linux (Linux 4.18.6 x86_64). Bug was originally found in Rust calling into C but can be reproduced in pure C.

## Expected Behavior

Passing "tcp:://127.0.0.1:5555" to `nng_listen` and `nng_dial` should return `NNG_EADDRINVAL`.

## Actual Behavior

`NNG_EINVAL` is returned instead.

## Steps to Reproduce

Pass the incorrectly formatted URL to the function. A minimal test program follows:

```c
#include <stdio.h>
#include <stdlib.h>
#include <nng/nng.h>
#include <nng/protocol/reqrep0/rep.h>

void fatal(const char* func, int rv)
{
	fprintf(stderr, "%s: (%d) %s\n", func, rv, nng_strerror(rv));
	exit(1);
}

int main(int argc, char** argv)
{
	nng_socket sock;
	int rv;

	if((rv = nng_rep0_open(&sock)) != 0) {
		fatal("nng_rep0_open", rv);
	}

	if((rv = nng_listen(sock, "tpc:://127.0.0.1:5555", NULL, 0)) != 0) {
		fatal("nng_listen", rv);
	}

	return 0;
}
```

**Comment by neachdainn** [comment]
Looking through `nni_url_parse`, it appears that all errors in parsing return an `NNG_EINVAL` without a single instance of `NNG_EADDRINVAL`. It seems to me that the fix is easy as either replacing all instances of `EINVAL` with `EADDRINVAL` or to update the documentation to correctly reflect which error code is returned.

I'm willing to submit a pull request for either solution if I am told which one is better.

**Comment by gdamore** [comment]
I don’t think we should change nng_url_parse() — that is a public API and
(via nng_url_parse()) and so it has a documented return code of NNG_EINVAL.

I’d be open to *either*:

a) Updating the docs for dial and listen to indicate that NNG_EINVAL is a
possible error for an invalid (unparseable) URL
b) Updating the implementation of nni_dialer_create() and
nni_listener_create() to convert NNG_EINVAL coming from nni_url_parse to
NNG_EADDRINVAL.

Frankly, “a” seems the lower risk, simpler, and possibly the better of the
two.

 - Garrett

**Comment by neachdainn** [comment]
I have an example that I could email you if you wish but it isn't available in a public repository at this moment. That being said, I am currently working on a Rust wrapper [here](https://gitlab.com/neachdainn/nng-rs/tree/2-nng-wrapper) and I have contacted the person who owns the `nng` names on Crates.io. He has agreed to transfer the `nng` and `nng-sys` names to me.

As for the native library, I don't think there is a need. The build requirements for `nng` are so few that I've just been building and linking it to my crates as part of a build script. At some point in the future I would like to create a native Rust library since there are a few parts of `nng` that aren't Rust level of thread-safe. However, that is probably something I wont attempt for a while.

**Comment by ChristopherRabotin** [comment]
Awesome, thanks plenty! I'll follow these developments closely, and maybe
contribute if you're interested and time allows.

**Comment by neachdainn** [comment]
I forgot I can attach files to these comments.
[rtdl.zip](https://github.com/nanomsg/nng/files/2470201/rtdl.zip)
