### ISSUE TITLE
Documentation needs to update

### ISSUE THREAD

**Issue by QXSoftware** [nanomsg/nng#743]
Hi~

The documentation at 
[libnng.3.html](https://nanomsg.github.io/nng/man/v1.0.0/libnng.3.html) needs to update, there are some typos exist, for example the [http](https://nanomsg.github.io/nng/man/v1.0.0/libnng.3.html#_http_support) part.

**Comment by gdamore** [comment]
Please check the "tip" docs, which have fixes that are not present in the 1.0 release.

**Comment by QXSoftware** [comment]
> Please check the "tip" docs, which have fixes that are not present in the 1.0 release.

Thanks~
