### ISSUE TITLE
atomics may be faster than locks

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#78]
There are a number of situations (reference counts, etc.) where perhaps we could use atomics instead of locks.  This may help reduce contention and increase performance.  In some of these cases (like bumping a reference count), we don't even care about the final result.

**Comment by Crest** [comment]
In FreeBSD kernel there is a special type of counter for write mostly counters. Each logical core maintains its own counter and the reader has to add all counters. The same could be done for POSIX threads by putting the counters in thread local storage. Of course that approach won't work for atomic reference counters, but it allows updating lots counters quite often without suffering from cache contention.

**Comment by gdamore** [comment]
So counters like this for stats -- aggregated ones -- don't use or need locks, or even atomics, most of the time, because they are already accessed under other locks.

I'm more interested in atomics for use in reference counters.

**Comment by gdamore** [comment]
I've started to use atomic reference counters, and have seen some nice performance gains.  Also the pollables now use atomics. 

I'm going to close this because it doesn't really address anything specifically actionable.  I do think we will continue to reduce heavy weight locks with atomics and lock-free algorithms -- but we'll call those out on a case by case basis.
