### ISSUE TITLE
travis-ci cmake fails with `No VERSION specified...`

### ISSUE THREAD

**Issue by jeikabu** [nanomsg/nng#780]
Just to be clear, this isn't a bug per-se.

NNG v1.1.0-rc builds fine in the following environments:
- Win10 cmake 3.9.2 and 3.11.2
- Ubuntu 18.04.1 cmake 3.10.2 and 3.11.4
- Appveyor "VS 2017" cmake 3.12.2
- OSX 10.14 cmake 3.12.1

But it fails in:
- Ubuntu 14.04 cmake 3.9.2 (travis)
- OSX 10.13 cmake 3.11.4 (also travis...)

My travis builds were fine with NNG v1.0.1, but now the branch with v1.1.0-rc fails with:
```
--- stdout
running: "cmake" "/home/travis/build/jeikabu/runng/runng-sys/nng" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DNNG_TESTS=OFF" "-DNNG_TOOLS=OFF" "-DCMAKE_INSTALL_PREFIX=/home/travis/build/jeikabu/runng/target/debug/build/runng-sys-dfce1d0359a9a74c/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++"
-- Building static libs
-- Configuring incomplete, errors occurred!
See also "/home/travis/build/jeikabu/runng/target/debug/build/runng-sys-dfce1d0359a9a74c/out/build/CMakeFiles/CMakeOutput.log".
See also "/home/travis/build/jeikabu/runng/target/debug/build/runng-sys-dfce1d0359a9a74c/out/build/CMakeFiles/CMakeError.log".
--- stderr
CMake Error at /home/travis/build/jeikabu/runng/cmake-3.11.4-Linux-x86_64/share/cmake-3.11/Modules/WriteBasicConfigVersionFile.cmake:40 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /home/travis/build/jeikabu/runng/cmake-3.11.4-Linux-x86_64/share/cmake-3.11/Modules/CMakePackageConfigHelpers.cmake:209 (write_basic_config_version_file)
  src/CMakeLists.txt:295 (write_basic_package_version_file)
```

I tried installing cmake 3.11.4 to no avail.
Don't really expect you to do anything.  Just curious if you have any idea what cmake changes might do this since I'm out of guesses.

**Comment by jeikabu** [comment]
Actually, I just realized it says what the problem is, I just didn't recognize what I was looking at.

src/CMakeLists.txt:
```
write_basic_package_version_file("${version_config}"
    VERSION ${NNG_PACKAGE_VERSION}
    COMPATIBILITY SameMajorVersion
)
```

CMakeLists.txt:
```
if (DEFINED ENV{TRAVIS_TAG})
    set (NNG_PACKAGE_VERSION "$ENV{TRAVIS_TAG}")
```

**Comment by jeikabu** [comment]
`if (ENV{TRAVIS_TAG})` seems to work, but I'm no cmake expert.  It looks like you're not using travis anymore, so can probably just remove it.

**Comment by gdamore** [comment]
good idea.  yeah i can remove that. :)

thanks for reporting this.
