### ISSUE TITLE
can nng work with external event loops (libevent, libev based system) ? 

### ISSUE THREAD

**Issue by Fedora7** [nanomsg/nng#786]
We try to integrate nng with existing system with external event loops (libevent, libev based system). That will require expose internal socket file descriptor (OS level) to external select/poll.  What will be the right way to do it ?   We found nn_getsockopt with NN_RCVFD / NN_SNDFD but this API is in compatible mode for legacy support only. Thanks.

**Comment by Fedora7** [comment]
Does the the file descriptor from nng_getopt( NNG_OPT_RECVFD ) notify the beginning of any receiving data ? or the receive of a complete message ? 

My concern: If it will notify any part of the receiving message, and I received the first couple bytes of message, my nng_recv() might block the whole even loop for a long time if the message sender having problem to send the rest of message due to process crash or network problem.

2nd question:  After calling nng_dial and nng_getopt(s1, NNG_OPT_RECVFD, &fd, &sz) == 0) to get the notification fd, The value of notification fd won't change until I call nng_close(), correct ?  Should I calling nng_getopt(s1, NNG_OPT_RECVFD, &fd, &sz) to get a new fd after every socket reconnect ? Thanks

**Comment by gdamore** [comment]
Receive notifications occur when an entire message is ready for receive. The work to gather an entire message from the network occurs in the background.  (Note that this is responsible for a very small additional latency, as we have to use a thread context switch to notify the receive is ready for handling, but that's the only way we can avoid the application from having to worry about this.

The notification fd is the same for the socket, and in fact if you call the nng_getopt() on the same socket you will get the same file descriptor!  This file descriptor is held open for the duration of the socket.  When you call nng_close the notification file descriptor will also be closed for you.

**Comment by gdamore** [comment]
Closing this... I think I answered your question.
