### ISSUE TITLE
Very slow PAIR performance compared to nanomsg

### ISSUE THREAD

**Issue by dgl72** [nanomsg/nng#808]
Throughput performance measured with embedded local_thr and remote_thr show 40 times slower performance compared to nanomsg! 
nanomsg: > 600.000 msg/sec
nng:         15.000 msg/sec

**Comment by gdamore** [comment]
This is a very poor result.

I am aware that NNG can be slower than nanomsg for some configurations.  On my mac for example, nanomsg achieves about 105Kmsgs/sec, but NNG only gets about 32K msgs/sec.  But that is only a 3x difference.   There remains performance work to do.

Having said that, a 40x difference is totally unexpected.

Can you provide both details on the platform you are using, and what command line arguments you are using?  I'd like to see if I can reproduce your result, and hopefully track this down.

**Comment by dgl72** [comment]
Yes, I have tested on an Ubuntu 18.10 VM with 4 vCPU and 4 GB RAM with:

./local_thr tcp://127.0.0.1:5555 64 100000
./remote_thr tcp://127.0.0.1:5555 64 100000

**Comment by dgl72** [comment]
Yet another test on DELL PowerEdge R320, with Intel Xeon E5 2403 v2, 4 GB RAM, Ubuntu Server 18.04
nng: ca. 28.000 msg / sec
nanomsg: ca 320.000 msg / sec

**Comment by gdamore** [comment]
got it.  i will take a look at this. its possible that some tuning changes can help. normally with such small messages you are not concerned with throughput but rather latency.

i will do some more testing but it might be a day or two.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dgl72** [comment]
Hi Garret,
did you find anything belong slow performance?

**Comment by gdamore** [comment]
I'm continuing to work on this now, along with other changes.  Stay tuned.

**Comment by gdamore** [comment]
Not super conclusive, but using WSL (I've switched to a Microsoft Surface Book 2), I obtain about 30K msgs/sec for NNG, and about 62K msgs/secs for libnanomsg.

**Comment by gdamore** [comment]
Well this is rather interesting... using the *native* Windows code, legacy libnanomsg only achieves about 26K msgs/sec.  The newer libnng outperforms a bit, getting about 31K msgs/sec.

I think I need to look hard at the POSIX aio scheduler.

**Comment by gdamore** [comment]
Its also interesting that the Windows TCP code seems to underperform the Linux code, even when running on the same kernel and hardware!

**Comment by gdamore** [comment]
Looking at stuff in more detail, I've become convinced that the biggest offender here is the message queue code.  I've a plan to mostly gut that.

**Comment by gdamore** [comment]
For pair v1 this is now done.  I'll probably close this and open a separate one for v0.

**Comment by gdamore** [comment]
I'm going to defer this to 1.4 -- we're going to switch the pair code, but it's not something I want to hold the 1.3 release for.
