### ISSUE TITLE
Can not recvie msg header

### ISSUE THREAD

**Issue by linuxsky** [nanomsg/nng#816]
hi,
   when i used code ,i can not recive msg header corect 

```
#include <stdio.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <nng/nng.h>
#include <nng/protocol/pair1/pair.h>
#include <nng/supplemental/util/platform.h>

#define SECOND(x) ((x) *1000)
#define MILLISECOND(x) (x)

#define APPENDSTR(m, s) nng_msg_append(m, s, strlen(s))
#define CHECKSTR(m, s)                   \
    So(nng_msg_len(m) == strlen(s)); \
    So(memcmp(nng_msg_body(m), s, strlen(s)) == 0)

int main(int argc, char const *argv[])
{
    const char * templ = "inproc://sky_test";
    char         addr[NNG_MAXADDRLEN + 1];
    nng_socket   s1 = NNG_SOCKET_INITIALIZER;
    nng_socket   c1 = NNG_SOCKET_INITIALIZER;
    nng_socket   c2 = NNG_SOCKET_INITIALIZER;
    nng_duration tmo;
    uint32_t     v;
    size_t       sz;
    nng_msg *msg;
    int ret = 0;

    memset(addr, '\0', sizeof(addr));
    sprintf(addr, templ, strlen(templ));

    nng_pair1_open_raw(&s1);
    nng_pair1_open_raw(&c1);
    nng_socket_id(s1);

    tmo = MILLISECOND(3000);
    nng_setopt_ms(s1, NNG_OPT_RECVTIMEO, tmo);
    nng_setopt_ms(c1, NNG_OPT_RECVTIMEO, tmo);

    nng_listen(s1, addr, NULL, 0);
    nng_dial(c1, addr, NULL, 0);

    nng_msleep(20);

    nng_msg_alloc(&msg, 0);

    APPENDSTR(msg, "ALPHA");
    nng_msg_header_append_u32(msg, 0x5a5a5a5a);
    ret = nng_sendmsg(c1, msg, 0);

    nng_recvmsg(s1, &msg, 0);
    nng_msg_header_chop_u32(msg, &ret);
    printf("msg header(%d) is:0x%x\n", nng_msg_header_len(msg), ret);
    printf("msg body is:%s\n", nng_msg_body(msg));

    nng_msg_free(msg);

    nng_close(s1);
    nng_close(c1);

    /* code */
    return 0;
}
```

**Comment by gdamore** [comment]
The header is generally reserved for application specific purposes.  Pair protocol does not use this at all.   (Some of the protocols will use the header to include protocol-specific details.)  You can only send data in the message body.

**Comment by linuxsky** [comment]
> The header is generally reserved for application specific purposes. Pair protocol does not use this at all. (Some of the protocols will use the header to include protocol-specific details.) You can only send data in the message body.

thx .
by the way , does nng have a poll or epoll interface for wait event ?

**Comment by gdamore** [comment]
Yes.  There are multiple different APIs available for this.

In general I recommend using the nng_aio_* API to make a callback based API.  This is the most performant option available.

If however you need to integrate into an existing epoll() or poll() event loop, you can ask NNG for a file descriptor suitable for this using nng_getopt_int() -- two options exist:

1. NNG_OPT_SENDFD -- this obtains a file descriptor that will be readable when the socket can accept a message for sending.

2. NNG_OPT_RECVFD -- this obtains a file descriptor that will be readable when the socket has a message available for receiving.

You should never write to the file descriptor returned by either of these options.  Nor should you close it.  This is a notification descriptor exclusively.

**Comment by gdamore** [comment]
I think I've answered the questions.  Please also know that you can use either our gitter chat or the nanomsg mailing list to ask questions.
