### ISSUE TITLE
demo/rest  does not work

### ISSUE THREAD

**Issue by linuxsky** [nanomsg/nng#817]
demo/rest does not work well

when send req ,can not recv rep form server

**Comment by gdamore** [comment]
I've confirmed this, and verified that the code in the server which changed to automatically grab the client supplied data "broke" the old API.

The good news is that the new API is actually easier to use, as the server will collect all the client data automatically as part of the request, unless you go out of your way to ask it not to.

The demo application just needs to be updated.

**Comment by gdamore** [comment]
To be clear, it was the fix for #738 that broke the demo.
