### ISSUE TITLE
Accessing ws transport headers when using device forwarder! 

### ISSUE THREAD

**Issue by afshin2003** [nanomsg/nng#818]
Hi,
I'm thinking about a scenario in which we forward incoming messages from a ws/req socket to the tcp/rep one. I need to verify the **Authorization** header of the connection (or incoming messages ?) to make sure that the client has been authenticated or not. It's been stated in ws transport that the request headers can be accessed from the associated pipe (how?). In case of forwarding messages by a device how it can be achieved?

Best,
Afshin

**Comment by gdamore** [comment]
So the option you want to get at is NNG_OPT_WS_REQUEST_HEADERS, which gives you the client's headers as a single string; lines will be separated by newlines, so you'll have to parse out the individual bits.

In the future there will be a better way to do this, with more direct programmatic API access to the headers, but I've not exposed that yet.  In the meantime, the method I just described should work, and will continue to work for the future.

To get that option, you'll use something like:

nng_msg_get_pipe() - to get the pipe from the message
nng_pipe_getopt_string() - to get the specific string of headers

I hope that helps!

**Comment by gdamore** [comment]
I believe I've answered your question.  Feel free to ask more questions on either our gitter chat or the mailing list.  Thanks.
