### ISSUE TITLE
MSVC2015  nng-1.1.1  cmake only win32 project, not x64 project 

### ISSUE THREAD

**Issue by 363568233** [nanomsg/nng#828]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.
windows7 nng-1.1.1  MSVC2015

## Expected Behavior
cmake can generate x64 project

## Actual Behavior
only win32 project

## Steps to Reproduce
compile result:  35 projects success, 29 projects failed

**Comment by 363568233** [comment]
Oh, I forgot the cmake-gui should configure the MSVC 32-bit or 64-bit. Thanks.

**Comment by gdamore** [comment]
Ok, I'm closing this then.
