### ISSUE TITLE
Feature Request: Setup and teardown functions for nng spawned threads

### ISSUE THREAD

**Issue by athei** [nanomsg/nng#855]
I am using [userspace rcu](http://liburcu.org/) in an application that also uses nng async. This requires some per-thread setup and teardown code.

Is is possible to add functionality to nng_aio_alloc where I can supply two callbacks which are executed on either thread setup or thread teardown?

**Comment by gdamore** [comment]
It seems like this should happen in the platform code.  Normally that's where threads are created and torn down.  Can you send me links to documentation on the APIs needed?

**Comment by athei** [comment]
I am not sure if I understand you correctly. Do you mean the APIs I need to call per thread because I am using urcu? That's gonna be rcu_register_thread() and rcu_unregister_thread(): 
https://github.com/urcu/userspace-rcu/blob/master/doc/rcu-api.md
But it can be different depending on which features you use.

**Comment by gdamore** [comment]
There are multiple versions of the RCU apis, and some have registration functions, and some don't.  Arguably you could stash the fact that an initialization has been done (or not) on thread-local storage, although I don't think I have offered a public API for accessing that either.

I want to think about the best way to do this, as additional APIs like this increase the cognitive load on users, and the documentation burden.

I wonder if it makes sense to make the threading API itself pluggable.

**Comment by athei** [comment]
Currently I am using the mentioned thread-local approach to call the initialise functions. What I currently cannot do is calling the cleanup function as I do not know when nng removes threads. 

This is not a big issue for me right now. But it could be depending on the situation. I just return from main() on exit and thats it. I don't see any function where I could wait for the nng spawned threads to join.

**Comment by gdamore** [comment]
Generally, NNG does not destroy threads until process exit or the library is terminated with nng_fini().  We use fixed size thread pools for the things we need concurrency for.

**Comment by athei** [comment]
Is nng_fini() part of the public API. I could not find it here: https://nanomsg.github.io/nng/man/v1.1.0/index.html

Should I call this before returning from the main thread?

**Comment by gdamore** [comment]
I'm not sure I've ever documented it.  nng_fini() is intended to facilitate cleanup that most applications shouldn't need -- but it may be useful if you're using NNG in a shared library form and intend to unload the shared library (unusual!).  More typically, this is something you'd want to call using atexit() to clean up resources when using a leak checker -- otherwise a leak checker may complain about some of the global resources that NNG normally holds forever.

**Comment by gdamore** [comment]
I'm gonna close this.  As indicated, nng never terminates it's own threads except as a complete part of library shut down. 

Users who need more custom stuff should consider just forking and modifying the platform layer directly.  In the future, we might permit the library to be initialized with replacement functions, but that's not likely to happen in the near time without some stronger use case.
