### ISSUE TITLE
Nng-rust repo

### ISSUE THREAD

**Issue by jeikabu** [nanomsg/nng#866]
We're [discussing unifying](https://github.com/jeikabu/runng/issues/29) Rust bingings to NNG. One point was moving it to the nanomsg org.

Looks like pynng is already there, so I'd assume you're open to the idea.

**Comment by codypiersall** [comment]
I'm not aware of pynng being under the nanomsg org, although I am interested in that happening one day.  Unless we're talking about different `pynng`? I don't want to derail the discussion for the Rust bindings, just a point of clarification.

**Comment by jeikabu** [comment]
I had to check again, I guess it was __nnpy__ I saw.  I'm imagining letters that aren't there, nevermind....

**Comment by gdamore** [comment]
There's nothing here for the NNG repo.   Send me email if you want me to set something up in the nanomsg.org however.
