### ISSUE TITLE
nng_http_handler_set_tree fails match if path is "/" 

### ISSUE THREAD

**Issue by jimmy00784** [nanomsg/nng#869]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

nng v1.1.0
Arch Linux 64bit
C++ 

## Expected Behavior
nng_http_handler_alloc with "/" and nng_http_handler_set_tree should allow dynamic path resolution.  

## Actual Behavior
nng_http_handler_alloc with "/" and nng_http_handler_set_tree only seems to resolve "/". Anything else results in a 404 status 
If nng_http_handler_alloc is setup with, for example, "/test", then "/test/this" and "/test/that" are handled successfully. But if nng_http_handler_alloc is setup with "/", then only "/" is handled and "/this", and "/that" result in 404 status.

## Steps to Reproduce
void rest_handle(nng_aio *aio) definition excluded for brevity.
```
int main()
{
  cout << "Hello World!" << endl;
  nng_http_server * server;
  nng_http_handler * handler;
  nng_url * url;

  char rest_addr[128] = "http://127.0.0.1:8888";
  int rv = 0;

  if((rv = nng_url_parse(&url,rest_addr)) != 0)
  {
    cout << "nng_url_parse error:" << rv << endl;
    return 1;
  }

  if((rv = nng_http_server_hold(&server,url)) != 0)
  {
    cout << "nng_http_server_hold error:" << rv << endl;
    return 1;
  }

  if((rv = nng_http_handler_alloc(&handler,"/", rest_handle)) != 0)
  {
    cout << "nng_http_handler_alloc error:" << rv << endl;
    return 1;
  }

  if((rv = nng_http_handler_set_method(handler, "GET")) != 0)
  {
    cout << "nng_http_handler_set_method error:" << rv << endl;
    return 1;
  }

  if((rv = nng_http_handler_set_tree(handler)) != 0)
  {
    cout << "nng_http_handler_set_tree error:" << rv << endl;
    return 1;
  }

  if((rv = nng_http_server_add_handler(server,handler)) != 0)
  {
    cout << "nng_http_server_add_handler error:" << rv << endl;
    return 1;
  }

  if((rv = nng_http_server_start(server)) != 0)
  {
    cout << "nng_http_server_start error:" << rv << endl;
    return 1;
  }

  while(true);
  nng_url_free(url);

  return 0;
}
```

**Comment by gdamore** [comment]
One possible idea, is to try setting the handler to "" instead of "/".  I suspect that the fact that "/" is kind of a special case may be to blame here.

**Comment by gdamore** [comment]
So internally we need to treat "/" like "", but we should report it as "/" for external consumers.
