### ISSUE TITLE
How to get socket fd to use with nn_setsockopt and nn_getsockopt 

### ISSUE THREAD

**Issue by vikramkarandikar** [nanomsg/nng#874]
NNG version : 1.1.0

If we have to set socket options (like manipulate rcv/ send buffer) then how can we get hold of the socket fd created using one of the *_open NNG API?

I feel this approach is not good as this has to be done every time peer reconnects. Instead is there a option to achieve same thing through nng_setopt? NNG_OPT_RECVBUF and NNG_OPT_SENDBUF work at message level, i was looking for something which is at byte level.

**Comment by gdamore** [comment]
There is no way to tune the TCP sockets directly, or to get access to the underlying file descriptor.  This is fairly intentional, as the file descriptor(s) can change over time, as NNG manages the underlying connections (there can be *many* such connects per NNG socket), and as not every system uses file descriptors.

I might be convinced to add some kind of underlying socket options for this sort of thing (we have them for TCP nodelay, for example), but really would want to see a compelling use case.  I've rarely found tuning the system provided TCP buffers to be useful.

**Comment by gdamore** [comment]
(If you're just looking for byte based flow control, that's a different matter entirely.  I can see that we might do that for managing the *NNG* queuing, although ultimately NNG has to make the decision at message boundaries, as messages are considered atomic in NNG.)

**Comment by vikramkarandikar** [comment]
Is it possible to know what value is being used for send/ recv buffer? Is the default configured on system or some caluculated value?

**Comment by gdamore** [comment]
Unfortunately, no.  We use whatever the system default is.

**Comment by reqshark** [comment]
what about the old compat functions in [`src/compat/nanomsg/nn.c`](https://github.com/nanomsg/nng/blob/master/src/compat/nanomsg/nn.c#L1080-L1113)?

We used to be able to pass in `*valp` pointer with `NN_SOL_SOCKET` level either `NN_RCVFD` `NN_SNDFD` flags for "opt/type." That worked to get back a descriptor... or at least whatever integer process space thought

```c
if (nn_getsockopt(s, NN_SOL_SOCKET, fdtype, &fd, &fdsz) != 0)
  return -1;                     // fdtype would be like SENDFD/RECVFD flags
return fd;
```

**Comment by gdamore** [comment]
You do get back a file descriptor.  But it isn't a TCP file descriptor at all.  (Except on Windows, where it *has* to be for odd reasons.)  Even with old legacy nanomsg the descriptor was not related to the actual TCP connection, but was used for notifications using a named pipe or similar.

**Comment by reqshark** [comment]
> Even with old legacy nanomsg the descriptor was not related to the actual TCP connection

lol so it's just a coincidence that `node-nanosmg` works for all my distributed TCP send and recv?

polling and selecting that fd is how we've always done this in node.js. maybe we're using an old enough version of upstream that it happens to still work?

```cc
nn_getsockopt(s, NN_SOL_SOCKET, is_sender ? NN_SNDFD : NN_RCVFD, &sockfd, &siz);
if (sockfd != 0) {
  uv_poll_init_socket(uv_default_loop(), &poll_handle, sockfd);
  uv_poll_start(&poll_handle, UV_READABLE, NanomsgReadable);
```

we're calling `nn_getsockopt` and passing the returned fd straight to libuv for event polling in node:

https://github.com/nickdesaulniers/node-nanomsg/blob/master/src/poll_ctx.cc#L16-L24

**Comment by reqshark** [comment]
we're on an older pre-1.0 version of nanomsg so that's probably why.

although we never updated the build to cmake nanomsg, I'm doing some testing this week on building node bindings using cmake...

a couple people were asking about nng bindings in node-nanomsg

**Comment by gdamore** [comment]
Even with pre-1.0, the descriptor obtained by that socket option had nothing to do with the actual TCP socket used for data.  Sorry.

**Comment by reqshark** [comment]
hmm sounds inefficient.

So you're saying `nn_recv` reads from file or something curated by another operation writing to that from the TCP socket?

**Comment by codypiersall** [comment]
@reqshark the file descriptor you were getting was associated with the nng_socket (or nanomsg socket), not the underlying tcp (or whatever transport) socket. It is created internally by nng with [eventfd](http://man7.org/linux/man-pages/man2/eventfd.2.html) or something similar. You can poll that file descriptor, but not read or write to it. I think the equivalent nng option you want is called `NNG_OPT_RECVFD`.

**Comment by reqshark** [comment]
ahh that makes sense. Thanks for clarifying @codypiersall!

**Comment by gdamore** [comment]
For the record, as using that eventfd implies several extra system calls, its generally better to *not* use it if you don't need to.  With NNG the aio callback mechanism is quite a bit lighter.  (Unfortunately, if you have to integrate into an existing poll() or similarly driven event loop, you will still need the eventfd.)

**Comment by gdamore** [comment]
At the moment, there is nothing further actionable on this, so I'm closing it.

I am open the idea of a request to tune the send and receive buffering though.  But that would be a separate request.

**Comment by HustacYB** [comment]
In our company CI/CD server , a ut with nanmsg TCP publish server get following error, but  occasionally
[error] [General]300000: Fault. Address already in use: tcp://127.0.0.1:15555
 
 I check with nanomsg source code ,I found within NN_SOL_SOCKET type ,no socket option of SO_REUSEADDR, But I find it's set in transport layer in function nn_usock_bind,  Didn't it come into effect ？  Is there any interface that I can set SO_REUSEADDR socket option ? Thanks , looking forward to your reply !
