### ISSUE TITLE
Bus protocol stops accepting new connections

### ISSUE THREAD

**Issue by rizickus** [nanomsg/nng#885]
Hi,
At first thanks for this amazing library! Great job! However I have some unexpected issues with the bus protocol over the TCP.

## NNG & Platform details.

NNG 1.1.1.
Windows 10.

## Expected Behavior

Bus stops accepting new connections when a new client connects and disconnects immediately without sending any data.

## Actual Behavior

I expect to accept new clients.

## Steps to Reproduce
1. Start simple bus application to listen for the specific TCP port:
```
    if ((rv = nng_bus0_open(&socket)) != 0) {
        LOG(ERROR) << "nng_bus0_open failed" << ": " << nng_strerror(rv);
        return false;
    }
...
        std::string listenEndpoint = "tcp://*:" + port;
        if ((rv = nng_listen(socket, listenEndpoint.c_str(), NULL, NNG_FLAG_NONBLOCK)) != 0) {
            LOG(ERROR) << "nng_listen failed for " << listenEndpoint << ": " << nng_strerror(rv);
            return false;
        }
```
2. Use any raw TCP client to connect and disconnect immediately without sending any data.
3. Try to use BUS client to connect. Connections will fail.

Have you ever seen similar behavior? Or do you have any ideas how I can recover from that state?

**Comment by jake-ruyi** [comment]
Sounds similar to #848

**Comment by gdamore** [comment]
Yes, I think its probably the same problem, and unrelated to the "protocol" but rather to the initial handshake logic.

**Comment by gdamore** [comment]
I'm actually going to close this as a dup of 848 for now.  I'm completely convinced its the same root problem.
