### ISSUE TITLE
Options docs proposal

### ISSUE THREAD

**Issue by jake-ruyi** [nanomsg/nng#887]
Two things.

First, sometimes options are enumerated in multiple man pages.  E.g.:
- `nng_tcp_options.5.adoc`
- `nng_tcp.5.adoc`
- `nng_tcp.7.adoc`

It would be easier to keep things correct with respect to header files if there was only one listing (in `nng_tcp_options.5.adoc`) and any other locations link back to it.

Second, for similar reasons, keeping identifiers and descriptions in the same order as in header files.  I already did this in [a PR](https://github.com/nanomsg/nng/pull/886/files#diff-eb84102bc7d4c6e6901eb9e56bfe1004).  But there's some cases where an order different from the header file might be more aesthetically pleasing.  For example `NNG_OPT_IPC_SECURITY_DESCRIPTOR` is the first IPC-related option in `nng.h`, but I happen to find:
```c
#define NNG_OPT_IPC_PEER_GID            "ipc:peer-gid"
#define NNG_OPT_IPC_PEER_PID            "ipc:peer-pid"
#define NNG_OPT_IPC_PEER_UID            "ipc:peer-uid"
#define NNG_OPT_IPC_PEER_ZONEID         "ipc:peer-zoneid"
#define NNG_OPT_IPC_PERMISSIONS         "ipc:permissions"
#define NNG_OPT_IPC_SECURITY_DESCRIPTOR "ipc:security-descriptor"
```
vaguely more appealing than:
```c
#define NNG_OPT_IPC_SECURITY_DESCRIPTOR "ipc:security-descriptor"
#define NNG_OPT_IPC_PEER_GID            "ipc:peer-gid"
#define NNG_OPT_IPC_PEER_PID            "ipc:peer-pid"
#define NNG_OPT_IPC_PEER_UID            "ipc:peer-uid"
#define NNG_OPT_IPC_PEER_ZONEID         "ipc:peer-zoneid"
#define NNG_OPT_IPC_PERMISSIONS         "ipc:permissions"
```
I was inclined to change the header file since it would also alphabetize defines, but wasn't sure it you have any druthers about the ordering in header files, the appearance of man pages, etc.

**Comment by gdamore** [comment]
I originally did not want to have a simple link back, as there may be multiple contexts where a given option is valid, and you may need that context specific information to use the option properly.  Of course that thinking predates my nng_stream work, so maybe its clearer and better now.

I'm kind of ambivalent about alpha sorting the options in the headers.   If it bothers you, I'd be willing to accept a PR.

**Comment by jake-ruyi** [comment]
Ok, thanks for the feedback
