### ISSUE TITLE
undefined reference to `nng_inproc_register()'

### ISSUE THREAD

**Issue by LaG1924** [nanomsg/nng#896]
## NNG & Platform details.
NNG v1.1.1
`Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019`
`gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)`
## Expected Behavior
My program compiles.
## Actual Behavior
ld gives `undefined reference to 'nng_inproc_register()'`
## Steps to Reproduce
Use `nng_inproc_register` in C++ code without `extern "C"`

Minimal repro:
```c++
#include <nng/nng.h>
#include <nng/transport/inproc/inproc.h>

int main() {
	nng_inproc_register();
	return 0;
}

```
paste it to `nng_test.cpp` and `gcc nng_test.cpp -o nng_test -lnng -lpthread`

*I just looked `/include/` dir and saw that `external "C"` is present for everything except `/include/transport/`. Why?*

**Comment by gdamore** [comment]
It was an oversight.  Having said that, you really don't need to explicitly call that function -- the transport is built in and does not need to be registered.
