### ISSUE TITLE
pipe events and read events

### ISSUE THREAD

**Issue by vikramkarandikar** [nanomsg/nng#898]
NNG Version : 1.1.0
Platform: CentOS Linux release 7.4.1708

Questions:
- if there are multiple dialers connecting to a polymorous listener then are the pipe notify events (nng_pipe_notify) delivered in multiple separate threads?
- if above is yes, is it same for ADD and REM events?
- Is there a possibility of combining this with libevent integration somehow?
- is it possible to explicitly document the behavior in the documentation?

This would help single threaded applications to have no locking done in application and only have single libevent main thread do all the work.

**Comment by gdamore** [comment]
There are zero guarantees about what thread or threads pipe notifications come in on, and I have no plans to change that.  (In fact, I believe the events actually arrive on different threads, because of the way our completions for aio work.)

**Comment by gdamore** [comment]
There's nothing more for me to do on this, so closing it.
