### ISSUE TITLE
Stream get/set functions naming consistency

### ISSUE THREAD

**Issue by jake-ruyi** [nanomsg/nng#901]
## NNG & Platform details.
HEAD

## Expected/Actual Behavior
The `nng_stream` family of get/set methods have a few differences from the rest of the API:
- should be `getopt`/`setopt`
- `_addr` should be `_sockaddr` (this is __not__ fixed in the PR)

It's a little annoying when automagically generating things to have to deal with special cases (e.g. `get`/`opt` instead of `getopt`/`setopt` like everywhere else).

**Comment by gdamore** [comment]
As  I commented in your PR, I'd rather resolve this the other way way around, where the newer shorter API versions become the preferred, and we add "legacy" bindings for the longer names.  If you want to pick this up, I'd be grateful.  Otherwise I'll get to it later.

**Comment by jake-ruyi** [comment]
I suspected that was a possibility. I'll update the PR accordingly.
