### ISSUE TITLE
Does the websocket mode server support normal client connections?

### ISSUE THREAD

**Issue by qtcdxxyuc** [nanomsg/nng#908]
## NNG & Platform details.

- `version`:`1.1.1`
- `system`:`ubuntu 18.04 LTS`
- `language`:`C`

## Expected Behavior

I don't know if the result I got is right.

-  `Pair` mode do not supports `aio` asynchronous operation.
-  `Server` in `websocket` mode  do not support `normal client` connections.
    - If it does not support, can I have a way to support its?

## Actual Behavior

Can not open aio context with pair.

`Normal Client`can not connect `server`. 

## Steps to Reproduce

```c++
//web socket server
TEST(nng,wsServer){

    int rv;
    constexpr const char* url = "ws://0.0.0.0:50051";
    nng_socket socket;
    if(rv = nng_pair0_open(&socket);rv !=0){
        LOG(FATAL)<<"pair open error";
    }

    if(rv =nng_listen(socket,url, nullptr,0);rv != 0){
        LOG(FATAL)<<"server listen error";
    }

    char *buf = nullptr;
    size_t size;

    if (rv = nng_recv(socket, &buf, &size, NNG_FLAG_ALLOC);rv != 0) {
        LOG(FATAL)<<"recv error: "<<nng_strerror(rv);
    }

    LOG(INFO)<<"server get with client: "<<buf;

    std::string str(buf,size);
    str  = "server get recv:" + str;

    LOG(INFO)<<"server send to client: "<<str;

    if (rv = nng_send(socket, const_cast<char*>(str.c_str()), str.size()+1, 0);rv != 0) {
        LOG(FATAL)<<"send error: "<<nng_strerror(rv);
    }

    nng_free(buf, size);

}

//web socket client
TEST(nng,wsClient){
    int rv;
    constexpr const char* url = "ws://0.0.0.0:50051";
    nng_socket socket;
    if(rv = nng_pair0_open(&socket);rv !=0){
        LOG(FATAL)<<"pair open error";
    }

    if(rv =nng_dial(socket,url, nullptr,0);rv != 0){
        LOG(FATAL)<<"client dial error";
    }

    std::string str("i am ws Client");

    LOG(INFO)<<"client send to server: "<<str;

    if (rv = nng_send(socket, const_cast<char*>(str.c_str()), str.size()+1, 0);rv != 0) {
        LOG(FATAL)<<"send error: "<<nng_strerror(rv);
    }

    char *buf = nullptr;
    size_t size;

    if (rv = nng_recv(socket, &buf, &size, NNG_FLAG_ALLOC);rv != 0) {
        LOG(FATAL)<<"recv error: "<<nng_strerror(rv);
    }

    LOG(INFO)<<"server recv to client: "<<buf;

    nng_free(buf, size);

}
```

When this service is running:

- If it is a `nng-client` connection: Sending and receiving are true.

  - > Client

    ```c
    I0312 11:30:41.682714 25758 test7.cpp:74] client send to server: i am ws Client
    I0312 11:30:41.687430 25758 test7.cpp:87] server recv to client: server get recv:i am ws Client
    ```

  - > Server

    ```c
    I0312 11:30:41.682893 25008 test7.cpp:44] server get with client: i am ws Client
    I0312 11:30:41.682930 25008 test7.cpp:49] server send to client: server get recv:i am ws Client 
    ```

- If it is a `normal-client` connection:  Unable to connect.

  - > Client	

    ```c
    Waiting for the server to shake hands...
    Disconnect from the server!
    ```

  - > Server

    ```c
    Blocked in nng_recv
    ```

**Comment by gdamore** [comment]
You can use AIO APIs. (nng_send_aio, nng_recv_aio) with any NNG protocol.  Pair0 does not support *contexts*, but contexts are an extra feature in addition to the aio APIs.

I'm not sure what you mean by "normal client".

There are at least three different layers here.

1. TCP. 
2. WebSocket
3. NNG/Pair0

When using NNG/Pair0 mode sockets, you cannot connect non-nanomsg/NNG clients to them.  There is protocol layer stuff (message framing) that may be present, and which any remote client would need to adhere to.  (There are ways to mix and match, but they require an understanding of the SP layer messaging details, and the ability to explicitly deal with websocket messaging framing as well.  This is discouraged!)

If you want to  communicate using vanilla websockets, you can look at the new nng_stream API for ws:// URLs.  The same works with vanilla TCP, using tcp:// URLs.


Let me know if that didn't answer your question.

**Comment by qtcdxxyuc** [comment]
Thank you.I have solved the problem.

- I use aio to bring asynchronous operations.

- I think the normal client is js or web client instead of a  nng client.

  -  it is Native websocket,not  Vanilla websockets.

- In fact, I have been able to connect to the server in `pair0` mode .

  - > javascript

    ```javascript
    const WebSocket = require('ws');
    const ws = new WebSocket('ws://192.168.3.66:50051/','pair.sp.nanomsg.org');
    //set Sub protocol is pair.sp.nanomsg.org
    ```

  - When I do this, the server can receive information from the client.

  - I want to build a `websocket` service using `nng`, which can be accessed directly in the browser.

    - If allowed, I want to use `aio`'s mode to control the `websocket` instead of the advanced mode such as the `pair` provided by `nng`.
    - I use websocket to distribute the video, and I hope I can get it directly from my browser.

**Comment by gdamore** [comment]
Glad to hear you got it sorted out.  Check out nng_stream in the new (not yet tagged) code in NNG.  It will give you direct access to ws streams.
