### ISSUE TITLE
nng IPC unable to reach the limit

### ISSUE THREAD

**Issue by qtcdxxyuc** [nanomsg/nng#912]
## NNG & Platform details

- `NNG`:`1.1.1`
- `OS`:`ubuntu 18.04 LTS`
- `builder`:`gcc 7.3`
- `CPU`:`Intel i5-7400 @3.00GHz`
- `memory`:`8GB`
- `memory speed`: test by `mbw`
  - `MEMCPY`:`4781.486 MiB/s`
    - Random memory size allocation
  - `DUMB`:`8022.463 MiB/s`
    - I dont know what this.
  - `MCBLOCK`:`9657.170 MiB/s` 
    - Fixed memory size allocation

---

#  Expected Behavior

`IPC` communication speed should be approximate to `MCBLOCK`.

`Nng` single thread performance is weaker than `nn`.

`Nng` multithreading performance is stronger than `nn`;

---

# Actual Behavior

In my test(send `1MB`block),result is:

|    library    |     speed(GB/s)     |
| :-----------: | :-----------------: |
|      NN       |         7.5         |
|      NNG      |         2.7         |
| NNG(3threads) | `ONE`:0.6 `ALL`:1.8 |
|    system     |         9.6         |

From the results, NNG seems to have a performance limit(about `2.5G/s`).His performance is not as good as `NN`.Actually,I also tested on other machines.It seems that the speed of single-threaded `nng` is half of `MEMCPY`.Multi-threaded bandwidth is slightly lower than single thread.Multithreading does not bring performance improvements.

---

# Steps to Reproduce

I will give my test code.Forgive me, I only use `std::thread` to open threads.

> NN.cpp

```c++
char buf[1024 * 1024] = {};

std::thread t1([&]{
    const size_t itr = 1024 * 12;
    int socket = nn_socket(AF_SP, NN_PUSH);
    int opt = 6 * 1024 * 1024;
    nn_setsockopt(socket, NN_SOL_SOCKET, NN_SNDBUF, &opt, sizeof(opt));
    nn_bind(socket, "ipc:///tmp/sss");
    //This is just a timer
    folly::AutoTimer<> tmr;
    for (size_t i = 0; i < itr; i++) {
    	int bytes = nn_send(socket, buf, sizeof(buf), 0);
        CHECK_EQ(bytes, sizeof(buf));
    }
    //Output time spent
    tmr.log("finish ", folly::prettyPrint(itr * sizeof(buf), folly::PRETTY_BYTES));
});

std::thread t2([&]{
    int socket = nn_socket(AF_SP, NN_PULL);
    nn_connect(socket, "ipc:///tmp/sss");
    int opt = 1024 * 1024 * 6;
    nn_setsockopt(socket, NN_SOL_SOCKET, NN_RCVBUF, &opt, sizeof(opt));
    void* msg = nullptr;
    while (true) {
    	int bytes = nn_recv(socket, &msg, NN_MSG, 0);
    	nn_freemsg(msg);
    }
});
t1.join();
t2.join();

//result: 
//finish 12 GB in 1.566 s 
//speed: 7.7GB/s
```

> NNG.cpp

```c++
constexpr const char *url = "ipc:///tmp/sss";

std::thread t1([]() {
    nng_socket sock;

    nng_pull0_open(&sock);
    nng_setopt_size(sock, NNG_OPT_RECVMAXSZ, 0);
    nng_listen(sock, url, nullptr, 0);

    size_t sz = 1024 * 1024 * 1024;
    char *buf = new char[sz];
    for (;;) {
        size_t mutable_sz = sz;
        nng_recv(sock, buf, &mutable_sz, 0);
    }
});

//Control thread count
for(int i=0;i<1;i++){
    std::thread t([i]() {
        nng_socket sock;
        size_t sz;
        char *buf = nullptr;

        nng_push0_open(&sock);
        nng_setopt_size(sock, NNG_OPT_RECVMAXSZ, 0);

        //wait for server started
        sleep(1);

        nng_dial(sock, url, nullptr, 0);

        int size = 1024 * 1024;
        buf = new char[size];
        memset(buf, 'a', size);

        while (true) {
            //Output time spent
            folly::AutoTimer timer(std::to_string(i)+" send 1G");
            int frequency = 1024 * 1024 * 1024 / size;
            for (int i = 0; i < frequency; i++) {
                nng_send(sock, buf, size, 0);
            }
        }
        nng_close(sock);
    });
    t.detach();
}

t1.join();

//Single thread result: 
//0 send 1G in 337.2 ms 
//speed: 2.96GB/s	 
//
//Multithreading(3) result: 
//1 send 1G in 1.644 s 
//2 send 1G in 1.648 s
//0 send 1G in 1.65 s 
//speed: ONE: 0.6 GB/s ALL:1.8GB/s
```

---

# Other

I am going to use `nng` to transfer some image data in `IPC`.Image size is generally around `6MB`.No special requirements for `IOPS`.So I care about the performance of this size.

**Comment by gdamore** [comment]
So you're using the least efficient form of nng_send and nng_recv, which extra requires that messages be copied.  Please change your test to make use of nng_sendmsg and nng_recvmsg, which will avoid data copies at both send and receive time.  This should have a quite noticeable impact.

**Comment by qtcdxxyuc** [comment]
## new test


> new_NNG.cpp

```c++
constexpr const char *url = "ipc:///tmp/sss";

    std::thread t1([]() {
        nng_socket sock;
        nng_msg* msg;

        nng_pull0_open(&sock);
        nng_setopt_size(sock, NNG_OPT_RECVMAXSZ, 0);
        nng_listen(sock, url, nullptr, 0);

        for (;;) {
            nng_recvmsg(sock,&msg,0);
            nng_msg_free(msg);
        }
    });

    for(int i=0;i<1;i++){
        std::thread t([i]() {
            nng_socket sock;
            nng_msg* msg;

            nng_push0_open(&sock);
            nng_setopt_size(sock, NNG_OPT_RECVMAXSZ, 0);

            //wait for server started
            sleep(1);

            nng_dial(sock, url, nullptr, 0);

            int size = 1024 * 1024;
            char* buf = new char[size];
            memset(buf,'a',size);
            while (true) {
                //Output time spent
                folly::AutoTimer timer(std::to_string(i)+" send 1G");
                int frequency = 1024 * 1024 * 1024 / size;
                for (int i = 0; i < frequency; i++) {
                    nng_msg_alloc(&msg,size);
                    nng_msg_clear(msg);
                    nng_msg_append(msg,buf,size);
                    nng_sendmsg(sock,msg,0);
                }
            }
            nng_close(sock);
        });
        t.detach();
    }

    t1.join();
//Single thread result: 
//0 send 1G in 214.1 ms 
//speed: 4.6GB/s	 
//
//Multithreading(3) result: 
//1 send 1G in 1.174 s 
//2 send 1G in 1.188 s
//0 send 1G in 1.181 s 
//speed: ONE: 0.9 GB/s ALL:2.7 GB/s
```

This seems to improve performance by about `1/3`.

This still has a problem. It seems that `multithreading` does not have stronger performance than single thread.

I remember that you said that `nng` is not as good as `nn` on a single thread, so can it improve performance through multithreading?

---

## other

I have a service that needs to distribute data to the client as much as possible. So what mode should I use `NNG`? 

- Which `protocols`?
- much `sockets`?
- Multithreading or much `aio`  in `fibers`(running in one thread)?

**Comment by gdamore** [comment]
You're still copying a lot of data.  The idea is that you allocate the message and work directly into it.  What instead you're doing is allocating a send buffer, *and* the message, writing to your scratch buffer, then *copying* the data to the message.  Try eliminating all that writing of the message buffer -- you don't need to clear the message and append to it -- just allocate it at the size you want, and then try sending it verbatim.  Otherwise you're measuring copy performance in your application!

Having said all that, for very large message sizes (like 1MB), the issue becomes data copies, as all the nng or nanomsg (nn) overhead becomes in the noise.  This only becomes more true as the message size increases.

Where things get more exciting is when you use smaller message sizes, so the differences in how the library can scale out, and the overheads of nanomsg/NNG overheads become more measurable.

**Comment by qtcdxxyuc** [comment]
## test

Is this correct to use?

```c++
nng_msg* msg = nullptr;
int size = 1024 * 1024;
char* buf = new char[size];
memset(buf,'a',size);
//-------------------------------------
nng_msg_alloc(&msg,size);
memcpy(nng_msg_body(msg),buf,size);
nng_sendmsg(sock,msg,0);
```

## other

As you said, large chunks of data are mainly limited to `memcpy`, I will consider improving machine performance.

If you have time, can you provide some general examples for everyone. I am now guessing how to use `NNG` through `API-doc` and `test`, which may be misleading.`Examples` does not give too much information.

Thank you for your answer.

**Comment by gdamore** [comment]
Instead of writing into buf, then copying it directly into the message with memcpy, why not write directly to the message instead.  For performance testing I generally discourage doing any of that, since you really want to measure how fast NNG moves messages, not how fast you can move data to and from NNG.  (The most efficient way to use the data associated with the message buffers directly if you can.  That is how "zero copy" works.)

**Comment by qtcdxxyuc** [comment]
Thank you, I know how to use it.

**Comment by qtcdxxyuc** [comment]
Thank you, I know how to use it.

**Comment by gdamore** [comment]
So can we close this then?
