### ISSUE TITLE
websocket stream mode should support TEXT

### ISSUE THREAD

**Issue by afshin2003** [nanomsg/nng#914]
## NNG & Platform details.

Debian 8.11
Compiler GNU 4.9.2
NNG master

## Expected Behavior
A websocket connection from browser then wait for receiving some bytes. 

## Actual Behavior

The connection is established successfully. The stream is up till browser sends some bytes. The aio receive operation ends with error code 7.

## Steps to Reproduce

nng_stream_set  NNG_OPT_TCP_NODELAY
nng_stream_set NNG_OPT_TCP_KEEPALIVE
nng_aio_alloc 
malloc memory allocation for iov buffer
nng_aio_set_iov
nng_stream_recv

**Comment by afshin2003** [comment]
Update!
It turned out that text protocol is not supported yet!  Switched to binary mode :)

**Comment by gdamore** [comment]
Oh yeah, I should probably allow text mode to be set for non-SP streams.  (SP requires binary data, so I forced this -- but when we generalized the library I failed to account for this requirement.)

I'm relabeling the issue so I remember what this is about. :-)

**Comment by gdamore** [comment]
I'm moving this to 1.4.  Only because I don't want to hold the 1.3 release for it.

**Comment by robiwano** [comment]
> Update!
> It turned out that text protocol is not supported yet! Switched to binary mode :)

May I ask how you switched to binary mode?

**Comment by robiwano** [comment]
I'm trying to do exactly this, and get the same exact result with different websocket test clients. Is binary mode set on the client or the server side?

**Comment by robiwano** [comment]
Ok, so it's a client side thingy. Hmm... I can probably work with this.
