### ISSUE TITLE
Memory Leak in pub

### ISSUE THREAD

**Issue by elbarto1980** [nanomsg/nng#915]
As I intend to use nng in my project, I ran Valgrind on the "server side" of reqrep demo (commit f723fa9655e1e7fadc1a15b94b66de674ab9fe17). It found several "possibly lost" and "still reachable" bytes.
I ran "valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes ./reqrep server tcp://192.168.0.10:1234"
I am attaching the LEAK SUMMARY:

==5876== LEAK SUMMARY:
==5876==    definitely lost: 0 bytes in 0 blocks
==5876==    indirectly lost: 0 bytes in 0 blocks
==5876==      possibly lost: 6,952 bytes in 30 blocks
==5876==    still reachable: 19,298 bytes in 77 blocks
==5876==         suppressed: 0 bytes in 0 blocks

Is it normal? Running Valgrind on the pub/sub example from the Getting Started page, the output is even worse:

==8180== LEAK SUMMARY:
==8180==    definitely lost: 208 bytes in 2 blocks
==8180==    indirectly lost: 306 bytes in 4 blocks
==8180==      possibly lost: 7,032 bytes in 31 blocks
==8180==    still reachable: 4,240 bytes in 12 blocks
==8180==         suppressed: 0 bytes in 0 blocks

Could you please shed some light on this outcome?
Thank you.

**Comment by codypiersall** [comment]
Are you calling [`nng_fini`](https://github.com/nanomsg/nng/blob/master/include/nng/nng.h#L180-L189?)  This should be called whenever doing memory profiling.

**Comment by elbarto1980** [comment]
Thank you @codypiersall . I changed the for-loop in the server block [here](https://nanomsg.org/gettingstarted/nng/pubsub.html) to run 20 times and then added [nng_close](https://github.com/nanomsg/nng/blob/master/include/nng/nng.h#L180-L189?) and [nng_fini](https://github.com/nanomsg/nng/blob/master/include/nng/nng.h#L191-L194?) after the loop. 
The Valgrind output is better now (the "possibly lost" and the "still reachable" bytes are gone) but the "definitely lost" and the "indirectly lost" are still there:

==18752== LEAK SUMMARY:
==18752==    definitely lost: 208 bytes in 2 blocks
==18752==    indirectly lost: 306 bytes in 4 blocks
==18752==      possibly lost: 0 bytes in 0 blocks
==18752==    still reachable: 0 bytes in 0 blocks
==18752==         suppressed: 0 bytes in 0 blocks

The problem seems to be in the nng_send function:

==18752== 514 (208 direct, 306 indirect) bytes in 2 blocks are definitely lost in loss record 3 of 3
==18752==    at 0x4C2DA60: calloc (vg_replace_malloc.c:711)
==18752==    by 0x415B05: nni_zalloc (in /home/emanuele/eclipse-workspace/nng/pubsub/pubsub)
==18752==    by 0x40B106: nni_msg_alloc (in /home/emanuele/eclipse-workspace/nng/pubsub/pubsub)
==18752==    by 0x404C82: nng_msg_alloc (in /home/emanuele/eclipse-workspace/nng/pubsub/pubsub)
==18752==    by 0x402D19: nng_send (in /home/emanuele/eclipse-workspace/nng/pubsub/pubsub)
==18752==    by 0x4027F4: server (in /home/emanuele/eclipse-workspace/nng/pubsub/pubsub)
==18752==    by 0x402971: main (in /home/emanuele/eclipse-workspace/nng/pubsub/pubsub)

**Comment by gdamore** [comment]
Looks like a bug, probably a new regression!  Thanks.

**Comment by gdamore** [comment]
I confirm that this is *definitely* a bug.  It's probably thrown some of my other performance test results out, because it means we were hitting the allocator harder.  Essentially, if there are no subscribers able to receive the message (or the last subscriber is not keeping up), then we can wind up not freeing the final message because we didn't send it.  On a busy publisher with no subscribers, this would be very bad indeed.

**Comment by elbarto1980** [comment]
Thank you! @gdamore
