### ISSUE TITLE
Support ZT federations (moons)

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#92]
We need a means to orbit (or operate in a different federation), to permit disconnected (from the broader Internet) use.

When we do this, we need to figure out a way to set this property up as part of the URL, so that administrators can do this, without requiring code changes.

**Comment by gdamore** [comment]
So maybe instead of URL, we can use a combination of environment variable and option settings to do this.  Or even (*gasp*) direct API calls specific to ZT.  (I'm not keen on the latter.)

**Comment by janjaapbos** [comment]
The advantage of supporting direct API calls specific to ZT could be that it forms a basis to support other other options / tuning of the ZeroTier transport in the future. Also the federation and other tuning of ZeroTier (e.g. path preferences) is something that you'll want to control / change without having to restart / reinit the nanomsg library.

**Comment by gdamore** [comment]
I'm pretty sure that what we will want to do initially is with nng_set_option() (socket options, or endpoint options).  I think there are two needed -- "NNG_OPT_ZT_ORBIT" and "NNG_OPT_ZT_DEORBIT".  Perhaps also a read-only option NNG_OPT_ZT_MOONS to obtain the current list of moons.  I need to better understand the syntax of moons so that the option can be configured properly.

**Comment by gdamore** [comment]
So my current change lacks iteration support, but it does support persistent orbiting.  Note that *network* membership is *not* persistent, since that comes with the URL implicitly.

It's possible that we really want to remove the network identity from the URL, and make network membership an option -- but the problem with that is that (like federations), it then becomes a matter for application developers instead of system administrators.
