### ISSUE TITLE
nng can't nng_close() running on FreeBSD 12.0

### ISSUE THREAD

**Issue by raphaelahrens** [nanomsg/nng#928]
NNG is stuck on on nng_close() and stays in an endless loop.

The recognized the problem, when I ran the example programs of [pynng](https://github.com/codypiersall/pynng) and could verify that they are also in the nng lib, by running `ninja test` and by compiling on of the demo programs.

## NNG & Platform details.
I tried with tag v1.1.1 from FreeBSD ports and with the latest commit from 11.04.2019 (d08cef5df2951d489236ea65b65a7db4a3489756).

The OS is FreeBSD 12.0-RELEASE-p3 amd64.

## Expected Behavior
`nng_close` to return after a some time.

## Actual Behavior
`nng_close` keeps spinning in an endless loop. And can only be killed by sending a  Signal (SIGINT or SIGKILL).

I also have a [dtrace output](https://github.com/nanomsg/nng/files/3089291/dtrace_output.txt) from the reqrep client- Where it keeps calling `poll`, and `recvmsg`.

## Steps to Reproduce
When running for example the reqrep demo under FreeBSD 12 the client hangs on `nng_close(sock);`
Also when running `ninja  test` many tests timeout (see [test output](https://github.com/nanomsg/nng/files/3089241/test.txt) ) and test _nngcat_async_  keeps spinning and can only be aborted.

Also the example programs of pynng behave similar.

Under Ubuntu the errors can't be reproduced.

**Comment by gdamore** [comment]
This is probably a kqueue problem.

**Comment by gdamore** [comment]
Actually, its surprising to me that poll() is being called at all on FreeBSD.  I try to use only kqueue for that platform.  Something strange is occurring.

**Comment by raphaelahrens** [comment]
I did some further testing and the problem with the reqrep demo came from the parallel installed nng package.
After `pkg delete nng` and by linking against the build with master it works.
pynng uses an older commit to build the package so the error I saw with pynng could also be solved. (i will look into it.)
So the dtrace output is only valid for v1.1.1.

But when I run `ninja test`I still get the timeouts, even with the latest commit.

Were you able to reproduce some of the errors?

**Comment by raphaelahrens** [comment]
I found out which commit fixes the issue with the halting reqrep example. It is 5cf750697624d4fd63cfe26921209d7c30e1a2d2.

**Comment by gdamore** [comment]
Can I see the remaining timeouts?  I have not had a chance to test any of this on FreeBSD yet.

**Comment by gdamore** [comment]
My VMware host is unavailable right now, so I cant test right now.  Stay tuned.

**Comment by raphaelahrens** [comment]
I did some further testing and the problem seems to come from IPC handling.

When I compile the reqrep from the demo folder and run it with a TCP URL as described in its README.adoc

    ./reqrep server tcp://127.0.0.1:8899 & sleep 1;
    ./reqrep client tcp://127.0.0.1:8899;

It works as aspected.

But when I use an IPC URL it hangs, similar to the `ninja tets` run.

     ./reqrep server ipc:///tmp/reqrep.ipc & sleep 1;
     ./reqrep client ipc:///tmp/reqrep.ipc

The client program receives the reply message, but cannot close the socket.

Hope this helps to pin it down.

Greetings

**Comment by gdamore** [comment]
I think this is probably fixed now.  Can you retest?   (I think it got fixed in 6f084d8c33e44cc69c7e5f29b6e169d7f34d0e0b)

**Comment by raphaelahrens** [comment]
Hi,

so I tried by running `ninja test` first and the ipc test still has a timeout.
I get the same output which is described by https://github.com/nanomsg/nng/issues/1275.

**Comment by raphaelahrens** [comment]
I tested the setup with the `reqrep` demo and indeed the ipc.// call works as expected.

```
$ ./reqrep server ipc:///tmp/reqrep.ipc & sleep 1; ./reqrep client ipc:///tmp/reqrep.ipc; killall reqrep
[1] 244
CLIENT: SENDING DATE REQUEST
SERVER: RECEIVED DATE REQUEST
SERVER: SENDING DATE: Thu Aug  6 10:03:12 2020
CLIENT: RECEIVED DATE: Thu Aug  6 10:03:12 2020
[1]  + 244 terminated  ./reqrep server ipc:///tmp/reqrep.ipc
```

**Comment by gdamore** [comment]
I'm 99% certain that this is fixed in the changes I made today.  Basically the EVFILT_USER code was apparently busted, and rather than try to debug it, I've just rewritten the code to use a pipe for orchestrating the final close (which is similar to what we do for epoll and poll based systems.)

This seems to work, and should have the bonus value of improving portability for systems that have kqueue but don't have EVFILT_USER (NetBSD and OpenBSD, I'm looking at you.)

**Comment by raphaelahrens** [comment]
Cool, now 78 of the tests pass. Only `nng.compat_ws` fails. Thanks for the time and effort you put into the fix.

```
The following tests FAILED:
         75 - nng.compat_ws (Child aborted)
Errors while running CTest
```
