### ISSUE TITLE
Non CMake Build script

### ISSUE THREAD

**Issue by jimmy00784** [nanomsg/nng#929]
Is there a way to build nng with something other than CMake?
A non CMake based build script is necessary for building nng where CMake may not be available or may not be a version suitable for the CMake build to work.
Oracle Linux 7 is the version for example where latest CMake version available is v 2.x which is lower than minimum CMake version needed to build nng.

**Comment by gdamore** [comment]
At present, no.  You can *run* CMake on one system, to generate Makefiles, which you can use with another.  But really, if you're going to the trouble of installing nng, it shouldn't be that much effort to install CMake -- it works with pretty much ~everything.

We could try to come up with other options, but you also need a compiler, make or ninja, and so forth.  So optimizing to remove cmake has seemed of dubious merit.

(Now if CMake was difficult to install, or not widely available, or not supported on typical build systems, then it would be a vastly different situation.)

**Comment by gdamore** [comment]
Maybe this will help you: https://stackoverflow.com/questions/48831131/cmake-on-linux-centos-7-how-to-force-the-system-to-use-cmake3

**Comment by gdamore** [comment]
So you can download actual installable packages from cmake.org.  I'm simply not going to mess with trying to address helping folks who can't be bothered to install reasonably modern tools.

**Comment by unspecd** [comment]
@gdamore 
How about meson build system? unspecd/nng@16486c32

**Comment by unspecd** [comment]
[Some compiler warnings are generated](https://github.com/unspecd/nng/runs/1748475332?check_suite_focus=true).

**Comment by gdamore** [comment]
I have looked at meson build in the past.  There are two problems with it. 

1. It requires Python, which can itself be onerous to install.
2. It's niche, with very little adoption and support from tools vendors (very few if any IDEs support meson, whereas nearly all support CMake)

I'm not interested in investing energy in meson at this time.

**Comment by unspecd** [comment]
> It requires Python, which can itself be onerous to install.

Agreed. I hope it will be rewritten in C :)

**Comment by stephanlachnit** [comment]
> I have looked at meson build in the past. There are two problems with it.
> 
>     1. It requires Python, which can itself be onerous to install.
> 
>     2. It's niche, with very little adoption and support from tools vendors (very few if any IDEs support meson, whereas nearly all support CMake)
> 
> 
> I'm not interested in investing energy in meson at this time.

@gdamore given how much has changed in the last two years, is this still your current opinion? IDE support has gotten much better and there are C/C++ alternative to the default python-based meson (https://git.sr.ht/~lattis/muon and https://github.com/dcbaker/meson-plus-plus)

**Comment by gdamore** [comment]
I am actually very much considering a move to meson.  So yes my position on this has changed a bit.

**Comment by stephanlachnit** [comment]
There are community maintained build files for nng: https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/nng/meson.build
Looks like it's lacking a bunch of configuration options, but might be a nice starting point.
