### ISSUE TITLE
nng_setopt_size with NNG_OPT_RECVBUF/NNG_OPT_SENDBUF fails with "Incorrect type" on req0 and rep0 sockets

### ISSUE THREAD

**Issue by bsirang** [nanomsg/nng#935]
## NNG & Platform details.

Linux x86_64 (nng commit = 5c0f6268d00edde5d9fb4728e3efd92499159d1b)

## Expected Behavior
Calling `nng_setopt_size()` with `NNG_OPT_RECVBUF` or `NNG_OPT_SENDBUF` on a socket opened via `nng_req0_open()` or `nng_rep0_open()` succeeds.
## Actual Behavior
These calls fail with "Incorrect type" error

## Comments
Note that calling `nng_setopt_size()` with `NNG_OPT_RECVBUF` was tested with a socket opened with `nng_sub0_open()` and behaved as expected.

**Comment by neachdainn** [comment]
Note that [the documentation][1] says that they take `int`, not `size_t`. I can confirm that on Linux x86_64 `nng_setopt_int` does not return an error for those socket types.

[1]: https://nanomsg.github.io/nng/man/tip/nng_options.5.html
