### ISSUE TITLE
 Memory Leak in wsstream

### ISSUE THREAD

**Issue by chuyue86** [nanomsg/nng#937]
As I test websocke stream in my project, I found some memory leak , then I ran Valgrind on the wsstream demo ((commit c036b3e4a)). It found several "possibly lost" bytes.

wsstream summary:

==8732== HEAP SUMMARY:
==8732==     in use at exit: 117,531 bytes in 390 blocks
==8732==   total heap usage: 847 allocs, 457 frees, 288,470 bytes allocated
==8732== 
==8732== LEAK SUMMARY:
==8732==    definitely lost: 4,032 bytes in 12 blocks
==8732==    indirectly lost: 99,180 bytes in 330 blocks
==8732==      possibly lost: 469 bytes in 24 blocks
==8732==    still reachable: 13,850 bytes in 24 blocks
==8732==         suppressed: 0 bytes in 0 blocks

Is stream API still in the experimental stage now?

**Comment by gdamore** [comment]
Well, you'll note that the stream stuff isn't in a labeled (tagged) version yet.

That said, it should be reliable, but this leak needs to be fixed.
