### ISSUE TITLE
 httpclient Timeout can succeed in cloud

### ISSUE THREAD

**Issue by glycerine** [nanomsg/nng#940]
nng at 7eaccabfe

All tests are green on OSX, but on my Windows 2016 server vps, the httpclient test consistently fails on the "Timeout works" test. Line 38, Test: nng_aio_result(aio) == NNG_ETIMEOUT.

**Comment by gdamore** [comment]
Any chance at getting a determination of what the actual value of nng_aio_result(aio) is?

**Comment by glycerine** [comment]
yes, remind me if I don't get to it by tomorrow.

**Comment by glycerine** [comment]
Also paperspace.io was very useful. Windows machine for a couple hours for a buck or two.

**Comment by glycerine** [comment]
I think I recall that there was just no error. But I'll have to double check tomorrow.

**Comment by glycerine** [comment]
Ugh. My compilation environment is FUBAR. Sorry. Not going to be able to figure this one. I recommend spinning up a cheap paperspace to debug.

**Comment by gdamore** [comment]
I test normally on Windows at AppVeyor and on my desktop.  Is there reason to believe that Windows Server 2016 is somehow significantly different from Windows 10?

**Comment by gdamore** [comment]
Note that httpclient is also sensitive to your network environment -- it needs to connect to remote servers.

I'm also expecting that example.com takes > 1 msec to respond.  If your clock is slower to schedule timeouts, or if you have networking that somehow resolves example.com elsewhere and faster (< 1msec) then all bets are off.

Maybe check that?

**Comment by gdamore** [comment]
I'm seeing this fairly frequently in github now.  I suspect caching is making this go faster than anticipated.

This is a test failure, and not a failure of the underlying code.   I think it has a lot to do with the details of cloud deployments.
