### ISSUE TITLE
How to complie nng by cmake for support tls in windows?

### ISSUE THREAD

**Issue by allen2015555** [nanomsg/nng#953]
At the first, I am sorry my englist is poor.

I clone nng and mbedtls-2.16.1.
The following is how i builded it.
1. Build mbedtils-2.16.1 by vs2017, and get mbedTLS.lib.

2. Open nng CMakeLists.txt set TLS flag in ON, like this:
option (NNG_ENABLE_TLS "Enable TLS protocol (requires mbedTLS)" ON)

3. Set mbedtils path in CMakeLists.txt, like this:
set(MBEDTLS_ROOT_DIR "D:/lib/mbedtls-2.16.1")
set(MBEDTLS_INCLUDEDIR "D:/lib/mbedtls-2.16.1/include")
set(MBEDTILS_LIBRARYDIR "D:/lib/mbedtls-2.16.1/visualc/VS2010/Release")

4. User CMake(gui) generate *.sln.

In the last, I get error in CMake:
CMake Warning at src/supplemental/tls/CMakeLists.txt:26 (message):
  

          ************************************************************
          Linking against mbedTLS changes license terms (Apache 2.0).
          Consult a lawyer and the license files for details.
          ************************************************************

CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find mbedTLS (missing: MBEDTLS_TLS_LIBRARY MBEDTLS_CRYPTO_LIBRARY
  MBEDTLS_X509_LIBRARY) (found version "2.16.1")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindmbedTLS.cmake:78 (find_package_handle_standard_args)
  src/supplemental/tls/CMakeLists.txt:32 (find_package)

Configuring incomplete, errors occurred!

So, how to build nng support TLS? I never have writed cmake script. Anyone can help me for fix this?
Thank you!

**Comment by jeikabu** [comment]
It says libraries are missing.

Make sure you read [BUILD_TLS doc](https://github.com/nanomsg/nng/blob/master/docs/BUILD_TLS.adoc).

Here I'm using the git bash shell:  
```
# Build/install mbedTLS
cd mbedtls-2.16.1/
mkdir build && cd build
cmake ..
# open `mbed TLS.sln` and build "Release" x64
# In "Solution Explorer" right-click `INSTALL` project and build that (note default install path requires VS run as admin)
# Check `C:\Program Files (x86)\mbed TLS` for output

# Build nng
cd ../../nng
mkdir build && cd build
# Note you can set variables on the command line you don't need to edit `CMakeLists.txt`
cmake -DNNG_ENABLE_TLS=ON -DMBEDTLS_ROOT_DIR=c\:/Program\ Files\ \(x86\)/mbed\ TLS/ ..
# Open build/nng.sln and build "Release" x64 again
```

That should all work.

**Comment by allen2015555** [comment]
> cmake -DNNG_ENABLE_TLS=ON -DMBEDTLS_ROOT_DIR="c:/Program Files (x86)/mbed TLS/" ..
Thank you! I had complied it fully.
