### ISSUE TITLE
Is there an example of using a nng secure websocket to connect to a non nng based websocket server ?  

### ISSUE THREAD

**Issue by jsimmons089** [nanomsg/nng#955]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

<include NNG version, and platform/operating system, and if you are using
another programming language what language> 

## Steps to Reproduce

<If possible, if include a copy of, or link to, a minimal test program
to demonstrate the behavior.  We prefer test cases written in C when
possible.>

**Comment by gdamore** [comment]
I'm sorry, but I don't have any examples of this at present.  Note that NNG currently does not support "text mode" WebSockets -- that's on the TODO list.

**Comment by gdamore** [comment]
I've answered as best as I can for now.
