### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by maingig** [nanomsg/nng#957]
We were using 1.1.1 but had to pull latest due to a "hanging" issue on Windows. 
We use the same version (latest) for all platforms.

It was working on Android until we upgraded.

## Expected Behavior

We expect the address to work.

## Actual Behavior

tcp://10.0.2.15:6677
nng_listen: Address invalid

This address is the android emulator ip address for local hosting machine.

## Steps to Reproduce

Open up a socket in Bus mode.
`tcp://10.0.2.15:6677` doesnt work.
`tcp://127.0.0.1:6677` works

Is there something we can try to narrow this down.

**Comment by maingig** [comment]
The error number is 15.  And when I say it use to work, that was only in Pair mode.  Now it doesn't work at all.

**Comment by gdamore** [comment]
Do you have an IP interface configured on the system that can reach the 10.0.2.15 destination, and is it "up"?

**Comment by maingig** [comment]
Yes - we are following these [instructions](https://developer.android.com/studio/run/emulator-networking).

**Comment by gdamore** [comment]
Please paste the output from 'ifconfig -a'

**Comment by maingig** [comment]
```
generic_x86:/ $ ifconfig -a                                                                                                 

ip_vti0   Link encap:UNSPEC  

          NOARP  MTU:1364  Metric:1

          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 

          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0 

          collisions:0 txqueuelen:1 

          RX bytes:0 TX bytes:0 

sit0      Link encap:UNSPEC  

          NOARP  MTU:1480  Metric:1

          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 

          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0 

          collisions:0 txqueuelen:1 

          RX bytes:0 TX bytes:0 

radio0    Link encap:UNSPEC  

          inet addr:192.168.200.2  Bcast:192.168.200.255  Mask:255.255.255.0 

          inet6 addr: fec0::c1b:6547:e001:7d72/64 Scope: Site

          inet6 addr: fe80::54a9:a8ff:fec9:b659/64 Scope: Link

          inet6 addr: fec0::54a9:a8ff:fec9:b659/64 Scope: Site

          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

          RX packets:235 errors:0 dropped:0 overruns:0 frame:0 

          TX packets:254 errors:0 dropped:0 overruns:0 carrier:0 

          collisions:0 txqueuelen:1000 

          RX bytes:576359 TX bytes:39845 

lo        Link encap:UNSPEC  

          inet addr:127.0.0.1  Mask:255.0.0.0 

          inet6 addr: ::1/128 Scope: Host

          UP LOOPBACK RUNNING  MTU:65536  Metric:1

          RX packets:8 errors:0 dropped:0 overruns:0 frame:0 

          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0 

          collisions:0 txqueuelen:1 

          RX bytes:390 TX bytes:390 

ip6_vti0  Link encap:UNSPEC  

          NOARP  MTU:1500  Metric:1

          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 

          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0 

          collisions:0 txqueuelen:1 

          RX bytes:0 TX bytes:0 

wlan0     Link encap:UNSPEC    Driver mac80211_hwsim

          inet addr:192.168.232.2  Bcast:192.168.239.255  Mask:255.255.248.0 

          inet6 addr: fe80::15:b2ff:fe00:0/64 Scope: Link

          inet6 addr: fec0::b9b5:e871:b5b:3221/64 Scope: Site

          inet6 addr: fec0::15:b2ff:fe00:0/64 Scope: Site

          UP BROADCAST RUNNING MULTICAST  MTU:1400  Metric:1

          RX packets:914 errors:0 dropped:0 overruns:0 frame:0 

          TX packets:599 errors:0 dropped:0 overruns:0 carrier:0 

          collisions:0 txqueuelen:1000 

          RX bytes:505517 TX bytes:207489 

ip6tnl0   Link encap:UNSPEC  

          NOARP  MTU:1452  Metric:1

          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 

          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0 

          collisions:0 txqueuelen:1 

          RX bytes:0 TX bytes:0 

```

**Comment by maingig** [comment]
Any advice?

**Comment by codypiersall** [comment]
@maingig It looks to me like 10.0.2.15 is not a valid IP address for your system. Should you be using one of the 192.168 addresses?

**Comment by maingig** [comment]
@codypiersall - The instructions link I posted above is for the Android emulator - which suggests using the 10.0.2.15 address.

**Comment by gdamore** [comment]
I can't address issues with the android emulator or the instructions, but your output clearly indicates that you don't have a 10.x address configured.  That's why you're getting this error -- you can't bind to an IP address which is not on your system.

You'll need to figure out what went wrong in the instructions, the emulator, etc.  This is no bug in nng here -- it is performing exactly as it should in this circumstance.

**Comment by maingig** [comment]
We have the same problem on the actual device because Android restricts servers from using 0.0.0.0.
I'm curious what others have tried.

**Comment by gdamore** [comment]
You can't bind to INADDR_ANY ???  You shouldn't be able to use that as an *outgoing* address (for connect()), but you should be able to use it as a bindable interface....
