### ISSUE TITLE
Are there any examples for implementing a broker with nng

### ISSUE THREAD

**Issue by luke-titley-dwarf** [nanomsg/nng#959]
Hey,
So I implemented a very quick hacky router/broker that forwards messages from a collection of incoming sockets to outgoing sockets. Each message has a routing key that is used to determine the outgoing socket to send the message down.

## Currently
My implementation at the moment works, under simple testing conditions but I'm about to re-write it to be more efficient. Right now I'm looping over each input socket reading messages with a non blocking nng_recvmsg. Then I'm inspecting the tail of the message for a routing key, looking the key up in a table, which gives me the right outgoing socket.

I'm about to re-write it.

The options I have in front of me are:
## poll
Get a file descriptor for each socket, and use poll. This will give me one place to block, then I can easily forward whatever I get with much the same code I already have. This seems pretty simple to me, and will mean I'm not preferring any socket, but may not scale.

## aio
Use the aio api, and a recv callback. This seems like the recommend approach. But it's not clear to me how I safely write to the outgoing sockets from a callback which will be executed on another thread. I can wrap my outgoing socket table in a big mutex but it's kind of shitty.

I've looked at your aio demo, which is pretty understandable, but it doesn't really explain how you might deal with this scenario.  I feel like it's a pretty common pattern. I am wondering what your 'best practice' advice for this would be.

**Comment by neachdainn** [comment]
It sounds to me like you're trying to rewrite the [`nng_device`] function?

[`nng_device`]: https://nanomsg.github.io/nng/man/v1.1.0/nng_device.3

**Comment by gdamore** [comment]
Not precisely nng_device, as he's added some additional processing to select the socket.   I've thought about adding an API to allow user logic to be inserted into nng_device, but I've not implemented that yet.

In the meantime, yes, aio is the right approach.

From the perspective of locking, you may be more worried than you need to be.  nng itself guarantees both that the callbacks for a single aio are run single threaded (you do have to promise not to reuse the aio before it's callback is executed though!), and the sockets themselves are completely thread safe -- you can issue many concurrent requests to the same socket and it all should work -- provided that you probably want to use raw mode sockets if you're using REQ/REP or SURVEYOR/RESPONDENT.  (You could use separate contexts as well.)  If you're using PAIR you don't need to worry about that, and can use either cooked or raw mode sockets.

**Comment by gdamore** [comment]
Btw, please use either our gitter chat room or the nanomsg mailing list for questions like this -- GitHub issues is for reporting things that would require changes to the repos.

**Comment by luke-titley-dwarf** [comment]
Ah, apologies. I wasn't aware of these.
