### ISSUE TITLE
NNG threads inherit application thread name

### ISSUE THREAD

**Issue by TBastiani** [nanomsg/nng#960]
## NNG & Platform details.

NNG version: master
OS: Linux
Language: C++

## Expected Behavior

In my application I name threads with `pthread_setname_np` in order to facilitate debugging but also to make some of the behaviour more transparent in tools such as `htop`. This is ruined by the fact that NNG spawns quite a lot of threads and inherits the thread name from the thread that creates the (first?) socket. I realise that this is normal and expected behaviour but I wish that I could easily identify NNG threads at a glance, this could be done by giving them a distinctive name such as "nng_thread" or even "nng".

## Steps to Reproduce

Run any NNG application under `htop` and enable "show custom thread names" under the display options. Alternatively run any NNG app under `gdb` and type `info threads`.

## Suggested patch

Due to `pthread_setname_np` being "non-portable" it's quite hard to write a version that will work correctly on all unix platforms. Even [chromium resorts to `dlsym()` on OSX](https://github.com/adobe/chromium/blob/master/base/threading/platform_thread_mac.mm#L49) so I'm only trying to fix the issue on Linux which is the platform where I've seen this behaviour. I don't believe there are any downsides to a fix like this, unless one is concerned by the small amount of overhead when spawning a new thread.

```
commit c37205f669a8037a11339e42647e6fd9e04611a9 (HEAD -> thom/dev, master)
Author: Thomas Bastiani <thom@codehawks.eu>
Date:   Mon Jun 10 17:06:38 2019 +0100

    Don't inherit thread name from caller
    
    This will only work on Linux

diff --git a/src/platform/posix/posix_thread.c b/src/platform/posix/posix_thread.c
index b8fa814e..8f438501 100644
--- a/src/platform/posix/posix_thread.c
+++ b/src/platform/posix/posix_thread.c
@@ -215,6 +215,11 @@ nni_plat_thr_main(void *arg)
        sigaddset(&set, SIGPIPE);
        (void) pthread_sigmask(SIG_BLOCK, &set, NULL);
 
+       // Give the thread a name
+#if defined(__linux__) && defined(_GNU_SOURCE)
+       (void) pthread_setname_np(pthread_self(), "nng_thread");
+#endif
+
        thr->func(thr->arg);
        return (NULL);
 }
```

**Comment by gdamore** [comment]
For Linux this is low hanging fruit.  I really want to do "more" here, because we now have nng_thread as a public API so we should permit applications to request a name for their threads..  And it would be good to separate the NNG worker threads (taskqs) from the pollqs, from the worker threads.

And Windows 10 recently added this too.  So rather than rush something out, I'm going to try to get this right in the next release.

Deferring to 1.4.

**Comment by gdamore** [comment]
It looks like all the POSIX-like platforms have slightly different variants of this. :/
