### ISSUE TITLE
PR: NNG Julia binding

### ISSUE THREAD

**Issue by ZHENGSY** [nanomsg/nng#962]
as the title of the PR, we use Julia intensively and found that we need nng's Julia binding more and more, or we have to use the ZMQ binding which is now available. Hope to see the binding soon!

Thank you for your great work!

**Comment by jeikabu** [comment]
I don't use Julia but it looks to support FFI to native code. Can't you directly call the C static/shared library?

**Comment by codypiersall** [comment]
Hi @ZHENGSY,

I don't want to speak for Garrett, but I think it's outside the scope of *this* repository.  If you create bindings for Julia or find some that work well, you can make a PR to add the bindings to the docs!

I did find some bindings for Nanomsg which might work for you: https://github.com/redsift/Nanomsg.jl.  Remember that nng/Nanomsg are wire compatible, so you can mix and match programs using nng and nanomsg.

**Comment by ZHENGSY** [comment]
@jeikabu Yes it does. I will try. :)
@codypiersall OK I got you. I will try the one you recommended. 
Cheers!
