### ISSUE TITLE
aio in nng_stream can get msg?

### ISSUE THREAD

**Issue by qtcdxxyuc** [nanomsg/nng#967]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

- NNG:`1.1.1`
- system: ubuntu 18.04LTS
- language: c++

## Expected Behavior

When I use nng_stream with websocket, I found an interesting thing.

```c++
nng_iov iov;
//...
iov.iov_len = 0; 
nng_aio_set_iov(aio, 1, &iov);
nng_stream_recv(stream, aio);
nng_aio_wait(aio);//wait until data recv,nng_aio_count = 0
nng_stream_recv(stream, aio);
nng_aio_wait(aio);//no delay
auto msg = nng_aio_get_msg(aio);
```

I set the iov to 0 size.

First recv in stream will wait , and the count is 0,this aio call get_msg get nullptr .

Then,second recv no delay,  the count is data size,this aio can get msg. Data from the sender is stored in msg.

## Actual Behavior

Is the above phenomenon intentional? Is it correct for me to use this? 

Many times I don't know the size of the data sent by the other party. Can I use msg to intercept the data?

## Steps to Reproduce

null

**Comment by gdamore** [comment]
No, this not intentional -- it's a bug.  You're supposed to set an iov when using nng_stream to receive things.

**Comment by qtcdxxyuc** [comment]
Thank you.
