### ISSUE TITLE
CMake : export target to current build scope

### ISSUE THREAD

**Issue by bonwilliam** [nanomsg/nng#969]
## Expected Behavior

When using nng as a sub-directory of a top level project, we should be able to link any project of the current build scope  with nng by simply adding

```CMake
target_link_libraries(${PROJECT_NAME} PUBLIC nng)
```
## Actual Behavior
```
export called with target "..." which requires target "nng"
  that is not in the export set.
```
## Steps to Reproduce

With the following architecture
```CMake
- project
    - CMakeLists.txt # add_subdirectory(nng) add_subdirectory(exe)
    - nng # nng sources from master branch
        - CMakeLists.txt
        - src
            - CMakeLists.txt
    - exe
        - CMakeLists.txt # target_link_libraries(exe PUBLIC nng)
```

## Suggestion

In nng/src/CMakeLists.txt, there is an export for finding and linking properly to the target after having installed it, but there is nothing for using it properly in the current build scope. I would suggest to add the following that will create an export file for the current build scope, and the target will be known all over the build scope (tested, it worked)

```CMake
export(EXPORT ${PROJECT_NAME}-target
        FILE ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}-targets.cmake
        NAMESPACE nng::)
```

**Comment by gdamore** [comment]
Thanks for the suggestion.  Fix on the way.
