### ISSUE TITLE
Very slow pull/push performance compared to ZMQ

### ISSUE THREAD

**Issue by ocoanet** [nanomsg/nng#972]
Hello,

I am porting messaging code from ZMQ to NNG and I get very poor performance results. I suspect that the issue comes from my usage of NNG.

I am using TCP pull / push sockets on Windows.

The code:
- Starts a dedicated sender thread that creates a push socket. This threads gets messages from a queue and sends them using nng_send.
- Starts a dedicated receiver thread that creates a pull socket. This thread busy-spins on nng_recv and forward messages to a queue. Messages are read using NNG_FLAG_ALLOC / memcpy / nng_free.

Both sockets are configured with timeouts and buffer sizes options.

The benchmark sends 2M messages and waits until they are all received.

The throughput on ZMQ is around 700K msg/s.
The throughput on NNG is around 35K msg/s.

I suspect that the dedicated threads might not be necessary anymore with NNG. I also suppose that my usage of nng_send and nng_recv is not optimal.

How can I improve my code to get a better throughput?

**Comment by neachdainn** [comment]
Use `nng_sendmsg` and `nng_recvmsg` instead, as that will allow you to take advantage of the zero-copy mechanisms. I suspect that any other attempts at improving performance is moot until you do that.

**Comment by gdamore** [comment]
As @neachdainn indicates, nng_sendmsg and nng_recvmsg are preferred.  You also probably don't need separate threads, as you suggest.

Having said all that, there has been a lot of performance work in NNG lately, but unfortunately the push/pull pattern has not received any of that attention *yet*.  Maybe it's time (really past time) for me to invest some cycles in that.  (It all comes down to finding time.)

Btw what is your message size?

**Comment by ocoanet** [comment]
Thank you for your answers.

The message size is 137 bytes.

On the sending side, I use a serializer that generates (writes to) a byte array, so the `nng_send` seems appropriate. I do not think using `nng_sendmsg` can make thinks faster.

On the receiving side, I can replace `nng_recv`/`NNG_FLAG_ALLOC`/`nng_free` by `nng_recvmsg`/`nng_msg_len`/`nng_msg_body`/`nng_msg_free` but again I am not sure to understand how it can improve performance.

I tried to change the receiving code to use `nng_recvmsg` and the benchmark throughput was the same.

**Comment by neachdainn** [comment]
> On the sending side, I use a serializer that generates (writes to) a byte array, so the nng_send seems appropriate. I do not think using nng_sendmsg can make thinks faster.

Why not serialize directly into the message?

>  I am not sure to understand how it can improve performance.

Using the `nng_{send,recv}msg` functions allow NNG to avoid copying data internally. If you look [here][1], you can see that NNG has to copy your buffer into a message and then call `nng_sendmsg`. If you serialize directly into the message, you can avoid that copy.

[1]: https://github.com/nanomsg/nng/blob/master/src/nng.c#L151

**Comment by gdamore** [comment]
I'd be less concerned about the data copies (these are tiny messages) than I would be about the impact on the allocator.  Ultimately, probably the limiting factor is the multithreaded design in NNG and some of the legacy still in push/pull -- would be interesting to see if PAIR gives better results.

**Comment by neachdainn** [comment]
> I'd be less concerned about the data copies (these are tiny messages)

True. Just trying to explain why one is preferred over the other.

**Comment by gdamore** [comment]
Also for fun, you could compare with legacy nanomsg, and try both push and pull mixed combos (e.g. nng push with nanomsg pull and vice versa... might inform where we should focus efforts.)

**Comment by gdamore** [comment]
Just a heads up -- there have been a bunch of improvements lately.  The Push/Pull isn't the main beneficiary of these, but it still might be worth checking into -- I expect its better now than it was before. (It will get a bunch better in the not distant future when I finally migrate pipeline away from the message queue implementation.)

**Comment by gdamore** [comment]
I'm going to release 1.3 sooner than planned, so punting this to 1.4.  In 1.4 I will be refactoring this to use aio and bypass the message queue (as I've done elsewhere for performance wins) so it will get better then.

**Comment by zhyang-liu** [comment]
I'm on a project with heavy load, and the low performance made me use legacy nanomsg instead of nng. Wish performance will be better in later versions.
It's about at least a million packages per second.

**Comment by gdamore** [comment]
If you're using pipeline -- I have a change coming momentarily that should help a lot.  I don't know if we'll get to ZMQ or libnanomsg for the simple cases -- but we should *scale* very well.  (In particular latency is a challenge, due to the multithreaded architecture -- context switching isn't free -- but this allows us to get some scale out performance benefits that allows us to engage multiple cores a lot more effectively than either nanomsg or ZMQ could.
