### ISSUE TITLE
nng_http_res_alloc does not init status code properly

### ISSUE THREAD

**Issue by bubbasc831** [nanomsg/nng#975]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.
NNG: `4dcfdd65318b706e139658842c9f406e906a8003 nng (v1.1.1-89-g4dcfdd65)`
OS: Ubuntu 19.04

## Expected Behavior
The man page for nng_http_res_alloc states:

> The nng_http_res_alloc() function allocates a new HTTP response structure and stores a pointer to it in resp. The response will be initialized with status code 200 (NNG_HTTP_STATUS_OK), and a reason phrase of `"OK`", and HTTP protocol version `"HTTP/1.1`".

## Actual Behavior
The rest demo as written returns an invalid status code of 0:
```
$ wget -d --post-data=ABC http://127.0.0.1:12345/api/rest/rot13
Setting --post-data (postdata) to ABC
Setting --post-data (postdata) to ABC
Setting --method (method) to POST
Setting --body-data (bodydata) to ABC
DEBUG output created by Wget 1.19.4 on linux-gnu.

Reading HSTS entries from /home/me/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'rot13' (UTF-8) -> 'rot13' (UTF-8)
--2019-08-07 21:48:05--  http://127.0.0.1:12345/api/rest/rot13
Connecting to 127.0.0.1:12345... connected.
Created socket 3.
Releasing 0x0000557ce8215530 (new refcount 0).
Deleting unused 0x0000557ce8215530.

---request begin---
POST /api/rest/rot13 HTTP/1.1
User-Agent: Wget/1.19.4 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: 127.0.0.1:12345
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 3

---request end---
[BODY data: ABC]
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 0 Unknown HTTP Status
Content-Length: 3

---response end---
-1
2019-08-07 21:48:05 ERROR -1: Malformed status line.
Closed fd 3
```

## Steps to Reproduce

Compile NNG and demos
Run rest demo per instructions in rest/server.c

Setting the status code to 200 immediately after the call to `nng_http_res_alloc` in server.c fixes the demo.

Thanks

**Comment by gdamore** [comment]
Oops!  Thanks for reporting this!
