### ISSUE TITLE
how does the server detect network status changes?

### ISSUE THREAD

**Issue by sujx0123** [nanomsg/nng#983]
Hi all. I am trying to integrate nanomsg in monitoring app/service which needs to send its data via the TCP sockets to remote master server. Thus it is critical for the app to re-connect/manage state of connection properly so it won't lose data. My question:  When the network is disconnected, nng will automatically reconnect, but how does the server detect network status changes?

**Comment by codypiersall** [comment]
You should be able to use [`nng_pipe_notify`](https://nanomsg.github.io/nng/man/tip/nng_pipe_notify.3) for that.  Alternatively, you could add a heartbeat socket to you application and detect when it times out.

**Comment by gdamore** [comment]
Most applications should not be designed to react to these connectivity changes -- this makes them more fragile.

If you use REQ/REP, and a remote connection to a REP server is dropped, then the REQ will automatically retry a different server if one is available, or when one becomes available (provided that one becomes available before the request times out.)
