### ISSUE TITLE
 ws_read_finish_str  free invalid pointer

### ISSUE THREAD

**Issue by qtcdxxyuc** [nanomsg/nng#986]
## ws_read_finish_str  free invalid pointer

- NNG:`1.1.1`
- system: ubuntu 18.04LTS
- language: c++

## Expected Behavior

In websocket_stream.

When the sender sends 10KB of data, and the receiver only has 1KB of iov.

The receiver should get 10 nng_stream_recv calls, each time filling a 1MB buffer.

Always quit unexpectedly on the last acceptance.

```c
//free(): invalid pointer
//Signal: SIGABRT (Aborted)
```

GDB:

```c
SIGABRT (Aborted)
__GI_raise
__GI_abort
__libc_message
malloc_printerr
_int_free
__GI___libc_free
ws_read_finish_str
ws_str_recv
```

In addition, when the sender sends an empty packet as a heartbeat packet。

nng ws_stream seems to filter empty packets, nng_stream_recv does not call callback function when empty packets are received.

What should I do to get an empty package?

## Steps to Reproduce

Server

```c++
 int rv;
nng_url *url = nullptr;
nng_stream_listener *stream_listener = nullptr;

nng_url_parse(&url, "ws://192.168.3.66:50051");
nng_stream_listener_alloc_url(&stream_listener, url);
nng_stream_listener_set_bool(stream_listener, NNG_OPT_TCP_NODELAY,true);
nng_stream_listener_set_bool(stream_listener, NNG_OPT_TCP_KEEPALIVE,true);
nng_stream_listener_set_size(stream_listener, NNG_OPT_WS_SENDMAXFRAME,1'000'000);
nng_stream_listener_listen(stream_listener);

nng_aio *aio = nullptr;
nng_aio_alloc(&aio, nullptr, nullptr);

nng_stream_listener_accept(stream_listener, aio);
nng_aio_wait(aio);
rv = nng_aio_result(aio);
if (rv != 0) { return;}

nng_stream *stream = static_cast<nng_stream *>(nng_aio_get_output(aio, 0));

nng_iov iov;
while (true) {
    std::string oid_str;
    oid_str.resize(9'500);//have 9500B data

    if (oid_str.size()) iov.iov_buf = oid_str.data();
    else               			  iov.iov_buf = nullptr;
    iov.iov_len = oid_str.size();
    rv = nng_aio_set_iov(aio, 1, &iov);

    nng_stream_send(stream, aio);
    nng_aio_wait(aio);
    rv = nng_aio_result(aio);
    if (rv != 0) break;
    sleep(5);
}
nng_aio_free(aio);
nng_stream_close(stream);
nng_stream_free(stream);
```

---

client 

```c++
//... like server
nng_iov iov; // 1KB
while(int i=0;i<10;i++){
    nng_stream_recv(...);
    //On the last call, it will crash
    //Regardless of the size of the remaining data
}
//...
```

**Comment by gdamore** [comment]
On the empty packet -- the API here is stream based, so if there is no payload, you won't get notified.  If you need such notifications you might want to look at the underlying websocket API, although use of the websocket framing layer by applications is pretty much universally discouraged.

**Comment by qtcdxxyuc** [comment]
I changed the heartbeat package by using ping-pong in the websocket protocol.
There is still a problem with the above.
When the client's receive buffer is smaller than the data sent by the server, nng will fill the client buffer multiple times. 
At this time, the last padding will be wrong. `SIGABRT (Aborted)`.

**Comment by gdamore** [comment]
So I'm fairly convinced that I've seen the crash of the double free of the string when accidentally freeing the stream twice.  Probably we should look at ways to make that a bit more resilient, but really its a fairly direct case of a bug in the consuming code.

I'm going to try your test case to see if it reproduces and I'll codify into a formal part of the test suite, because I'm pretty sure somewhere in the code there is one of these bugs -- I've seen the crashes in the test suite at least.

**Comment by gdamore** [comment]
Oh wait, that's a *different* crash than the one described here.

**Comment by qtcdxxyuc** [comment]
Since you haven't answered this question for quite some time, I finally implemented the websocket part myself. But if there is a test needed, I'll be happy to help.

**Comment by qtcdxxyuc** [comment]
In my previous tests, it behaved as an invalid pointer instead of double free.
And the use case does not seem to release the stream multiple times.

**Comment by gdamore** [comment]
Ok.  Did you wind up fixing a bug in NNG, or doing something totally different?  Sorry it's been a while, I have only a limited number of cycles to work on NNG right now as I don't have any clients actively paying me to work on it.

**Comment by qtcdxxyuc** [comment]
I will test this bug again next Monday

**Comment by gdamore** [comment]
Don't worry -- I've reproduced it reliably now.

**Comment by gdamore** [comment]
So I have diagnosed properly, and have a fix coming -- my code no longer crashes, but there is some kind of corruption coming in the stream with my fix, so I've got to sort that out before I ship it.  Stay tuned.

**Comment by gdamore** [comment]
Good news, I think I have it fixed!

**Comment by gdamore** [comment]
Please go ahead and test it now (HEAD).

I'm probably going to tag a v1.2.2 soon -- because this fix is pretty important.

**Comment by qtcdxxyuc** [comment]
I will go to the company for testing now

**Comment by qtcdxxyuc** [comment]
I looked at your test cases and modified them slightly.

Do the opposite:

- server send `9500B` once
- client recv `1024B` once, try recv multiple

Will block at the client's second acceptance.

The server source code has not changed, as I described above.

> client.c

```c++
    int rv;
    nng_url *url = nullptr;
    nng_stream_dialer *stream_dialer = nullptr;

    rv = nng_url_parse(&url, "ws://192.168.3.66:50051");
    LOG_ASSERT(!rv)<<nng_strerror(rv);
    nng_stream_dialer_alloc_url(&stream_dialer, url);
    LOG_ASSERT(!rv)<<nng_strerror(rv);

    nng_aio *aio = nullptr;
    nng_aio_alloc(&aio, nullptr, nullptr);

    nng_stream_dialer_dial(stream_dialer,aio);

    nng_aio_wait(aio);

    nng_stream *stream = static_cast<nng_stream *>(nng_aio_get_output(aio, 0));

    std::string data;
    data.resize(1024);
    nng_iov iov; // 1KB
    iov.iov_buf = data.data();
    iov.iov_len = data.size();
    nng_aio_set_iov(aio, 1, &iov);

    size_t sz = 0;
    while (true){
        nng_stream_recv(stream, aio); //block this second loop
        nng_aio_wait(aio);
        rv = nng_aio_result(aio);
        sz = nng_aio_count(aio);
        LOG(INFO)<<sz;
        if (rv != 0) return;
    }

```

**Comment by qtcdxxyuc** [comment]
> src/supplemental/websocket/websocket.c

```
//line 817
static void ws_read_finish_str(...){
		//line 847
    	if ((n = frame->len) > iov->iov_len) {
				// This eats the entire iov.
				n = iov->iov_len;
			}
			
             
             nni_aio_bump_count(aio, n); //
}
```

It looks like you intentionally cut it.

What do I need to do for `aio` to continue reading?

**Comment by qtcdxxyuc** [comment]
Does it mean that I cannot be fully accepted if I don't provide enough iov messages?
