### ISSUE TITLE
[Q] Stability of master branch

### ISSUE THREAD

**Issue by pzoltowski** [nanomsg/nng#988]
I have noticed that there haven't been any new release version for while even though master branch seems active and had many commits since 1.1.1 release. Does it mean 1.1.1 still should be considered stable and preferred over master when using with other projects?

**Comment by gdamore** [comment]
1.1.1 is the stable version -- master can contain bugs and represents higher risk.  Particularly I may change APIs in the unstable version.  At some point soon I hope to cut a 1.2 release.
