### ISSUE TITLE
How to implement async pair

### ISSUE THREAD

**Issue by kv-gits** [nanomsg/nng#990]
I am looking async demo but can't understand how to implement smth like this:

Server is blocked and waits for some event. Event may be incoming message or outcomming send emitting. Is it possible to make async pair this way with nng?

**Comment by gdamore** [comment]
The async demo uses callbacks to achieve this, which is what I recommend.  Alternatively you can use NNG_OPT_SENDFD and NNG_OPT_RECVFD to get pollable file descriptors (they poll as readable) when either of these events occur.  (You can use these fds with poll(), epoll(), select(), and similar APIs.)
