### ISSUE TITLE
Crash - panic

### ISSUE THREAD

**Issue by maingig** [nanomsg/nng#992]
panic: appending node already on a list or not inited
This message is indicative of a BUG.
Report this at https://github.com/nanomsg/nng/issues

**Stack**
nni_plat_abort
nni_panic
nni_list_append
nni_task_dispatch
nni_msgq_aio_get
bus0_sock_getq_cb_raw
nni_taskq_thread
nni_thr_wrap
nni_plat_thr_main
start_thread
clone

## NNG & Platform details.

NNG at commit 7eaccabfef35774b13da215a53736d3b7956a592 (May 7)
Ubuntu 16.04 and QNX 7.0  C++

## Expected Behavior

Not crashing

## Actual Behavior

Crash

## Steps to Reproduce

I have a server sending 6 messages (each 688 bytes) every 16 msecs (Bus).  There is only one client.  It takes a couple of hours before it crashes.  I will  work up a small example, however let me know if there is anything you can suggest that will help track this down.

**Comment by maingig** [comment]
I have attached a small example which crashes in a different place (nni_msg_len).
The name is misleading - the file supports Bus and Pair. 
I run 6 clients  with TestNNGAsyncPair tcp://127.0.0.1:5556 1 &
I then run one server - TestNNGAsyncPair tcp://127.0.0.1:5556 -s 1
This seems to only happen if the server responds in receive_cb.


`// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitoar.com>
//
// This software is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

// This program serves as an example for how to write an async RPC service,
// using the l.  The server receives
// messages and keeps them on a list, replying to them.

// Our demonstration application layer protocol is simple. Either side
// can send a message.  Upon receiving such message it will acknowledge

// To run this program, start the server as async_pair <url> -s 0|1
// Then connect to it with the client as async_pair <url> 0|1\.
//
// Last arguments specifies whether to send messages or wait.
// It doesn't make sense for both sides to be 0
//
//  For example: only client sends messages
//
//  % ./async_pair tcp://127.0.0.1:5555 -s 0 &
//  % ./async_pair tcp://127.0.0.1:5555 1
//

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <time.h>

#include <nng/nng.h>
#include <nng/protocol/pair1/pair.h>
#include <nng/protocol/bus0/bus.h>
#include <nng/supplemental/util/platform.h>

// Parallel is the maximum number of outstanding requests we can handle.
// This is *NOT* the number of threads in use, but instead represents
// outstanding work items.  Select a small number to reduce memory size.
// (Each one of these can be thought of as a request-reply loop.)
#ifndef PARALLEL
#define PARALLEL 16
#endif

#define BUS

#ifdef BUS
#define MESSAGE_SIZE 688
#else
#define MESSAGE_SIZE 4
#endif

// The server keeps a list of work items, sorted by expiration time,
// so that we can use this to set the timeout to the correct value for
// use in poll.
struct work {
    nng_aio *send_aio;
    nng_aio *recv_aio;
    nng_socket sock;
    bool server;
};

struct work *works[PARALLEL];

void
fatal(const char *func, int rv)
{
    fprintf(stderr, "%s: %s\n", func, nng_strerror(rv));
    exit(1);
}

static void send_cb(void *arg)
{
    int result = 0;
    struct work *work =arg;

    result = nng_aio_result(work->send_aio);
    if (result != 0) {
        fprintf(stderr, "%s: %s\n", "nng_aio_result-SEND", nng_strerror(result));
        nng_msg_free(nng_aio_get_msg(work->send_aio));
        nng_aio_set_msg(work->send_aio, NULL);
    }
}

static void receive_cb(void *arg)
{
    int result = 0;
    struct work *work = arg;

    result = nng_aio_result(work->recv_aio);
    if (result == 0) {
        nng_msg *msg = nng_aio_get_msg(work->recv_aio);
        size_t len = 0;
        if (msg != NULL) {
            len =  nng_msg_len(msg);
            if (len >= MESSAGE_SIZE) {
                nng_msg_trim(msg, MESSAGE_SIZE);
                fprintf(stderr, "%s processed message.\n", work->server ? "Server" : "Client");
#ifndef BUS
                bool respond = true;
#else
                bool respond = work->server;
#endif
                if (respond) {
                    // Acknowledge that we received the message.
                    nng_msg *response = NULL;
                    result = nng_msg_alloc(&response, 0);
                    if (result == 0) {
                        result = nng_msg_append(response, "SEND", 4);
                        if (result == 0) {
                            nng_aio_set_msg(work->recv_aio, NULL);
                            nng_aio_set_msg(work->send_aio, response);
                            nng_send_aio(work->sock, work->send_aio);
                        }
                        else {
                            nng_msg_free(response);
                        }
                    }
                }
            }
        }
        if (len > 0) {
            if (len == MESSAGE_SIZE) {
                fprintf(stderr, "%s received message.\n", work->server ? "Client" : "Server");
            }
            nng_msg_free(msg);
        }
        nng_recv_aio(work->sock, work->recv_aio);
    }

    if (result != 0) {
        fprintf(stderr, "%s: %s\n", "Receive callback", nng_strerror(result));
    }
}

static int m_index = 0;

/* Either side can send messages. */
void
send()
{
    static char buffer[MESSAGE_SIZE];
    int rv;
    struct work *work = works[m_index];
    m_index = (m_index+1) % PARALLEL;
    nng_msg *msg = NULL;

    if ((rv = nng_msg_alloc(&msg, 0)) != 0) {
        fatal("nng_msg_alloc", rv);
    }
#ifndef BUS
    if ((rv = nng_msg_append(msg, "SEND", MESSAGE_SIZE)) != 0) {
        fatal("nng_msg_append", rv);
    }
    if ((rv = nng_msg_append(msg, "DATA", MESSAGE_SIZE)) != 0) {
        fatal("nng_msg_append", rv);
    }
#else
    if ((rv = nng_msg_append(msg, buffer, MESSAGE_SIZE)) != 0) {
        fatal("nng_msg_append", rv);
    }
#endif
//    fprintf(stderr, "%s send message.\n", work->server ? "Server" : "Client");
    nng_aio_set_msg(work->send_aio, msg);
    nng_send_aio(work->sock, work->send_aio);
}

struct work *
alloc_work(nng_socket sock, bool server)
{
    struct work *w;
    int          rv;

    if ((w = nng_alloc(sizeof(*w))) == NULL) {
            fatal("nng_alloc", NNG_ENOMEM);
    }
    if ((rv = nng_aio_alloc(&w->send_aio, send_cb, w)) != 0) {
            fatal("nng_aio_alloc", rv);
    }
    if ((rv = nng_aio_alloc(&w->recv_aio, receive_cb, w)) != 0) {
            fatal("nng_aio_alloc", rv);
    }
    w->sock  = sock;
    w->server = server;
    return (w);
}

// Each runs forever.
int
init(const char *url, bool server, bool send_messages)
{
    nng_socket   sock;
    int          rv;
    uint32_t     i;

    /*  Create the socket. */
#ifndef BUS
    rv = nng_pair1_open(&sock);
#else
    rv = nng_bus_open_raw(&sock);
#endif
    if (rv != 0) {
#ifndef BUS
        fatal("nng_pair1_open", rv);
#else
        fatal("nng_bus_open_raw", rv);
#endif
    }

    for (i = 0; i < PARALLEL; i++) {
        works[i] = alloc_work(sock, server);
    }

    if (server)
    {
#ifndef BUS
        if ((rv = nng_setopt_bool(sock, NNG_OPT_PAIR1_POLY, true)) != 0) {
            fatal("nng_setopt_bool", rv);
            return false;
        }
#endif
        if ((rv = nng_listen(sock, url, NULL, NNG_FLAG_NONBLOCK)) != 0) {
            fatal("nng_listen", rv);
            return false;
        }
    }
    else {
        if ((rv = nng_dial(sock, url, NULL, NNG_FLAG_NONBLOCK)) < 0) {
            fatal("nng_dial", rv);
        }
    }

    for (i = 0; i < PARALLEL; i++) {
        nng_recv_aio(works[i]->sock, works[i]->recv_aio);
    }

    while (true) {
        if (send_messages) {
            nng_msleep(16);
            for (i = 0; i < 6; i++) {
                send();
                //int sleep = (int) (rand() % 1000) + 500;
                // fprintf(stderr, "Sleep %d\n", sleep);
                //nng_msleep(sleep);
            }
        }
        else {
             nng_msleep(10000);
        }
    }

    for (i = 0; i < PARALLEL; i++) {
        struct work* w = works[i];
        nng_aio_cancel(w->recv_aio);
        nng_aio_cancel(w->send_aio);
        nng_aio_free(w->send_aio);
        nng_aio_free(w->recv_aio);
      //  delete w;
    }
    nng_close(sock);

    if (server) {
        fprintf(stderr, "Server closed socket\n");
    } else {
        fprintf(stderr, "Client closed socket\n");
    }
    return 0;
}

int
main(int argc, char **argv)
{
    int rc;
    bool server = false;
    bool send_state = false;

    if (argc < 3) {
        fprintf(stderr, "Usage: %s <url> [-s  and/or 0/1]\n", argv[0]);
        exit(EXIT_FAILURE);
    }
    server = (strcmp(argv[2], "-s") == 0);
    if (server) {
        send_state = (atoi(argv[3]) > 0);
    }
    else {
        send_state =  (atoi(argv[2]) > 0);
    }
    rc = init(argv[1], server, send_state);
    exit(rc == 0 ? EXIT_SUCCESS : EXIT_FAILURE);
}
`

**Comment by maingig** [comment]
Here is another instance of the crash using Pair.  It happens pretty quickly.  Can only run  one client of course.
Is there any interest in investigating the issue? 

[async_pair.txt](https://github.com/nanomsg/nng/files/3598198/async_pair.txt)

**Comment by gdamore** [comment]
I will look this weekend.  Unlikely to have cycles before then.

**Comment by gdamore** [comment]
Looking at this , it looks initially like you might be assuming some correlation between your work send aio and receives.  Meaning you might wind up sending on an aio that already has an outstanding operation on it.  This is an application error on your part.

You may need to have to keep track of free aios (those not in use).  You can tell that an aio is not in use by having the send callback executed on it.

This problem in your code arises because you can wind up receiving a message send on another aio, before the others have completed sending.

Perhaps a different solution, and one I'd recommend you use, is to use a single aio per worker.  You should send(), then only call the receive from the send callback.  Then the receive callback will call send again.  You can have a bunch of these going in parallel.

Most server applications would not start with send(), but that would occur in another program.  Instead they would start in receive().   Client programs usually do the reverse.

**Comment by gdamore** [comment]
I'm going to close this bug, as its in your code, but you may feel free to continue to ask questions about it here.  I will still respond.
