### ISSUE TITLE
aoi callbacks to  c++ classes, inspiration wanted 

### ISSUE THREAD

**Issue by fpvision** [nanomsg/nng#993]
I' new to nng. We desided to give nng a spin for a complex application written in C++, with a bunch  of independent modules (classes that are instantiated in either the same executable or in individual executables ) , each inheriting from a common class providing endpoints ( wrapping nng), does anybody have inspiration preferably with examples of  how to assure the callbacks from nng are handled by the correct objects ? 
if this question is matter out of place - please just ignore and delete.
regards Lars

**Comment by gdamore** [comment]
Unfortunately I'm not a C++ wizard.  But what I'd probably look to do is create some kind of wrapper object that contains the aio, your private class state, and have the aio callbacks be methods on the wrapper object.   This won't guarantee you're using it all correctly, but it should help avoid at least one class of common problems.

**Comment by gdamore** [comment]
I'm closing this out for now.  Not that further discussion can be done on the mailing list (nanomsg@freelists.org) or our gitter chat.
