### ISSUE TITLE
pair1 with NNG_OPT_PAIR1_POLY always discards datas(event one pair and tiny datas) when sending

### ISSUE THREAD

**Issue by norsd** [nanomsg/nng#995]
NNG Version : 1.1.1

First I have read the issue "always see 1% message drop on listener #878".
And I'm still confusing why it is so frangible when there is just one pair and sending tiny datas.
In my test, listener will send bytes which content is like "Hi, I'm X" about 10times. But the dialer will always lost some data, maybe 50-70%.
I know all the demo will add "Sleep(1)" to delay sending, but it is not suitable in many situations. 
Since what I sent is very tiny size of data, there is no reason the linstener should discard them. (I confirm the listener discard them, cause I monitor socket  at tcp/ip layer and find the listener not send all datas to dialer but part of them.)

Here is the codes(C#
[TestNngPair1.zip](https://github.com/nanomsg/nng/files/3606846/TestNngPair1.zip)
):
Run Listener and enable NNG_OPT_PAIR1_POLY will survey the situation, and disable it everything is ok.
Expected display at Dialer part is looks like: 
"Hi, I'm 10    [No.10]"
If there is any msg be discarded:
"Hi, I'm X   [No.Y]"

**Listener:**
`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

using NngLibrary;

namespace TestNngPair1ListenerConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Use NNG_OPT_PAIR1_POLY?(y/n)");
            _usePOLY = Console.ReadKey().KeyChar.ToString().ToLower() == "y";
            Console.WriteLine($"\r\n{(_usePOLY ? "Use":"Disable")} NNG_OPT_PAIR1_POLY");

            var sk = new nng_socket();
            var l = new nng_listener();
            nng.nng_pair1_open(ref sk);
            if (_usePOLY)
                nng.nng_setopt_bool(sk, NNG_OPT.NNG_OPT_PAIR1_POLY, true);              

            var url = ("tcp://127.0.0.1:7710");         
            nng.nng_listen(sk, url, out l, 0);

            while (true)
            {                                
                nng.nng_recvmsg(sk, out var ptrMsg, 0);                
                var ptrMsgContent = nng.nng_msg_body(ptrMsg);
                var contentsize = nng.nng_msg_len(ptrMsg);
                var pipe = nng.nng_msg_get_pipe(ptrMsg);

                var bytesRecv = new byte[contentsize];
                Marshal.Copy(ptrMsgContent, bytesRecv, 0, bytesRecv.Length);
                var str = Encoding.ASCII.GetString(bytesRecv);
                Console.WriteLine($"{pipe}:{str}");

                int num = 10;
                Console.WriteLine($"Send {num}Times");
                var dtS = DateTime.Now;
                for (var i = 0; i < num; i++)
                {
                    send(sk, pipe, $"Hi, I'm {i + 1}");
                    //Thread.Sleep(1);                                        
                }                
                Console.WriteLine($"Send Completed");                
            }                                                                              
        }
   
        static void send(nng_socket socket, nng_pipe pipe, string name)
        {
            var bytes = Encoding.ASCII.GetBytes(name);
            var npdata = Marshal.AllocHGlobal(bytes.Length);
            Marshal.Copy(bytes, 0, npdata, bytes.Length);

            nng.nng_msg_alloc(out var nmsg, 0);
            nng.nng_msg_append(nmsg, npdata, bytes.Length);
            nng.nng_msg_set_pipe(nmsg, pipe);
            nng.nng_sendmsg(socket, nmsg, 0);
        }
        
        static bool _usePOLY = true;
    }
}
`

**Dialer:**

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

using NngLibrary;

namespace TestNngPair1DialerConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            var sk = new nng_socket();
            nng_dialer l = new nng_dialer();
            nng.nng_pair1_open(ref sk);
            var url = ("tcp://127.0.0.1:7710");                        
            nng.nng_dial(sk, url, ref l, 0);

            send(sk, "Hello World");
            Console.WriteLine($"Recv:\r\n");
            while (true)
            {
                recv(sk);                
            }                    
        }
       
        static int recv(nng_socket socket)
        {                                   
            var rv = nng.nng_recvmsg(socket, out var msgptr, 0);
            var msgbodyptr = nng.nng_msg_body(msgptr);
            var size = nng.nng_msg_len(msgptr);            

            var bytes = new byte[size];
            Marshal.Copy(msgbodyptr, bytes, 0, size);

            var str = Encoding.ASCII.GetString(bytes);
            Console.Write($"\r{str}   [No.{++_recvNumber}]");            
            
            nng.nng_msg_free(msgptr);
            return 0;
        }
        static void send(nng_socket socket, string str)
        {
            var bytes = Encoding.ASCII.GetBytes(str);
            var npdata = Marshal.AllocHGlobal(bytes.Length);
            Marshal.Copy(bytes, 0, npdata, bytes.Length);

            nng.nng_msg_alloc(out var nmsg, 0);
            nng.nng_msg_append(nmsg, npdata, bytes.Length);
            nng.nng_sendmsg(socket, nmsg, 0);
        }
        static int _recvNumber = 0;        
    }
}
`

**Comment by gdamore** [comment]
Polyamorous mode is *quite* different, because it takes an other wise 1:1 "reliable" communication, and makes it 1:n (or even m:n), and also unreliable.  The polyamorous host can't send reliably.  Note that if it is partnered with monogamous peers (perfectly valid), then those peers *can* send reliable, and the poly partner will receive reliably -- but still the poly node can't *send* reliably.
