### ISSUE TITLE
[Question] How to do service discovery across different machines?

### ISSUE THREAD

**Issue by rolandjitsu** [nanomsg/nng#996]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

```
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
```
```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
```
nngcat --version
1.1.1
```

## Expected Behavior
I was wondering how to use this lib to do service discovery on a cluster of machines connected to the same network.

I initially thought that I could run a survey on TCP on some port, but no specific hostname specified and then the respondents would reply with some info.

But I tried using nngcat w/
```
# Listen
nngcat --respondent --listen=tcp://0.0.0.0:4567 --data="42" --quoted

# Send survey
nngcat --surveyor --dial="tcp://*:4567" --data "test" --quoted
```

But the survey request doesn't work as the address is invalid.

## Actual Behavior
I would expect to be able to send a survey to any host on some specific port, similar to how mDNS works. But is this actually possible?

**Comment by gdamore** [comment]
You can't dial to a wild card host.

You need to specify a single hostname -- typically you will set up a "registry" host, that other parties can dial to.  You may even set up multiple this way.

Remember that under the hood this is all TCP, so no form of multicasting is present.
