### ISSUE TITLE
NNG_OPT_SUB_SUBSCRIBE: nng_setopt vs nng_setopt_string

### ISSUE THREAD

**Issue by matt-deboer** [nanomsg/nng#999]
## NNG & Platform details.
nng: tip (master 32d17517b87713e4d584555c35ac48d010243910)
platform: any

When trying to set a subscription on a sub socket, it is easy to accidentally set an incorrect subscription intended to catch all messages by using `nng_setopt_string(s, NNG_OPT_SUB_SUBSCRIBE, "")`; this actually filters on messages beginning with null character `\0`, which is likely not what one wants.

The correct way to subscribe to all messages is `nng_setopt(s, NNG_OPT_SUB_SUBSCRIBE, "", 0)`.

There is nothing wrong with nng here to be fixed, per se; maybe an extra warning could be added to the documentation.

Perhaps this issue is enough for someone to happen upon and realize what they're doing wrong--possibly a future version of me :grinning:

**Comment by gdamore** [comment]
It's a good point.  I'll note this for the next update on docs.
